### ISSUE TITLE
[Issue]: Order By last added not working properly

### ISSUE THREAD

**Issue by marcoh242** [jellyfin/jellyfin#10001]
### Please describe your bug

When I move a new Folder to the Video Library Folder the added Movie doesnt appear first when I order by last added. This happens obviously because the modification date of the movie isnt touch when moved under linux. If I copy the folder inside a windows environment modification date is updated and it shows as last added movie. 

It would be better when the 'order by' depends on when jellyfin added the movie to its database instead of relying on thos modification dates.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux/Synology DSM
- Clients:  jellyfin-androidtv, jellyfin-web
- Browser: Chromium
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkanilsson** [comment]
This is intentional, reasoning can be found here https://github.com/jellyfin/jellyfin/pull/10239#pullrequestreview-1630119170

This functionality can be changed by going to `Dashboard` under `Administration` then click on `Libraries` and going to `Display` (found at the top center of the screen) and change `Date added behavior for new content` to `Use date scanned into the library`
