### ISSUE TITLE
[Issue]: the name not show correct

### ISSUE THREAD

**Issue by vansto** [jellyfin/jellyfin#10092]
### Please describe your bug

metadata (filepath and title) just like this:
<img width="634" alt="2023-08-07_004730" src="https://github.com/jellyfin/jellyfin/assets/10329221/8a74443d-2153-435d-aff7-782ac1087028">

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Windows 11
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:jellyfin-ffmpeg_6.0-4
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by boc-the-git** [comment]
@vansto can you provide more detailed information about this please?

**Comment by srcrist** [comment]
Hey, vansto. The parser relies on the use of the naming and organization convention outlined in our documentation here: [](https://jellyfin.org/docs/general/server/media/shows/
)
If you want to use a different convention, you will likely have to use NFO files in order to manually provide your own metadata for the episodes, as Jellyfin will be unable to parse the episodes correctly in order to match them with a metadata provider to retrieve the correct information.

Closing this issue as incorrect matches are expected behavior when file names do not adhere to the conventions.
