### ISSUE TITLE
question: What's the actual use for max_delay option in ffmpeg?

### ISSUE THREAD

**Issue by ringus1** [jellyfin/jellyfin#10247]
I see it breaks produced HLS ts files in a manner that they have wrong start timestamps set. Setting value to **0** correctly fixes that. Is that a bug or is there a specific reason for it?

**Comment by ringus1** [comment]
@nyanmisaka Could you help out? Is this option supposed to be on by default for static sources with such high value (5000000)?

**Comment by w-hc** [comment]
I suspect the issue has broader impact than it may appear. The -max_delay 5000000 flag causes HLS TS segments to start at PTS ~10s instead of 0, while the manifest declares them starting at 0.
  Most clients (web, Android, VLCKit) tolerate this mismatch, but Apple's AVPlayer doesn't seem to — it requires PTS to match the manifest.

  - In my limited testing, AVPlayer cannot play Jellyfin's HLS TS streams at all. The player presents but never advances — currentTimeInterval stays at 0 forever. CoreMedia errors: -12753, -12785, -16845, -16240. 
  - HLS subtitle timing is also broken. The X-TIMESTAMP-MAP in WebVTT segments assumes the TS PTS offset, so subtitles are misaligned by ~10 seconds when using fMP4 segments (which have correct PTS at 0) as a video workaround.

Workaround that confirms the cause: Using SegmentContainer=mp4 (fMP4) instead of TS produces segments with correct PTS starting at 0, and AVPlayer plays them fine. This points directly to -max_delay affecting only the TS muxer.

**Comment by LTe** [comment]
@w-hc I investigated this in detail — ran Apple's `mediastreamvalidator` against a local Jellyfin instance (built from master), tested with AVPlayer on the iOS Simulator (iPhone 16 Pro), and used real Blu-ray content (x264 High 4.1 + EAC3 5.1, irregular keyframes).

**The 10s PTS offset is spec-legal and plays fine on AVPlayer.**

An Apple Systems Engineer confirmed this explicitly in [Developer Forums thread 113190](https://developer.apple.com/forums/thread/113190):

> "In general HLS clients cannot assume any relationship between the media timestamp of the first segment (tfdt in fmp4, ES PTS in MPEG2-TS, clock time in WebVTT) and presentation time."

The ~10s offset is intentional — Apple's own `mediafilesegmenter` hard-codes it:

> "Creating example streams that do not start at media timestamp 0 by default helps reinforce the fact that in general they do not. This initial value is hard-coded and does not depend on the input file."

Apple's official HLS test streams at https://developer.apple.com/streaming/examples/ also start at PTS ~10s. You can verify yourself — `ffprobe` reads HLS playlists directly:

```bash
# Apple's TS test stream — first 3 video packets
ffprobe -v error -select_streams v -show_entries packet=pts_time,dts_time \
    -of csv=p=0 -read_intervals "%+#3" \
    "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/v5/prog_index.m3u8"
# 10.016667,10.000000
# 10.066667,10.016667
# 10.033333,10.033333

# Apple's fMP4 test stream — same result
ffprobe -v error -select_streams v -show_entries packet=pts_time,dts_time \
    -of csv=p=0 -read_intervals "%+#3" \
    "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/v5/prog_index.m3u8"
# 10.016667,10.000000
# 10.066667,10.016667
# 10.033333,10.033333
```

Both Apple's fMP4 and TS test streams start at PTS ~10.0s — the same offset Jellyfin produces.

**Verified empirically:**
- `mediastreamvalidator` processes Jellyfin's HLS TS streams with **zero errors** — the ~10s PTS offset passes Apple's own validation tool.
- AVPlayer on iOS Simulator plays both TS and fMP4 Jellyfin streams with **zero errors** using real Blu-ray content (Cars 2006, Bluray-1080p, x264 + EAC3 5.1). No -12753, -12785, -16845, or -16240.
- With an artificially slow transcode (simulated via an ffmpeg wrapper adding 8-30s startup delay), AVPlayer logs `-12889` ("No response for media file") but **recovers and plays normally**. Only with extreme 60s delays does it hard-fail — with `-16849` (HTTP 503 from server), not the codes listed in your comment.

**Regarding the specific error codes:**
- `-16845` is CoreMedia's internal mapping for HTTP 400 responses during HLS segment fetch. This would indicate the server is returning 400 for a segment request — unrelated to the PTS offset or `-max_delay`.
- `-12889` (segment timeout) — This is about **transcode latency**, not PTS offset. On slow hardware or with complex content, the first HLS segment takes too long to transcode, and AVPlayer logs a timeout warning.
- `-12785` / `-12753` — These are secondary lifecycle errors (object invalidated, sync parameter error) that cascade after a primary failure, not root causes.

**Comment by w-hc** [comment]
Thanks for the detailed investigation @LTe. You're right that the ~10s PTS offset is spec-legal — I was wrong about that.

I still notice `TS` segments being displayed as a black screen on some of my files. `fMP4` segments (`SegmentContainer=mp4`) are generally more robust. There are probably more nuances in `TS` behavior, but I guess it's legacy format at this point. 

But there is still the subtitle timing issue with the `fMP4` + `SubtitleMethod=Hls` combo.  With `SegmentContainer=mp4` and `SubtitleMethod=Hls`, native HLS subtitles arrive approximately 10 seconds late. This is now filed as a separate issue. 

Thanks agains for your help.

**Comment by gnattu** [comment]
This was long baked into the HLS handling but this option is actually needed to make the output more robust, as some input may have non-monotonic timestamp (which means packet reordering is required) and max_delay would help in this case.

All the side effects it causes , if can be confirmed as bug behaviors, should be reported directly as a separate bug report, instead of asking for "just disable it." 

I highly doubt the black screen is caused by this. For subtitle transcoding it makes sense, but for other compatibility issues you claimed, it does not at all. Did you actually verified that the issues are gone after removing max_delay, or those are just you (or some LLM)'s speculation?

**Comment by w-hc** [comment]
It was speculation. I didn’t modify the Jellyfin server. Only played with the API requests on client side in tvOS simulator. Sry abt that @gnattu
