### ISSUE TITLE
add additional build targets for FreeBSD 32/64 bit and Linux 32 bit

### ISSUE THREAD

**Issue by PaddyMac** [jellyfin/jellyfin#1042]
Please add additional build targets to the build script for FreeBSD, both 32 and 64 bit. Please also add a Linux target for 32 bit. I noticed that Windows is the only build target which currently offers a 32-bit option. I often contribute ebuilds for Gentoo and occasionally ports for FreeBSD. Getting Jellyfin into the repos for these two operating systems is my intention, and this would make that easier.

**Comment by LogicalPhallacy** [comment]
So there are technical limitations preventing all these things. Jellyfin is written to use dotnet core which means dotnet core must be available for the system in question.
#250 - There are no current plans from Microsoft to port dotnet core to 32 but linux, and there has not been much success from community efforts on that front.

https://github.com/dotnet/core/issues/522 - Dotnet core has a community supported functioning BSD build, but since there are no binary packages for it, and at the moment there is not an RID in dotnet core to build self contained BSD builds of netcore apps with, every user would have to compile a functional version of dotnet core on BSD themselves, then they'd be able to install a generic unoptimized binary for jellyfin or compile it from source as well. To the best of my knowledge no one has done the first step yet for this project.

**Comment by Bond-009** [comment]
Look like FreeBSD support is planned for .Net core 3.0.
https://github.com/dotnet/corefx/issues/1626

**Comment by LogicalPhallacy** [comment]
Awesome we will make some builds when we start the dotnet 3 work

**Comment by PaddyMac** [comment]
For the time being, the Linux version of Dotnet is in the FreeBSD repos and runs with FreeBSD's Linux emulation. So until a FreeBSD native version of Dotnet is available, it may still be able to get Jellyfin running on FreeBSD using the Linux version of Dotnet. The following versions are currently available in FreeBSD Do these appear to be suitable? linux-dotnet-cli-2.0.7 linux-dotnet-runtime-2.0.7 linux-dotnet-sdk-2.1.201 linux-dotnet10-runtime-1.0.11 linux-dotnet10-sdk-1.1.9 linux-dotnet11-runtime-1.1.8

**Comment by LogicalPhallacy** [comment]
linux-dotnet-sdk-2.1.201 should be sufficient to run a version of jellyfin built with a linux-x64 target.

**Comment by moritz31** [comment]
How is the status here ? 
Just saw that emby offers some freebsd builds 
https://emby.media/freebsd-server.html if we would have freebsd as build target, we could bundle jellyfin as freenas plugin, too.

**Comment by asmusz-adobe** [comment]
I'd like to cast a vote for a freenas/freeBSD build too.  I'm not a real developer so I'm not able to assist but love my freeNAS.  Need to get away from Plex/Emby and one to real open source.

**Comment by zorglube** [comment]
Since .Net framework is know available for FreeBSD, I think packaging Jellyfin for this target is know possible.

**Comment by Bond-009** [comment]
Closing as an official FreeBSD port exists for Jellyfin
https://ports.freebsd.org/cgi/ports.cgi?query=jellyfin&stype=all
