### ISSUE TITLE
Replace `WebSocketSharpRequest.PathInfo` custom URL query parsing with a framework function

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#1047]
**Is your feature request related to a problem? Please describe.**
Right now the code is littered with custom implementations for things that the framework has built in functions for.

**Describe the solution you'd like**
Probably something based on `QueryHelper.ParseQuery`

**Comment by voodoos** [comment]
I am having a look at it right now and it does look like a lot of dead code to me:
If I am not mistaken the [` ResolvePathInfoFromMappedPath(string fullPath, string mappedPathRoot)`](https://github.com/jellyfin/jellyfin/blob/79d9b8e693e4c53a56f610482f5f36f7a58f39f7/Emby.Server.Implementations/SocketSharp/WebSocketSharpRequest.cs#L366) function subtracts the prefix `mappedPathRoot` from the full path `fullPath`.

But the second argument is always `null`or `""` because it is used with the `string HandlerFactoryPath` member variable which is *never* initialized...

Thus in this state the `ResolvePathInfoFromMappedPath` does nothing more than the identity function.

Do you know what would be the role of `HandlerFactoryPath` ? 
Should I just remove all that complexity or make is as flexible as it is now (but using more standard ways) even if it is of no use yet ?

PS: new dev here, hope I can help with some parts of this great adventure !

**Comment by voodoos** [comment]
For reference, the best tool to do that is probably: [System.Uri.MakeRelativeUri(Uri)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri?view=netframework-4.7.2)

**Comment by voodoos** [comment]
@cvium : you seems to be at the origin of the whole `WebSocketSharpRequest.cs` file in cvium@852460b99155e015ed5f1d7ad2fab0281bfdfbec . Can you confirm that I am not mistaken in my previous comment ?

In the same way the `NormalizePathInfo(string pathInfo, string handlerPath)`is always useless because `handlerPath` is always `null` (because `mode = HandlerFactoryPath` which is never initialized).

If that's correct I made  [these simplifications in a branch on my fork](https://github.com/voodoos/jellyfin/blob/dd1710f5dc04b32c399b81cec6fa283792e637a4/Emby.Server.Implementations/SocketSharp/WebSocketSharpRequest.cs#L322) and am ready to PR.

Also, I am not sure of how to test my changes (apart from running the server), is there some guidance written somewhere ?
