### ISSUE TITLE
[Issue]: Downloading files with Japanese and special characters in the file name will result in URL encoding.

### ISSUE THREAD

**Issue by tatamiboy** [jellyfin/jellyfin#10488]
### Please describe your bug

If I download a music file whose file name contains both Japanese and special characters (`!, (, )`), it will be URL encoded.

Example:
Original: `03. ふわふわ時間 (Instrumental).flac`
After downloading: `03.+%E3%81%B5%E3%82%8F%E3%81%B5%E3%82%8F%E6%99%82%E9%96%93+(Instrumental).flac`

This will not occur if only Japanese or alphanumeric and special characters are used.
It occurs on jellyfin-android, jellyfin media player on kubuntu, Google Chrome 118.0.5993.117, but not FireFox 119.0. 

### Jellyfin Version

10.8.z

### if other:

10.8.11

### Environment

```markdown
- OS: Unraid 6.12.4
- Virtualization: Docker
- Clients: Browser, Android, Jellyfin Media Player
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
I was able to reproduce on 10.8.11, behavior matches description

Firefox:
<img width="478" alt="截圖 2023-10-28 上午4 01 56" src="https://github.com/jellyfin/jellyfin/assets/25688628/8d32244f-729b-4263-a866-082e484095ca">

Chrome:
<img width="312" alt="截圖 2023-10-28 上午4 02 24" src="https://github.com/jellyfin/jellyfin/assets/25688628/9651af88-248d-4341-8552-39b4fdfe3293">

**Comment by tatamiboy** [comment]
There was a mistake in my first post, so I'll correct it.

I mentioned that this does not happen with Japanese-only files, but I checked again and found that it occurs with Chrome and Jellyfin Media Player even when the file is Japanese-only and has no special characters.
Also in FireFox, the space seems to have been replaced by "+".

On the Android client, Japanese-only files that do not contain special characters will be saved correctly as original.

**Comment by TheMelmacian** [comment]
I made a quick test myself and had a look into the browser dev-tools. It seems the problem is related to the [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#filename) http header:

```
attachment; filename="03.+%E3%81%B5%E3%82%8F%E3%81%B5%E3%82%8F%E6%99%82%E9%96%93+(Instrumental).flac";
filename*=UTF-8''03.+%25E3%2581%25B5%25E3%2582%258F%25E3%2581%25B5%25E3%2582%258F%25E6%2599%2582%25E9%2596%2593+%28Instrumental%29.flac
```

It seems the `filename*` property is double [URL encoded](https://www.url-encode-decode.com/). If you decode it twice you get the correct filename. Firefox seems to be aware of that but chromium based browsers are not.

But I couldn't reproduce the error with the latest master branch in my local dev environment (currently on windows). Only on my server with 10.8.11 (Linux, Docker). So maybe it is already fixed? Or it is related to the environment/operating system.

The http header on my dev environment looked like this:
```
attachment; filename="03. ______ (Instrumental).flac"; filename*=UTF-8''03.%20%E3%81%B5%E3%82%8F%E3%81%B5%E3%82%8F%E6%99%82%E9%96%93%20%28Instrumental%29.flac
```
`filename*` is encoded only once and the file is correctly named (spaces, Japanese characters etc.) in both firefox and chromium based browsers.


So the solution is to set the correct filename* property in the Content-Disposition on the server.
