### ISSUE TITLE
Add ability to change advertised local IP (docker issue)

### ISSUE THREAD

**Issue by forkineye** [jellyfin/jellyfin#1050]
**Is your feature request related to a problem? Please describe.**
Yes. When ran as a container, the server advertises its local IP using the container IP assigned by docker.  This can cause issues with clients failing to re-connect (Emby on a Firestick in my case), forcing the user to re-enter the docker host IP when connecting. 

**Describe the solution you'd like**
Provide an option under "Advanced" to override the advertised IP.  Another option could be to add a docker specific configuration item that would both change the advertised IP and take in account that same IP's subnet as a "LAN Network".

**Describe alternatives you've considered**
Running the container in host mode is a workaround, but not ideal and causes conflicts with other containers running on the system.

**Comment by hawken93** [comment]
If jellyfin isn't directly on the lan, it can't send broadcasts to the lan and so automatic discovery is impossible. I'm not sure I understand you correctly but if I do, this is impossible by design. Maybe the only solution I can come up with is to have a small dedicated "responder" directly on the lan network. This would have to be made from scratch though, but could possibly be a small script

**Comment by JustAMan** [comment]
The issue itself has nothing to do with broadcasts or stuff, it's more about JF trying to be too clever on determining how to access itself. There should be a configuration on the server which the admin could put a full URL, so that reverse proxy setups with URL prefixes are well supported. Docker internal IP is only a one case where this "smartiness" detection fails.

**Comment by mattthhdp** [comment]
Or you could use the. Net = host on docker ? Not the prettiest method but this should work.
