### ISSUE TITLE
Performance issue and a possible memory leak? 

### ISSUE THREAD

**Issue by Uatschitchun** [jellyfin/jellyfin#1053]
Hi. Someone using jellyfin with a large music collection?
I'm testing jellyfin with docker and music only atm. The performance is quite reduced (maybe because it's only single threaded?). 
Yesterday I noticed that my system started to swap and jellyfin's docker instance was using up all memory (8GB). After restarting the container the memory usage went down to 200MB. 

What is the best way to debug/inspect what's going on?

**Comment by mu-stash** [comment]
Hi, with docker on my synology, the jellyfin 10.2.2 container is filling up allowed ram (4 Go) in a few hours. The web interface is not responsive and I have to restart the container several times a day since a few days now to get it working again. The logs show nothing special except warnings about longer and longer db requests as ram is filling up. I believe it may be linked to opensubtitles searches but I can't be sure.
Hope this helps.

**Comment by JustAMan** [comment]
> Hi, with docker on my synology, the jellyfin 10.2.2 container is filling up allowed ram (4 Go) in a few hours.

Did you see this with earlier releases? Is it possible to check with `10.2.0` or earlier builds to try to find when this was introduced? This search should help us find the root cause.

**Comment by Uatschitchun** [comment]
What I can tell is that I'm not using subtitles as I only have a source with music added.

Is it possible to downgrade the docker container and restart with same settings, then testing would be easy

**Comment by JustAMan** [comment]
You should be able to run docker image using same settings but different container tag (but make sure your settings and data and whatnot are backed up).

cc @sparky8251 / @nvllsvm for Docker help

**Comment by mu-stash** [comment]
I've been doing some test, setting parameters on and off, and I think I found something.

I have kodi with the emby addon (4.0.5). With Jellyfin and kodi online and idle, logs were showing only the following lines, and yet I could see ram filling by 1% each one or two minutes:

[17:52:27] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 
[17:53:08] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 
[17:53:49] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 
[17:54:30] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 
[17:55:11] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 
[17:55:52] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 
[17:56:33] [INF] HTTP GET http://192.168.0.200:8096/emby/Users/c3f3.../Items?Recursive=true&SortBy=Random&IncludeItemTypes=Movie,Series&ImageTypeLimit=1. UserAgent: 

With kodi shutdown, jellyfin container seems to behave normally. The problem is the same with or without the "kodi sync queue" installed on jellyfin side. 

When I upgraded, I also made massive changes in my library structure so I couldn't tell if the ram increase was temporary and only because of the many scans. Now it's over, I'm pretty sure I would have noticed this behavior with 10.2.0 as jellyfin, even idle, become pretty quick unusable and the container need to be restarted.

**Comment by JustAMan** [comment]
ping @cvium @Bond-009

**Comment by acl1704** [comment]
I'm seeing behavior along the same lines, although running JF in a VM instead of a container. JF will slowly use nearly all the available ram, 100gb of it, as movies are streamed. No corresponding increase in CPU usage. Sitting idle, ram usage remains flat, though that can be 2gb or 80gb. 
What's the best way to debug?

Running latest 10.3.6, in Debian 10.0.0 amd64 on Proxmox. Installed from the JF repo.

**Comment by jamduck** [comment]
Hi, any update of this problem? I am using JF on windows and I got memory use up issue as well. It happened after my large family videos and photos folder added, there are over 100,000 pictures and 1,000 videos files, the machine has16G ram and JF used 15G. Does it mean that I should not use JF to handle so many files?

**Comment by dkanada** [comment]
@acl1704 it looks like you're using proxmox, which has a deceptive value for RAM usage on the dashboard. There are two different types of unused RAM in the system as far as I know. Normally both will be reported as unused, but proxmox only reports free RAM in the web interface. If you ssh into that machine and check the RAM in htop or something you should see the actual value.

**Comment by jamduck** [comment]
Hey all, I think it's caused by too many files in one folder, say over 30,000. I used visual studio diagnostics tool to trace the memory usage and found the most memory was spent on files metadata collection.  Please team member check the code
 \jellyfin\Emby.Server.Implementations\IO\ManagedFileSystem.cs, line 723,
return ToMetadata(directoryInfo.EnumerateDirectories("*", searchOption))
                .Concat(ToMetadata(directoryInfo.EnumerateFiles("*", searchOption)));
I think when files count over 30,000, the FileSystemMetadata array spent too many memory, can we improve this?

**Comment by visualblind** [comment]
@jamduck how certain are you that the high memory usage you're seeing if not the operating system caching Jellyfin data? If you're a developer, you out of all people should take this into account.

**Comment by Uatschitchun** [comment]
With latest docker (10.3.7) there's no problem with memory anymore

**Comment by JustAMan** [comment]
That RAM usage is (my guess) probably caused by transcoding directory sitting somewhere in `tmpfs`-mapped storage, and Jellyfin at that time didn't clean up transcoding cache in a reliable way.

@anthonylavado I remember you wanted to add a scheduled task to clean up transcoding cache, did it happen? If so, I think we should close that issue and open a new one if that issue surfaces again.

**Comment by anthonylavado** [comment]
@JustAMan This task does exist in 10.4.0. It’s disabled by default, but when turned on/run, it will delete anything older than 24 hours in the transcode temp directory.

**Comment by JustAMan** [comment]
Why it is turned off then? Can we have it on by default?

**Comment by JustAMan** [comment]
I see. Well, unused items (like, for which a watch is over) are useless if a video wasn't played from the beginning in current implementation... but let's keep it this way for now.
