### ISSUE TITLE
[Issue]: No option to change content type for library?

### ISSUE THREAD

**Issue by RDKRACZ** [jellyfin/jellyfin#10570]
### Please describe your bug

I can't find a way to change the library content type from movies to shows. How to do it?

### Jellyfin Version

Other

### if other:

10.8.11

### Environment

```markdown
- OS: Windows 11

does not matter...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
That isn’t supported. You will have to remove the library and recreate it.

**Comment by RDKRACZ** [comment]
Is it not possible even in a hacky / database editing way?
I understand it's not supported atm but why "not planned"?

**Comment by cvium** [comment]
Why can't you just remove the library and create a new one? It's not planned because it's _very_ _very_ niche and ultimately pointless

**Comment by tenshiism** [comment]
> Why can't you just remove the library and create a new one? It's not planned because it's _very_ _very_ niche and ultimately pointless

Hi, I really don't think this is niche at all since someone decided to create an issue for it and research shows that for every issue created, theres many more people who didn't create an issue. Ultimately you are saying "we dont care about you" to anyone who has this issue. I don't agree that this attitude is appropriate for a community project.

**Comment by joshuaboniface** [comment]
You can't because the item schema is vastly different for both media types.

So far, we've seen no reasonable way to convert this proposed, and even if we did the implementation would have to be a mess of spaghetti code to handle the conversion. This is not something we intend to try to change until our entire library schema is replaced. Creating a new library is the only valid solution.

If this is a very common situation as suggested, I find it hard to undertand why. The library types are discrete because they are different media types with completely different metadata structures (i.e. a movie doesn't have seasons or episodes in a sequential order). What reason is there to try to take an existing library of one type and replace it with another? If the answer is that the media is actually a 3rd kind (e.g. hom movies), the solution is a mixed or generic library.

I know this sounds a bit dismissive, but consider how complex this would be for us to implement in the current legacy (Emby 3 derived) library database code. We already have plans to replace this, but work is slow because of how convoluted and complex it is. This functionality would just add to that burden and significantly impeded the effort to replace it.
