### ISSUE TITLE
[Issue]: seasons on the detail page sort out of order

### ISSUE THREAD

**Issue by ausar47** [jellyfin/jellyfin#10607]
### Please describe your bug

Seasons on the detail page are displayed out of order, like 1, 3, 2, 4 or 1, 2, 0. I replaced seasons with their titles, e.g. replacing 'season 2' with '更多 出包王女', maybe Jellyfin sorts seasons not by season number in the metadata but by name and that's the reason causing the problem.

![image](https://github.com/jellyfin/jellyfin/assets/73766358/bc4238be-b292-4d33-9703-acd77fc4ea6d)
Season 2 is placed after Season 3.

![image](https://github.com/jellyfin/jellyfin/assets/73766358/c1d0a97e-ef73-4e37-8148-53d82ca4ce1f)
Season 0(Specials) is placed after Season 2.

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Synology DSM 7.2-64561
- Linux Kernel:
- Virtualization: Docker nyanmisaka/jellyfin:latest
- Clients: Browser and Jellyfin Media Player
- Browser: Edge 119.0.2151.72
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zuavra** [comment]
This has also started happening to me recently. Adding new seasons to a show inserts them out of order (eg. adding 6-7 to 1-5 became 1,2,3,6,7,4,5). Changing the "sort by" in the show metadata seems to have no effect.

**Comment by zuavra** [comment]
Nevermind, I found the reason: this is caused by the value in the "sort title" field of each individual season's metadata. Depending on which plugin was used to fetch the metadata at the time, some of them will have "Season 5", or just "5", or blank etc. leading to incorrect orders. Editing the metadata for each season and making sure all seasons have the same kind of value will fix it. After you're done editing you will have to refresh the show page to see the new order.
