### ISSUE TITLE
[Issue]: does not see subdirectories in the user's directory

### ISSUE THREAD

**Issue by saber716rus** [jellyfin/jellyfin#10824]
### Please describe your bug

when selecting a directory for the media library, then I don't see any subdirectories in the user's directory. I tried to install both from flatpack and through the command on the server, but the result is the same.

saber716rus@saber716rus-BMW XX 9 ~ [0|1]> apt list --installed | grep jelly fun

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

jelly fun-FFMPEG 5/unknown,now 5.1.4-2-Jammy amd64 [installed, automatically]
jelly fun-server/unknown,now 10.8.13-1 amd64 [installed, automatically]
jelly finweb/unknown,now 10.8.13-1 all [installed, automatically]
jelly fun/unknown,now 10.8.13-1 all [installed]
saber716rus@saber716rus-BOM-WXX9 ~>

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Green Linux 21.2 (fork Linux mint 21)
- Linux Kernel:6.6.10-x64v3-xanmod1
- Virtualization:no
- Clients:Browser
- Browser:yandex-browser-stable
- FFmpeg Version: 7:4.4.2-0ubuntu0.22.04.1, 
  jellyfin-ffmpeg5 5.1.4-2-jammy
- Playback Method:
- Hardware Acceleration:
- GPU Model:AMDGPU
- Plugins:none
- Reverse Proxy:none
- Base URL:none
- Networking:host
- Storage:local
```

### Please attach any browser or client logs here

[Log.txt](https://github.com/jellyfin/jellyfin/files/13851594/Log.txt)
[Log (1).txt](https://github.com/jellyfin/jellyfin/files/13851595/Log.1.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
This is not a Jellyfin bug but wrong Linux permissions. By default only the corresponding system users have access to their home folders.

I strongly suggest moving your data out of the user folder to a common shared location where you can either grant all users or only the jellyfin user access to the data.

Since this is not a Jellyfin but a permission issue, please either seek help on our forum or check the various online tutorials on Linux permissions.
