### ISSUE TITLE
[Issue]: web interface still available at 8096 even after changing it

### ISSUE THREAD

**Issue by eobet** [jellyfin/jellyfin#10896]
### Please describe your bug

I changed the Server Address Settings and the Remote Access Settings in the Advanced Networking part of the web interface to both use port 8097, and I'm still able to access the web interface via localhost:8096 (even after the system tray app says the server is stopped too, and that's despite me installing it using the default settings which, if I read things correctly, does not use Windows services).

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization:
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: default?
- Playback Method: not relevant
- Hardware Acceleration: none
- GPU Model: none
- Plugins: default?
- Reverse Proxy: none
- Base URL: none
- Networking: Mesh wifi/ethernet
- Storage: local
```

### Jellyfin logs

```shell
I see no ports in the log at all.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please try rebooting your system.

**Comment by crobibero** [comment]
It's likely that you're just accessing a cached version of the web client.

**Comment by eobet** [comment]
Not only have I restarted several times, but I've also turned off the Auto Start option in the system tray app, and I *still* see Jellyfin in the browser even though it supposedly isn't running.

Now, fully disclosure: What I actually expect to see is my Emby server which was already installed and running on that same default port (and that's installed as a service because that's how Emby does it by default). But ever since I installed Jellyfin, I'm locked out of my Emby server.

**Comment by danielb2** [comment]
you'll need to actually delete the cached version from your browser. It's the browser which is caching it.

<img width="343" alt="Screenshot 2024-02-27 at 20 41 50" src="https://github.com/jellyfin/jellyfin/assets/26678/9e195071-2588-467c-b806-be8a03895d6b">

you'll want to delete it here (example is using github)

I came here because after changing the port, running "Launch web ui" still opens the original port, not the new one. 

btw, one way you can easily test is to just manually browse to your new port
