### ISSUE TITLE
Issues with 265/hevc playback on TV

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/jellyfin#10944]
**Media Info of the file**

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

![Skærmbillede 2024-02-01 184652](https://github.com/jellyfin/jellyfin/assets/6765298/af7fac9c-30e3-43af-972d-e7a7811615db)

**Server System (please complete the following information):**
 - OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows] win10
 - Jellyfin Version: [e.g. 10.0.1] 10.8.13
 - Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K] amf on 2400g
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC] google tv 4k
 - OS: [e.g. iOS, Android, Windows, macOS] android
 - Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron] android
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0] 0.16

Player on TV says "giving up, too many attempts"
In the user panel, it just says "user stated playing movie" & "user stopped playing movie"
I have no idea what the issue is, or where to start.

Is this of any use?
"[AVHWDeviceContext @ 000002122f85b400] Using device 1002:15dd (AMD Radeon(TM) RX Vega 11 Graphics).
[matroska,webm @ 000002122e06d900] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options"

**Comment by felix920506** [comment]
Please include the ENTIRE ffmpeg log.

**Comment by felix920506** [comment]
Can you also provide Jellyfin logs?

**Comment by fusk-l** [comment]
Not sure where they are located.

Vh
Nicolaj

fre. 2. feb. 2024 01.12 skrev felix920506 ***@***.***>:

**Comment by felix920506** [comment]
they are alongside the ffmpeg logs in the logs section of the dashboard

**Comment by fusk-l** [comment]
As it looks to me, on the dashboard, there is one location for logs "server/logs" and there are no "log_xxxx" file from around that time.

**Comment by MichaelRUSF** [comment]
I think this is an audio problem, not a video codec issue.  Is this the only media you are having issues with? 

If I force transcode TrueHD 7.1 media, I get the same results.  Any media transcoded to AAC 7.1 fails to play in exoplayer: [debug logcat file](https://github.com/jellyfin/jellyfin/files/14144007/logat.AAC7.1.txt)

Workarounds:
1. It's transcoding because the bitrate is set too low. Change this setting in the AndroidTV client and see if it plays without transcoding.  
Preferences --> Playback --> Max Streaming bitrate: change to 120 Mbits/s

3. If it doesn't work after changing the bitrate, then you can try using VLC.
Preferences --> Playback --> Preferred media player: change to LiibVLC

**Comment by fusk-l** [comment]
Oh, i thought it would always do 120mbit. It is set to auto, but i imagined that because the network is always fast enough, and the igpu was also fast enough, it would always default to 120mbit.
I will try setting it manually.

Could this has something to do with initial bitrate, it starts at a lower value and increases it when it's detected that the network is fast enough?
If that is not the case, what determines when and if it'll increase to 120mbit automatically?

Player is also set to auto, here i also imagined that if one failed, it would automatically try a different one. I assumed that is what "auto" meant.

**Comment by fusk-l** [comment]
i changed it from "auto" to 120mbit and now it worked. So i guess i'll just leave the default as 120mbit from now on.

**Comment by MichaelRUSF** [comment]
Sounds like it's direct playing now and just taking some time to buffer. I would try something simple like rebooting your router and see if that helps.

**Comment by fusk-l** [comment]
Did a network test and everything is running as it should, latency, speed etc. TV and chromecast also appears to run just fine. Can reboot it too.

**Comment by MichaelRUSF** [comment]
The [code](https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/util/AutoBitrate.kt) uses the [detectBitrate ](https://javadoc.io/doc/org.jellyfin.sdk/jellyfin-api/latest/jellyfin-api/org.jellyfin.sdk.api.extensions/detect-bitrate.html)function from the SDK  to calculate the auto bitrate. I see you are already on a [thread ](https://github.com/jellyfin/jellyfin-androidtv/issues/2601)where the developer specifically says "At this moment we do not recommend using the "auto" bitrate and it is disabled by default."

Back to your original issue about the stream failing to transcode causing the player to error out. I was able to test out exoplayer on the master and transcoding TrueHD or DTSHD 7.1 audio to AAC now transcodes without issue. 10.9 doesn't yet work with the AndriodTV client so if you are playing media that transcodes to AAC 7.1, then the player will fail.

I think the issue is resolved and you might want to check out the [networking troubleshooting forum](https://forum.jellyfin.org/f-networking-access).

**Comment by fusk-l** [comment]
I did not know about that thread, just looked through it don't recognise it. But if it's not recommended, then I won't use it.

**Comment by MichaelRUSF** [comment]
> I did not know about that thread, just looked through it don't recognise it. But if it's not recommended, then I won't use it.

Lol, I definitely need to get some glasses. There's a username that has a similar structure to yours. Apologies for the mix-up.

**Comment by Zbuddy13** [comment]
> I think this is an audio problem, not a video codec issue. Is this the only media you are having issues with?
> 
> If I force transcode TrueHD 7.1 media, I get the same results. Any media transcoded to AAC 7.1 fails to play in exoplayer: [debug logcat file](https://github.com/jellyfin/jellyfin/files/14144007/logat.AAC7.1.txt)
> 
> Workarounds:
> 
> 1. It's transcoding because the bitrate is set too low. Change this setting in the AndroidTV client and see if it plays without transcoding.
>    Preferences --> Playback --> Max Streaming bitrate: change to 120 Mbits/s
> 2. If it doesn't work after changing the bitrate, then you can try using VLC.
>    Preferences --> Playback --> Preferred media player: change to LiibVLC

Changing the player to LibVLC worked for me on both my fire tv and nvidia shield. Thanks
