### ISSUE TITLE
[Issue]: Wrong play time shown

### ISSUE THREAD

**Issue by stefan1983** [jellyfin/jellyfin#11113]
### Please describe your bug

Hey there,

I am using Jellyfin 10.8.13 on a Linux server 5.10.0-0.deb10.16-amd64 Debian 5.10.127-2~bpo10+1 (2022-07-28) x86_64.
When using the web browser or any client to play my music, I always get a wrong play time shown. Especially when using gapless tracks (live albums) those are completely off:

Web player:
![308967832-20901e66-b8b3-436a-8eac-807f9bbf3e07](https://github.com/jellyfin/jellyfin/assets/8542806/55d498fa-c4a2-4e3a-8753-d3f692ec1e9b)

Finamp (counts further):
![308661745-136cd2cd-dae6-4ce7-9f2e-adc985eeeca9](https://github.com/jellyfin/jellyfin/assets/8542806/531a347d-1877-437c-aac3-10545ecbd15f)

Is there anything I can do on server side?
The files don't have any issues when playing somewhere else (foobar2000, IINA, VLC...).
That are just standard MP3 or FLAC files.

### Reproduction Steps

Just play music in the web or any available jellyfin compatible app (iOS / macOS).

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian
- Linux Kernel: -
- Virtualization: - 
- Clients: WEB, Jellyfin iOS App, Finamp
- Browser: Safari / Chrome
- FFmpeg Version: -  
- Playback Method: -
- Hardware Acceleration: none
- GPU Model: Intel Onboard
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Attached
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefan1983** [comment]
[Log.txt](https://github.com/jellyfin/jellyfin/files/14500578/Log.txt)

**Comment by stefan1983** [comment]
I would be able to deliver sample files if needed.

**Comment by stefan1983** [comment]
I just found out that it is specific to macOS Safari. When using another browser, there is no such issue. 
Currently I am using Safari Version 17.3.1:

<img width="396" alt="image" src="https://github.com/jellyfin/jellyfin/assets/8542806/226820da-aaf6-40d8-8034-b5acb4168a78">

**Comment by gnattu** [comment]
It seems to be related to jellyfin/jellyfin-roku#1629, and it happens to certain media files where the playback time is encoded weirdly.

**Comment by Chaphasilor** [comment]
@stefan1983 you could try re-encoding your files with ffmpeg or Audacity. If @gnattu is correct and it's a problem with the track itself, that might help 🤔

**Comment by gnattu** [comment]
Well, at this point, we cannot do much here.

For some tracks/formats (FLAC/VBR MP3), we have to set `AVURLAssetPreferPreciseDurationAndTimingKey : true` on Apple platforms; otherwise, seeking would result in incorrect timing (off by a few seconds or completely off). This option will have a performance impact, so it is disabled by default.

This option can be set by native players, but I'm not sure if there is any way to set it for browsers. Perhaps we can implement an audio-remuxing mechanism to remux FLAC into fmp4 containers and stream it, which could potentially solve this issue not only for Apple platforms but also for the Roku case I've linked.

**Comment by BBaoVanC** [comment]
This is still an issue, please do not close.
