### ISSUE TITLE
Handle movies with multiple/split files as one item

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1125]
### Problem:
currently (master branch in docker) when there is a movie with two files(CDs), lets say this structure:

Amazing.Movie.2002.DTS.Bluray.x264/CD1/cd1.mkv
Amazing.Movie.2002.DTS.Bluray.x264/CD2/cd2.mkv

jellyfin detects two movies with the same name("Amazing Movie").

### Idea:
In case of a "movie" library, I think it makes sense to join these files with ffmpeg or somehow combine them into one item/movie

**Comment by trumblejoe** [comment]
Your issue is a little muddy using two directories below the main movie directory. I'm going to simplify down a second case, combining multiple/split parts within the same movie directory.

Media\Sports\Soccer\USWNT\2017\USWNT - 2017-07-27 - ToN USA vs Aus pt1.mkv
Media\Sports\Soccer\USWNT\2017\USWNT - 2017-07-27 - ToN USA vs Aus pt2.mkv

These show up as two entries in my server. I would also prefer they be one.

Here's a list of keywords to consider when adding this feature in,

cdX
discX
diskX
dvdX
partX
ptX
