### ISSUE TITLE
Duplicate Playlist, Maintain Order

### ISSUE THREAD

**Issue by pixel24** [jellyfin/jellyfin#11354]
### Please describe your bug

When duplicating a playlist, the track order is not preserved. I have a playlist that I want to use as a base for a new playlist. When I select the playlist in the web UI and choose "Add to Playlist" -> "New", I get a new playlist. However, the tracks are re-sorted or the original order is not preserved. Is this intentional?

### Reproduction Steps

1. Create a playlist with various music tracks.
2. Rearrange the order of the tracks.
3. Use this playlist to create a new playlist.
4. The order will be different.

### Jellyfin Version

10.8.13

### if other:

none

### Environment

```markdown
- OS: Ubuntu 23.04
- Linux Kernel: 6.2.0-39-generic
- Virtualization: Proxmox / KVM
- Clients: Webclient
- Browser: Firefox
```

### Jellyfin logs

```shell
To the operation, nothing is being written to the log.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solidsnake1298** [comment]
I confirmed this behavior in both stable and the current unstable build.

**Comment by nickyg91** [comment]
Hello! I am _very_ new to this codebase as I literally just got it running locally and started looking over it. I did some digging, and it seems like the issue stems from the Playlist.GetPlaylistItems method.  The InternalItemsQuery that runs (specifically in the case if the item is a Folder type) tells the query to order items by ItemSortBy.SortName and SortOrder.Ascending. Removing this line fixes the issue - but due to my unfamiliarity with the codebase I am not sure if this would break existing functionality. If you'd like, you can assign the issue to me, and I can dig in a little deeper to make sure it does not break anything else.

**Comment by Chaphasilor** [comment]
I think changing the default sorting when fetching playlist items is reasonable here. I see little use for the default sort, and since playlist items are inherently ordered, they should be returned in that order by default.

And any clients that fetch playlists will most likely apply the correct sorting already, which shouldn't break.

**Comment by ldexterldesign** [comment]
👋 https://github.com/jellyfin/jellyfin-web/issues/7019
