### ISSUE TITLE
Doesn't work with archived XMLTV (zip or gz)

### ISSUE THREAD

**Issue by rindazzz** [jellyfin/jellyfin#1135]

**Comment by fruhnow** [comment]
Could you please provide more detail using the given issue template?

**Comment by 0ddb0d** [comment]
**Describe the bug**
TV guide doesn't accept gzipped XMLTV.

**To Reproduce**
Add an XMLTV guide feed that is gzipped.

**Expected behavior**
Guide data should be decompressed by SharpCompress and imported in to Jellyfin.

**Logs**
[https://pastebin.com/Vs8Fp1tV](url)
N.B. My location and API key have been intentionally removed from the feed URI but will be supplied on request if a dev deems it necessary.

**System (please complete the following information):**
 - OS: Generic Linux
 - Browser: Vivaldi 2.4.1488.35 (Chrome 73.0.3683.88)
 - Jellyfin Version: 10.2.2
 - Reverse proxy: No

**Comment by fruhnow** [comment]
Thank you @0ddb0d!

I just tested this with a gzipped xml from my tvheadend instance and it was working flawlessly.

according to your logs, your gzip might be corrupt? 

> SharpCompress.Compressors.Deflate.ZlibException: Bad GZIP header.

anything to help me reproduce this is appreciated.

Thanks in Advance

**Comment by 0ddb0d** [comment]
> according to your logs, your gzip might be corrupt?
> 
> > SharpCompress.Compressors.Deflate.ZlibException: Bad GZIP header.

I don't think so, then again I didn't build Jellyfin myself. 

This [EPG.xml.gz](https://github.com/jellyfin/jellyfin/files/3041408/EPG.xml.gz) doesn't work for me.

**Comment by EraYaN** [comment]
Is that the file directly downloaded by jellyfin or the download you initiated for the same link as the browser?

**Comment by 0ddb0d** [comment]
@EraYaN That file was downloaded with wget because AFAIK the compressed file is not retained by Jellyfin after decompression to the xmltv cache directory.

> I just tested this with a gzipped xml from my tvheadend instance and it was working flawlessly.
> 
> according to your logs, your gzip might be corrupt?

I was too hasty and not clear enough in my last post as the EPG actually does work for me.

Re-reading the log and having a look at the [XmlTvListingsProvider.cs source](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs) I've just realised what the log actually says is that Jellyfin is trying to decompress the cached XML file. It appears that UnzipIfNeeded is supposed to return the file untouched if it's not gzipped, this isn't happening as we're seeing error messages from inside both try-catch blocks.

Perhaps a less naive check should be performed as XML, GZ and ZIP formats all have standardised header bytes, this path string matching stuff seems iffy (pun intended).

While someone is fixing this issue could they also review [this](https://github.com/jellyfin/jellyfin/blob/a1d50a6d055c414c95fa0ea2bf58db79afb6dc74/Emby.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs#L82) please?
