### ISSUE TITLE
[Issue]: Jellyfin uses "Artist" tag rather than "Artists" tag

### ISSUE THREAD

**Issue by NicholasFlamy** [jellyfin/jellyfin#11411]
### Please describe your bug

So MusicBrainz Picard and therefore the entire MusicBrainz database uses "Artists" as the field for pulling the artists in the song and formats it with semicolons (when you set that as delimiter and use ID3V2.3) and uses "Artist" 

Look at screenshots to see more detail.

I would suggest using the "Artists" tag to determine which artists are in the song. Edit: Fallback to "Artist" if "Artists" is unpopulated.

Read about the difference which seems to stem from Kodi:
https://community.metabrainz.org/t/artist-vs-artists-tag/672616

### Reproduction Steps

Tag some music with multiple artists using MusicBrainz Picard. Add Music Library to Jellyfin with all the internet based metadata providers disabled except for artist related ones (so that you get artist images and descriptions, but only use embedded metadata for albums and songs).

### Jellyfin Version

Unstable (master branch)

### if other:

I tested on 10.8.13 as well as unstable.

### Environment

```markdown
- OS: TrueNAS Scale
- Linux Kernel:
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Not relevant as there is no error.
```

### Please attach any screenshots here

Jellyfin displaying artists:
![Screenshot 2024-04-22 201642](https://github.com/jellyfin/jellyfin/assets/30300649/69981cf9-e8a6-41c8-ba1d-9672943166fe)

Jellyfin Metadata not showing artists correctly:
![Screenshot 2024-04-22 201256](https://github.com/jellyfin/jellyfin/assets/30300649/352b9682-12a3-47b2-a330-fb156cdd550a)

Jellyfin making a mess by adding an artist for two artists but only for the times when the artists show up in "Artist" but for the other songs with other artists that aren't listed under "Artist" and only under "Artists" not showing up:
![Screenshot 2024-04-22 202213](https://github.com/jellyfin/jellyfin/assets/30300649/5afc7844-26e3-4fce-a0af-81cb7c3401fd)

MusicBrainz Picard and the "Artist" and "Artists" tag:
![Screenshot 2024-04-22 201323](https://github.com/jellyfin/jellyfin/assets/30300649/5a10c4a5-f79e-46a2-8090-17992294fba4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NicholasFlamy** [comment]
I would also suggest falling back to the "Artist" tag if the "Artists" tag is unpopulated.

(And if anyone is worried about screwing up people's library with an update, make it opt-in for existing users, or don't worry, as not many people use Jellyfin for music and it's a mess as it is so this may be a big improvement.)

**Comment by NicholasFlamy** [comment]
Maybe changing this from `var artist = tags.GetFirstNotNullNorWhiteSpaceValue("artist");` to `var artist = tags.GetFirstNotNullNorWhiteSpaceValue("artists");` would do the trick:

https://github.com/jellyfin/jellyfin/blob/374b6ca0e22719df25b8d0aa51c510515b928104/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L179

**Comment by gnattu** [comment]
The problem with this tag is that it's a non-standard user tag, so there isn't a well-defined usage for it and it is unlikely to be supplied in a lot of current files. Like all non-standard behavior, the usage of this tag hasn't been universally agreed upon. Just because Kodi uses this tag in a certain way doesn't mean everyone else uses it the same way. Defaulting to this tag would greatly impact database entry creation and isn't an easy migration, potentially causing the library's metadata to be entirely re-generated.

Metadata handling for tracks with multiple artists is always challenging because there is no standard way to handle it, and it's full of implementation-specific approaches. I'm not against improving the handling for Jellyfin, but we don't necessarily have to follow exactly what Kodi is doing, especially for default behavior change that would cause huge database change.

**Comment by NicholasFlamy** [comment]
> The problem with this tag is that it's a non-standard user tag, so there isn't a well-defined usage for it and it is unlikely to be supplied in a lot of current files. Like all non-standard behavior, the usage of this tag hasn't been universally agreed upon. Just because Kodi uses this tag in a certain way doesn't mean everyone else uses it the same way. Defaulting to this tag would greatly impact database entry creation and isn't an easy migration, potentially causing the library's metadata to be entirely re-generated.
> 
> Metadata handling for tracks with multiple artists is always challenging because there is no standard way to handle it, and it's full of implementation-specific approaches. I'm not against improving the handling for Jellyfin, but we don't necessarily have to follow exactly what Kodi is doing, especially for default behavior change that would cause huge database change.

Okay. All of my music is tagged with MusicBrainz Picard, which does the metadata this way. I think somehow Kodi and MusicBrainz worked together or something. I think as a workaround I could make a script to write "Artists" tags to the "Artist" tag but I'm not sure if this would break something else.

**Comment by NicholasFlamy** [comment]
This seems to support the idea that they are working together to some degree:
"Kodi has strong support for MusicBrainz tagging. It is highly recommended that users tag their music files using MusicBrainz Picard." https://kodi.wiki/view/Music_tagging#MusicBrainz

**Comment by gnattu** [comment]
> Okay. All of my music is tagged with MusicBrainz Picard, which does the metadata this way. I think somehow Kodi and MusicBrainz worked together or something. I think as a workaround I could make a script to write "Artists" tags to the "Artist" tag but I'm not sure if this would break something else.

You will need to replace all metadata for sure, but you will also see the artist being listed separately instead of a formatted string. Kodi uses the extra non-standard tag to allow the artist being displayed as a formatted string like `Foo feat. Bar` instead of only `Foo, Bar`, while still indexing multiple artists correctly. If you don't care about this, then retagging it into the artist field would be good enough, as Jellyfin already handles this.

To make Jellyfin work in the Kodi way, we need to modify the database schema to support an extra field so that the artist being displayed can be different from the actual artist lists, and that requires much more work.

**Comment by NicholasFlamy** [comment]
Yeah it would be nice if it could do this. I saw this on an issue about the artist separators (which is a problem because FFmpeg doesn't support, well it's broken and therefore I don't consider it supported as it doesn't meet the spec, ID3v2.4) that this has become a thing:
"Problem is, there are so many crappy music players that choke on multi-valued fields, that MusicBrainz Picard has started using custom tags Artist**s** and Album Artist**s** instead. The idea is that you keep a one-value field `ARTIST` for buggy legacy applications, and sophisticated modern players are smart enough to read this new multi-value field `ARTISTS`."
#2305 https://github.com/jellyfin/jellyfin/issues/2305#issuecomment-809161542

**Comment by NicholasFlamy** [comment]
> which is a problem because FFmpeg doesn't support, well it's broken and therefore I don't consider it supported as it doesn't meet the spec, ID3v2.4 so you're stuck with ID3v2.3

Jellyfin switched to something else (I think taglib) for metadata parsing so that should be fixed.

**Comment by NicholasFlamy** [comment]
It looks as though Jellyfin being somewhat of a mess with Music metadata stems from Music metadata being a disaster.

**Comment by Shadowghost** [comment]
We're using taglib now (which sadly has its own problems) and it properly supports reading multiple tags of the same kind if the underlying tagging format supports it.

A sidenote for "not supported" use case: ID3 on FLAC is not FLAC spec conformant and therefore fails.

**Comment by NicholasFlamy** [comment]
Setting My Artist tag to what is in my Artists tag works, but is not a full solution because the formatting of the artists isn't applied (because it doesn't exist, since the combination of the tags served that purpose).

MusicBrainz Picard script in case someone stumbles across this:
```
$set(artist,%artists%)
```

P.S.
I also found a weird issue where an artist with a dash gets spaces added around the dashes. Such as `K-391` becoming `K - 391`. The Artist page is only accessible though the song they are part of. So I don't see the artist on the artist page. I'll check for similar issues and if there is no existing issue I'll open one (I'll also double check unstable before that).

**Comment by NicholasFlamy** [comment]
> P.S. I also found a weird issue where an artist with a dash gets spaces added around the dashes. Such as `K-391` becoming `K - 391`. The Artist page is only accessible though the song they are part of. So I don't see the artist on the artist page. I'll check for similar issues and if there is no existing issue I'll open one (I'll also double check unstable before that).
> 
> Edit: The space before and after is part of the dash character. It's some weird ASCII vs UTF thing I assume.

It's fixed in unstable. It's a ASCII vs UTF thing and the dash showing up was likely UTF and the dash in the metadata and what is supposed to show up is ASCII.

**Comment by rosxz** [comment]
Sorry, I probably shouldn't necropost here, but would it be possible to add functionaly to use the ALBUMARTISTS tag as well to have an album correctly attributed to multiple artists? If in Jellyfin's case only one artist can be assigned to a given album, it could very well be that it displays only the first artist as the album artist, but in the other artists' pages you could see something like "appears in".

As far as i understand, the tag is identical in nature to the ARTISTS tag.

![Image](https://github.com/user-attachments/assets/1761e193-0fff-4dae-95db-66919236ae81)
The songs are correctly attributed to the two different artist since I enabled the option to use the ARTISTS tag in the settings, but the album artist is still the joined artist.

Gonic has the intended behavior working correctly so if necessary maybe look there for inspiration (?).
