### ISSUE TITLE
[Issue]: Unnecessary transcoding of LiveTV instead of Directplay

### ISSUE THREAD

**Issue by avionics75** [jellyfin/jellyfin#11847]
### Please describe your bug

Following the publishing of 10.9.3 and PR#11801, I'm now facing a forced transcoding of any LiveTV stream with a 20Mb/s bitrate even though I was able to directplay the LiveTV stream on 10.9.2 with a local broadband of 1gb/s.
This becomes problematic when multiple users want to watch LiveTV, the server performance is affected by multiple transcodings. 

Is there any way to add an option to disable this forced transcoding and return to directplay when it is available ?

Reverting to 10.9.2 for now

### Reproduction Steps

No document attached

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: Windows 11 x64
- Linux Kernel:
- Virtualization:
- Clients: AndroidTV, WebOS
- Browser: 
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Yes
- GPU Model: Nvidia GTX1070
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: 1GB/S
- Storage: 240 GB/SSD
```

### Jellyfin logs

```shell
No logs attached
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
This is a hard decision for use because we are having people with playback error due to too high bitrate

Adding option usually introduces API change with normally will not happen for patch releases

Our first goal is to make it play, how good it plays is the afterthought for now.

Can you share your original stream's bitrate? Maybe we can increase the bitrate a bit for a workaround.

**Comment by avionics75** [comment]
Thanks for the reply ! 

According to VLC and ffprobe here are the results: 

LiveTV 4K HEVC HDR 10 Bits : Bitrate of around 17 Mbt/s

Input #0, mpegts, from 'http://127.0.0.1:8866/live?channel=52&client=52':
  Duration: N/A, start: 58902.315967, bitrate: N/A
  Program 2305
  Stream #0:0[0xbcd]: Video: hevc (Main 10) ([36][0][0][0] / 0x0024), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn
  Stream #0:1[0xbce]: Data: bin_data (AC-4 / 0x342D4341)
  Stream #0:2[0xbd8](fre): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:3[0xbd9](qaa): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:4[0xbda](fre): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s (visual impaired) (descriptions)
  Stream #0:5[0xbdb](fre): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
  Stream #0:6[0xbdc](fre): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)

LiveTV 1080p h264 : Bitrate of around 6Mbts/s 

Input #0, mpegts, from 'http://127.0.0.1:8866/live?channel=6&client=6':
  Duration: N/A, start: 30931.099211, bitrate: N/A
  Program 1025
  Stream #0:0[0x78]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x82](fra): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 192 kb/s
  Stream #0:2[0x83](fra): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 96 kb/s (visual impaired) (descriptions)
  Stream #0:3[0x84](qaa): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:4[0x8c](fra): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
  Stream #0:5[0x8d](fra): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
  Stream #0:6[0xaa]: Unknown: none ([5][0][0][0] / 0x0005)
  Stream #0:7[0xab]: Unknown: none ([11][0][0][0] / 0x000B)
  Stream #0:8[0xac]: Unknown: none ([12][0][0][0] / 0x000C)


It's actually weird that Jellyfin 10.9.3 is automatically transcoding as the bitrate is way below the 20Mbt/s hard limit ...

**Comment by gnattu** [comment]
Your tuner returns an MPEG-TS stream directly and doesn't use HLS, right? That might be the problem. Due to TV tuners' unpredictable behavior, it is impossible to reliably detect the type of stream they return. The MIME type could be inaccurate, and the URL might lack a file extension. We used to try detecting these streams, but it caused many users' live TV to break because of tuners' broken HTTP server implementations. We reversed the decision, opting for the safest way, which results in more transcoding but ensures the stream plays for more users. While it's less than ideal that some users are forced to transcode like you, it's better than many users not being able to play the stream at all.

Additionally, ffprobe reports the bitrate as "N/A," which means it cannot probe the source bitrate. In our logic, "N/A" is interpreted as the maximum signed integer, which is why we apply the bitrate cap.

For your situation, we need more user-set options for TV tuners, and that might be a 10.10 feature. The goal for 10.9 is to "let it play as much as possible." Or if the team agrees on an API change for liveTV, we can make this happen in 10.9.
