### ISSUE TITLE
Add support for HDHomeRun TV guide API

### ISSUE THREAD

**Issue by 0ddb0d** [jellyfin/jellyfin#1186]
**Is your feature request related to a problem? Please describe.**
Silicon Dust provide XMLTV guide data to customers for free, limited to 4 hours for non-DVR subscribers (they claim 24 hours on their website?!?) and 14 days for subscribers.

**Describe the solution you'd like**
Integrated retrieval of guide data directly from SiliconDust, from the script linked below it doesn't seem very difficult to implement this feature and even have setup be automatic if an HDHR tuner is found on the network.

**Describe alternatives you've considered**
I'm currently using the python script from [https://forum.libreelec.tv/thread/12228-tvheadend-epg-guide-from-hdhomerun/](url) to grab guide data for Jellyfin.

**Additional context**
Apparently written permission has to be obtained from SiliconDust to use this data in third party software, using Kodi as a yardstick they seem to be friendly to free software projects. The limitation for non-DVR subscribers is a little disappointing as is the low number of supported regions but this could still be useful for some users.

**Comment by BobOkisama** [comment]
Hey, thanks for pointing this out! Currently I am running zap2xml to get data, but it seems to be.... not the best. I tried out this script and it seems to work quite well! The .xml file is MUCH smaller than the one from zap, looks to have nearly as much info, and the icons are way better quality. I would love to see this integrated into JF as well, it is working VERY well!

**Comment by JustAMan** [comment]
I think this is better suited as a plugin, do you have any arguments for having it in the server core?

**Comment by 0ddb0d** [comment]
Nope. Plugin is the way to go.

**Comment by dkuchay** [comment]
Its 2022 and this issue is not really solved. Unless pointing the finger and making the user go elsewhere for support on this is considered "supported".  Python script no longer working. Bash script is also no longer working. I am a subscriber to hdhomerun guide and at current the only way to get guide data that I pay for is to pay for another service or run a whole docker container just for a web-request? Kodi software has absolutely no issues pulling this data nor does Plex. Is it possible the developer could revisit this feature and duplicate what either of the other mentioned apps use for this? I saw mention of a plugin in my searches. Not sure if this is normal but plugin repo is empty. Nothing in the catalog. Would like to move away from Plex but wont be able to until I can get live TV working. Not interested in installing a whole docker container when a single file can be the solution.

**Comment by iophobia** [comment]
Since a "single file can be the solution" why not code it yourself instead of condescendingly bashing devs of an open-source project who - I guess - don't even have the HW to verify a successful integration whereas you have it.

**Comment by darylkk** [comment]
One doesnt need hardware when most other tv centric dvr offereing open source projects have hdhomerun solved. TVheadend and kodi are examples. Apologies for offending. Not everyone who posts on github is code capabe.
