### ISSUE TITLE
[Feature Request] add full-width comma as _nameDelimiters

### ISSUE THREAD

**Issue by yuygfgg** [jellyfin/jellyfin#11965]
Currently, jellyfin splits artist name by these characters: ``` '/', '|', ';', '\\' ```

I would like to add ``` ，``` as _nameDelimiters. It's used in some Chinese and Japanese CDs and seldom appear in an artist name.

**Comment by TheMelmacian** [comment]
Modern tag systems (ID3v2.4, FLAC tags/Vorbis comments, ape tags etc.) allow multiple tags with the same name. Instead of using a delimiter you could use these tagging feature to add multiple artists, genres etc. to an audio file.

Having a list of predefined delimiters means you also have to maintain a list of exceptions since some artists use these delimiters in their name.

**Comment by gnattu** [comment]
> Having a list of predefined delimiters means you also have to maintain a list of exceptions since some artists use these delimiters in their name.

This is why this needs to be user-configurable and not a hard-coded list.

**Comment by yuygfgg** [comment]
> Modern tag systems (ID3v2.4, FLAC tags/Vorbis comments, ape tags etc.) allow multiple tags with the same name. Instead of using a delimiter you could use these tagging feature to add multiple artists, genres etc. to an audio file.
> 
> Having a list of predefined delimiters means you also have to maintain a list of exceptions since some artists use these delimiters in their name.

That's for sure. But for files created in the past or from cue sheets(which most high-quality rip requires), they need those delimiters.

**Comment by felix920506** [comment]
Duplicate #10730
