### ISSUE TITLE
Setup bounties for directed development

### ISSUE THREAD

**Issue by manetherenio** [jellyfin/jellyfin#1203]
Can you consider setting up a bounty system for certain larger features through something like Bountysource? Your OpenCollective funding system seems to work well with ongoing development costs, but large one-time costs like making a new client app might be better served by a bounty system.

In particular, I'd like to financially support getting the Roku channel/client app officially published on the Roku store. I'm sure there are certification fees and other expenses that would make official publication low on the list of priorities unless there were a pool of money dedicated specifically to that effort.

**Comment by anthonylavado** [comment]
Gonna call in @jellyfin/core here for the rest of the opinion. What follows is mine.

---

We don’t have anything against people setting up bounties of their own if they choose, but we have thus far decided not to “officially” do so. We thought about it for a while, and were concerned with the idea of how we would value people’s time. 

It’s not to say that we would never do it ever, but it’s a tricky situation - other contributors have given up so much of their time and effort, I would want to reward them first before putting up a reward for another area.

**Comment by anthonylavado** [comment]
Also - just to add - we don’t have anything against spending money on certification/publishing costs/licensing as needed. The issue is even having the app to begin with. Apparently BrightScript coders are hard to come by 😅

**Comment by anthonylavado** [comment]
Closing this, as the original request has been answered...
also: https://github.com/jellyfin/jellyfin-roku

**Comment by joshuaboniface** [comment]
I never did leave my "official" stance here, so might as well so it's out there somewhere.

I'm against the idea of Bug bounties officially for the project. As @anthonylavado said, we don't actively *stop* anyone from trying to create them but we won't endorse them.

My main reason for being against them is simple: I don't like the idea of prioritizing features just because one or more people are able to throw dollars behind them. Basically, I think it's the wrong incentive for a project with the philosophy and goals we have. More specifically:

1. This privileges users with money to spare over those who don't, which I'm generally not a fan of - all features should be treated equally, or at least treated based on the overall needs of the project, rather than specific features for niche usecases that happen to have a bounty out.

2. They're not really compatible with the "doocratic" methodology we're striving for: we want to encourage people to work on features they use themselves and make them good - bounties on individual features tend, in my experience, to lead towards shoddy implementations that "work" today to collect the bounty, but make the software as a whole more unmaintainable - too much "oh I'll implement this terrible hack because $$$" already exists in this software because this is precisely how Emby operated, and that's a philosophy we're not intent on continuing.

3. It ruins our internal attempts to prioritize things, as much as we can within the "doocracy", by putting a big "implement this now" sign over the feature. It's one thing if this is unofficial, but trying to do so in an official capacity just screams "this is what's important to work on because $$$", while less glamorous parts of the codebase go ignored.

We're fundamentally, and explicitly, a *volunteer* project that is *free as in beer* as well as *free as in speech*, always - that's the philosophy we want to explicitly follow to differentiate ourselves from Plex and Emby, both of which started as "oh yea we're FOSS" but with long-term ulterior motives to take themselves closed for the benefit of the owners. Now I'm not going to say that there's a straight jump from "bug bounties" to "taking the software closed", but the "give us money to do X or Y" mentality is a critical part of that philosophy and our rejection of it helps, in my opinion, to define us as something different - community maintained, community focused, and free.

If you do want to send money our way to help out with infrastructure, feel free to check out [our OpenCollective](https://opencollective.com/jellyfin) which helps cover app store licenses, VPSes, domains, Patrons (for OMDB), etc. Or simply use Jellyfin, tell people about it, and help report issues/bugs/feature requests - this is one of the best things a normal, non-coder can do to help us out. There are so many niche usecases that having a huge userbase helps us find bugs faster and get them fixed properly!

**Comment by pktiuk** [comment]
One additional note about Polar.  It is not supposed to be a typical bounty platform. They are targeted for community members ([FAQ](https://polar.sh/docs/overview/faq/for-maintainers)).

> However, unlike traditional bounty solutions, we don't currently maintain a public directory of such rewards/bounties. Since such directories have historically attracted the wrong incentives, poor contributions and added overhead. Instead of rewarding your community. [Read more](https://blog.polar.sh/introducing-rewards/) about this design choice.

**Comment by pktiuk** [comment]
Some feature requests also contain people promising bounties for developers implemented selected features.   
Check this thread for `bounty` keyword: https://features.jellyfin.org/posts/57/support-download-of-transcoded-files


@joshuaboniface    
Are you going to respond?

**Comment by yavorl** [comment]
> My main reason for being against them is simple: I don't like the idea of prioritizing features just because one or more people are able to throw dollars behind them

What if you (the maintainers) decide what is fundable and what's not? You can open only the already prioritized work for funding.
