### ISSUE TITLE
[Issue]: Search is bad and slow.

### ISSUE THREAD

**Issue by VigibotDev** [jellyfin/jellyfin#12228]
### Please describe your bug

I need to search a library of 25K+ videos, and search result are not pertinent for a title keyword. please sort by title by size to get small title first, and only title.

### Reproduction Steps

Make a large jellyfin video database.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 11.11
- Linux Kernel: Last from 11.11
- Virtualization: No (dedicated Ryzen 9950X 64GB DDR5 6GHz CL30)
- Clients: All types
- Browser: All types
- FFmpeg Version: Last from Jellyfin Stable
- Playback Method: No video transcoding / audio transcoding only
- Hardware Acceleration: No
- GPU Model: No
- Plugins: No
- Reverse Proxy: Apache2
- Base URL: /jellyfin
- Networking: 10Gbps XGS-Pon
- Storage: 384TB Exos
```

### Jellyfin logs

```shell
No log required, all work good.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krim404** [comment]
can confirm, the search is absurdly slow on my system even with the database on SSD.

**Comment by caaptusss** [comment]
I confirm that the search motor is very slow. I have actually 3500 movies, and 800 complete series in the database.
When i make a seach in desktop web client (or on a app as LG or android app), the search result don't appear before 2-10 minutes !
The storage of the server if already on a RAID 0 SSD local mount.
Version of Jellyfin : 10.9.4.
Please tell me if you have a solution for that ?
Maybe add a index in the database ?

**Comment by VigibotDev** [comment]
My search speed is around 1 to 2 seconds for over 25,000 videos and 1,000 shows. However, with a few optimizations (such as better sorting == using shorter localized title strings before longer ones, and reducing the number of displayed results), it can be reduced to near-instantaneous, without any unfindable localized titles —similar to older Jellyfin server versions that I patched. The database is stored on a dedicated SSD.

**Comment by verybadsoldier** [comment]
I can confirm search also for me is too slow. Takes around 10 seconds. Jellyfin on latest version running in a Linux VM on a Windows host (Intel i5).
I can see Jellyfin maxing out all 3 CPUs cores in that time.

**Comment by verybadsoldier** [comment]
I assigned now all 6 cores to the VM and that improved the speed a bit, bringing it down to like 6–7 seconds for a search. But it is still too slow in my opinion and does not feel good.

**Comment by Knaspin** [comment]
Can confirm. Upgraded from 10.8.13 to 10.9.9 (docker) and the performance impact has been immense. No other changes in the setup.

I don't have hard numbers, but my perception is: results that before were "instantaneous" now take around 2~6 seconds. For reference, my library has around 4500 albums, 2500 movies & 500 shows.

Also, possily related to the "sucks" part of the issue: I'm pretty sure that in 10,8.x search was case insensitive. It is now case sensitive, for sure. Am I misremembering?

**Comment by nestmadt2h** [comment]
I've been using jellyfin for a few months now and I see that the search is very slow for the devices.

As a recommendation, it would be good if you could add in the configuration of the entire server the possibility of selecting what you want to search for.

Example:
-If I only want it to search for series, movies and music

-If I want it to skip the search for episodes

-If I want to include or not the search for people

In this way, users can define what they want to search for or what is available to search for.

**Comment by VigibotDev** [comment]
A basic nbResults Limit configuration, and the proper search order (smaller titles to longer titles) is perfect for huge database (about 500K vids). I already patched code and tested myself on previous versions. A bad search order like this and you can't search for some short and generic titles that use common words.

**Comment by krim404** [comment]
I've just discovered that this isn't an error with the search functionality itself, but rather with the GUI. 
When using jellyfin-vue, the search works almost instantly. I suspect this might be related to the autocomplete / predictive search feature.

**Comment by nodje** [comment]
I concur, without giving any numbers, it's too slow to be usable.
Hard to say where is the bottleneck, but it seems that there isn't any proper RDBMS database that would allow an indexed search. Or is there?
At least not documented and I can't see any process that would be a db in the container.

**Comment by verybadsoldier** [comment]
> many of these reports sound like you might have put your databases on raid Z. You cannot put sqlite on any COW fs ever. So if you have used ZFS, btrfs, xfs, etc and you have put jellyfin's .db files on those filesystems, you are malconfigured and are causing yourself massive write magnification.

For me, it is also very slow on a regular ext4.

**Comment by krim404** [comment]
I have the database on a raid5 (md) nvme pool formatted with ext4. So no. No ZFS.

**Comment by VigibotDev** [comment]
For me Jellyfin-Vue is unusable because too mutch video. Best is jellyfin with hacked code to just show small len titles to longer len titles, with a low limit

**Comment by felix920506** [comment]
External database support should hopefully land in 10.12, possibly 10.11 if things are going well.

**Comment by felix920506** [comment]
There is also a plugin interface for external search providers in the works

**Comment by krim404** [comment]
> External database support should hopefully land in 10.12, possibly 10.11 if things are going well.

i'm pretty sure this would fix this issue. I'm looking forward to it.

**Comment by sevenrats** [comment]
really the majority of suggestions on this thread either wouldn't work, have already been done, or would substantially slow the database down. if you have not even looked at the schema of the database before, or have no idea what the state of the database code is, please consider withholding your comments from this very busy thread.
@darthShadow I really don't see the team baking in a sqlite extension, our development direction with the db has been to increase flexibility not reduce it.  but i understand that the search plugin interface is supposed to enable cool stuff like elastic and meili, which should satisfy everybody's needs.

**Comment by sevenrats** [comment]
@felix920506 I say we limit this thread to discussion of the aforementioned potential bug.

**Comment by sevenrats** [comment]
@krim404 open an issue in jellyfin-vue please if it is hitting the server too much.

**Comment by krim404** [comment]
> @krim404 open an issue in jellyfin-vue please if it is hitting the server too much.

it doesnt, the regular jellyfin does. With vue its fast.

**Comment by Knaspin** [comment]
> This comment is suggesting that it was fast with 10.8 and turned slow with 10.9 which would mean we are talking about a bug or a regression here, and not a general behavior of SQLite, right? 
> I personally cannot really say if it was faster with 10.8, maybe I just didn't notice it.
 

It does seem like a regression of some sort. In my scenario, the only difference in the setup was bumping the jellyfin image version.

To sum up my experience, this is what I can report:
* I backed up jellyfin version 11.8.13's volume data (`/config/` & `/cache/`) and reused both for the new version (11.9.9)
* Search was noticeably slower -- from milliseconds to ~5 seconds (for any search terms).
  * Search also went from being case insensitive to case sensitive.
* Went back to 11.8.13 (bringing back the backups). Confirmed that everything continued working as before.


(Due to lack of time, I haven't been able to go through the release notes (and much less the code) to try and pinpoint the relevant changes, so I'll avoid unfounded speculations.)

**Comment by JPVenson** [comment]
To awnser this:
The current implementation of TypedBaseItem search is slow, complex and very static.
Given that the client implementations have equal terms associated with them, because the search interface itself isn't all that great any non optimally configured database will be slower, however i have seen 600TB librarys searching _just fine_ coming from SSDs. 

There is currently a rewrite of the Db access underway, which will also refactor many of the worst design patterns currently present, speeding up everything quite a bit (fingers crossed). We are aware of the issue and are working on it but this bug isn't really the place for this discussion.

**Comment by VigibotDev** [comment]
> https://gitlab.com/DomiStyle/jellysearch would be nice to have something native like this.

Awesome. This gave me the idea to hack the search with my own algorithm and reverse proxy.
I can do a fuzzy search in all TMDb titles in all languages ​​in about 50ms... For titles in Jellyfin database it will be instantaneous...

**Comment by VigibotDev** [comment]
Looks like Jellyfin 10.10.0 is getting better results in searches and SQL queries, removing the search field is instantaneous which wasn't the case before if I remember correctly, also all searches are faster It is comfortable to use. There may be a placebo effect because I just upgraded the server RAM to 128GB.

**Comment by gnattu** [comment]
10.10 removed tags from the search query and that could be why: https://github.com/jellyfin/jellyfin/pull/12741

**Comment by VigibotDev** [comment]
Great job. Search is now much faster and we can search for a tag by clicking on it in a movie page.

**Comment by Knaspin** [comment]
Just tried 10.10.0 (same process as [here](https://github.com/jellyfin/jellyfin/issues/12228#issuecomment-2410682700)) and it's even worse -- around ~10 second for a search that is near instantaneous in 10.8.13.

**Comment by VigibotDev** [comment]
Yes, I remember in 10.8.x it was instantaneous, but not anymore, because they add too many search results. With a better order (small to long title) and less results, it is instantaneous... Now it is usable for me thanks to a powerful server... but not optimized

**Comment by verybadsoldier** [comment]
Sorry, but I cannot confirm that 10.10 searches faster. Looks very similarly (slow) on my end.

**Comment by sevenrats** [comment]
@felix920506 can we get a lock on this please.

**Comment by joshuaboniface** [comment]
Just to reiterate - @JPVenson's comment above (https://github.com/jellyfin/jellyfin/issues/12228#issuecomment-2417002855) is correct.

In short, we are aware this is a problem. Search is currently very slow because the database queries to implement it are very slow with the current database schema. It was fine in an older version because that version was before we implemented tag and genre search which ballooned the queries to unmanageable levels, and is why we're laser-focused on moving forward with the EFCore database migrations.

Once those migrations are done, things will ideally be fast again as we'll be able to properly optimize the database queries.

But until then, there's no solutions to this. Search will just be slow in 10.10.x and we'll have to live with it

I trust everyone to accept this final word without locking this thread, but let's end it here or I will.

**Comment by oddstr13** [comment]
No need to lock, but please, if you have new information to add, please create a new issue with all the relevant information.

There have been changes in the relevant code since this issue was created, and as such most of the initial information provided in this issue is likely to be outdated and no longer relevant.

If you still feel like this particular issue thread is the best place to add more information on the issue, I expect a full on `git bisect` to track down exactly which changes are the cause of this slow-down, with timing numbers to back it up. 

There are about 2.5 years and 496 commits between 10.8.13 and 10.10.0 (only in the server)
