### ISSUE TITLE
jellyfin can not find dlna client on centos7 with firewalld

### ISSUE THREAD

**Issue by welpher** [jellyfin/jellyfin#1255]
RT
All port used by dlna allowed passthrought
emby 3.5 cannot too, but emby 4+ fixed this issues.

**Comment by sparky8251** [comment]
Please edit the issue to follow the issue template.

**Comment by sparky8251** [comment]
[Does the comment here provide any recourse for you?](https://github.com/jellyfin/jellyfin/issues/1464#issuecomment-505810523)

**Comment by 0ddb0d** [comment]
It's a .net core bug which took months to pin down.

Emby discussion is [here](https://emby.media/community/index.php?/topic/61265-error-dlna-error-in-beginlisteningforbroadcasts/page-2), the cause is [this commit](https://github.com/dotnet/corefx/commit/7eba4bf88983ac276348ea1626c81595e1b237c6#diff-3c0edd8d16aa366989215dba11a0bc08), the workaround that Emby 4 used is [here](https://github.com/dotnet/corefx/issues/32027#issuecomment-418082355). As @welpher said, it does work, but I have no idea whether the fix was backported to .net core 2.2.

I'm perfectly happy for JF devs to leave it broken and wait for .net core 3.0 since it looks like you're gearing up for another release pretty soon.

**Comment by dkanada** [comment]
The next release will include the latest version of NetCore so this issue should be resolved then.
