### ISSUE TITLE
Library settings are ignored

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#1275]
**Description**
When creating a new library with video content (TV Shows, Movies, not Music, Books or Unspecified), library settings like the enabled metadata agents (TheMovieDB, TVDB, Screen Grabber...) set at creation time are ignored and are not saved and are left at default. Trying to modify those library settings afterwards is unsuccesfull as well.

Library names, types and folders are the only saved details. This issue difficuts a workaround on #1269 because it's impossible to disable the Screen Grabber and the multiple ffprobe threads.

**Steps to Reproduce**
1. Go to Dashboard
2. Create a Library
3. Choose between TV Shows or Movies. Fill the basic info
4. Turn on the switch to edit Advanced Confing. Change some settings there (ike disabling Screen Grabber)

The settings you modify in step 4 won't be applied and you will be able to see in the logs how Screen Grabber is working. Restarting the server and editing the library settings doesn't function as expected and fails, just like when creating a library.

**System:**
 - OS: Debian Jessie ARMv7 on Raspberry PI 3B+
 - Browser: Chrome 73
 - Jellyfin Version: 10.3.0
Installed through repo and apt package manager

**Comment by WWWesten** [comment]
Duplicates #1235

**Comment by ferferga** [comment]
@WWWesten I don't know if it's something else causing this, related or not, but I didn't change the /var/lib/jellyfin data folder for sure, my Jellyfin data is still at that location. I changed literally nothing, and dashboard reports me that the directory is the default one, so definitely I can assure is something else.

**Comment by anthonylavado** [comment]
Okay, so from what I can find (because I did locate some of the code that does this), ScreenGrabber being disabled is ignored by Mixed Content/Home Movies libraries.

I know where to disabled it from being a default all together, but not how to selectively disable it for Home Movies/Mixed Content. 

It seems to respect my settings in other library types (TV Shows, Movies) though.

**Comment by ferferga** [comment]
> Okay, so from what I can find (because I did locate some of the code that does this), ScreenGrabber being disabled is ignored by Mixed Content/Home Movies libraries.
> 
> I know where to disabled it from being a default all together, but not how to selectively disable it for Home Movies/Mixed Content.
> 
> It seems to respect my settings in other library types (TV Shows, Movies) though.

Wow, so, as you can see, we are having the reverse behaviour: I can disable it/change any library settings for Mixed content libraries, but not TV/Movies.

I don't know if it might be related to #1235 as @WWWesten said, but I forgot to comment in the day that I wanted to start fresh with my Jellyfin libraries, so I removed all of them through the web browser, waited for the logs to show that it was done, execute "clean cache" and "clean people" scheduled tasks, stopped Jellyfin service and deleted all the contents of /var/lib/jellyfin/metadata, to later start the service. Maybe that has been causing this?

**Comment by anthonylavado** [comment]
>  @anthonylavado Btw, could you point me to the piece of code where I can disable the Screen Grabber in order to make it myself? Or are you going to do a PR?

@ferferga https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Api/Library/LibraryService.cs#L511-L513

Set L513 to False. Screen Grabber will then be off my default for any new library. I don't know how to disable it entirely, but I figure you could set this next line to false as well:

https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/MediaInfo/VideoImageProvider.cs#L140

**Comment by ferferga** [comment]
@anthonylavado As long as I can disable it for new libraries, it's great. 

Regarding your edit: I also see Screen Grabber as an useful feature, but sincerely not enough to be used in every single video. Running the screen grabber for every video, even if it has metadata from other sources, just makes the scan process after adding a new library unnecessarily slow, no matter if you are on a Pi or an Intel Xeon, Jellyfin will be always slower than Plex in this sense. Doesn't seems coherent for me as well, as Screen Grabber is by default the last metadata agent in the priority list: doesn't that mean that it should be used only when the image metadata is missing from other sources?

Btw, somewhat out of topic, but what's the difference between Screen Grabber and the chapter generation (last two checkboxes in library settings)? When diagnosing the original issue #1269, thought that the bug was related to those chapter generation, until I found out I always had them disabled and that the issue was caused by Screen Grabber, a completely different feature.

Thank you very much again for the effort you guys are putting into this project!

**Comment by anthonylavado** [comment]
@ferferga Yes, it’s only supposed to be used as a last resort feature on most libraries, except for mixed content (because there are no other sources for that).

To be clear - there are two things going on. FFprobe runs on every video, because we have to get the details of the file (length, codecs, number of video/audio streams, subtitles included, chapters). This typically takes a second per file (it’s very fast). Then, it checks the metadata sources. If it finds details, it will use those. Only if then it doesn’t find an episode image, then screen grabber is run (using FFmpeg). This is the one that takes considerably longer, and uses more CPU.

So far, we’ve only succeeded in limiting FFmpeg, and in a very hacky way. The bigger work to be done would scale both FFprobe and FFmpeg appropriately per architecture (num. of processor cores, etc). It’s very involved. We also plan to analyze what the “competition” is doing, to see how we can improve even more in future.

- - -

Chapter image extraction is different - if the video has chapters in it (most don’t, some movies do), then that setting, when enabled, will go and grab a screen cap for the time stamps of the chapters (just like you’d see when browsing chapters on a DVD/Blu-Ray disc).

**Comment by ferferga** [comment]
@anthonylavado Crystal clear now, thanks for explaining! :)

Yes, it seems that we have a problem with ffprobe as well, as a lot of them are spawned when a library scan starts (no sight of ffmpeg). Will try to build my own Jellyfin version whenever I have some free time to test what happens if I disable Screen Grabber, though, there is no harm in testing :)
