### ISSUE TITLE
Movie grouping/Box Sets doesn't work

### ISSUE THREAD

**Issue by huudafakk** [jellyfin/jellyfin#1278]
Grouping manually or with the TMDb Box Sets-Plugin does create the correct Movie Collection Folder but with no Movie-Files in it to select or to play. Adding the movie manually, jellyfin says "added" but in the Collection Folder are still no movies/content to play.
verifying the collection.xml file under /var/lib/jellyfin/data/collections/<movie>, the path is correct, but the single movies are not shown in the collection folder. 

**System (please complete the following information):**
 - OS: Debian
 - Browser: chrome
 - Jellyfin Version: Version: 10.3.0

**Comment by papadeeh** [comment]
The Windows build has the same issue.

**Comment by oddstr13** [comment]
Seems to be working for me (ubuntu) - the TMDb Box Set plugin is on a 24h timer by default, and I'm not sure if it runs automatically right after install, or only after 24h (I triggered it manually).

I am not entirely sure if I installed the plugin just before, or after updating to 10.3.0 however.

**Comment by huudafakk** [comment]
Upgraded to 10.3.1, but issue remains. Even if the path to the movie file is correct, in the Movie-Collection-Folder is only indicated "Content" and a "+", but not the single movies to watch.

**Comment by Liggy** [comment]
I'm having the same issue and my media is either .iso images or VIDEO_TS folders. I noticed that the iso files are missing, but the VIDEO_TS folders are included. But all entries were added to the collection data, they're just not listed.
On the other hand, Jellyfin now started to include the whole content of the VIDEO_TS folder as a special feature, but that might be related to a different issue

**Comment by lukastribus** [comment]
Since 9753a76905 (`Populate video extras again`) from PR #952 for every movie (single mkv in a folder) a `MediaBrowser.Controller.Entities.Video` item is added to the database (library.db table TypedBaseItems), with a different `PresentationUniqueKey`. The collection item (`MediaBrowser.Controller.Entities.Movies.BoxSet`) will then point to this new, wrong entry as opposed to the proper `MediaBrowser.Controller.Entities.Movies.Movie` item, which is why collections are broken now.

Reverting the change only fixes the issue for new movies. Existing movies can only be fixed by purging MediaBrowser.Controller.Entities.Video items from the TypedBaseItems table manually.

This affects all 10.3 releases.

CC @Liggy @cvium @JustAMan

I also suggest we use valid Author/Commit data in commit, [email address can be redacted without pushing completely bogus data](https://help.github.com/en/articles/about-commit-email-addresses).

**Comment by lukastribus** [comment]
For the record this fix is only about *new movies* added to the library. Existing movie entries in the database will remain corrupted from the bug in previous 10.3 releases.

Use @oddstr13 [jellyfin-collection-fix.py](https://github.com/oddstr13/jellyfin-fixup-scripts/blob/master/jellyfin-collection-fix.py) to fix your database.

**Comment by w111a** [comment]
Would it be possible to get some instructions on how to use @oddstr13's jellyfin-collection-fix.py? Thanks

**Comment by choakem** [comment]
Hi W111a

Ubuntu Docker configuration: (it shouldn't matter)

I simply copied the jellyfin-collection-fix.py into my config directory of JellyFin (i'm using docker) but it shouldn't matter.

Stop JellyFin on local server or the Docker...
Copy jellyfin-collection-fix.py to config directory
then i SSH into server & ran:-
./jellyfin-collection-fix.py library.db

(Note I placed the script into the same folder as the library.db file)

The script ran PERFECTLY!!!!!!!!!!

**Comment by w111a** [comment]
Thanks so much. I'll give it a try when I get home.

**Comment by w111a** [comment]
@choakem 

I'm running Jellyfin in an UnRaid (6.7.2) docker and have not been able to get it working yet. I created an executable file in appdata/jellyfin/data (where the library.db is). I installed python3 through the add-on "nerd tools'.

 I had to change the path in the first line because "which python3" shows usr/bin/python3, and I was getting  `-bash: ./jellyfin-collection-fix.py: /usr/bin/env/python3: bad interpreter: Not a directory` 

SSH from putty and after changing the .py file I got `-bash: ./jellyfin-collection-fix.py: /usr/bin: bad interpreter: Permission denied`

I then went into the console inside the Jellyfin docker container and got `sh: 7: ./jellyfin-collection-fix.py: Permission denied` Does this sound like an issue with python3 since it seems it was not located in the regular /env/? 

Thanks

**Comment by cvium** [comment]
> I should add: Doing the steps as you described got /usr/bin/env: ‘python3 \r’: No such file or directory

@w111a That sounds like a line ending thing as `\r\n` is a carriage return + line feed. Try using `dos2unix` to convert the line endings to the proper `\n` for nix environments.

**Comment by choakem** [comment]
I agree - Open in notepad ++ (if windows) and click edit - EOL conversion -> Unix

I assume you are running as root user ?
Retry and let us know!

**Comment by oddstr13** [comment]
> @choakem
> 
> I'm running Jellyfin in an UnRaid (6.7.2) docker and have not been able to get it working yet. I created an executable file in appdata/jellyfin/data (where the library.db is). I installed python3 through the add-on "nerd tools'.
> 
> I had to change the path in the first line because "which python3" shows usr/bin/python3, and I was getting `-bash: ./jellyfin-collection-fix.py: /usr/bin/env/python3: bad interpreter: Not a directory`
> 
> SSH from putty and after changing the .py file I got `-bash: ./jellyfin-collection-fix.py: /usr/bin: bad interpreter: Permission denied`
> 
> I then went into the console inside the Jellyfin docker container and got `sh: 7: ./jellyfin-collection-fix.py: Permission denied` Does this sound like an issue with python3 since it seems it was not located in the regular /env/?
> 
> Thanks
> 
> I should add: Doing the steps as you described got `/usr/bin/env: ‘python3 \r’: No such file or directory`

Executing Python directly with the script as the first argument should avoid these issues;
`python3 jellyfin-collection-fix.py library.db`

You may have to specify the whole location of Python if it isn't in your `PATH`;
`/path/to/python3 jellyfin-collection-fix.py library.db` (I don't know where Python gets installed on UnRaid)

Remember that the Jellyfin server *must* be stopped before running the script, and that the user you run the script with must have write access to the library.db file.


The problem you have above is due to your shell (and or the `env` executable) not understanding CRLF (`\r\n`) line endings, and interpreting `\r` as a part of the Python executable name. Python itself *should* handle this fine.

You can also download the file directly to the NAS using either
`wget https://github.com/oddstr13/jellyfin-fixup-scripts/raw/master/jellyfin-collection-fix.py` or `curl -LO https://github.com/oddstr13/jellyfin-fixup-scripts/raw/master/jellyfin-collection-fix.py`
This should result in the file having LF line endings, as that is what's in the repo.
To make this file executable, run `chmod +x jellyfin-collection-fix.py`. You should now be able to run the script with `./jellyfin-collection-fix.py library.db`, assuming python3 in in your `PATH`.

**Comment by w111a** [comment]
Copy. I'll try then report back.

**Comment by w111a** [comment]
Thanks to everyone who replied. Got it working. 

I first followed @choakem suggestion and it worked like a charm. I shut down the Jellyfin docker and created jellyfin-collection-fix.py as it appears in the repo by coping the text of the file and pasting it into a new file in Notepad++ file named jellyfin-collection-fix.py. I used @choakem suggestion of EOL>UNIX in Notepad++ then saved the file. Then in the UnRaid Terminal I navigated to where it put jellyfin-collection-fix.py (which was appdata/jellyfin/data), which was also the same folder as library.db. Then ran the command `./jellyfin-collection-fix.py library.db`

The script ran, found library entries that needed fixing and did its thing. 

To note: As mentioned, I previously installed python3 through "nerd tools" plugin for UnRaid. 

All's well with Jellyfin collections again. 

Thanks again. Thanks @oddstr13 for the explanation and script.

**Comment by choakem** [comment]
Excellent.

Thanks for the feedback, it may help others.

Choakem

**Comment by icf20** [comment]
i am going to bump this and let you know this is not a fix, an fix dont require end user to run scripts to get proper functionality for a plugin, unless the there is a fix that simply works or this issue should remain open

**Comment by anthonylavado** [comment]
@icf20 This bug was fixed though?

**Comment by cvium** [comment]
A fix is a fix. We do not have the means to create easy automatic database migrations, so unfortunately you and others afflicted by this bug will just have to deal with a script to handle the cleanup.

**Comment by icf20** [comment]
> his bug was fixed though?

i will have to set a container and see if was FIXED
