### ISSUE TITLE
Thread utilization causing server to become unresponsive, requiring restart to respond again.

### ISSUE THREAD

**Issue by Jomack16** [jellyfin/jellyfin#12807]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The jellyfin server will reach a tipping point where it begins to use more and more threads. When this happens the server becomes unresponsive. The webpage will not load, new streams will not start, and current streams will falter/fail and not continue.
This seems to correlate to greater than 30 sessions and/or greater than 10 simultaneous streams (of various types of playback)

### Reproduction steps

1. Run more than 30 sessions / more than 10 simultaneous streams.
2. Monitor the thread utilization for the Jellyfin process.

### What is the current _bug_ behavior?

The jellyfin process will use greater and greater number of threads, eventually becoming unresponsive.

### What is the expected _correct_ behavior?

The jellyfin process will only use the necessary threads and remain responsive.

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Ubuntu 22.04.05
- Linux Kernel: 6.8.0-45-generic x86_64
- Virtualization: Docker
- Clients: All [Browser, Android, Fire Stick, etc.]
- Browser: Firefox 131
- FFmpeg Version:  6.0.1-Jellyfin
- Playback Method: All [Direct Play, Remux, Direct Stream, Transcode]
- Hardware Acceleration: VAAPI
- GPU Model: Intel Arc A770
- Plugins: AniDB, AudioDB, MusicBrainz, OMDb, Open Subtitles, Studio Images, TMDb, TheTVDB, Webhook
- Reverse Proxy: Nginx-Proxy-Manager
- Base URL: non
- Networking: Bridge
- Storage: SMB share from TrueNAS
```

### Jellyfin logs

```shell
relevant logs attached. Unsure what parts are relevant.
```

### Additional information

1. ThreadCount.log is the output log from my script that restarts the jellyfin container when the thread utilization crosses a threshold and continues to increase.
2. jf_session_data.db is a sqlite database with non-private summary info about how many streams/session and other info (numTranscoding, etc)
3. logging.json is the way I have configured debug logging, and the file is included.
[20241009.zip](https://github.com/user-attachments/files/17348639/20241009.zip)

**Comment by kkaniewski** [comment]
I'm hitting the same issue. It looks like Jellyfin doesn't stop threads when host machine gets close to utilize 100% of CPU (which is not too difficult on my machine as I'm running it on N100 where rechecking a torrent already gets me to 100% CPU use). Jellyfin just constantly spawns new threads without killing any of them. I've just observed Jellyfin to spawn total of 900 threads which were rising like 1-2 per second. I'm also on 10.9.11 version.

**Comment by felix920506** [comment]
Are you using the official docker image, the linuxserver.io docker image, or something other image (please specify)?

**Comment by felix920506** [comment]
@kkaniewski are you using any virtualization? if so please specify. If you are using docker please also specify which image you are using

**Comment by felix920506** [comment]
On my install I just started 10 streams at the same time and the behavior described in the report cannot be observed.
all streams are 1080p HEVC 10bit -> AV1 w/ ASS burnin
My Setup: Intel Core i5-10400F, 20GB Ram, Ubuntu 24.04, Intel Arc A750, No Virtualization

**Comment by Jomack16** [comment]
I am using the jellyfin/jellyfin image, and this may have been a problem for me as early as 10.9.2+. Definitely since 10.9.9

**Comment by kkaniewski** [comment]
@felix920506 I'm running Jellyfin in Docker, using official jellyfin/jellyfin image. It was happening on LSIO image as well, that's why in the end I moved to the official one as I read a comment about a bug in LSIO around detecting amount of cores. 

I have limited all the parallel stuff to 1 (library scan, trickplay generation). Trickplay uses QSV. I'm currently trying to narrow it down on my machine to find some scenario which can trigger it, as it doesn't happen all the time. The last time it appears it looked following way:

1. Added new series to download via Jellyseerr and Sonarr starts to look for it.
2. Transmission starts to download it (3 item queue). Transmission takes about 30-40% of CPU in htop to handle the downloads, average load gets to 3.0-4.0. N100 has 4 cores.
3. Jellyfin has 1 stream running, but with direct play so that shouldn't take much resources.
4. Meanwhile one of torrents (whole series season) finishes to download, Sonarr triggers Jellyfin library rescan via Webhook.
5. Jellyfin starts library scan, runs ffprobe and triggers trickplay generation as I had it accidentally automatically enabled on library scanning. 
6. While Jellyfin scans the library (it takes around 2-3 minutes, as I have around 200 movies and 2000 series episodes in my library), another torrent finishes the download and triggers notification via Webhook to perform library scan.
7. The same happens another 3-4 times as other torrents finish.
8. Jellyfin slowly dies, spawns tons of threads until CPU gets completely hammered. 

For now, I've disabled trickplay generation on library scan and moved to 10.9.10, however version change probably doesn't make any sense looking at the changelog. Probably the easiest way to resolve it would be to move away from N100 in favour of something with better performance. On the other side, N100 has quite great transcoding capabilities so for my use N100 theoretically it should be enough as it's capable of transcoding even 4k streams (which I don't really use, as the vast majority of my media just direct plays in 1080p).

**Comment by JPVenson** [comment]
Please check if you have the Server Dashboard open somewhere.

**Comment by michelsup** [comment]
I have the exact same issue even without much use. I can't find a pattern of utilization leading to this thread starvation but I will try to get a log to investigate.
Proxmox virtualization, official docker image, plenty of resources.

**Comment by JPVenson** [comment]
@Jomack16 jellyfin is absolutly not build for 25 simultaneous streams. Jellyfin is a __home__ media server and designed for a handful of users. What is your usecase?

**Comment by Jomack16** [comment]
If it is not expected to function at that scale, then it doesn't matter much what the use case is.
Mine is that I share access to my server with family and friends, both of which I continue to accumulate with age :)
Any thoughts on what a reasonable handful is?

**Comment by Jomack16** [comment]
@JPVenson Thank you for the confirmation.
Do you know what level of simultaneous activity could be expected to be reliable?

**Comment by felix920506** [comment]
Please answer the question about your use case.

**Comment by Jomack16** [comment]
@felix920506 @JPVenson 
Let me know if this does or does not answer your question.
I run my media server from my home, with local storage that I have built and accumulated over many years.
Over those same many years I have created and accumulated many family members and friends.
I share my media server with those family members and friends.

**Comment by Jomack16** [comment]
same problem happened again today with only 13 simultaneous streams, but still with a high(?) number of sessions, 51.
Seems like maybe it is more tied to the number of sessions rather than the number of simultaneous streams.

**Comment by Jomack16** [comment]
Closing as it was confirmed that Jellyfin should not be expected to handle 26 simultaneous streams.

**Comment by memehammad** [comment]
Same issue here with a single stream.

`[2024-11-21 05:23:09.006 +01:00] [ERR] [28] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Unexpected end of request content". URL "POST" "/Sessions/Playing/Progress".
[2024-11-21 05:23:10.510 +01:00] [ERR] [17] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Unexpected end of request content". URL "POST" "/Sessions/Playing/Progress".
[2024-11-21 05:32:02.075 +01:00] [WRN] [14] Microsoft.AspNetCore.Server.Kestrel: As of "11/21/2024 04:32:01 +00:00", the heartbeat has been running for "00:00:01.1487632" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-11-21 05:33:24.999 +01:00] [WRN] [14] Microsoft.AspNetCore.Server.Kestrel: As of "11/21/2024 04:33:24 +00:00", the heartbeat has been running for "00:00:01.0153480" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-11-21 05:38:04.867 +01:00] [WRN] [14] Microsoft.AspNetCore.Server.Kestrel: As of "11/21/2024 04:38:04 +00:00", the heartbeat has been running for "00:00:01.0163669" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-11-21 05:40:30.173 +01:00] [WRN] [14] Microsoft.AspNetCore.Server.Kestrel: As of "11/21/2024 04:40:30 +00:00", the heartbeat has been running for "00:00:02.4260637" which is longer than "00:00:01". This could be caused by thread pool starvation.
[2024-11-21 05:41:31.093 +01:00] [WRN] [14] Microsoft.AspNetCore.Server.Kestrel: As of "11/21/2024 04:41:31 +00:00", the heartbeat has been running for "00:00:01.4288359" which is longer than "00:00:01". This could be caused by thread pool starvation.`
