### ISSUE TITLE
Trickplay being killed too soon

### ISSUE THREAD

**Issue by tcely** [jellyfin/jellyfin#13116]
There should really be a mention on the settings page that when using "Idle" priority, the interval between images needs to be set higher.

My logs are full of "starting ffmpeg" followed by "killing ffmpeg" because while sometimes there were 7 seconds between images, often enough the system wasn't idle and it took longer.

I'm trying 30 seconds now, to see if that's a more useful timeout. Maybe the default should just be to wait longer?

https://github.com/jellyfin/jellyfin/blob/1272bb9a8420a92329cdd36898b4b0240018327f/MediaBrowser.Model/Configuration/TrickplayOptions.cs#L40

I had no idea why the logs were not making sense until I searched / browsed GitHub to see what the conditions were for "killing ffmpeg" in the code.

**Comment by gnattu** [comment]
30 seconds is not a more useful timeout and that is a ridiculously high timeout. If your CPU needs 30 seconds to even extract one single frame you really should not enable this feature because the generation will take years or even lifetime.

**Comment by tcely** [comment]
As I understand the code, if any image takes longer than 10 seconds, then the ffmpeg will be killed. It's not as if it's only checking for the first image to appear then leaving the ffmpeg to complete in the idle time.

The idle priority means that when the system is busy for longer than 10 seconds, no idle cycles are assigned to trickplay, then the process is killed.

This is suboptimal behavior, because it wasted all the completed images and if the process were not killed it would have completed as normal when idle cycles became available.

**Comment by ElDavoo** [comment]
About 1/4th of my trickplays failed because of this. Sometimes the network can be slow, and/or the CPU is busy doing other stuff. I'd at least make it tunable somehow.

**Comment by tcely** [comment]
> I'd at least make it tunable somehow.

"Increasing the `ImageExtractionTimeoutMs` value above 20,000 may be needed for the 'Idle' priority."

There is a tunable setting for this, but there is no way to adjust it from the web interface that I am aware of.

**Comment by ElDavoo** [comment]
> There is already a tunable setting for this (in `system.xml`),

uh cool thanks i didn't know, so ok solved for me xd

**Comment by Zennii** [comment]
I know this is closed and old at this point but I wanted to throw some of my own info and opinion in. I also just hit this issue, I'm not sure if it's related to the length of the video as I haven't done enough testing, but I have fairly long videos (usually over 5 hours) and the trickplay images seem to consistently take around 20 seconds per image on my NAS's poor little CPU on 1 thread. I don't think it's quite fair to dismiss it on a theoretical timespan alone. There are many factors here that can change that timespan. Number of videos, number of threads (?), the image interval, maybe even process priority. Let people decide for themselves how long they're willing to let this take since they have all of the context. For me, I set 1 trickplay image every 60 seconds, and while it might take months to get initially caught up, it's still fast enough for me overall. I think it wouldn't be unfair to have this setting better exposed for tweaking if possible. For now, editing the XML file seems to have fixed my issue. But I still think it should be more visible at least
