### ISSUE TITLE
5.1 downsampling only supported on native client

### ISSUE THREAD

**Issue by elliottetzkorn** [jellyfin/jellyfin#13214]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

5.1 audio is not being correctly downsampled to stereo on most Jellyfin platforms

### Reproduction steps

1. Sign into jellyfin using the native client on mac
2. Sign into jellyfin using any of the web clients
3. Play the same video on both, which has a 5.1 audio track, and expect it to output to stereo, use headphones to hear the difference
4. On native, the downsampling is correct, on web (also on my lg tv) the audio is a mess, highly compressed, clipping, channels coming in and out

### What is the current _bug_ behavior?

5.1 audio does not consistently downsample across platforms

### What is the expected _correct_ behavior?

5.1 audio should consistently downsample across platform

### Jellyfin Server version

10.10.0+

### Specify the build version

Release

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
None
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
What browser are you using?

**Comment by felix920506** [comment]
What is the playback method when you are having the issues?
Direct Playing? Remuxing? Direct Streaming? Transcoding?
If not direct playing please also share ffmpeg logs.

**Comment by gnattu** [comment]
So, things are a bit tricky here. Providing no information and just saying “it doesn’t work” isn’t very helpful. We’d have to guess all the possibilities, which isn’t only ineffective, but it could also be wrong.

On the bright side, we do support 5.1 downmixing, and it works for all browsers because the downmixing is done server-side. But, you’ll need to enable transcoding on the server to make it work. If you’ve disabled that for the account you’re using, the server-side downmixing won’t work.

JMP always uses client-side downmix, and that one doesn’t always work better than server-side downmix. We’ve gotten a lot of user reports saying that the downmixing of JMP is too quiet, and there’s no way to customize it yet.

The server-side downmix is customizable in Dashboard -> Playback -> Transcoding. You can see the “Audio boost when downmixing” and the “Stereo Downmix Algorithm” options.

**My guess is that you don’t like the audio boost and should set that to 1.** You can also try other algorithms, but I think none without any audio boost should work well enough for you.

We need to see the ffmpeg logs because there must be one when server-side downmixing is working. If there’s none, then for some reason, the server-side downmixing isn’t triggered, and that could be a bug. But if there’s a log and from the content of the log, we can tell the server is just doing downmixing fine, then this issue is more or less a subjective preference issue rather than a software bug. But again, we need at least the ffmpeg log to see what was happening to not guess from nothing. 

You can refer to https://jellyfin.org/docs/general/server/transcoding/downmix for more info about our customizable server-side downmixing algorithms.

**Comment by gnattu** [comment]
![Image](https://github.com/user-attachments/assets/4f341e33-74e7-4822-ac26-6fc987ccd136)

Are you using current version?
