### ISSUE TITLE
Unable to remove a ChannelMapping

### ISSUE THREAD

**Issue by Giermann** [jellyfin/jellyfin#13254]
Next try: open an issue...

I detected the issue that one cannot undo a channel mapping without manually editing a channel.
To get some practice, I created the PR #12970 - but without any response yet.
Last time I wanted to open an issue as Feature Request I was told to do so at [https://features.jellyfin.org](https://features.jellyfin.org/posts/3006/undo-remove-a-channel-mapping), which I did - but still no response.

Can please someone tell me how to point the maintainers to the open (and very simple) PR to get a review there?

**Comment by felix920506** [comment]
After you open a PR you wait until someone reviews it.

**Comment by thornbill** [comment]
It can definitely be frustrating to open a PR and not get any feedback. Unfortunately we have a pretty [limited set of volunteers](https://jellyfin.org/posts/a-call-for-developers) performing reviews and sometimes things go unnoticed or hit at times when everyone is otherwise busy. In an ideal world we would have many more reviewers/maintainers so PRs were reviewed in a more timely manner, but that’s not currently the case. 

If you have a PR that has been sitting for awhile without any feedback, I would post it in a development [chat](https://jellyfin.org/contact/) to hopefully get the attention of someone on the server team. You can also comment on the PR so it shows back up in the team’s GitHub notifications.

Thanks for your patience.

**Comment by clseibold** [comment]
The PR was reviewed, and now there's no response from the original developer! I'd really like this issue/PR to move along, because I've been running into trouble not being able to unmap channels for xmltv guides.
