### ISSUE TITLE
Add support for raw image formats

### ISSUE THREAD

**Issue by osscombat** [jellyfin/jellyfin#1328]
It was not implemented in Emby in spite the requests, probably this could happen in Jellyfin? DNG is an open RAW photo format, it's working in Plex without problems.

**Comment by Jab2870** [comment]
I am pretty sure that imagemagick has support for dng files. Am a right in thinking that jellyfin uses imagemagick in the background for image generation.

**Comment by EraYaN** [comment]
No, Jellyfin uses Skia in the background, although that also supports dng. BUT for viewing pictures I think your browser would need to support it, or we would need to convert them or soemthing.

**Comment by Jab2870** [comment]
My bad. I am sure Emby used to use image magick although it looks like it was changed in 2017 https://emby.media/community/index.php?/topic/47486-32154-skia/

I don't think any browsers support it. We would definitely have to do some conversion. I have never used Skia but it looks perfectly capable of doing the conversion. Is this something that you think jellyfin core should implement or is this something that should be a plugin?

**Comment by EraYaN** [comment]
I feel like this should be implemented in jellyfin, since transcoding is too. It would be the same discovery process as for video formats.

**Comment by osscombat** [comment]
> browser would need to support it
Dunno how, but plex renders it great everywhere in the apps/browsers, probably transcoding, but blazing fast. MB still lacks this, even with the latest build.

**Comment by 0ddb0d** [comment]
Plex doesn't render raw image formats it extracts the embedded JPEG thumbnail.

Rendering DNGs or any other raw format is pretty slow. When this was proposed for Emby I did some calculations based on my own system's speed and found it took 7-10 minutes to render a hundred 20 megapixel images.

**Comment by EraYaN** [comment]
This would be a on-demand transcode I believe, since for example any desktop app could just implement local image viewing. But this would also need to support xmp and other sidecar files to apply any non-destructive edits made. Essentially, you should probably just use Lightroom/Darktable/Capture One or any of the other actual raw viewers. And export jpegs for sharing (with Jellyfin).

If someone really wanted to someone can probably make a plugin that wraps darktables engine for most of the color edits and other live viewing functions.

**Comment by osscombat** [comment]
I believe an embedded jpeg preview (and EXIF data) is just enough, the point is just to browse the read-only gallery with DNGs.

**Comment by oddstr13** [comment]
List of raw image formats;
[Raw filename extensions and respective camera manufacturers (Wikipedia)](https://en.wikipedia.org/wiki/Raw_image_format#Raw_filename_extensions_and_respective_camera_manufacturers)
We probably want to support most of these, or at least the most popular ones (my personal photo library contains a lot of cr2)

**Comment by EraYaN** [comment]
RAW image formats are very tricky though, Photoshop Camera RAW needs a ton of profiles for cameras.

**Comment by oddstr13** [comment]
Indeed, but even just recognizing it as an image and extracting the embedded preview/thumbnail would be an improvement.

**Comment by philippk80** [comment]
I'm a bit confused because of this lines:
https://github.com/jellyfin/jellyfin/blob/da7abea9aa33a1bd903b6e4ba8407e894b509b96/Emby.Drawing/ImageProcessor.cs#L86-L116

It seems like this is already supported on windows systems.
I tested it with w10 and .arw files yesterday and had no effort.

**Comment by philippk80** [comment]
I made another test today and now it's working. 
Maybe I wasn't patient enough with the scan process.

**Comment by osscombat** [comment]
at least those of them, which are open.

вс, 28 июл. 2019 г., 22:59 Odd Stråbø <notifications@github.com>:

**Comment by gfeng85** [comment]
sony a7m3,its arw raw file doesn't support in ver 10.5.5

**Comment by pixel24** [comment]
Hi@all,

I am an ambitious amateur photographer and only shoot in RAW format. Nikon D750 -> .NEF

On the desktop I use Darktable (Ubuntu) to edit my photos. I think Darktabel is great software because it writes all processing steps into an XMP file and the original is preserved.

I came across this post today and would love it if Jellyfin could handle my images.

Is there any hope that this will be the case at some point in the future?

Today I integrated my photo library into Jellyfin. However, only the embedded preview is displayed. Opening the photo does not work.

with best
pixel24

**Comment by osscombat** [comment]
Doubt this would be implemented ever, especially for proprietary raw
formats. I ended up modifying the workflow to keep jpg copy along the raw
file to make it usable.

пт, 19 мая 2023 г., 13:06 pixel24 ***@***.***>:

**Comment by xyboox** [comment]
Is this still not implemented by now? I mean the open formats.

**Comment by docsdv** [comment]
Is this planned to ever be implemented? Emby does it no issue at least with Nikon NEF files (both old and high efficiency).

EDIT:

What Emby does is really simple. It simply requests the thumbnail from the raw image 
`/Items/232/Images/Primary?maxWidth=1188&tag=aebf62ca6a07e7d0b903d71d60bfc216&quality=90`

Jellyfin calls the download endpoint which results in the browser not being able to render the raw itself 
`Items/4128215f63c47d8379c94e43342abf5d/Download?api_key=381fbcaf09d540af9e4076d40a0381f4`

EDIT 2:

Apparently it works because when downloads are disabled, it fallsback to the image thumbnail:

[slideshow.js](https://github.com/jellyfin/jellyfin-web/blob/a25295194fa0afd9dc4b4826f1e466d6f10b247f/src/components/slideshow/slideshow.js#L90)

<img width="842" height="472" alt="Image" src="https://github.com/user-attachments/assets/49b370b7-c68a-4a2b-a10b-8f1fe13fe0a5" />

Current hacky solution: disable downloads for your user then both web client and android client will fallback to the thumbnail, effectively letting you see the image. I'll create a different user with downloads enabled just in case I need to download a file.

I feel like this is such an easy thing to implement in both web and mobile clients so that we're able to check our RAW images.
