### ISSUE TITLE
Make the web UI full screen on iOS

### ISSUE THREAD

**Issue by phha** [jellyfin/jellyfin#1344]
**Is your feature request related to a problem? Please describe.**
Jellyfin currently doesn't have native iOS app support, however the web interface is quite nice and functional and when adding a link to the home screen it's almost the same as having an app. Almost.

**Describe the solution you'd like**
The web interface should implement Safari iOS web app features, specifically adapt the [web-app-capable](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW3) and web-app-status-bar-style properties. This will hide most of the iOS UI elements and it appears to be a quick and easy way for giving a more app-like experience to iOS users.

**Comment by DMouse10462** [comment]
This appears to have been present since commit https://github.com/jellyfin/jellyfin-web/commit/1c06eed0985da6bded90c3c26fb99a8ef61c3f86 and testing this with my iPad Air 2 running iOS 12.1.1 and Jellyfin 10.3.3 gives me the web app without the Safari GUI and seems to work just fine. Here's the code in question in jellyfin/jellyfin-web:

https://github.com/jellyfin/jellyfin-web/blob/6f569bfdff1ed492569bc359585ffd9ea486f735/src/index.html#L10-L21

Looking back on it, I can recall having noticed this before sometime this calendar year, but I can't seem to locate why that may have been the case. Are you still experiencing this issue? Have you removed your home screen icon and added it back since first experiencing this issue?

**Comment by PrplHaz4** [comment]
This can probably be closed - most recent improvements here (including fullscreen fix):
- https://github.com/jellyfin/jellyfin-web/pull/304

SO post indicating that manifest.json  with `"display": "standalone"` will override these settings on iOS > 11.3:
- https://stackoverflow.com/questions/48774142/after-upgrade-to-ios-11-3-web-app-does-not-show-full-screen-per-apple-mobile-web
