### ISSUE TITLE
Plex Versions?

### ISSUE THREAD

**Issue by dragon2611** [jellyfin/jellyfin#1374]
Is there any reason the JellyFin Server would ignore offline transcodes created by a plex server? (Located in the "Plex Versions" Subdir)

As far as I can tell the .mp4 files Plex creates are playable with other software (The file played ok on a Linux and Windows machine when copied from the filesystem)

I'd expect them to show up as either another version or at least as a duplicate.

**Comment by RazeLighter777** [comment]
Did you do a rescan?

**Comment by dragon2611** [comment]
Yep seems to straight up ignore those folders

**Comment by DrPandemic** [comment]
Is there some interesting logs in the terminal?

**Comment by dragon2611** [comment]
Not really, I delete the Library and added a directory I knew to have 2 versions in, it did find it in that case.
Just waiting for it to rescan after adding the whole library again

**Comment by dragon2611** [comment]
Right figured it out, Jellyfin is actually finding them but it's getting very confused about the way plex names the file which is essentially Plex Versions/<Preset>/<movie name>.mp4

Instead of taking the name of the file JF is using the name of the directory so it got added as Custom_Universal_TV <Number>

Since this then of course fails to match metadata lookup it becomes rather hard to see in the library ;-)

**Comment by oddstr13** [comment]
Just `movie name.ext`? I should think `movie name (year).ext` is the minimum needed for proper identification.

It would also be interesting to know what metadata Plex puts in the files;
`/usr/lib/jellyfin-ffmpeg/ffprobe /path/to/plex/version.mp4`

**Comment by dragon2611** [comment]
It includes the year.

**Comment by 0ddb0d** [comment]
The naming convention used by Plex's offline transcoder doesn't conform to Jellyfin's naming convention, that's why they get ignored. Keep in mind that Kodi doesn't recognise "Plex Versions" either which is important because that's where Plex, Emby and Jellyfin inherited their naming conventions from.

Currently, multiple versions of the same movie are recognised if Emby's naming convention is used (see [https://github.com/MediaBrowser/Wiki/wiki/Movie-naming](url)) but this will almost certainly change as Jellyfin matures.
