### ISSUE TITLE
Limit the number of concurrent ffprobes

### ISSUE THREAD

**Issue by Makeshift** [jellyfin/jellyfin#1378]
**Is your feature request related to a problem? Please describe.**

I have jellyfin set up with an rclone backend (previously a plexdrive backend, but as it's no longer maintained I've switched to a cached rclone) connected to Google Drive on a gigabit line.

When attempting to do a library scan, jellyfin spawns thousands of ffprobes at the same time, causing either:
1) Insanely high CPU usage
2) Rclone to run out of memory and crash

**Describe the solution you'd like**

An ability to limit the number of concurrent ffprobe processes when scanning a library.

**Describe alternatives you've considered**

I could change my rclone settings to use less ram, but it still seems that jellyfin fires a hell of a lot of ffprobe processes up. This wasn't an issue a couple of weeks ago, so it may due to a version change. I'm not sure if it's intentional, hence an enhancement and not a bug.

**Additional context**

I'm running Jellyfin 10.3.2 in Docker on an Ubuntu host. The drive is encrypted and mounted via Rclone 1.47.0 as read-only on the host.

My rclone config has a Google drive wrapped by a 'crypt' wrapped by a 'cache'.

Some logs:

```
[2019-05-13 19:13:05.534 +00:00] [INF] Executing "Scan media library"
[2019-05-13 19:13:05.618 +00:00] [INF] Stopping directory watching for path "/media/Movies"
[2019-05-13 19:13:05.618 +00:00] [INF] Stopping directory watching for path "/media/TV"
[2019-05-13 19:13:05.633 +00:00] [INF] Validating media library
```
It hangs there for about 15 minutes, then spawns several hundred ffprobes, killing rclone.

If there are any other details I can provide, please let me know.

**Comment by Makeshift** [comment]
I have no idea what I changed, but it suddenly stopped spawning tons of ffprobes. I think my rclone settings might have just been a bit weird.

**Comment by anthonylavado** [comment]
You probably didn't change anything. Somewhere along the way from 10.2.2 to 10.3.0, we (think) we fixed so many errors and exceptions, that the FFprobe used for a library scan just got, well, unleashed.

It's likely only to happen on first time scans, because after that, it only has to gather data about new media. It's very fast at least, each one should only take about 1-2 seconds to get data for a file.

We have plans to rate limit this as a workaround, and then we'll expand to a better queue based system.
