### ISSUE TITLE
Using "Identify" on a series with the "TheTvDB" provider sets wrong episode description/name/image

### ISSUE THREAD

**Issue by marius-luca-87** [jellyfin/jellyfin#1467]
**Describe the bug**
Incorrect episode name/description/image for TheTvDB metadata provider

**To Reproduce**
 - add a TV Shows library with a folder structure like
  Love.Death.and.Robots.S01.1080p.NF.WEB-DL.DDP5.1.x264-NTG/Love.Death.and.Robots.S01E01.Sonnies.Edge.1080p.NF.WEB-DL.DDP5.1.x264-NTG.mkv
 Love.Death.and.Robots.S01.1080p.NF.WEB-DL.DDP5.1.x264-NTG/Love.Death.and.Robots.S01E02.Three.Robots.1080p.NF.WEB-DL.DDP5.1.x264-NTG.mkv
 - browse to the show in the library and call identify with the TvDB id 357888 and replace all existing images
 - the show description and image are correct since the correct series id 357888 was used
 - the episodes all show the name "Avsnitt 2" as the series id 357888 was used instead of actually resolving each episode id

**Code version**
master branch with latest commit SHA-1: 2baddc17092ed466c84faf7a02ab1b5321e664a0
release 10.3.5
release 10.3.3

**Additional context**
In 3 locations a pattern of code exists that uses the series ID ( searchInfo.GetProviderId(MetadataProviders.Tvdb); ) instead of resolving the episode ID.

> MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs
```
public async Task<IEnumerable<RemoteSearchResult>> GetSearchResults(EpisodeInfo searchInfo, CancellationToken cancellationToken)
public async Task<MetadataResult<Episode>> GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
```

> MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs
```
public async Task<IEnumerable<RemoteImageInfo>> GetImages(BaseItem item, CancellationToken cancellationToken)
```

> Code where tvdbId is "357888" from the searchInfo instead of resolving the actual episode ID
```
                var tvdbId = searchInfo.GetProviderId(MetadataProviders.Tvdb);
                try
                {
                    if (string.IsNullOrEmpty(tvdbId))
                    {
                        tvdbId = await _tvDbClientManager
                            .GetEpisodeTvdbId(searchInfo, searchInfo.MetadataLanguage, cancellationToken)
                            .ConfigureAwait(false);
                        if (string.IsNullOrEmpty(tvdbId))
                        {
                            _logger.LogError("Episode {SeasonNumber}x{EpisodeNumber} not found for series {SeriesTvdbId}",
                                 searchInfo.ParentIndexNumber, searchInfo.IndexNumber, tvdbId);
                            return result;
                        }
                    }
```

**Comment by sparky8251** [comment]
THe following is from a duplicate issue I have closed that was submitted by @Webbeh.

Hi !

Describe the bug
While adding the tv show The Grand Tour (2016), the scraper found all the episodes of the two seasons I added in my library, but reported them all as episode the episode Black Tie, Black Night from the show Storm Stories.

What I reckon happened was that the scraper used the TV Show's ID from TheTVDB (which is 314087) as episode ID for all the found episodes.

The end result is that all my episodes were found but shown as Episode 11.

I tried naming them in a few different ways :
"Season xx / The Grand Tour SxxEyy - name.mkv"
"Season xx / SxxEyy.mkv"
"Season xx / Eyy.mkv"
"Season x / SxxEyy.mkv"
"Season x / Eyy.mkv"
...
None of them produced correct results.

Tried to identify it manually by title, by MovieDB ID, by IMDB ID, and picked a few of the different values returned by the Identify tool everytime, to no avail.

Changing the parser from TheTVDB to TheMovieDB worked and my episodes parsed properly.

To Reproduce

    Add "The Grand Tour" to your library
    Try to scrape it using the default options (TheTVDB)

Expected behavior
Episodes found and displayed correctly

Logs
No error logs, however, what's happening while the parsing is going on :
https://glassey.dev/jellyfin.log

Screenshots
Sorry, don't really want to redo my library with the TVDB parser for this just yet.
If absolutely necessary, I can provide it upon demand later.

System (please complete the following information):

    OS: Arch Linux
    Jellyfin Version: 10.3.5-1 (Arch Linux AUR package)

If you need anything, I guess I could provide the media upon request as well.

**Comment by Dovry** [comment]
Had same problem, tv show 'Archer (2009)', all episodes listed as the same episode of some anime I've never heard of. 
Removed TheTvDB as a metadata provider and refreshed.

**Comment by jaredallard** [comment]
Same issue, glad to see we have some sort of workaround at least.

**Comment by ChaoticHolon** [comment]
Had this exact same issue as Dovry, also with 'Archer (2009)' and a number of other shows. The problem was TheTVDB metadata provider in every case. This provider should probably be disabled until this can be fixed, because it doesn't seem to have issues with it manually disabled/removed.

**Comment by Dovry** [comment]
> all episodes listed as the same episode of some anime I've never heard of.

> https://www.thetvdb.com/?tab=series&id=110381&lid=1 [Archer (2009) / Series ID 110381]
> https://www.thetvdb.com/series/jing-king-of-bandits/episodes/110381 [All Archer episodes were identified as this episode / episode ID 110381]
That's the one

**Comment by Silent-Hunter** [comment]
Yes, this happens with Dilbert as well, it shows every episode as S1E13 of "Jake and the Fatman"

Dilbert has the same series ID as that episode's episode ID.

**Comment by Misterke** [comment]
Could someone explain the work-around a bit better?  I have a library containing several series that had some of their seasons end up with this problem.  I disabled every option I could find containing "TheTVDB" in the setting you get when selecting "Manage library" on that library, but what should I now do to "refresh" those TV series?  Scan for new/update on the complete library?  Identify the series again?  Should I delete all .nfo files created before?  So, can someone explain a bit better how to get things corrected?  Thanks in advance!

**Comment by Webbeh** [comment]
I had to clear the library and do a full rescan.

**Comment by ChaoticHolon** [comment]
I too had to fully clear the library and do a full re-scan to fix every occurrence of this without other odd shenanigans that the very wrong cached TheTVDB info was causing.
