### ISSUE TITLE
Remote and delete install Cache

### ISSUE THREAD

**Issue by koelner21** [jellyfin/jellyfin#1494]
Hello, 
I would like the following options: 

- Remote access from external should resemble that of Plex, so easy to install and the connection from external should be easy to implement even for beginners. Optionally even with the automatic installation of certificates. I	ve already had to install Emby x times and just can not create an external access 

 - Because of the multiple installations of Emby I came to my second point, because the uninstallation is not clean and many remaining files remain in the system, which can lead to further problems during the 

Thank you

**Comment by DrPandemic** [comment]
Hey, there's a lot of things in this issues and this makes it hard for us to give you any feedback. So, if you want us to use your issues, please split them in single addressable units. eg. One feature request or enhancement request. But that being said, let's try to unwrap that message.

# Remote

> Remote access from external should resemble that of Plex, so easy to install and the connection from external should be easy to implement even for beginners

We are not aiming for that. Jellyfin is not a service like Plex. We don't have and don't want central servers to manage those kind of features. This means, that we don't have central servers reachable from the Internet that we can use to middleman every connections to your personal server. That being said, we have features like UPnP that can be found under `Advanced`, that can help you achieve that.

# Certificates

> Optionally even with the automatic installation of certificates

I'm not sure to understand what you mean. But, we currently don't generate certs. This might change in the future, but right now we don't. Though, we have [a guide to help you set your cert](https://jellyfin.readthedocs.io/en/latest/administrator-docs/reverse-proxy/#letsencrypt-with-certbot).

# Cleaning

> Because of the multiple installations of Emby I came to my second point, because the uninstallation is not clean and many remaining files remain in the system, which can lead to further problems during the

Here, I don't have enough information to really help you, there's many important variables like your OS and how you installed Jellyfin. But we try to not dirty your system too much. We normally write to a data folder and a cache folder. Those folders can be found in Jellyfin's `General` settings. If keeping your system clean is really important to you, you should consider [using docker to run Jellyfin](https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#official-docker-hub). 

Since this issue is not really usable to us (there's too many things and no actionable), I'll close it soon if it doesn't get modified. Also, feel free to [come talk directly with us](https://jellyfin.readthedocs.io/en/latest/getting-help/). Your questions might have been answered faster there.

**Comment by koelner21** [comment]
Ok... thanks for this answer. 

I Hope the SDK for Synology Installation comes soon.

**Comment by DrPandemic** [comment]
If I remember correctly, nobody on the core team has a Synology but there was some people offering some help to test it. The discussion is currently on https://github.com/jellyfin/jellyfin/issues/293
