### ISSUE TITLE
Move all metadata providers to plugins

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1550]
**Is your feature request related to a problem? Please describe.**

Metadata providers are part of main server code. Updates only possible with server updates.

**Describe the solution you'd like**

All functionality related to metadata providers should be moved to plugins. These plugins would come pre-installed. This would allow for metadata provider updates on a separate schedule than server updates.

**Describe alternatives you've considered**

**Additional context**

These plugins could also serve as an example code base to add more metadata providers.
This is a low priority enhancement in my opinion.

**Comment by nextlooper42** [comment]
Also this plugins should include ALL posible languages supported by content providers.

**Comment by Xyz00777** [comment]
it would also be cool when you could say in what languages the metadata should be scraped (all or only marked languages) with a list. So that when you have your display language in eg rusian, than the information you see are in rusian and when you have it in german than in german (with english as fallback when scraped metadata is not available in the language)

**Comment by cvium** [comment]
The work for this has already begun. I don't think it makes sense to keep this open.
