### ISSUE TITLE
Support for Fedora 25?

### ISSUE THREAD

**Issue by ronilaukkarinen** [jellyfin/jellyfin#1618]
Hello! I'd love to try Jellyfin, but my server runs on Fedora 25 and the current package is only for fc29. Any way to install from source or other ways to install for Fedora 25? I'd rather not upgrade my whole system just for Jellyfin. Thanks in advance!

**Comment by onny** [comment]
It is possible to run the latest Jellyfin inside a docker container, see [here](https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#containers)

**Comment by timhughes** [comment]
@ronilaukkarinen can this ticket be closed. 


Not a developer here so please don't take this as an an official statement. You really should upgrade your server. Fedora 25 went well almost 2 years ago https://fedoramagazine.org/fedora-25-end-life/ This means there are probably numerous security issues with your server. While this may not be critical depending on how you use it, it is not the best situation to be in. I understand that upgrading something that has all your media on it is not fun especially if it is all on one disk, it is probably something you need to do rather than expecting people to support a product that is end of life. 

If you can ,remove the HDD with all your media, then use a second HDD to install a new version of fedora and then put the media drive back in and mount it. This way you protect the HDD with all your media from being overwritten when you are doing the upgrade. This should only take about half an hour or so.

**Comment by ronilaukkarinen** [comment]
@timhughes Good point. This is my home server with only some web server featured enabled, of course I should have it more up to date. But as my devops-father said (rest his soul), don't update what aint broken. Started 25->26->27 upgrade today, let's see how it goes. I'll close this ticket once I get jellyfin up and running. Been using Plex but open for alternatives and eager to try new things :) thanks for the support so far!

**Comment by ronilaukkarinen** [comment]
I have upgraded my server to Fedora 30. The rpm package for 29 works fine on this version also. This issue is now resolved, thanks for everything!
