### ISSUE TITLE
Database rapidly increases in size

### ISSUE THREAD

**Issue by utiltiy** [jellyfin/jellyfin#1655]
Hello,
i use the same data source for emby and jellyfin. The host with emby use for database:`1,7G    /var/lib/emby` and jellyfin use current: `6,3G    /var/lib/jellyfin` and blow up more, every day.
Where is the problem?
I use jellyfin as debian/lxc on proxmox, they shoot my storage system two times!

**Comment by onny** [comment]
You mean in terms of size? Can you install the command line tool ``tree`` and run:
```
tree --du -h /var/lib/jellyfin
```
Please post the output here :)

**Comment by utiltiy** [comment]
Please: https://pastebin.ubuntu.com/p/X2YyXd4Qds/

**Comment by onny** [comment]
The file which is over 4GB big is ``/var/lib/jellyfin/data/library.db-wal``
I'm also using Jellyfin for music and movies but my file is only at 10MB. Does anybody know what this file is for?

**Comment by utiltiy** [comment]
I delete this thre days ago, now it ist also big as before

**Comment by utiltiy** [comment]
I restart the server btw., at now, yes it did a big import, but the file is every time so big and bigger. Last time, whitout new files in my storage used the database up to 7 GB and more, this is not normal, or?

**Comment by utiltiy** [comment]
I have 415 GB music and 745 GB video in my storage.

**Comment by utiltiy** [comment]
Today:

> sudo du -ch --max-depth=1 /var/lib/jellyfin
56K     /var/lib/jellyfin/plugins
68K     /var/lib/jellyfin/root
8,3G    /var/lib/jellyfin/data
12K     /var/lib/jellyfin/ssl
68K     /var/lib/jellyfin/localization
24K     /var/lib/jellyfin/.dotnet
4,0K    /var/lib/jellyfin/transcoding-temp
1,5G    /var/lib/jellyfin/metadata
9,8G    /var/lib/jellyfin
9,8G    insgesamt

**Comment by utiltiy** [comment]
Today the same, 9,8 GB from yesterday. This is not usable, i switch jellyfin off!

**Comment by joshuaboniface** [comment]
I noticed something similar to this, my `library.db-wal` is over 9GB. I've never seen it this big before. We'll do some digging.

**Comment by utiltiy** [comment]
Bug or feature this issue?

**Comment by joshuaboniface** [comment]
Definitely a bug. Mine has almost doubled again:

```
-rw-r--r--  1 jellyfin adm      188M Sep  3 21:07 library.db
-rw-r--r--  1 jellyfin jellyfin 384K Sep  3 21:09 library.db-shm
-rw-r--r--  1 jellyfin jellyfin  14G Sep  3 21:09 library.db-wal
```

**Comment by joshuaboniface** [comment]
@utiltiy Have you tried flushing the WAL? I just did so and it seems stable again. After some discussion this seems to be a long-running, inherited issue.

To flush the WAL:

```
sudo systemctl stop jellyfin
sudo -u jellyfin sqlite3 /var/lib/jellyfin/library.db
> PRAGMA wal_checkpoint;
```

**Comment by utiltiy** [comment]
I use your commands, but my *wal is also big as before 9,7GB

**Comment by utiltiy** [comment]
Is this OK
`[2019-09-04 22:48:59.320 +02:00] [INF] Default journal_mode for "/var/lib/jellyfin/data/library.db" is "wal"
[2019-09-04 22:49:06.397 +02:00] [INF] PRAGMA synchronous=1`

**Comment by utiltiy** [comment]
Yesterday i install a new fresh and clen jellyfin on a lxc with debian.

It run's fine, but after hours comes the problem back with the libary. The system restarts some times without any hint in the logfile and blow up the database.

Here the restart from the logfile: https://pastebin.ubuntu.com/p/nQKjTMfc83/

jellyfin can't clean the "wal" file in this short time between the restarts, so make every restart an additional size to the libary an blow them up.

**Comment by utiltiy** [comment]
I think, i found the problem / bug!

I have one plugin installed, TMDb Box Sets.

When i switch off the function in "Setting - General  'Automatic Updates' 'Allow the server to restart automatically to apply updates'" is all fine.

My Database with a fresh scan is now:
`289M    /var/lib/jellyfin/data/library.db`
`64K     /var/lib/jellyfin/data/library.db-shm`
`17M     /var/lib/jellyfin/data/library.db-wal`

It seems the restart every time, see my logfile here, blow the *wal up and a cleanup is so not possible for jellyfin

**Comment by utiltiy** [comment]
Today, without Automatic Updates is also all fine :)

I found my problem!

Developers please have a look at this code, i think there is a bug inside - thanks!

**Comment by utiltiy** [comment]
No feedback from any developer, strange.....

**Comment by sachk** [comment]
I had a similar issue while running nightlies. A 82GB library.db-wal was created. My library.db is only 204Mb. I renamed it, and jellyfin was able to start just fine.

**Comment by anthonylavado** [comment]
>No feedback from any developer, strange.....

@utiltiy Sorry, we had thought this was a different issue than it was.

We were pretty sure we took out this automatic update code. We don’t have any intention of using it, because we believe you should be in control of updating manually. It is safe to have this feature off, and we will remove the option entirely.

**Comment by joshuaboniface** [comment]
Echoing @anthonylavado - sorry @utiltiy and @Disposaber, we've been deep in the prep for 10.4.0 release, and I never did type up what I found in this issue.

Basically, what's happening is that the SQLite database is using WAL, which is why that second file exists that keeps getting huge. The WAL stores details of every update to the database to prevent corruption during a crash, which is why it seems to grow most during library refreshes (since those update tons of data in the DB).

The issue is that for some reason, the WAL isn't being flushed properly. To be totally honest I'm not sure what it has to do with that checkbox, since as Anthony mentioned we actually removed auto-update functionality in a much earlier version. But without the WAL being flushed, every time the DB is updated it just keeps getting bigger.

For our side, there's 2 things to do here:

1. Find out what that checkbox is *actually* doing now that auto-update is removed, and why it would affect this.
2. If the cause isn't obvious from the above, we should look into adding manual WAL flushes at strategic points in the code, specifically after any sort of major DB operation (library scan being the big one, and also at shutdown). SQLite doen't do this automatically so it has to be explicit in the code.

Hopefully someone from @jellyfin/core with more knowledge of the DB and C# than me can take a look and see if we can get this solved quickly, if not the quick solution might just be to force that auto-update checkbox off and remove it from the UI if it indeed is solving the issue.

**Comment by utiltiy** [comment]
My problem was the auto-update function. You can see my logfiles with some restarts of jellyfin with this option. I think the WAL file can't clean if the system makes these restarts.

**Comment by anthonylavado** [comment]
@utiltiy That’s interesting - maybe we removed the update part, but not the scheduled restart. Do you have any logs showing the restart?

**Comment by utiltiy** [comment]
You found the Log in these thread as link

**Comment by Dug-lass** [comment]
So, I seem to have the bigger issue and Auto-Update does not seem to help at all. About every 8 hours, my var fills to full.....

Any other thoughts?

Centos 7, lastest
Latest Jellyfin 10.3.7

You think rolling back to something older? But what version?

**Comment by Dug-lass** [comment]
Seemed to have found my issue also.  

I also have the "Library Scan Hangs forever #1531", https://github.com/jellyfin/jellyfin/issues/1531, so I stopped the scheduled task and this seems to have fixed my issue. After a day, my file is only 43M now.

So this issue might have 2 different heads..

**Comment by VigibotDev** [comment]
[Debian 11 iotop] I get 100% I/O on jbd2/nvme0n1p2 Samsung PRO SSD when Jellyfin rescan to delete a lot of music file.
I tryed to re enable WAL to make some benchmark

jbd2 is the filesystem journaling quickly make a lot of I/O when Jellyfin use library.db....

(root|/var/lib/jellyfin/data) sudo -u jellyfin sqlite3 library.db 'PRAGMA journal_mode=WAL;'
wal

But on restart Jellyfin overwrite the journal_mode :

(root|/var/lib/jellyfin/data) sudo -u jellyfin sqlite3 library.db 'PRAGMA journal_mode;'
delete

Can you give a some tuning in system.xml for sysadmins ?
A way to consume more ram (i have 64GB on this server) for better performance ? I must move my database to a ramfs (lol) or a non journaling fs ?
