### ISSUE TITLE
/mediabrowser/Notifications/Admin Endpoint returns 404

### ISSUE THREAD

**Issue by s-zeng** [jellyfin/jellyfin#1681]
**Describe the bug**
@dkanada as discussed on matrix
A variety of applications such as Sonarr and Radarr support Emby interfaces that try to use the /mediabrowser/* REST endpoint. However, it seems that current versions of Jellyfin do not support this endpoint, and therefore break compatibility with these legacy applications.

**To Reproduce**
1. Start up Sonarr
2. In settings->connect, create a new Emby (Media browser) connection
3. Plug in a valid jellyfin host, port, and API key
4. Press the 'test' button, and observe the following error:
```
Unable to send test message: HTTP request failed: [404:NotFound] [POST] at [http://localhost:8096/mediabrowser/Notifications/Admin]
```

**Expected behavior**
According to matrix chat, it is a general rule to conserve compatibility, at least until version 11 of Jellyfin. So it is expected that we should preserve this endpoint.

**System (please complete the following information):**
 - OS: Gentoo hardened non-root user, running portable build
 - Browser: Any
 - Jellyfin Version: Nightly build (commit e87d7cfaf3ce2432e9a1da9901b96d5a683a7e00)
 - Reverse proxy: None

**Comment by anthonylavado** [comment]
To be clear for others, we are looking to add these back for now for release 10.4.

**Comment by Qstick** [comment]
Are there API docs for new/future state? We can go ahead and start working on support in **arr separate of the Emby Implementation.

**Comment by anthonylavado** [comment]
@QStick There's nothing at the moment. Right now, pretty much everything is the same as Emby with one change, which is authentication. We don't auth with a hash, we take the plaintext password instead. The endpoint change described in this issue is only in the nightly builds, and we're planning to revert it for backwards compatibility for now.

On the larger side, an API re-write is theoretically planned for 11.x, but we don't have a timeline that far out. If you wanted to go ahead, I would say it's perfectly fine to do so for now :-)

**Comment by thornbill** [comment]
It looks like this is the root cause of https://github.com/jellyfin/jellyfin-androidtv/issues/155 also. The Android TV app calls `/mediabrowser/users/{USER_ID}` when validating a user is authenticated. This should probably be updated in the Java apiclient so it will generate the url using the same method as all other API requests.

Refs: https://github.com/jellyfin/jellyfin-apiclient-java/blob/b9c78aa57526490abde74434b0b4592302ff5a0d/library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/ValidateAuthenticationResponse.java#L41
