### ISSUE TITLE
Subtitle extraction is slow

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#172]
With subtitles disabled, an 11GB mkv started playback almost instantly. With subtitles enabled, it took around 60 seconds before playback began.

`ffprobe` and `mkvinfo` command output.

[30_days_of_night.mkvinfo.txt](https://github.com/jellyfin/jellyfin/files/2683128/30_days_of_night.mkvinfo.txt)
[30_days_of_night.ffprobe.txt](https://github.com/jellyfin/jellyfin/files/2683129/30_days_of_night.ffprobe.txt)

**Comment by JustAMan** [comment]
Isn't this a ffmpeg thing?..

**Comment by nvllsvm** [comment]
Yeah, but there might be something we can do here.

**Comment by JustAMan** [comment]
We may want to add an option like "Don't wait for subtitles to be extracted, start playback straight away", or "Extract subtitles upon import". Opinions?

**Comment by nvllsvm** [comment]
I agree. With a spinning indicator would be great.

**Comment by MatMaul** [comment]
I will have a look, but perhaps instead of extracting subtitles we could convert it on the fly with ffmpeg to webvtt which seems supported by browsers in an HLS stream.
This would cut the need from extracting them.

**Comment by MatMaul** [comment]
And still avoid video transcoding to burn the subtitles.

**Comment by MatMaul** [comment]
No that's the point, you only need to extract because we are providing an out of band srt to the player, which need to be fully there before the playing begins. If the subtitles are in the HLS stream no need to extract, they will be converted by ffmpeg on the fly and added chunk by chunk to the HLS stream.

**Comment by MatMaul** [comment]
Talking text subtitles here. For picture subtitles we don't really have a choice for now indeed, we would need quite some logic client side to handle the overlay.

**Comment by JustAMan** [comment]
I'm not particularly fond of HLS - some my content is in vp9/vorbis, other in x265/aac. Neither fits to hls causing transcoding on the fly.
I'd rather look into DASH as a possible alternative to HLS (or looked into something that would allow me to select audio tracks - right now this html5 api support is... flaky at best).

**Comment by MatMaul** [comment]
DASH looks nice indeed. It seems to supports embedded webvtt subtitles too.

**Comment by Tthecreator** [comment]
The strange thing is that with jellyfin it takes minutes while if I use a custom ffmpeg command, extraction is waaay faster. Pretty much instant. The problem lies with WaitForExitAsync, called from SubtitleEncoder line 608. I'm trying to fix it now but I've never worked with C# before and am a little bit thrown off by code like ```() => tcs.TrySetResult(HasExited)```.

**Comment by Tthecreator** [comment]
Fixed. I also learned a lot trying to fix it so that's a good thing.

**Comment by cvium** [comment]
Closing this as it was either included in 10.1.0 or 10.2.0
