### ISSUE TITLE
IMDB ratings

### ISSUE THREAD

**Issue by yoasif** [jellyfin/jellyfin#1741]
Any chance there could be a IMDB community rating import added to jellyfin? I prefer this as a rating source if at all possible.

**Comment by anthonylavado** [comment]
Hey there, I believe you get this if you enable OMDB support in your Library settings. We do pay for it and it’s there to use :-)

**Comment by zehnerGIT** [comment]
is this also valid for tv data?

For example:

I have Chernobyl on bluray and created stubs for it. Folderstructure is:

Chernobyl
Chernobyl\S01\
Chernobyl\S01\Chernobyl-S01E01.bluray.disc
Chernobyl\S01\Chernobyl-S01E02E03.bluray.disc

I would expect
S01     9.5
E01     9.5
E02     9.7
E03     9.6

If I enable german data, series metadata (order: TVDB, MovieDB, OMDB), season metadata (MovieDB) and episode metadata (TVDB, MovieDB, OMDB), then I get:
S01     9.5 (OK), description is german
E01     8.6 (NOK), description is german
E02     8.6 (NOK), description is german
E03     not listed, no description (I think jellyfin handles episodes the same way like emby and combines episode 2 and 3, but other software like KODI lists separate episodes if multiple episodes are on one disc)

Then I changed the order for series metadata (order: OMDB, TVDB, MovieDB) and episode metadata (OMDB, TVDB, MovieDB) and update with "Replace all metadata". Result is:
S01     9.5 (OK), but description is now english (NOK)
E01     8.6 (NOK), description is german
E02     8.6 (NOK), description is german
E03     not listed, no description

I've switched the order again to: series metadata (MovieDB, TVDB, OMDB) and episode metadata (MovieDB, TVDB, OMDB) and updated again:
S01     9.5 (OK), description is german
E01     9.059 (NOK), description is german
E02     9.481 (NOK), description is german
E03     not listed, no description

What settings do I have to make, to get IMDB ratings for episodes or is this not supported?

**Comment by anthonylavado** [comment]
So I dug into this further. TheTVDB appears to have it's own stale ratings provided through its API (which don't appear anywhere on the website). TheMovieDB also has community ratings, which get imported when it's turned on.

OMDB does give us an actual IMDB rating (and pretty accurate too, though there is some cache delay sometimes), but the others get "preferred" because they have more series data to provide.

In this case, it would make sense that we figure out some method of setting a preferred rating source for the library. I would make it just OMDB for all myself, but some users might like the ratings from other sources.

**Comment by anthonylavado** [comment]
Regarding the disc handling - you're the first person I know of to ask about this in Jellyfin, and for right now, I don't know how it works. The best I can say is that it behaves like Emby would have in version 3.5.2.

**Comment by zehnerGIT** [comment]
> So I dug into this further. TheTVDB appears to have it's own stale ratings provided through its API (which don't appear anywhere on the website). TheMovieDB also has community ratings, which get imported when it's turned on.
> 
> OMDB does give us an actual IMDB rating (and pretty accurate too, though there is some cache delay sometimes), but the others get "preferred" because they have more series data to provide.
> 
> In this case, it would make sense that we figure out some method of setting a preferred rating source for the library. I would make it just OMDB for all myself, but some users might like the ratings from other sources.

but even with OMDB at first place, I don't get the IMDB rating for episodes (8.6 is not the IMDB rating)?

TVDB always had their own ratings on their website. They disappeared with one of their latest updates (perhaps the update is not finished and they appear again?). Their switch from V2 to V3 was very problematic. V3 was published, then reverted to V2, then back to V3...

For example the TVDB-Plugin of KODI also has a setting to use IMDB ratings instead of TVDB ratings and their universal metadata plugin allows to configure different metadata providers for title, description, genre individually. But Jellyfin has a finer configuration with the order of the plugins, so this setting would not be needed in my opinion. If OMDB is at first place, OMDB should be used, but then the language setting must have precedence (search the metadata providers for the first column data in the given language in the given order). Otherwise OMDB would be very problematic for non english users, because IMDB has many columns in multiple languages (title, ...) but some columns (description, genre, ...) are always english. Without searching the second or third provider for non empty data in the given language, you always have a mix of german and english data

**Comment by zehnerGIT** [comment]
> Regarding the disc handling - you're the first person I know of to ask about this in Jellyfin, and for right now, I don't know how it works. The best I can say is that it behaves like Emby would have in version 3.5.2.

Episode handling should be equal to emby, because handling of multiple episodes and crossover episodes should be the most mentioned feature requests for tv data on their forum. I find the current solution someway inconsistent, because the behavior is more like S01E01-001 and S01E01-002 (e.g an episode is split in two parts and aired on different days) and not S01E01E02.iso (there is more than one episode on the disc). For downloaded episodes, where each episode is in a separate file, everything works as expected, but for users with original DVDs and BluRays it's not ideal.

**Comment by anthonylavado** [comment]
@zehnerGIT I agree that the handling can be improved for ratings. It was only a cursory search last night (I’m UTC -4, so it was ~00:22), so it’s something we should look closer at.

Regarding the disc episode handling, if the current handling is “wrong”, I would suggest another issue so we don’t lose track of it here. If it is working as it was in Emby 3.5.2 but could be better, perhaps a feature request would be best: https://features.jellyfin.org 😄

**Comment by zehnerGIT** [comment]
You are right, the disc episode handling is not wrong, it's only not ideal for all scenarios. I have created a new feature request for it, perhaps more jellyfin users want this change

**Comment by cvium** [comment]
Re-open on https://features.jellyfin.org if it's still relevant.
