### ISSUE TITLE
Proper handling of HTTP/HTTPS during setup and in settings

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#192]
Currently, the settings for handling HTTP/HTTPS listening ports, Certs, and local-only binding is a convoluted, broken mess. See #177. SSL it seems cannot even be turned off if it is not wanted. And if it is wanted inside Jellyfin, then there should be an option to turn HTTP off.

Therefore, we should have a dialog box in the Setup Wizard (reuse the one that asks 2 of these questions already), as well as an identical revamp of the "Expert" -> "Advanced" -> "Hosting" menu, to look like this (`*` indicates an existing field):

```
Access Control
Lan Networks [field]*
Remote IP address filter [field]*
Remote IP address filter mode [dropdown]*
Enable automatic port mapping [y/n checkbox, "y" by default]*
External domain [field]*

HTTP listener
Enabled [y/n checkbox, "y" by default]   Bind Address [field, "0.0.0.0" by default]   Port [field, "8096" by default]

HTTPS listener
Enabled [y/n checkbox, "n" by default]   Bind Address [field, "0.0.0.0" by default]   Port[field, "8192" by default]
SSL Certificate [field]*
SSL Certificate password [field]*
Secure connection mode [dropdown]*
```

We'd need the requisite modifications to enable/disable the listeners as well inside the code, so it's not just an UI improvement.

**Comment by joshuaboniface** [comment]
Digging through the code, it seems that there is actually a configuration option to enable/disable HTTPS, and worse still it's set to false by default:

```
<EnableHttps>false</EnableHttps>
```

This clearly isn't being reflected in the running configuration though.

From what I've found, this would include:

0. Discovering why this `EnableHttps` flag doesn't actually work.
1. Some configuration schema changes to add some of the new fields. For backwards compatibility we can keep and map the old ones to sane values in the new system.
2. Backend code to actually handle the various config states (specifically disabling HTTP).
3. API improvements to handle the frontend setting these config values.
3. Frontend improvements to add the new config values to the various pages.

I'm going to take a stab at implementing this and see how poorly it goes.

**Comment by DraZtiK** [comment]
Wouldn't a reverse proxy be an additional step/service to something which I assume Jellyfin would want to provide if the majority of the code is there? I'm just getting into trying out Jellyfin and think anything exposed to the WAN should be as secure as possible but adding additional steps may put people off. 

It's possible I'm not aware of the work required to provide HTTPS or what clients will not support it?

It seems as if it once worked [here.](https://emby.media/community/index.php?/topic/44757-setting-up-ssl-for-emby-wip/#entry419089? )

**Comment by sparky8251** [comment]
@DraZtiK As this is a volunteer project taking over an existing codebase, finding cruft that can be removed is likely one of the better options for moving forwards. HTTPS needs to be secure, which means this would take a lot of maintenance work in the future even if its made to work now (for security patches).

I'm in favor of removing HTTPS entirely. On first install, if you browse to it via HTTP throw a warning with the link to the wiki article on setting up a reverse proxy. Then maybe have the option for it replaced by a link to the wiki article explaining how to enable HTTPS access in settings. 

The official docker container should then include an HTTPS setup with LE certs by default.

Solves the "just trying" and "don't want to support an additional feature" issues for the most part (though not entirely).

**Comment by sparky8251** [comment]
Well, at least with docker we can keep the "simple port forward and go" mentality, even with the complete removal of HTTPS from Jellyfin.

I do understand that docker is a bit much for some folks, especially since its another thing to learn even if its minimal. The problem will be how we handle packaged bare metal installs, since there will be no easy or reliable way to automate the setup of an HTTPS reverse proxy that way.

All that said... I personally see no benefit to keeping HTTPS bundled. Especially since reverse proxies can be largely automated or easily setup with minimal documentation and it only assists those that are lazy or largely incapable of server management.

If we really do want HTTPS support built into Jellyfin, instead of distributing a single SSL cert we should pull in openssl as a dep and have a post install hook added to the packages to generate a self signed cert it can use. That way it's at least somewhat secure and automatically configuring.

**Comment by VGrol** [comment]
Honestly, @jeff7269 is pretty much on the money here.
Syncthing is exactly what you want to strive for in regards to implementation.
Both accessibility, security and sane defaults are implemented perfectly in that project.
So much so that a user never has to worry about certs, local forwarding or anything of the sort.
and the option to forbid http when required.

As for @sparky8251, I personally don't think you're going to have a lot of success catering a 'plug and play' mentality for docker images, as your average user has no idea what a docker image *is*.

Anything beyond a simple on/off switch for encryption is going to confuse a large portion of users.

Incase anybody wants to look at the Syncthing implementations mentioned.
[Syncthing docs](https://docs.syncthing.net/)
[Syncthing repo](https://github.com/syncthing/syncthing)

**Comment by anthonylavado** [comment]
@joshuaboniface Seems we should split this issue? UI component should go to jellyfin/jellyfin-web, and the server part stays here?

**Comment by sparky8251** [comment]
Meh... I'd say just keep it here. It requires significant server changes and most folks tend to default to looking in this repo for "project wide" issues.

**Comment by JustAMan** [comment]
Yeah, let's keep it here and add companion issue in `jf-web` when backend is ready for new settings.

**Comment by mazzystr** [comment]
Running yet another process (rev proxy) is an unacceptable solution.  I should not have to stand on one leg and rub my belly to stream.  The function should be minimal as possible meaning udp.  If we must do https the app needs to support it.

**Comment by EraYaN** [comment]
Well since the http implementation is custom right now, I don’t think you should be directly exposing it to the internet anyway.

**Comment by dkanada** [comment]
Any discussion on the interface isn't really related to the server and can be handled in the web repository. This discussion should be about which options we want to include for the web server, and then we can display those on the clients without issue. For example, checkboxes will always be used for boolean settings and options will be in select menus.

**Comment by npodbielski** [comment]
Probably I do not have say in this, but Microsoft states in docs: 
>If deploying on Linux, you should run a comparable reverse proxy server such as Apache or Nginx to proxy requests to Kestrel 
Kinds funny since they say that .net now have full web server and then they say: 'well actually it should not be used you know'. ;) 
Anyway since this is recomended way I guess Https should be removed, and maybe added some internal proxy in snap or docker.

**Comment by EraYaN** [comment]
I mean Kestrel should be used especially in containerized applications where you only want one process and you use a platform ingress or load balancer. And of course on Windows. And so you can’t just remove Https, that is not the move.

**Comment by npodbielski** [comment]
>And of course on Windows. 
I don't know about docker for windows. I would not use it since there is docker on linux. Acording to docs
https://aspnetcore.readthedocs.io/en/stable/fundamentals/servers.html#choosing-a-server
On windows you should use IIS too. Also load balancing? I do not know what is target of this project but I do not think that large companies need media server and even they need they probably would use more mature project or paid software. That leaves with home solutions with few users. I do not think load balancing is necessary for that. If official use of kestrel on linux is with proxy then I think three images: nginx, certbot and jellyfin would be much easier to deal with it. Look at bitwarden project. They have shell script with 'start', 'stop', 'update' and etc commands. Certificates via LE and nginx proxy. This is much easier to deal with and works. With jellyfin i created pfx added it to application without success and with no logs why it do not work.

**Comment by Artiume** [comment]
While http still can't be turned off, I think this can be resolved with this https://github.com/jellyfin/jellyfin-web/pull/1140
