### ISSUE TITLE
No playback on Chromecast with HDHomeRun device

### ISSUE THREAD

**Issue by mooninite** [jellyfin/jellyfin#1921]
**Media Info of the file**

MPEG2 TS stream from HDHomeRun HDHR4-US.

**Logs**

I have 3 command lines in the following gist:
https://gist.github.com/mooninite/3bf4c1c3151254ad9eb36673433f1fcb

The first two command lines are from Jellyfin 10.4.0. The first is the failing line used with Jellyfin and Chromecast. The second line successfully transcodes and plays in a Chrome browser. The third line is from Emby that successfully plays on a Chromecast.

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Fedora 30
 - Jellyfin Version: 10.4.0
 - Hardware settings & device: hardware transcoding is set to None, Intel Xeon server
 - Reverse proxy: apache
 - Other hardware notes: HDHomeRun HDHR4-US
 
**Client System (please complete the following information):**
 - Device: Chromecast 3 and Pixel 3
 - OS: Android 10
 - Client: Browser and Android
 - Browser (if Web client): Chrome
 - Client and Browser Version: 77.0

**Comment by stevehayles** [comment]
For me trying to transcode (VAAPI or QuickSync) to either the Android app or a Chromecast device failed.  This was from a DVB-T stream from the HDHomeRun as described in this issue.

It seems to be an incompatibility around the matroska container format and the use of headers in key frames vs extended data.  I haven't issued a pull request because I am new to the codebase and don't feel confident it's the correct fix but removing the 'global_header' flag for any mkv stream seems to solve it for all my test cases

Before the flag gets added within MediaBrowser.Controller\MediaEncoding\EncodingHelper.cs I simply check for an mkv container and don't add the flag in that case

```
if (!state.RunTimeTicks.HasValue)
{
    if (string.Compare(state.OutputContainer, "mkv", true) != 0)
        args += " -flags -global_header";
}
```

Hope it helps point in the right direction

**Comment by JustAMan** [comment]
First line uses some non-HLS transport.
It might be better to deprecate it and migrate all clients to use HLS one (clients include Chromecast).

paging @cvium who's the last one who touched Chromecast IIRC, feel free to tag other relevant people

**Comment by mooninite** [comment]
@stevehayles has the correct fix - works here. @stevehayles would you be willing to provide a patch?

**Comment by JustAMan** [comment]
This still doesn't look completely fine, as I would say the real issue is somewhere else.
Though I'm fine with workarounding this as shown above, as it should only very slightly increase the size of transcoded video (the fact that no one should really care about).

Maybe we should remove this `global_header` flag altogether...
