### ISSUE TITLE
Add jellyfin-ffmpeg support for Ubuntu 19.10 on armhf

### ISSUE THREAD

**Issue by FranzFelberer** [jellyfin/jellyfin#1951]
**Describe the bug**
Jellyfin can't be installed on Ubuntu 19.10 (missing dependency)

**To Reproduce**
`sudo apt install jellyfin`

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

**The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-ffmpeg but it is not installable
E: Unable to correct problems, you have held broken packages.**
```
**System (please complete the following information):**
 - OS: Ubuntu 19.10 (armhf)

**Comment by JustAMan** [comment]
I'm debating whether this issue should be here or in https://github.com/jellyfin/jellyfin-ffmpeg ... thoughts?

**Comment by ioogithub** [comment]
I have the same problem on Debian. I have tried installing on Debian 10.2 (Buster) and Debian Bullseye (testing). I have the same problem, can't install jellyfin because it depends on jellyfin-ffmpeg and I can't install jellyfin-ffmpeg because it depends on libx265-165 (>= 2.9) but it is not installable.

Does this mean that Jellyfin doesn't support Ubuntu and Debian? I've been struggling with this all night but if my OS isn't supported please let me know so I can move on to another project.

**Comment by JustAMan** [comment]
ping @joshuaboniface

**Comment by Artiume** [comment]
i believe this is fixed
