### ISSUE TITLE
Better Handling of Movie Versions in Multiple Directories

### ISSUE THREAD

**Issue by trumblejoe** [jellyfin/jellyfin#205]
Presently multiple versions of a movie in different directories will create multiple library entries, this is different then the (proper) handling of multiple versions of a movie while all are in the same directory.

Example :  Kids/Movies/
Dir Nutty for Nuttz (1988)/
..Nutty for Nuttz (1988).mkv
..Nutty for Nuttz (1988) Theatrical.mkv
Plex Versions/Optimized for TV/
..Nutty for Nuttz (1988).mkv

Should handle the same as,

Dir Nutty for Nuttz (1988)/
..Nutty for Nuttz (1988).mkv
..Nutty for Nuttz (1988) Theatrical.mkv
..Nutty for Nuttz (1988).mkv Optimized for TV Version

**Comment by JustAMan** [comment]
Could you please provide some points on why you think it should do so? Having related stuff in a directory looks good enough IMHO, what if there are several movies (like, "something - part1" and "something - part2") which _are_ different movies indeed?
The first example that comes to my mind is "Harry Potter and the Deathly Hallows".

**Comment by iacchi** [comment]
I agree this would be useful (although maybe not a top priority). To give a few examples, I keep my SD and HD movies in two separate folders, but for some movies I have both a SD and HD version. It would be good to have them listed as one item, with the possibility to choose between versions/qualities inside the movie page. Another example might be (although I agree it's a pretty rare example) Star Wars, where I have different versions, e.g. original, remastered, and so on.

**Comment by trumblejoe** [comment]
I just want to add one more point which is neither a subtraction nor an
addition to this conversation but right now Jellyfin shows the entire file
path at the bottom of the media item summary page and this is an *extremely
useful* thing to have and regardless of whether or not this idea is taken
further now or in the future, I hope that the file-path can remain.

**Comment by iacchi** [comment]
I never updated this issue, but I've noticed that in Jellyfin 10.1.0 this issue is at least partly fixed. You can now group different versions of the same movie by long clicking on one, then in the special edit mode that appears you can click on the other versions as well and in the top right menu click on "Group versions".
I say it's partly fixed because in the library list the different versions are not listed as a single entry, but they are still listed as different entries with a number on them specifying the number of different versions present. If you click on any of them, on the movie page you can select the version that you want to play. Since I'm telling Jellyfin that these different files are different versions of the same movie, it would be good if said movie was listed only once in the library listing (or inside a collection).

**Comment by PyR8zdl** [comment]
Any news on this? This is the only issue stopping me from moving from emby to jellyfin.
