### ISSUE TITLE
Login fails when using the "PIN-less" feature

### ISSUE THREAD

**Issue by JuantAldea** [jellyfin/jellyfin#2125]
**To Reproduce**

1. Create a user
2. Enable PIN login & leave it empty
3. Try to log in with it. User card's appears w/o the lock icon as expected.
4. Can't log in

**Logs**
```
jellyfin    | [20:09:53] [ERR] Error authenticating with provider Default
jellyfin    | MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
jellyfin    |    at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
jellyfin    |    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
jellyfin    | [20:09:53] [DBG] Serializing to file /config/config/users/1234/policy.xml
jellyfin    | [20:09:53] [INF] Authentication request for 1234 has been denied.
jellyfin    | [20:09:53] [ERR] Error processing request: [172.17.0.1] Invalid user or password entered.
```
I get the same error when connecting using the port redirection (see source IP changes):
```
jellyfin    | [20:10:50] [ERR] Error authenticating with provider Default
jellyfin    | MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
jellyfin    |    at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
jellyfin    |    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
jellyfin    | [20:10:50] [DBG] Serializing to file /config/config/users/1234/policy.xml
jellyfin    | [20:10:50] [INF] Authentication request for 1234 has been denied.
jellyfin    | [20:10:50] [ERR] Error processing request: [192.168.1.34] Invalid user or password entered.
```

**System:**
 - OS: Linux Docker, using either bridged (172.17.0.2/16) or host network-mode.
 - Client: Android TV & Website
 - Jellyfin Version: 10.4.3

**Comment by anthonylavado** [comment]
I don’t think we support empty PIN codes. You have to enter _something_ in to that field.

One way to tell it has worked is when you click save - if accepted, a button that says “Reset easy pin code” will appear. Otherwise, it has not taken effect.

**Comment by anthonylavado** [comment]
Okay, current workaround:

* Set an easy pin code (like `1234`)
* Click save
* Click “Reset easy pin code”

PIN is now blank in the system, even though text appears.

**Comment by JuantAldea** [comment]
It still asks for password, although it accepts an empty one.

**Comment by uchagani** [comment]
#2537 is probably related to this issue.

**Comment by dkanada** [comment]
I hope to overhaul the PIN feature in 10.6.0 if I can find the time.

**Comment by obradovichv** [comment]
I think this issue would more appropriate in `jellyfin-web`.
The contradictory behavior happens here: https://github.com/jellyfin/jellyfin-web/blob/cebcef6090525e54a1fece4b6c965c0c937cf877/src/controllers/dashboard/users/userpasswordpage.js#L73
If the entered easy pin is blank, no action is taken to save it.

The challenge in allowing a blank pin to be entered arises because a "blank pin" is not the same as "no pin". Unfortunately the same field is used to determine both (i.e.: the user has a blank pin, therefore the user has no pin).

Once a pin is saved for a user, the update form will not contain the value in future updates unless the user enters it each time (likely for security and because the value is now hashed).
Removing the non-blank condition would allow blank pins to be submitted but may lead to an unintended user experience.
For example:
1. A user might set a pin, (e.g.: `1234`) but does not check `Enable in-network sign in with my easy pin code`
2. They return to the page and check `Enable in-network sign in with my easy pin code` and save without re-entering the pin (assuming it would be preserved in the back end)
3. A blank pin is now stored for the user unintentionally

**Is this desirable?**

Without a larger overhaul the simplest way to intuitively have pin-less login might be use the existing flow but relabel some components.
Clicking the `Reset easy pin code` actually saves a blank password for the user (which is how the workaround is able to achieve this), I propose changing the checkbox description from 
> Use the easy pin code to sign in to clients within your local network. Your regular password will only be needed away from home. If the pin code is left blank, you won't need a password within your home network.

to something along the lines of
 
> Use the easy pin code to sign in to clients within your local network. Your regular password will only be needed away from home. If you reset easy pin code, you won't need a password within your home network.

It does mean re-localizing the text, but I suspect this is unavoidable for any interface change that would enable intuitive pin-less login.

**Comment by Hoernchen52** [comment]
Sorry for my bad english. I have installed jellyfin on MX-21.1_ahs_x64 Wildflower. Server runs only with systemd, with SysVinit its give an error.
