### ISSUE TITLE
jellyfin-git not updated on AUR

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#2168]
From a user report about a separate issue, it looks like `jellyfin-git` has stopped updating, but I’m not sure.

@z3ntu are you able to check it out?

**Comment by telans** [comment]
This may be an issue with `yay` (if that's what you tested with?) because otherwise pacman detects the version change as an upgrade

**Comment by z3ntu** [comment]
"stopped updating"? I've updated the package several days ago and it worked fine back then. If there's something not right in the packaging process, the package should be flagged out-of-date in the AUR with a reason why.

**Comment by dkanada** [comment]
Yeah, I think git packages on the AUR don't show users when the git repository has updated, only when the package itself has been updated. The user is probably seeing no updates when they check and think it means the package isn't working, but they have to manually update again for the latest commit to get used.

**Comment by z3ntu** [comment]
Yes, that's how `-git` packages work in the AUR ¯\\\_(ツ)\_/¯

Quote from [the Arch Wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?):
> Because these packages only download the latest available source when you execute makepkg, their pkgver() in the AUR does not reflect upstream changes.

**Comment by anthonylavado** [comment]
It’s confusing when a user says they’re running “10.4.0.r318.g831d1daa68” but I guess they were just looking at the wrong place. I don’t know enough sadly

**Comment by telans** [comment]
Actually regarding this specific package, it fails to be auto-updated when a commit is pushed to this repo, for some reason. I have to manually trigger an update for it to well, update.





> It’s confusing when a user says they’re running “10.4.0.r318.g831d1daa68” but I guess they were just looking at the wrong place.

What do you mean by this? That version was correct as supplied supplied by `pacman -Qi` (just not updated for a few days)

**Comment by z3ntu** [comment]
A user can rebuild the package every day and they will get a fresh package every time (assuming something has changed in the jellyfin git repo). The pkgver displayed in the AUR web interface is not accurate because it displays more or less a random value for pkgver (when the packager has last updated the PKGBUILD and uploaded it). The AUR does not do any dynamic updating of pkgvers automatically (because that would require either cloning repos or running any code which it doesn't do).
A user using AUR packages (and especially -git) packages is responsible for rebuilding the packages when needed (in the case of -git packages rebuild when they want to get a new version).
Changes to the PKGBUILD of -git packages only have to happen when something packaging-wise has changed (e.g. a new dependency, different build procedure, etc).

**Comment by telans** [comment]
Usually that process is streamlined when using an aur helper (works for other git packages, just not jellyfin-git). Updated my comment saying so

**Comment by z3ntu** [comment]
`jellyfin-git` has two git repos as source, so that might be the reason why the AUR helper is confused. Anyways, if you want that fixed, file a bug report for your AUR helper.
