### ISSUE TITLE
DVD subtitles (VobSub) are wrongly converted to SRT 

### ISSUE THREAD

**Issue by KeepBotting** [jellyfin/jellyfin#2239]
**Describe the bug**
External subtitle tracks in VobSub format (`.idx`/`.sub`) can be selected but subtitles are never shown onscreen

This appears to be because the sub track is converted to SRT, but the original files (.idx/.sub) should instead be played by Kodi directly.

Please grep through logs present in various issue comments for more information.

**To Reproduce**
1. Obtain a file with external subtitles
2. Play the file, note the ability to select the subtitle track
3. Note the lack of subtitles

**Expected behavior**
VobSubs should appear on the screen as other external subtitles (SRT) and muxed subtitles do.

**System (please complete the following information):**
 - OS: Docker server, LibreELEC client
 - Jellyfin Version: `10.3.5`, `10.4.0`, `10.4.3`
 - Kodi Version: `18.3`, `18.4`, `18.5`, `18.6`
 - Addon Version: `0.2.1`, `0.3.4`, `0.4.0`, `0.5.3`

**Comment by iwalton3** [comment]
Currently in MPV Shim I don't declare support for external PGSSUB and VOBSUB in the profile because otherwise it tries to send it but gets an empty file. I do for [*.sub](https://en.wikipedia.org/wiki/MicroDVD) files because that is also a text subtitle format, but this effectively breaks external vobsub subtitles without telling the client to transcode using the menu. (https://github.com/iwalton3/jellyfin-mpv-shim/issues/27)

I think a good solution would be to add the ability for the client to download the stream as a remuxed *.mks file. That can embed both the *.idx and *.sub file and is supported by mpv.

It also might help to have some way to differentiate between *.sub and *.sub/*.idx in the profile. But if it just serves mks for bitmapped subtitles it doesn't matter for my specific client.

**Comment by KeepBotting** [comment]
If any testing related to this is needed, please ping `branon` in IRC/Matrix

**Comment by sevenrats** [comment]
fixed by https://github.com/jellyfin/jellyfin-kodi/issues/189

**Comment by Shadowghost** [comment]
Likely fixed by #7960 or #8087

**Comment by sevenrats** [comment]
closing this issue, as its "likely fixed."
Please open a new issue if you experience this problem.
