### ISSUE TITLE
HD HomeRun Binding to Local HTTPS port when Secure connection mode: set to RP

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2259]
**Media Info of the file**

JF is attempting to bind to the `Local HTTPS port number:` when the network settings `Secure connection mode:` is set to `Handled by Reverse Proxy`

**Logs**

`
[tcp @ 0x55b019f6c800] Connection to tcp://127.0.0.1:8920 failed: Connection refused
https://127.0.0.1:8920/LiveTv/LiveStreamFiles/743d4f78d0564ef5ac4ba4102b11db23/stream.ts: Connection refused
`

Verified `Local HTTPS port number:` by setting Local HTTPS to 8921 and Public to 8919, testing came back as 8921. 

When changing `Secure connection mode:` from RP to Disabled, it requires a server restart to take effect.

When changing `Secure connection mode:` from Disabled to RP, the effects are seen immediately. 

Also, what should the difference be between Disabled and Handled by Reverse Proxy?

Not confirmed by me but I believe Disabled breaks Chromecast casting.

**Comment by PrplHaz4** [comment]
Glad you opened this. I had tried to document it but didn't get far.

IMO disabled should return http port (8096) on internal networks and public http port (80) for everything else. Handled by RP should return the public https port number (443) for everything. 8920 should only be used when there is an SSL cert loaded in Jellyfin.

I believe this also impacts DLNA and Chromecast clients.

**Comment by Artiume** [comment]
Why not public port 8096 for disabled or expose it and allow it to be modified. The preferred needs to be removed lol. The reverse proxy one can be tricky due to NAT or unique ports. The more I think about it, the more my head hurts

**Comment by PrplHaz4** [comment]
> 
> 
> Why not public port 8096 for disabled or expose it and allow it to be modified. The preferred needs to be removed lol. The reverse proxy one can be tricky due to NAT or unique ports. The more I think about it, the more my head hurts

Sorry my assumptions were that the existing config pages would stay mostly the same, and that exposing JF publicly should be done through RP.  I agree with defaults it would be 8096 that is returned for Disabled/Public.

So, generally for the configured ports, the `Local` ports should always be returned to clients on internal networks and `Public` ports should be returned to clients on external networks.

**Secure Connection Mode**

**Disabled:**
- Internal Network Clients: `Local HTTP`
- External Network Clients: `Public HTTP`

**Preferred:**
- DELETE THIS PLEASE!

**Required:**
- Internal Network Clients: `Local HTTPS`
- External Network Clients: `Public HTTPS`

**Handled by Reverse Proxy:**
- We should be able to provide what used to be called WAN Address (or something like that?) where we provide the URL/port that will be returned to all clients, so JF is not guessing the domain/port combo
- Do not differentiate btw clients on internal network or external network

In my head I want separation between "what ports should Jellyfin server listen on" from "where should I tell clients to find my Jellyfin server"

**Comment by Artiume** [comment]
Gotta be careful about how the RP does things. Hairpinning isn't supported in every home network/router.

**Comment by PrplHaz4** [comment]
> 
> 
> Gotta be careful about how the RP does things. Hairpinning isn't supported in every home network/router.

I'm OK if I have to specify the Jellyfin URL twice.  Handled By Reverse Proxy to me should mean let me explicitly tell JF what it should return to clients.
- Internal Network Clients: `https://jellyfin.example.com:443`
- External Network Clients: `https://jellyfin.example.com:443`

**Comment by Artiume** [comment]
Internal Network Clients: https://jellyfin.example.com:443

hairpinning :D

**Comment by PrplHaz4** [comment]
> 
> 
> Internal Network Clients: https://jellyfin.example.com:443
> 
> hairpinning :D

haha...yes i was just saying that if i had to enter an internal and external as the same i would be ok with that

**Comment by PrplHaz4** [comment]
created a doc task for this here: https://github.com/jellyfin/jellyfin-docs/issues/196

**Comment by bengalih** [comment]
Just adding some comments here instead of the other testing thread which is more generic:

1) Issue of "external" vs "internal" clients isn't straightforward.  If you are using a RP setup the RP is on the internal network in many/most configurations.  So even if client accesses JF via RP, JF would still return the "internal" address over the local LAN.

It seems to me that you will likely need to do some rewriting of requests based upon your needs as mentioned here:
https://github.com/jellyfin/jellyfin/issues/1396#issuecomment-570444722

2) Haripinning - yes...a shame when this can't be used.  It does work for me, but even so, due to issues with ISP outages, I have also setup split DNS internally.  So this is definitely an option.  Also, while not ideal, there is no reason you couldn't use jellyfin.example.com and jellyfin.internal.com.  True, this might require you to setup two server connections on your remote devices (like phone), but it still works.

The problem is that I'm not sure the issues you are describing are "bugs" per-se as much as unintended/unforseen use cases.  Ofc, I always told my dev team that as long as they document how it *does* work, then we don't consider a bug, we consider it "by-design" :).

It seems there hasn't been a lot of dev traction on this at all - and I think the right answer is a fairly large redesign of how things work, not a simple line fix in the present code.  That said, I think you guys will probably need to be inventive in a solution such as some of the options presented above.
Good luck!

**Comment by JustAMan** [comment]
I would say that when you set connection mode to "handled by reverse proxy" JF expects the RP to sit on the same host as JF itself, and to listen on JF secure port (instead of JF).
Not very smart set of assumptions, but if you take those, then JF behaviour is correct.

So it's working as intended, it was just intended backwards :D

**Comment by bengalih** [comment]
> I would say that when you set connection mode to "handled by reverse proxy" JF expects the RP to sit on the same host as JF itself, and to listen on JF secure port (instead of JF).
> Not very smart set of assumptions, but if you take those, then JF behaviour is correct.
> 
> So it's working as intended, it was just intended backwards :D

My NGINX server is *not* on the same box as my JF install, and I use the "handled by RP" setting and everything works.  In fact, without that setting things *don't* work, so I don't believe that statement to be accurate. 

I'm not sure how the RP being on the same machine or otherwise would make a difference or be considered backwards.  I would think most people - who have the ability would run their RP on a box separate from their services, but I see no reason why it shouldn't work with all services on the same box.  I'm pretty sure most people who are having issues have either not put the effort into configuring it properly, or they are in some sort of double-NAT scenario like a docker container which seems to cause more complications.

**Comment by JustAMan** [comment]
As you say yourself, most people using a RP would put it on a separate box, but JF currently _mostly_ expects it to sit on its localhost. That's why I call it "backwards". I can also call it "awkward" if you wish.

**Comment by bengalih** [comment]
> As you say yourself, most people using a RP would put it on a separate box, but JF currently _mostly_ expects it to sit on its localhost. That's why I call it "backwards". I can also call it "awkward" if you wish.

I guess I've misinterpreted your last statement.  The way I read it is you are stating that JF and RF proxy must sit on the same box for "Handled by RP" to function.  I was providing a data point that it does not seem to be accurate based on my experience.  Therefore, I don't understand your statement at all as it seems irrelevant/inaccurate based on my experience and current setup.
I must not be understanding what you are stating - could you please clarify?

**Comment by JustAMan** [comment]
We're both saying the same, but I am just adding that current JF implementation in a lot of cases expect the RP to sit on localhost which doesn't make a lot of sense. That's why I called it awkward.
