### ISSUE TITLE
compile source on window10 dont create emby.exe

### ISSUE THREAD

**Issue by gogoule** [jellyfin/jellyfin#231]
when i compile de source on windows10 the %APPDATA%\Jellyfin-Server\ is create, there is EXE for FFMPEg but no EXE for jellyfin.

**Comment by gogoule** [comment]
thanks , i will try this evening a home.

**Comment by LogicalPhallacy** [comment]
I could, but I think Joshua is slightly off. The windows build process no longer creates embyserver.exe (due to renames) but jellyfin.exe is created (this is essentially a wrapper for dotnet.exe being called against the dll)

When I get the documentation update done, I will call this out and resolve this issue, but for now you can use the jellyfin.exe

**Comment by joshuaboniface** [comment]
Thanks for the correction @LogicalPhallacy !

**Comment by gogoule** [comment]
thanks eveybody, now i have DL and  test the windows bluid verssion of this site and , it ok!

thansk again.
