### ISSUE TITLE
Playlist section is blank if user doesn't have access to "All Libraries"

### ISSUE THREAD

**Issue by HanFox** [jellyfin/jellyfin#2369]
**Describe the bug**
Playlist section is blank if user doesn't have access to "All Libraries".

**To Reproduce**
1. Create a playlist on a user who doesn't have access to "All Libraries"
2. Try to view playlist in "Playlists" page
3. Playlist is missing

**Expected behaviour**
That playlists are still available to users when they don't have access to all available libraries.

**Logs**
[2020-02-02 23:10:57.671 +00:00] [WRN] "**USER**" is not permitted to access Library "Playlists".

**System**
 - OS: Arch Linux
 - Browser: Firefox
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Auto Organize, Email Notifications, Open Subtitles, Playback Reporting
 - Reverse proxy: nginx

**Additional context**
It seems like attempts to fix this (or potentially similar issues) have come up before, and been merged, but evidently failed to fix this issue.

See recent confirmation of the issue by another user:
https://github.com/jellyfin/jellyfin/issues/1228#issuecomment-572911875
https://github.com/jellyfin/jellyfin/issues/1228#issuecomment-572920286

Similar bugs:
https://github.com/jellyfin/jellyfin/issues/1413
https://github.com/jellyfin/jellyfin/issues/339

**Comment by JhonnyMnemonic320** [comment]
I have the same issue. Using Jellyfin Version: 10.7.5 and the problem isn't solved.

I have different account with different permission and they behave this way:
1. Admin with _checked_ `Allow this user to manage the server` and _checked_ `Enable access to all libraries` --> can access to playlist in the home page.
2. User01 with _unchecked_ `Allow this user to manage the server` and _checked_ `Enable access to all libraries` --> can access to playlist in the home page.
3. 2. User01 with _unchecked_ `Allow this user to manage the server` and _unchecked_ `Enable access to all libraries` --> **can't** access to playlist in the home page. Even if the playlist was created by this same user.

**Comment by hoewer** [comment]
Issue is still present in Ver. 10.7.7.

Whenever a user's Library Access is resricted (unchecking "Enable access to all libraries"), auto-generated categories/libraries like "Movies", "TV-Shows" etc. are not accessible.

It's just an idea, but there is no option to explicitly grant access to auto-generated libraries like "Movies" or "TV-Shows". Access may therefore simply be impossible if "Enable access to all libraries" is unchecked. Simply adding the possibility to grant specific access (as if they were classic libraries) would solve the issue in this case.

Log-Entry is similar to JhonnyMnemonic320 
[WRN] [21] Jellyfin.Api.Controllers.ItemsController: "UserXY" is not permitted to access Library "TV-Shows".
[WRN] [58] Jellyfin.Api.Controllers.ItemsController: "UserXY" is not permitted to access Library "Movies".

For me it is a severe issue, since I did not plan to give full Library access to all users.
It is however possible to access permittet content by directly choosing the correct library. But esp. for younger kids I'd like to keep access as simple as possible.

**Comment by hoewer** [comment]
I guess this issue is covered here: #5939 ,
where it has been confirmed as bug yesterday.
