### ISSUE TITLE
[Feature Request] Animated (GIF) option for cover art

### ISSUE THREAD

**Issue by jamiethomaswhite** [jellyfin/jellyfin#2439]
I'm really not sure this is even possible and what the impact would be, especially in terms of resource usage, but I think it would a visually stunning (if a bit distracting) layout option to have animated cover art.

In my process of finding the coolest cover art for my media library, I was looking through options for my anime collection and found some fantastic GIF based cover/title art. This lead me to thinking about shows and films, especially ones that have an intro section with cool graphics during the credits and title reveal. I thought it would be interesting to be able to choose an animated image format like GIF and use it as the cover art and have it as a layout option, along with Default, Thumb, Banner etc.

**Comment by ZadenRB** [comment]
Wondering what people's thoughts are on only animating GIF's on hover to address the "distraction" aspect.

**Comment by GlassedSilver** [comment]
> Wondering what people's thoughts are on only animating GIF's on hover to address the "distraction" aspect.

I'm a big fan of this solution.
That + on an album's own page itself.

(can we unstale this idea?)

also, one should probably store the animated version separately from the static one, especially because fetching animated coverart might need less broad providers. So that the static one isn't just generated from the first frame of the animation.

As for format... probably better to not support gif. Apple Music (which I guess you'd usually source for animated coverart) uses gif and mp4 afaik. Animated webp and heif could be good further third and/or fourth candidates.

**Comment by felix920506** [comment]
Feature requests should be submitted to https://features.jellyfin.org

**Comment by GlassedSilver** [comment]
> Feature requests should be submitted to https://features.jellyfin.org

Fair enough, here's the feature request:
https://features.jellyfin.org/posts/3114/support-for-animated-coverart-gif-mp4

@jamiethomaswhite ping in case you're still interested and want to upvote there
