### ISSUE TITLE
Jellyfin:latest no VAAPI encoding with RX550

### ISSUE THREAD

**Issue by moritz31** [jellyfin/jellyfin#2473]
**Describe the bug**
Hardware encoding does not work with the latests linuxserver.io/jellyfin container.
The ffmpeg exits as seen in the logs.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients:  Browser
 - Browser: Edge/Firefox/Chrome
 - Jellyfin Version: nightly
 - Playback: Transcode
 - Installed Plugins:none
 - Reverse Proxy: traefik
 - Base URL:  none

**Expected behavior**
Hardware transcoding should just work

**Logs**
ffmpeg logs:
https://pastebin.com/SCniTqVL

vainfo in docker container

> error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 19.2.8 for Radeon RX 550 Series (POLARIS11, DRM 3.33.0, 5.3.13-2-pve, LLVM 9.0.0)
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileVC1Simple : VAEntrypointVLD
VAProfileVC1Main : VAEntrypointVLD
VAProfileVC1Advanced : VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSlice
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileNone : VAEntrypointVideoProc

discussion started in #1901

**Comment by nyanmisaka** [comment]
It is a bug in mesa driver and you can build mesa 20 or higher version with this [patch](https://trac.ffmpeg.org/ticket/8006)  to fix it. I have test it on my RX Vega.

**Comment by Artiume** [comment]
thanks @nyanmisaka

**Comment by nyanmisaka** [comment]
I create a PR to mesa with my tweaked patch hoping they can accept it.
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3983

**Comment by barolo** [comment]
> I create a PR to mesa with my tweaked patch hoping they can accept it.
> https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3983

@nyanmisaka 
Last time that I've tried that patch it made it work but produced garbled/corrupted results.

**Comment by barolo** [comment]
Just tested it with git-mesa and I'm very happy to report that it finally works, with very light cpu usage [ I'm using Raven APU ]

**Comment by moritz31** [comment]
Thank you guys, i guess i will just wait.

**Comment by Artiume** [comment]
Are there any docs you guys want me to add to show how to apply the Mesa patch?

**Comment by barolo** [comment]
@Artiume  The modified patch got merged, easier to just use git-mesa

**Comment by nyanmisaka** [comment]
> @Artiume The modified patch got merged, easier to just use git-mesa

These two PRs are a better solution. Should soon be merged into the main line of mesa.

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4001
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3998

And since some fixes related to 10-bit conversion were merged in the mesa mainline not long ago, these fixes may not backport to the previous version. You can probably expect these fixes in mesa 20.1.

**Comment by moritz31** [comment]
is there an easy way to get the git-mesa package in the docker container? 
And with 10.5.0 now released and supporting amd amf could this be used instead. Is there already some preview documentation on how to setup amd amf on linux ?

**Comment by nyanmisaka** [comment]
Try arch linux such as Manjaro. 
```
git clone https://aur.archlinux.org/mesa-git.git
cd mesa-git
makepkg -si
```
You need to manually compile jellyfin-ffmpeg because it contains an AMF-related patch. Then follow the instructions below to use it. In contrast, using AMF on Windows 10 is more convenient.


### Configuring AMD AMF encoding on Windows

1. Windows® 7 (SP1 with the Platform Update), Windows® 8.1, or Windows® 10

2. Update your Radeon Software to the lastest version

3. Use specific `ffmpeg` with `h264_amf` encoder in it.
   e.g. [`ffmpeg` 4.2.1](https://repo.jellyfin.org/releases/server/windows/versions/jellyfin-ffmpeg) comes with Jellyfin installation package and pre-compiled `ffmpeg` in [this page](https://ffmpeg.zeranoe.com/builds/win64/).

4. Choose AMD AMF video acceleration in Jellyfin and check the `Enable hardware encoding` option.

5. Watch a movie, then verify that `h264_amf` encoder is working by watching the `ffmpeg-transcode-*.txt` transcoding logs under `C:\ProgramData\Jellyfin\Server\log` or `C:\Users\USERNAME\AppData\Local\jellyfin\log` and using `GPU-Z` or `taskmgr`. 

###  Configuring AMD AMF encoding on Ubuntu

#### On Ubuntu 18.04.3

1. Install `amdgpu-pro` closed source graphics driver by following the [installation instructions](https://amdgpu-install.readthedocs.io/en/latest/).

2. Then install `amf-amdgpu-pro`:

```bash
$ sudo apt install amf-amdgpu-pro
```

3. Make sure your `jellyfin-ffmpeg` or `ffmpeg` contains `h264_amf` encoder:

```bash
$ cd /usr/lib/jellyfin-ffmpeg/
$ ./ffmpeg -encoders | grep h264_amf
V..... h264_amf             AMD AMF H.264 Encoder (codec h264)
```

> [!NOTE]
> If not contain, update your `jellyfin-ffmpeg` to the latest version and try again.
For compiling ffmpeg with AMF library, refer to [this page](https://www.ffmpeg.org/general.html#AMD-AMF_002fVCE).

4. Choose AMD AMF video acceleration in Jellyfin and check the `Enable hardware encoding` option.

5. Watch a movie, then verify that `h264_amf` encoder is working by watching the `ffmpeg-transcode-*.txt` transcoding logs under `/var/log/jellyfin` and using `radeontop` or similar tools. 


### Configuring AMD AMF encoding on Arch Linux

AMD does not provide official `amdgpu-pro` driver support for Arch Linux, but fortunately, a third-party packaged `amdgpu-pro-installer` is provided in the archlinux user repository.

1. Clone [this repository](https://aur.archlinux.org/pkgbase/amdgpu-pro-installer/) using `git`:

```bash
$ git clone https://aur.archlinux.org/amdgpu-pro-installer.git
```

2. Enter that folder and make the installation package and install it:

```bash
$ cd amdgpu-pro-installer
$ makepkg -si
```

3. Go to step 2 of **On Ubuntu 18.04.3** above.

**Comment by Artiume** [comment]
@nyanmisaka should we just update our ffmpeg?

**Comment by nyanmisaka** [comment]
> @nyanmisaka should we just update our ffmpeg?

It hasn't been updated since I last submitted [this patch](https://github.com/jellyfin/jellyfin-ffmpeg/pull/28). For those who want to manually configure AMF on Linux, they may need to compile jellyfin-ffmpeg by themselves.

**Comment by Artiume** [comment]
Yeah. So another issue that's popped up is someone needs these drivers but they're non-free. Gotta dig into the license to see if we're allowed to ship them

https://packages.debian.org/sid/i965-va-driver-shaders

**Comment by joshuaboniface** [comment]
@Artiume We're not. We can't support that inside our Docker container without violating the licenses.

**Comment by Artiume** [comment]
What about a script that checks if packages are missing at startup? We could just add info to the docks that there's post installation requirements to install missing packages

**Comment by joshuaboniface** [comment]
I think the latter is the best option - a script is still somewhat sticky territory plus adds a maintenance burden.

**Comment by Artiume** [comment]
I was trying something simple along as lines of this but I can't get it working. 

`sudo docker exec -it -u 0 jellyfin echo "deb http://http.us.debian.org/debian stable main contrib non-free" >> sudo tee /etc/apt/sources.list`

**Comment by NotExpectedYet** [comment]
> I was trying something simple along as lines of this but I can't get it working.
> 
> `sudo docker exec -it -u 0 jellyfin echo "deb http://http.us.debian.org/debian stable main contrib non-free" >> sudo tee /etc/apt/sources.list`

echo "deb http://http.us.debian.org/debian stable main contrib non-free" | tee -a /etc/apt/sources.list

that worked for me inside the container.

**Comment by JustAMan** [comment]
> Yeah. So another issue that's popped up is someone needs these drivers but they're non-free. Gotta dig into the license to see if we're allowed to ship them
> 
> https://packages.debian.org/sid/i965-va-driver-shaders

Related issue: https://github.com/jellyfin/jellyfin/issues/2726

**Comment by fengapappit** [comment]
A note or something in the logs would be a good option as I spent more than a week on trying to make it work with only an obscure error message to work with.

Maybe a warning in Jellyfin settings saying that for VAAPI on Intel, you might have to install the i965-va-driver-shaders package manually ? 

While I understand not being able to ship a non-free dependency, as it is right now, enabling VAAPI breaks any transcoding with an unhelpful error message to say the least and doesn't even fallback to software transcoding.

**Comment by Artiume** [comment]
We're working on a solution that'll replace the specific libraries with open licenses. 10.5.3 doesn't address this yet, but either the next hot patch or main release should have the fix.

**Comment by rderensy** [comment]
I'm not sure I understood everything, what's the status on this? I bought an RX550 just for Jellyfin and I can't transcode HEVC at all using VAAPI (AVC is working though).

I am running Debian 10, and everything is up-to-date (kernel 4.19.0-8, jellyfin 10.5.5.0, mesa-va-drivers 18.3.6-2, mesa-utils is not installed though, I don't think I need it since it's headless).

Should I build mesa from source to solve this or? I have no idea how to and if I should apply the patch linked above.

**Comment by Artiume** [comment]
See this thread, it might be helpful https://github.com/jellyfin/jellyfin/issues/2787#issuecomment-619763123

**Comment by Protektor-Desura** [comment]
AMD AMF and Vaapi are not working for me in the Jellyfin docker. In fact Linuxserver Jellyfin docker fixed the render group issue with /dev/dri/renderD128 not being in the video group, but it has the same problems for me.
https://github.com/jellyfin/jellyfin/issues/3580

**Comment by Protektor-Desura** [comment]
I got it working. You need to fix the render group issue for /dev/dri/renderD128. I fixed this by running the linuxserver/jellyfin docker version. Then you need to install this inside the container:
```
apt-get update && apt-get upgrade -y
apt-get install -y gpg
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu bionic main" > /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-bionic.list
apt-get update
apt-get upgrade -y
```
I also installed the amdgpu-pro drivers from the AMD website. You will need this as well for AMD AMF support also. The problem is once the docker is updated these changes will be lost. I have told the Linuxserver devs that this needs to be added to their docker.
