### ISSUE TITLE
Hardware decoding untick after playing AVI/MPEG4 files

### ISSUE THREAD

**Issue by billyinferno** [jellyfin/jellyfin#2528]
The hardware decoding configuration is being unticked after playing AVI container files.

**System:**
 - OS: Ubuntu Server 18.04
 - Clients: Browser
 - Browser: Firefox 72.0.2 (64-bit), Chrome 79.0.3945.130
 - Jellyfin Version: 10.4.3
 - Playback: Transcode
 - Installed Plugins: Report
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Local LAN
 - Storage: NAS (CIFS/Samba)
 - GPU: GTX 1650 4GB
 - Driver: 435.21 (with Unlimited Patch)

**To Reproduce**
1. Go to Dashboard
2. Go to Playback
3. Tick Hardware Decoding
4. Play AVI (AVI mediainfo: https://pastebin.com/T57d4LSP)
5. Hardware Decoding unticked, and all decoding passed to CPU (which spike the CPU)

**Expected behavior**
1. Should fall back to CPU decoding in case not supporting, but not remove the Hardware Decoding configuration

**Logs**
Transcode Log: https://pastebin.com/d23i1i4V
Jellyfin Log: https://pastebin.com/MeLekEMA

**Screenshots**
https://imgur.com/a/Zag2qhg

**Comment by billyinferno** [comment]
Further checking it seems when the media format is MPEG4, the Hardware Decoding option become un-tick.

This is tested with MP4 container with MPEG4, and the problem still persists.

Try to tick all option except MPEG4, and play the same media also give same issue.

**Comment by billyinferno** [comment]
Issue still persists in latest Jellyfin 10.5.0.

**Comment by dkanada** [comment]
We haven't tracked this down yet, but settings should never be toggled without user input.

**Comment by billyinferno** [comment]
> We haven't tracked this down yet, but settings should never be toggled without user input.

Agree, hence I am bit confused, as this only happen on MPEG4 files only as per now.

Might be due some error on the ffmpeg that causing the configuration to reset?

Any other info you need just let me know. Thanks.

**Comment by dkanada** [comment]
We've seen cases where the server has tried to automatically disable settings that weren't working properly, so I'm guessing this is the issue somewhere.

**Comment by billyinferno** [comment]
> We've seen cases where the server has tried to automatically disable settings that weren't working properly, so I'm guessing this is the issue somewhere.

I think so also, like the Jellyfin Server is decide, “oh, this doesn’t work, I need to disable this!”.

I tried screen recorded the issue, you can see it here:

https://youtu.be/EiGnIrLCcFE

**Comment by guythnick** [comment]
Confirmed I can reproduce this issue playing Xvid encoded files.

**Comment by JustAMan** [comment]
@billyinferno the JF logs you had attached show successful attempt of transcoding using NVidia HW acceleration. Please submit logs that show the failed attempt which un-ticks the box.

**Comment by AlexisLaurier** [comment]
I've exactly the same behavior as described and nothing into logs.

The hardware decoding configuration is being unticked after playing AVI container files.

System:

OS: OpenMediaVault 5.3.9
Clients: Browser
Browser: Chrome 80.0.3987.163
Jellyfin Version: 10.5.4 official docker
Playback: Transcode
Installed Plugins: Report
Reverse Proxy: yes
Base URL: none
Networking: Local LAN
Storage: Local
GPU: GTX 1060 3GB
Driver: 440.64 (with Unlimited Patch)
To Reproduce

Go to Dashboard
Go to Playback
Tick Hardware Decoding (HEVC, H264)
Set Transcoding thread count: : auto
Set Audio boost when downmixing: 2.5
Set H264 and H265 encoding preset: auto
Set H264 encoding CRF: 23
Untick Allow subtitle extraction on the fly
Untick Throttle Transcodes
Play AVI (AVI mediainfo: https://pastebin.com/matfUuwC)
Hardware Decoding unticked, and all decoding passed to CPU (which spike the CPU)
Hardware Encoding still working
Expected behavior

Should fall back to CPU decoding in case not supporting, but not remove the Hardware Decoding configuration
Logs
Two trancode log are created. However nNo issue when playing the file
Transcode Log 1: https://pastebin.com/YNAVRnW7
Transcode Log 2: https://pastebin.com/38bLNYyC
Jellyfin Log: https://pastebin.com/H2bk38qP

One strange line that make ffmpeg restart : [2020-04-20 13:32:12.416 +02:00] [INF] [5] App: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request

**Comment by JustAMan** [comment]
I wonder if this https://github.com/jellyfin/jellyfin/pull/2809 helps to fix "unticking"... cc @nyanmisaka

**Comment by nyanmisaka** [comment]
> I wonder if this #2809 helps to fix "unticking"... cc @nyanmisaka

Before this PR, many HW decoders were not listed in the validator, which caused the decoder not to be detected and caused the reset of toggles.

https://github.com/jellyfin/jellyfin/blob/a388d5dd72893fa0a4e30472bd1d5fc8854ad51d/MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs#L36

**Comment by Artiume** [comment]
this is also being seen with h264 being unticked when playing hevc
