### ISSUE TITLE
Collections Metadata lost after update

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2565]
If you upgrade to 10.5.0, the collection posters don't have their metadata.

https://www.reddit.com/r/jellyfin/comments/fgbkyj/collections_have_lost_their_poster_art/

**Comment by superhukun** [comment]
I've encountered the same issue when upgrade from 10.4.3 to 10.5.0,  several movies metadata lost in collections while some movies metadata are correct in collection.

**Comment by mcarlton00** [comment]
This may be what's causing new installs of the Kodi addon to also fail to sync boxsets properly.  It may be unrelated, but seems suspect since I started noticing the issue after I moved to 10.5.0

**Comment by tyhawk** [comment]
I'm having the same issue with 10.5.0, running a docker container (official Jellyfin image, not the Linuxserver version). Base OS is Ubuntu 18.04.3.
Only plugins I use are "Playback Reporting" and "Reporting", both version 4.0.0. "AudioDB 10.5.0" and "Musicbrainz 10.5.0" are also installled but seem to be part of the container itself.

In some collections (not even all of them), in stead of the cover/poster of the movie, you see a ransom screengrab, which is also used as a background. Most metadata is also missing. If you go to the same movie directly, everything is fine.

**Comment by CyferShepard** [comment]
10.5.2 Just launched, as far as i can tell it hast been fixed, although im not too sure if its some sort of caching issue that results in it not fixing the broken titles, maybe a clean install will help but i dont want to reset all my usage tracking.

**Comment by mcarlton00** [comment]
Confirmed still bugged.  A clean install does "fix" it, but then the issue comes back.  I suspect it's related to the library refresh scheduled task, but haven't been able to confirm for sure yet.

**Comment by lafricote** [comment]
I confirm the bug 10.4.3 ---> 10.5.0 ----> 10.5.2 and clean installation.

**Comment by CyferShepard** [comment]
So rolling back to 10.4.2 with clean install should be fine? I'm not hard pressed for new features and bug fixes because I've used 10.4.2 for a long time without issues

**Comment by AHrubik** [comment]
Problem still exists in 10.5.3

[Example 1](https://i.imgur.com/MUHrv8Z.png):
One movie has read it's cache correctly the other has not.

[Example 2](https://i.imgur.com/HPGIqO5.png): 
The movie that hasn't read the cache correctly has this "Content Type" box in the metadata menu. The movie that read the cache correctly does not.

**Comment by tyhawk** [comment]
Version 10.5.4:

- Created a new collection: movies show up as they should.
- Removed a movie to an existing, 'broken' collection: movie still doesn't show up as it should.
- Created another collection: the first three movies I added show up as they should, the fourth didn't.

Just like @AHrubik, all movies that don't show up correctly have a "Content Type" box in the metadata menu (options: Inherit & Series). The movies that show up just fine don't.

**Comment by Artiume** [comment]
We believe it is due to #2826

**Comment by BaronGreenback** [comment]
I'm also seeing repeated entries in the collection.xml for the group.

**Comment by mika91** [comment]
I checked the source code yesterday, and I can confirm there are several bugs with collections management.

The main root cause is related to #2826 
Some files are stored in the DB as both movie AND video item types.

When a collection is updated/refreshed, its children are cleared from library cache (not sure that's necessary), and when 'findByItemPath' is called to repopulate the cache entry, the "video" item type is returned instead of the movie.

I think two different stories are involved here:

- **fix broken collections root cause**: database movie/video duplicates (#see 2826)

and

-  **increase collections management robustness**

  
For the later story:

1. "AddToCollection" method should be idem potent: : If you add the same items several times, it shouldn't be duplicated in the .xml file
2. remove duplicates when writing or reading collection items .xml file
3. fix "delete" not working for 'broken' collection item
4. 'LinkedChild' should have another parameter to inform about type (movie, video, tvshow, music..)
I guess a collection could be heterogeneous.
5. 'FindByPathAndItemType' method in the libray manager as long the #2826 is not fixed
6. check if children items must be cleared from cache when collection is updated

**Comment by Artiume** [comment]
This has been fixed in nightly and is slated for 10.6, resolving ticket
