### ISSUE TITLE
Jellyfin Will Not Start, Getting: Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by Alcatraz077** [jellyfin/jellyfin#2616]
**Describe the bug**
Jellyfin will not start, logs just show `Failed to create CoreCLR, HRESULT: 0x80004005` over and over again. 

**System (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.5.1
 - Playback: N/A 
 - Installed Plugins: None
 - Reverse Proxy: Let's Encrypt/Nginx
 - Base URL: none
 - Networking: Docker - MacVLAN
 - Storage: local

**To Reproduce**

1. Install Jellyfin 10.5 via linuxserver docker repo.
2. Check Logs
3. Logs show "Failed to create CoreCLR, HRESULT: 0x80004005"

**Expected behavior**
Jellyfin to start

**Logs**
`Failed to create CoreCLR, HRESULT: 0x80004005`

**Screenshots**

**Additional context**
I've completely removed the jellyfin image, wiped my jellyfin app data folder, disabled/enabled docker, no dice.

**Comment by Bond-009** [comment]
Looks like a dotnet or linuxserver issue

**Comment by Alcatraz077** [comment]
My apologies, I'll reach out to LinuxServer people and go from there.

**Comment by Alcatraz077** [comment]
This seemed to be an issue with the container, not Jellyfin itself. Closing. Thanks for your insight Bond.

**Comment by gr33k** [comment]
I reverted to [10.8.8-1-ls191](https://github.com/linuxserver/docker-jellyfin/releases/tag/10.8.8-1-ls191) and the error went away

**Comment by paulgear** [comment]
I encountered this error today and found that it was due to /tmp being missing entirely from the official Jellyfin Docker image.  I'm not sure how this happened, but just building a new one with /tmp in place fixed the problem for me.  I've written about it in more detail here: https://www.libertysys.com.au/2023/03/a-tale-of-two-tmp-bugs/

**Comment by shazahm1** [comment]
@Alcatraz077  I'm not sure, but this might need to be reopened based on @paulgear response. I had the same issue. I tried the instructions, but I had no luck ... not experienced enough to know for sure if I was following them correctly. I managed by sheer luck to get 10.8.8-1-ls191  installed, and it worked perfectly without the error in the initial bug report.

**Comment by alanruttenberg** [comment]
I am having this problem having upgraded from 10.8.11 to 10.9.0 (also tried latest)

**Comment by alanruttenberg** [comment]
> I am having this problem having upgraded from 10.8.11 to 10.9.0 (also tried latest)

This is using docker, btw.

**Comment by TacticalLaptopBag** [comment]
I'm getting this too, on TrueNAS Scale, Jellyfin version 10.11.11. However, I did not update Jellyfin for this to start happening. I'm diagnosing now, but this seems to be a general C# error. A lot of what I'm seeing just says to reinstall C#, which is unfortunate since this is running in a container, so it theoretically should be "reinstalling" every time I restart the container ;-;

**Comment by TacticalLaptopBag** [comment]
Fixed it on my end - somehow, the solution was to delete all docker images relating to Jellyfin. If any containers still existing using those images, they need to be stopped and removed as well. Once all the images were removed, I started the Jellyfin app back up, and everything was right again. No data loss
