### ISSUE TITLE
Jellyfin 10.5.2 "Next Up" list is incorrect and won't update

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin#2686]
Hello guys, I searched and couldn't seem to find anything related to my issue. I'm running 10.5.2 on a Docker running on my Synology NAS using the official jellyfin/jellyfin package. The library is all scanned, and I've went through my library and marked my shows watched accordingly...

But it seems like Jellyfin's "Next Up" on my homepage doesn't match my actual watched status. It keeps putting random shows I haven't watched yet into "Next Up", but isn't actually showing the shows I've marked as watched and in progress.

10.5.2:
![Image](https://i.imgur.com/3Pke8OT.jpg)

As you can see, in my "Next Up" queue, there's Seton Gakuen S1E4, and We Bare Bears S4E23. I haven't watched these shows yet (And the entire series are marked unwatched), so they shouldn't be anywhere in my Next Up. And all the shows I am currently watching and have marked accordingly are missing (Curb Your Enthusiasm, One Piece, My Hero Academia, Will & Grace, etc etc). I've gone through my library and marked/unmarked the affected episodes correctly and even restarted the docker container a few times.

I have a docker container of 10.4.3 that's working fine and my Next Up is working correctly. Is this a known bug of 10.5.x? Any logs I can generate to provide? I've also noticed that 10.4.3 tends to run faster than 10.5.2...but that's an issue for another day.

**Comment by Jinxyface** [comment]
Here's another screenshot: ![image](https://i.imgur.com/p16Wz9U.jpg)

All I've done is refreshed the page and now Pokemon (haven't watched it) and Curb Your Enthusiasm (currently watching) show up.

**Comment by Artiume** [comment]
So I can replicate this. While the library is still building, show items do appear in the Next Up Section. This is occurring on nightly and 10.4.3. As the library builds, whatever appears in the Next Up Section can be bumped off. At first only a SpongeBob episode popped up. It's gone, now it's The Daily Show. On the nightly version, the library scan is at 93% and there's 24 shows in the Next Up Section. The 10.4.3 was just initialized so it only has one show for now. 

Every episode is based off the TV SHOW library type. I have three of them, Documentaries, Anime and TV Shows, Next Up has episodes from all three libraries. I can resolve this by marking watched then unwatched the episode in question, but as new content is scanned it, new shows will pop up occasionally.

**Comment by shark2k** [comment]
I just setup a new Jellyfin server (literally on 4/18/20) as I've been curious to check it out.  I am on 10.5.4 (linuxserver.io docker) and my library has been completely scanned and I am showing what looks like every single TV show from my server (I have 2 TV libraries, anime and TV shows).  I have not watched anything of type TV Shows from Jellyfin yet, so I don't feeli like anything should be showing there at this point.  What becomes more annoying (I can deal with it for now within the Jellyfin Android TV app) is that the Play Next section on my Shield TV is showing about 6 of the episodes (all from season 1) and for some reason there is no option to remove Jellyfin as being allowed to used the Play Next option so evertime I remove them from that queue, they just get added right back because they still exist in Jellyfin's Next Up section.

**Comment by dkanada** [comment]
possibly related to #2881
