### ISSUE TITLE
Support VAAPI on Intel without non-free drivers

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#2726]
As stated by @nyanmisaka, 

> `scale_vaapi=format=nv12` is necessary, otherwise transcoding may fail when the source video is 10-bit. I think the color conversion filter uses shaders. So these non-free components are necessary.
> 
> `scale_vaapi=format=nv12` was introduced in https://github.com/jellyfin/jellyfin/pull/2099

_Originally posted by @nyanmisaka in https://github.com/jellyfin/jellyfin/pull/2503#issuecomment-598178440_

I think we can try to avoid using `format=nv12` when source is 8-bit so VAAPI is usable without non-free drivers.

**Comment by cryptobank** [comment]
It should also be stressed that you will not be able to play vast majority of 4K unless you can direct play, as that is also 10-bit, unless your CPU is powerful enough to do it in software.

**Comment by nyanmisaka** [comment]
I have manually built `libva, intel-vaapi-driver, libva-utils` (all using the MIT license, without any non-free options), removing all the 2.4 version of `libva*, i965*` components existing in Ubuntu 18.04 LTS, and finally completely solved this problem. There is no longer any problem whether it is 8-bit or 10-bit transcoding or burning subtitles. I think I can consider integrating this part into our `jellyfin-ffmpeg` installation process.

**Comment by nyanmisaka** [comment]
Anyone who has encountered the problem of missing non-free intel driver can try [this](https://github.com/nyanmisaka/jellyfin-ffmpeg-dev/releases/tag/4.3-1-dev) now. 

I integrated the missing intel driver in the deb package, and it will not conflict with the `libva` and` i965-va-driver` provided by the official repository. If it is stable enough, I will start a PR to `jellyfin-ffmpeg`.

https://github.com/nyanmisaka/jellyfin-ffmpeg-dev/releases/tag/4.3-1-dev

**Comment by jgoclawski** [comment]
@nyanmisaka Hi, thanks a lot for that! I've just tested your version of ffmpeg and it works. :+1: 
I came here from #2503, because I had problems with HEVC not working with VAAPI

```
ffmpeg: i965_encoder.c:1692: intel_enc_hw_context_init: Assertion `encoder_context->mfc_context' failed.
```

Installing the non-free package `i965-intel-driver-shaders` fixed that problem.

Your version of ffmpeg works as well and fixes problems for me. HEVC decoding works on VAAPI.
Jellyfin is running in Docker on QNAP TS-453Be (CPU: Intel Celeron J3455, GPU: Intel HD Graphics 500).

**Comment by JustAMan** [comment]
@nyanmisaka I think we have enough confirmations, can you please update jf-ffmpeg with a PR if you hadn't done so already?

**Comment by nyanmisaka** [comment]
@jgoclawski @JustAMan 

https://github.com/jellyfin/jellyfin-ffmpeg/pull/33

I have already started a PR for this. Hope it will be updated with the next version of Jellyfin.

**Comment by prahal** [comment]
@nyanmisaka I am a bit late in the party but why build intel-vaapi-driver instead of using Debian non-free i965-intel-driver-shaders?
They are exactly the same!
i965-intel-driver is i965-intel-driver-shaders (ie intel-vaapi-driver) without the shaders that have no source for them in the intel-vaapi-driver repository.
intel-media-va-driver-non-free is another issue  "non-free" but is not required to fix video encode on i965, ie the error:
`ffmpeg: i965_encoder.c:1692: intel_enc_hw_context_init: Assertion `encoder_context->mfc_context' failed.`
Just pointing this out if you want to lower the code Jellyfin has to maintain.
