### ISSUE TITLE
File Limit inside a Directory

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2747]
If there are too many files inside one directory, the files will fail to play, it will cause a 413 Playload Too Long error. 

The max seems to be approximately 500 items inside a directory before issues start to occur.

**Comment by ZadenRB** [comment]
Are there any further details on this? Which request returns a 413 error?

**Comment by Artiume** [comment]
This wasn't my issue, it was reported via Matrix Chat.

This appears related. https://github.com/jellyfin/jellyfin-web/issues/590

**Comment by mahriman** [comment]
Ran into this issue today with an album with a large amount of discs and tracks , but less than 500.
The `Ids` parameter gets filled with too many hashes, causing ```net::ERR_ABORTED 414 (URI Too Long)```

**Comment by niftium** [comment]
I'm not convinced this was fixed in #1360/#2747.  I have a directory of 211 files (a soundtrack) and despite everything being correctly tagged, I still get the "Playback Error" I was getting before.  Are any other commenters still experiencing this?

**Comment by pgeorgi** [comment]
I get a 414 Request Too Long error from Kestrel because all tracks are enumerated in the URL, making it ~13kb long. According to https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits?view=aspnetcore-5.0 MaxRequestLineSize defaults to 8kb and I haven't found anything that increases it in Jellyfin (or allows to configure the value)

**Comment by jhol** [comment]
Can this be reopened? I think I just encountered it with a folder full of 500 audio recording

**Comment by thornbill** [comment]
No that is not a server issue
