### ISSUE TITLE
Playlists are deleted after library scan depending on playlist name

### ISSUE THREAD

**Issue by kwkeiser** [jellyfin/jellyfin#2845]
**Describe the bug**
Playlists are being deleted.  Happens after a library scan. It seems be related to the name of the playlist created.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.4LTS
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: Browser
 - Browser: Firefox 75 64bit
 - Jellyfin Version: 10.5.3
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: Apache
 - Base URL: Any (domain name or local host)
 - Networking: localhost
 - Storage: Local

**To Reproduce**

1. create 2 new playlists.  One named 2020.1 and one named 2020one
2. Note that two new folders are created for metadata at /var/lib/jellyfin/playlist.  The .xml file for the 2020one is created in the folder. The .xml file for 2020.1 is created one directory level higher.
3. Scan all libraries.  The 2020.1 playlist will disappear.  The 2020one will remain. Note that .xml and metadata directories are unaffected.

**Expected behavior**
Both playlists remain after scan or data validation preclude invalid playlist names

**Comment by kwkeiser** [comment]
I tested today using 10.6.2 and the issue persists.  I'm disappointed by the lack of engagement.

**Comment by dkanada** [comment]
Not many of the contributors use playlists, and I'm guessing none of us have run into this issue since it doesn't happen 100% of the time, so it has remained untouched.

**Comment by kwkeiser** [comment]
Hi, thanks for responding. I understand that I'm a noob and its not the highest priority problem but i think its 100% repeatable for the steps i listed.

**Comment by dkanada** [comment]
I checked and it does seem reproducible with the steps listed above, so this issue will no longer be touched by the stale-bot every three months.

**Comment by kwkeiser** [comment]
Thanks for the validation.

**Comment by BrianCArnold** [comment]
Well, I just ran into this bug, and I've contributed code before, so I guess I'm the contributor that's going to fix it.

I'm going to use this for some notes so I remember what I've discovered.

When playlists are saved, they're saved in `data/playlists/{playlist.Name}/playlist.xml`. However, when a playlist contains a `.`, this fails to happen correctly. Instead, the folder is created as expected, but the file is saved as `data/playlists/{playlist.Name.Split(".")}.xml` (note that this isn't the actual code that's run, that's just how I'm representing it)

So for a playlist called `My Playlist 2.Oh no`, we should expect the file with the playlist to be in `data/playlists/My Playlist 2.Oh no/playlist.xml`, but it's actually being saved in `data/playlists/My Playlist 2.xml`, but the folder `data/playlists/My Playlist 2.Oh no` is still being created.

To my eyes, it looks like it's probably something to do with how the file name is being calculated, probably just looking for an extension for some reason, but not finding it and doing something unintentional. About to dive into the code that **saves the actual file**, rather than the code that does the clean up, because I think that's about where the actual problem is.
