### ISSUE TITLE
Sort title metadata not read

### ISSUE THREAD

**Issue by Sonico98** [jellyfin/jellyfin#2908]
**Describe the bug**
Most of my music has embedded sortalbum / albumsort tags, but they are not being read by the server. Instead, the Sort title field is empty on every album.

**System (please complete the following information):**
 - OS: Archlinux 5.6.4
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.4
 - Installed Plugins: Anime
 - Reverse Proxy: none
 - Storage: Local

**To Reproduce**
1. Using either Kid3 or MP3Tag, add the Sort Album tag for an album.
2. Refresh the library's metadata.

**Expected behavior**
The newly added tag should show under "Sort title" when checking the library's metadata

**Screenshots**
![KhH7Irh](https://user-images.githubusercontent.com/61394886/79627635-627c6200-8110-11ea-966b-f55877533b9d.png)

**Comment by NeuroDawg** [comment]
Can this issue be re-opened and addressed by the developers. If not re-opened, I'll start a new issue. I tag my .flac files meticulously with how I want albums/artists/album artists to sort, yet Jellyfin doesn't read/apply those tags to music in its library. And since there is no way to assign sort metadata in batches, it would be nice if Jellyfin used these tags in the metadata files.

**Comment by bravely-beep** [comment]
I also think this should be reopened. These are commonly-used tags, and have a one-to-one mapping with Jellyfin metadata fields. I don't see why they shouldn't be supported.

**Comment by florianjacob** [comment]
Still an issue.

**Comment by nbabanov** [comment]
Hopefully https://github.com/jellyfin/jellyfin/pull/17048 will resolve the issue.
