### ISSUE TITLE
ASS subtitles unusual，several versions are like the same problem

### ISSUE THREAD

**Issue by jy3344511** [jellyfin/jellyfin#3006]
The ASS subtitles is unusual，Like a square。

Play video with browser or jellyfin-android-release-v1.0.0.apk，are the same problem。

![01](https://user-images.githubusercontent.com/49992475/80531702-9d627d80-89cd-11ea-99d3-dd7eb6300dd5.jpg)

The jellyfin version is 10.5.5 , running on docker。

**Comment by jy3344511** [comment]
The jellyfin-android-release-v1.0.0.apk，have a very important function, which has never worked。


![02](https://user-images.githubusercontent.com/49992475/80535634-b3733c80-89d3-11ea-81b3-923d0b51ac91.jpg)

**Comment by zzyandzzy** [comment]
Same problem, watching this issue.[#2670](https://github.com/jellyfin/jellyfin/issues/2670)

**Comment by jy3344511** [comment]
> The jellyfin-android-release-v1.0.0.apk，have a very important function, which has never worked。
> 
> ![02](https://user-images.githubusercontent.com/49992475/80535634-b3733c80-89d3-11ea-81b3-923d0b51ac91.jpg)


the external video players is never worked，if can fix this problem，that's better for me。

**Comment by Artiume** [comment]
This is the ticket for the broken External Player on Android. https://github.com/jellyfin/jellyfin-android/issues/302

The non-latin characters issue with ASS Subs has also been related as well. I'm closing this ticket since it's a duplicate. I'm going to post your image on the external player ticket since it's helpful to the issue.
