### ISSUE TITLE
How to make media libraries portable like jellyfin program?

### ISSUE THREAD

**Issue by iWangJiaxiang** [jellyfin/jellyfin#3078]
Hi, I put **both** portable **Jellyfin** program and its library on my portable hard drive. It works perfectly on my laptop that set them up.

However, when I connected the portable hard drive on another laptop, the jellyfin program could not load the library on the hard drive. 

The log showed Jellyfin tried to load it from the drive `J` on my first laptop instead of the drive name on the current laptop.

I think the fixed absolute library path is the reason why my media libraries not loaded when OS environment changed.

Is there any way to use relative path for library?

Or do you have better way to make libraries portable?

**Comment by Artiume** [comment]
This is a major blocker https://github.com/jellyfin/jellyfin/issues/3080

**Comment by bengalih** [comment]
I think best way would be to create some sort of symlink or drive mapping that can be duplicated when you move your system.  This would have to map to the exact same name on each system due to #3080.  I'm not sure if you are on Windows or Linux but the basic concept should be the same.

Create for example a directory called "library" at the root of the directory tree.  Then create a symbolic link or junction point from the actual library location to your library root.  Always reference the library by the "library" location in JF.  Then if you need to change your library location you would simply update the link and JF should not know better.

Another option would be to share the library via SMB and then map a drive.  As long as you always use the same drive mapping the library should appear the same to JF.

Granted, this method will take a couple minutes of setup when you move systems, but should work.

**Comment by iWangJiaxiang** [comment]
Since the reason why using portable version Jellyfin is to make the installation **PORTABLE**, I propose adding library relative path support in jellyfin `data` folder.

The `data` folder could be specific by parameter, which could be relative. So this would make library portable.

---

In summary, the library path should support two forms:

- **Non-portable** => Absolute path as usual.
- **Portable** => Relative path to jellyfin `data` folder.

**Comment by iWangJiaxiang** [comment]
Any further consideration?

This would be useful when I move jellyfin data from movable hard drive to NAS docker volume storage
