### ISSUE TITLE
Filter repository of binaries and remove other cruft from repository to shrink it

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#311]
All the removals will be done on the whole tree. (BFG and git filter-branch)

- [ ] Remove Nuget folder (also in all nested projects) Check the *.nuspec files, update or move)
- [ ] Remove ffmpeg*.7z archives
- [ ] Remove packages folder
- [ ] Remove ThirdParty folder
- [ ] Fix author name with broken UTF-8 characters to enable more git tools NOT breaking.
- [ ] Final reflog and gc
- [ ] Do something about Emby.XmlTv/Emby.XmlTv.Test/Xml Files/ES_MultiLanguageData.xml
- [ ] Remove Mono.Nat folder and change dependecy to Open.Nat for example (check for changes, switch to upstream)
- [ ] Remove .vs folder (also nested ones)
- [ ] Remove blobs larger than 10M (vote of size used below!)
- [ ] Remove all fonts
- [ ] Remove ImageMagickSharp and all other previous submodules, should be a build system prepare script that pulls these. (See 90c59cec9fce13482c0760bd933625baccdef979 for submodules to be removed (Emby.* modules excluded)

I have written a script and now used it 2 times successfully. 

For the main repo the resulting repo size is 41MB. Which is very nice. And it contains all code changes.

https://github.com/EraYaN/jellyfin_small

**Comment by EraYaN** [comment]
Wait including all the binaries?
That seems very not useful. We really will never restore any of the ffmpeg releases from 2013.

**Comment by nvllsvm** [comment]
I have another idea I'll discuss with the team that should help out without discarding history.

**Comment by EraYaN** [comment]
Mmm a full squash would do the trick, we should make sure to remove that 50MB xml and all those *.dll files before that though.

**Comment by joshuaboniface** [comment]
Yea it's not that the original idea is bad per se, it just leaves us still with thousands of redundant commits that we don't really need. Technically, based on [what was said here](https://web.archive.org/web/20181212100152/https://github.com/MediaBrowser/Emby/issues/3479), the only person we "have" to give copyright notice to is Luke, so despite Collaborator detection being broken, we'll still be in copyright compliance due to `CONTRIBUTORS.md` and one reference to him.

https://github.com/jellyfin/jellyfin/commit/50b88c5ac0e5a633d2d9aa01b446b252a6b0cb10 is our point of divergence, based on the history [here](https://github.com/jellyfin/jellyfin/commits/master?after=a6986943b2f265b72311aa71c96a80d935bdf888+279), so that seems like the best place to point the old repo to. Once we have that archive, which I'm doing now, we can squash, and then perform the history cleanup/rewrite steps with BFG as you suggest originally.

**Comment by joshuaboniface** [comment]
https://github.com/jellyfin/Emby has had its README updated. No commits were removed from it at all, just a reference to our divergence commit noted.

**Comment by joshuaboniface** [comment]
Updated the title to better reflect the idea!

**Comment by EraYaN** [comment]
You can archive the repo too. That should make everything static, and stop people from messing with it.

**Comment by joshuaboniface** [comment]
Done.

**Comment by EraYaN** [comment]
Well Mono.Nat could be removed IMHO. And most other "ThirdParty" libs too. Think ImageMagickSharp.

**Comment by anthonylavado** [comment]
Okay, in talking to @jellyfin/core, this won't be done just yet. We want to get this big release out first, then we can work on this.

**Comment by EraYaN** [comment]
I have also noticed with messing with jellyfin-web yesterday on windows and today on linux. That git is like 100+ times faster on linux, so the whole operation only takes a couple fo minutes now. So there is much more room for iteration.

**Comment by joshuaboniface** [comment]
> Okay, in talking to @jellyfin/core, this won't be done just yet. We want to get this big release out first, then we can work on this.

That time has come now that 10.1.0 is out - this is happening tonight along with consolidating into a master-only branch structure.

**Comment by nvllsvm** [comment]
Shrink complete. Used the following except that I had to manually delete the releases and git tags in the jellyfin repo. There were still referencing the old codebase.

[find-large-blobs.sh.txt](https://github.com/jellyfin/jellyfin/files/2794727/find-large-blobs.sh.txt)
[rewrite-history.sh.txt](https://github.com/jellyfin/jellyfin/files/2794728/rewrite-history.sh.txt)
