### ISSUE TITLE
Method for uploading media to the server

### ISSUE THREAD

**Issue by Strit** [jellyfin/jellyfin#312]
One of the annoying things about running a media server, has always been to get the media onto the server itself.

I would like a way to upload media to the media folders on the server itself. Kind of like a file manager, but from the webUI.

**Comment by LogicalPhallacy** [comment]
This is a good idea, but it might require n examination of user permission levels/the creation of a permissions system deeper than the admin/notadmin split that's there right now.

**Comment by Strit** [comment]
Well, make it a setting in the user profile, just like the "delete media" one is.
But yes, probably require better system permissions to write to the filesystem.

**Comment by joshuaboniface** [comment]
I'm kinda iffy on this, as I don't like what projects like Stream try to do regarding this, but if it can be implemented cleanly with a default-off flag I'd support it.

**Comment by Strit** [comment]
> can be implemented cleanly with a default-off flag I'd support it.

That's what I was thinking.
Make it an Admin only thing, that is not on by default.

Thanks for considering it!

**Comment by jaredallard** [comment]
You can always run a server on the host that allows you to upload media, i.e https://github.com/tritonmedia/twilight. Of course that's limited to in-network uploads. You could also use the entire platform (https://github.com/tritonmedia) to provide a pipeline to upload / download media.

Disclaimer: I'm the author of this, and it's not particularly ready for anyone else to deploy, but it might be useful per component.

**Comment by SenorSmartyPants** [comment]
It seems like this is a feature that would be better left to something like a WebDAV server or other software built specifically to handle uploads. Let Jellyfin just handle the media that's there.

**Comment by gsnerf** [comment]
I'm not sure it is a good idea for jellyfin to try to do to much stuff on it's own. Especially since this is crossplatform, it would probably need to support special cases for different filesystems. Also many users have different likes for stuff like folder structures naming etc. Trying to create a manager that can handle all that would essentially mean rebuilding already existing stuff like owncloud/nextcloud or similar stuff (why not use that instead?).

If this truly is something that should become a part of jellyfin I think its best seperated from the serving component into a separate file management component. Automatically adding the new files to the libaries should already be covered by the regular media scanner which monitors the library folders. Allowing this on a per user basis would definately need upload and filespace quotas, which might be overkill to start with. Better put it in the admin section and only allow admins to do this.

@joshuaboniface this request also heavily touches frontend stuff, is there a tag for that too?

**Comment by SenorSmartyPants** [comment]
> > Let Jellyfin just handle the media that's there.
> 
> But Jellyfin already can delete files/media on the server. So it's already doing part of the job of being a media manager too.

That's media that's already there. This should be a plugin IMHO if it ever gets implemented.

**Comment by thornbill** [comment]
I think this feature could make sense as part of the [Auto Organize plugin](https://github.com/jellyfin/jellyfin-plugin-autoorganize). It already handles identifying and moving new media files.

**Comment by JustAMan** [comment]
Hmm, what about "just" finding a good web-based filemanager and run it over the same place where JF libs are stored? I don't think we should aim to a Swiss-Army-Knife solution...

**Comment by Salamandar** [comment]
@JustAMan because when you're trying to "sell" jellyfin to non-tech users, that may be cool to have the upload feature integrated.

**Comment by dkanada** [comment]
We have stated since the beginning of the project that we don't have plans to add any kind of media upload to the server. It may change in the future, but that's the current stance.

**Comment by JustAMan** [comment]
I wonder if we should close this thread... it should really be a feature request here: https://features.jellyfin.org/

**Comment by Bond-009** [comment]
Already exists: https://features.jellyfin.org/posts/543/upload-file-from-the-app-or-site
