### ISSUE TITLE
unsigned repo

### ISSUE THREAD

**Issue by tgrrr** [jellyfin/jellyfin#3175]
**Describe the bug**

`sudo apt install jellyfin`

W: GPG error: https://repo.jellyfin.org/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 49023CD01DE21A7B
W: The repository 'https://repo.jellyfin.org/ubuntu bionic InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]

Ubuntu

raspberry pi, and Nvidia Jetson Nano

 - Jellyfin Version: Jellyfin.Server 10.5.5.0

**To Reproduce**

Follow these install instructions: https://jellyfin.org/docs/general/administration/installing.html#ubuntu-repository

`sudo apt install jellyfin`

Get this error:

W: GPG error: https://repo.jellyfin.org/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 

**Expected behavior**

The app is signed, and there's no error.

**Comment by karephre** [comment]
tgrrr,
Run the below command to add the key.
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 49023CD01DE21A7B`

**Comment by stribika** [comment]
I don't think this solves the issue. Sure I can fetch some random key from a keyserver, but I have no reason to think it's the correct one. It's not the one mentioned on the official website, it's not the one hosted on the repo server.

Let's assume for a moment this is an actual attack. Apt complains the release is signed with the wrong key, I download the wrong key, and tell it that's the right key. Either fix the repo or fix the website, because this is indistinguishable from a compromised repo.

**Comment by Ayitaka** [comment]
Sorry for adding such a late reply but I was going crazy trying every possible suggestion google could find to solve this problem without anything working.

Anyone using Debian Bullseye who stumbles upon this after trying the [official jellyfin install instructions](https://jellyfin.org/docs/general/installation/linux/#debian) and then tries the [suggested fix](https://github.com/jellyfin/jellyfin/issues/3175#issuecomment-635353294) by [karephre](https://github.com/karephre) but it still doesn't work, in /etc/apt/sources.list.d/jellyfin.sources you need to comment out this line:

> Signed-By: /etc/apt/keyrings/jellyfin.gpg

**Comment by jbergquist** [comment]
I know this issue is closed but for documentation purposes.

For Debian 12 Bookworm or all other Debian derivatives that use /etc/apt/trusted.gpg.d
`$> cd /etc/apt/trusted.gpg.d
$> curl -fsSL https://repo.jellyfin.org/jellyfin_team.gpg.key > jellyfin.asc
$> apt update`

And you shouldn't have the NO_PUBKEY issue anymore.
