### ISSUE TITLE
Sorting should respect the language settings of the user

### ISSUE THREAD

**Issue by ss1969** [jellyfin/jellyfin#3202]
Sorry to say that, but current (latest version in Dec,2019) sort of Chinese titles is completely useless, it cannot be used to locate titles. 
In Chinese language, you can sort characters by two ways mostly: PinYin or strokes. Most of us use PinYin。
As explained above, "蝙蝠侠"（aka "Batman") can be translated into PinYin as "Bian Fu Xia", then the Chinese way to sort them is using "bianfuxia" alphabetical.

here're some example document on this method:
 
https://blog.csdn.net/lgx040605112/article/details/6042316
https://blog.csdn.net/yeshennet/article/details/52288410
https://github.com/lisposter/sort-by-pinyin

or you can google for "Chinese Sort" for more infomation

I found something maybe useful: the web interface of jellyfin cannot sort Chinese titles correctly, but in Kodi them're correct. 

This feature is very important when you have to locate one in hundreds of movies.

**Comment by hisune** [comment]
need this feature

**Comment by J4gQBqqR** [comment]
Please note that there is a very famous library to transform Chinese into roman (latin) spelling: opencc

**Comment by BLumia** [comment]
Is it acceptable to introduce a new dependency in order to address this issue? I also have this issue as well and just took a glance of the source code, it seems the sort name is created here:

https://github.com/jellyfin/jellyfin/blob/b6d130ae2d337294904f6d46d943e9f82c162978/MediaBrowser.Controller/Entities/BaseItem.cs#L885-L899

...and it seems it always assume user are using English for the name to generate the sort name.

Libraries like [ICU](https://icu.unicode.org/) offers the ability to transliterates text from one format to another, which can be used to transliterate Chinese (and other languages as well) into Latin-Ascii, thus it can be used for sorting. It seems there are also .NET binding for the ICU transliterator as well: https://www.nuget.org/packages/ICU4N.Transliterator/

**Comment by BLumia** [comment]
Update:

My patch is here: https://github.com/jellyfin/jellyfin/pull/11172

The library mentioned above was used, hope it's okay. Once the patch is applied, it seems we still need to re-scan the library to make Jellyfin use the new `SortName`. Maybe the `SortName` is cached somewhere although I didn't find it in the sqlite database...

Also, here are some screenshots (the same screenshots posted in that PR):

![image](https://github.com/jellyfin/jellyfin/assets/10095765/1ba47f0c-7ead-46be-96dd-96b36fcebf82)

![image](https://github.com/jellyfin/jellyfin/assets/10095765/abcac750-c37e-45ae-9df1-4fcd59df7b2e)
