### ISSUE TITLE
Transcoding Does Not Work in Safari

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#3224]
**Describe the bug**
When using Safari (macOS/iOS) attempting to play any media that requires transcoding or remuxing will fail on `master`. The media will playback in another browser, such as Chrome.

**System (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Browser: Safari Version 13.1.1 (15609.2.9.1.2)
 - Jellyfin Version:
   - Server - [master@d38adb9](https://github.com/jellyfin/jellyfin/tree/d38adb95a727203b0d0dcee344f03b374b5d2b8f)
   - Web - [master@a0b99f0](https://github.com/jellyfin/jellyfin-web/commit/a0b99f0c0205f6088f1be020ce0e32e45abc6cbb)
- FFmpeg - ffmpeg-4.2.3-macos64-static from Zeranoe [(details)](https://www.zeranoe.com/builds/readme/macos64/static/ffmpeg-4.2.3-macos64-static-readme.txt)
 - Playback: Remux or Transcode
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Local
 - Storage: Local

**To Reproduce**
1. Load a media library.
2. Click play for any media that requires Transcoding or Remuxing.
3. See error "Playback Error: This client isn't compatible with the media and the server isn't sending a compatible media format."

**Expected behavior**
The media plays like it used to.

**Logs**
[ServerConsole-Chrome.txt](https://github.com/jellyfin/jellyfin/files/4715468/ServerConsole-Chrome.txt)
[ServerConsole-Safari.txt](https://github.com/jellyfin/jellyfin/files/4715469/ServerConsole-Safari.txt)
[SafariConsole.txt](https://github.com/jellyfin/jellyfin/files/4715470/SafariConsole.txt)

**Additional context**
It's believed that this started with the streaming change to HLS in #2573.

**Comment by anthonylavado** [comment]
Gathering more logs as per @YouKnowBlom.
These are all requests in Safari to play the same media as used in the previous request. Detailed media info can be provided upon request, but it should suffice to say it's an MKV with H264 video, and a DTS audio track.

[1_details.txt](https://github.com/jellyfin/jellyfin/files/4718293/1_details.txt)
[1_Master.m3u8.txt](https://github.com/jellyfin/jellyfin/files/4718299/1_Master.m3u8.txt)
[2_details.txt](https://github.com/jellyfin/jellyfin/files/4718300/2_details.txt)
[2_Master.m3u8.txt](https://github.com/jellyfin/jellyfin/files/4718301/2_Master.m3u8.txt)
[3_details.txt](https://github.com/jellyfin/jellyfin/files/4718302/3_details.txt)
[3_Master.m3u8.txt](https://github.com/jellyfin/jellyfin/files/4718303/3_Master.m3u8.txt)

**Comment by YouKnowBlom** [comment]
After some testing it seem related to the `RESOLUTION` and `FRAME-RATE` fields as when they are removed playback works. Unfortunately safari is not very verbal about HLS stuff. I'll do some more debugging and see what I can find.

**Comment by Spiritreader** [comment]
**Describe the bug**
I no longer get the "Playback Error: This client isn't compatible with the media and the server isn't sending a compatible media format" message with the latest nightly build nightly-20200606
available on dockerhub.
However media still won't play compared to 10.5.5 where everything works fine.

![image](https://user-images.githubusercontent.com/18438899/83957306-75d1c100-a867-11ea-87d5-2c7b0f10906e.png)
It only shows a struck through play icon.

**System (please complete the following information):**
- OS: iOS 12.4.7 iPad
- Browser: Apparently same as iOS version, I don't know much about apple devices, only use the ipad for streaming
- Jellyfin Version: https://hub.docker.com/layers/jellyfin/jellyfin/nightly-20200606/images/sha256-4092a5cfb5c93cd90dc79e25ae03d96fa3a0791fbc8379e0ef51da105142e379?context=explore
- Playback: Remux or Transcode
- Reverse Proxy: Yes
- Base URL: None
- Networking: Remote
- Storage: Local

**To Reproduce**
1. Load a media library.
2. Click play for any media that requires Transcoding or Remuxing.
3. Observe struck through playback icon, no playback

**Expected behavior**
The media plays like it used to.

**Logs**
Unfortunately I can't plug my ipad to my PC to show the console as I don't have a device set up for debugging.
But this is what the server logs report about the stream:

[ServerConsole-Safari_new.txt](https://github.com/jellyfin/jellyfin/files/4741234/ServerConsole-Safari_new.txt)

**Comment by Raul824** [comment]
It seems to be working in the jellyfin app. I was facing the same issue then i borrowed my friend's old iphone X and found out that the same video which is throwing error in safari is being transcoded and is playing in jellyfin app.
