### ISSUE TITLE
Real-time monitoring of new media does not work in latest 10.6.0 nightly 

### ISSUE THREAD

**Issue by eltiel** [jellyfin/jellyfin#3251]
**Describe the bug**
Moved from release 10.5.5 to nightly 10.6.0 20200604 and found that real-time monitoring of new media in all libraries is not working. When scan library task was triggered manually, the new media were promptly picked up. I made no configuration changes to my server. Reverted back to release 10.5.5 and it worked normally again.

**System (please complete the following information):**
 - OS: Synology DSM
 - Virtualization: Docker
 - Jellyfin Version: 10.6.0 nightly 20200604
 - Storage: Local using Btrfs 

**To Reproduce**
1. Use latest nightly
2. Add new media into library, with real-time monitoring enabled
3. Wait a few minutes of media to be recognised
4. New media will not be recognised until scan library task is activated

**Expected behavior**
New media is picked at real-time automatically and added into library. 

**Logs**
Not sure if logs are going to be useful here.

**Comment by akhoa12** [comment]
Hi all, it seems like this issue is still present. Jellyfin doesn't seem to recognize that new media is imported and only update it when library is scan manually.

**System (please complete the following information):**
OS: Linux Mint 20
Virtualization: Docker
Jellyfin Version: 10.6.1
Storage: Local using Btrfs

**To Reproduce**
Use latest
Add new media into library, with real-time monitoring enabled
Wait a few minutes of media to be recognised
New media will not be recognised until scan library task is activated

**Expected behavior**
New media is picked at real-time automatically and added into library.

**Logs**
Not sure if logs are going to be useful here.

**Comment by akhoa12** [comment]
Hi, it seems that this issue is still happening. My server still doesn't detect new media as soon as they are imported. I had to wait for the Scan Library task to be manually triggered.

**System (please complete the following information):**
OS: Linux Mint 20
Virtualization: Docker (linuxserver image)
Jellyfin Version: 10.6.2
Storage: Local using Btrfs

**Comment by crobibero** [comment]
> 
> 
> Hi, it seems that this issue is still happening. My server still doesn't detect new media as soon as they are imported. I had to wait for the Scan Library task to be manually triggered.
> 
> **System (please complete the following information):**
> OS: Linux Mint 20
> Virtualization: Docker (linuxserver image)
> Jellyfin Version: 10.6.2
> Storage: Local using Btrfs

What you're experiencing is not what this issue is. Please open an new issue and fill out the template.
