### ISSUE TITLE
RSSDP project license missing

### ISSUE THREAD

**Issue by cvium** [jellyfin/jellyfin#350]
It seems that the RSSDP project in the original source is from https://github.com/Yortw/RSSDP, which is MIT-licensed (and obviously, the license is nowhere to be found).

I'm not sure if any changes were made to RSSDP during the porting to netcore though, so I'm not sure what the best course of action is. The upstream RSSDP project looks like it should be compatible with netcore, so maybe it's best to grab it from nuget or something?

Problem is that the Emby team made a lot of changes to RSSDP, but I'm not entirely sure why they were necessary and I doubt we can just ask them.

For starters, the license should just be added I guess.

**Comment by EraYaN** [comment]
Any stuff that need changing should be pushed to upstream as well. Although we should make the changes from a "clean start". So we are free to push them.

**Comment by joshuaboniface** [comment]
We can't add the license, since it's not clear whether Emby kept this MIT or (as implied by its presence in the repo without an explicit sublicense) forked it into GPL. I have to assume the latter. Therefore I've added a simple copyright notice inside the submodule. If we/someone does eventually get this feature upstream, it can be replaced by a submodule.

**Comment by joshuaboniface** [comment]
Considering this closed as-is.
