### ISSUE TITLE
Multi versions break when version name contains date in 10.6

### ISSUE THREAD

**Issue by harry71019** [jellyfin/jellyfin#3605]
**Describe the bug**
The parsing for multi versions seemed to have changed a bit in 10.6
Previously in 10.5.5 for version names like:
`MovieName - Broadcast 2011.10.02`
`MovieName - Bluray`
Jellyfin recognizes the files as 2 verisons:

1. Broadcast 2011.10.02
2. Bluray

After the 10.6 update it does not recognize them as multi versions but instead creates two movies:
1. MovieName - Broadcast 2011.10.02
2. MovieName - Bluray

**System (please complete the following information):**
 - OS: Windows
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.6.0

**To Reproduce**
1. Name one of the movie versions to include an year, like "Broadcast 20111002", the parser will set the movie year to 2011.
Testing with "Broadcast 12345678" then the multi version function works fine, so i guess there is something to do with the year being parsed.

**Expected behavior**
For multi version movies, everything after the " - " should be parsed correctly as the version name.

**Comment by mikewesten** [comment]
This issue is re-occuring with Jellyfin v10.8.10

On a recent movie item I had to remove the year date from the version naming in order for the 2 versions to group correctly.

Example of what I mean:

Movie Name (1970) - [1972 Broadcast Version]
Movie Name (1970) - [Original 1970 Broadcast Version]

had to be changed to,

Movie Name (1970) - [Broadcast Version]
Movie Name (1970) - [Original Broadcast Version]

in order for the grouping to work correctly.
The first example kept splitting them up into 2 entries.
