### ISSUE TITLE
Cant uninstall plugins: how to remove them?

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#3614]
**Describe the bug**
I have installed some plugins to do some testing and i cant uninstall them now:
plugins are:  AudioDB, MusicBrainz, 

**System:**
 - OS: debian
 - Virtualization: docker
 - Jellyfin Version:10.6.0
 - Installed Plugins: audioDB Musicbrainz OMBd 

**Expected behavior**
having an uninstall button on installed plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/26579988/87937495-27822580-ca95-11ea-824f-997c4d4beb34.png)

**Additional context**
Hello!
Facing some trouble uninstalling installed plugins:
Are they mandatory or it's an instance related problem?

Is there any chance to force uninstallation or manually delete them?

Thanks for your great job on 10.6.0!

**Comment by dkanada** [comment]
Those are mandatory for now because they're bundled with the main binary. What you're seeing is the process of migrating the bundled metadata providers out into their own plugins, which isn't quite completed yet but will be eventually.

**Comment by antipiot** [comment]
@dkanada 
Thanks for your clear explanations.
Case closed - thanks

**Comment by JappeHallunken** [comment]
Will this ever be fixed?

I disabled all of these plugins for my music library, but whenever I rescan the library, my logs get spammed with:
`MetaBrainz.Common.HttpError: The MusicBrainz web server is currently busy. Please try again later.`
I don't want to use MusicBrainz, yet Jellyfin is still trying to connect to it. Why? The scan takes ages because of these requests.
