### ISSUE TITLE
Is it possible to have android server 

### ISSUE THREAD

**Issue by tom8zds** [jellyfin/jellyfin#3696]
I have some old android device , some of them have high end snapdragon cpu inside and ufs2.1 high speed  storage, it is powerfull enough to run jellyfin even in linuxdeploy but no hwa support, how about a android server for those devices to make old phones a low power media station

**Comment by PythonSmith** [comment]
A quite cool idea, but Jellyfins runtime is .NET Core. This runtime is not supported on Android.
The currently 'simple way' would be to install a linux distro in a chroot environment on your phone because their it should be possible to run dotnet. (rooted phone required)
However if we wait some time we could take advantage of .NET 6.
Another option would be to port Jellyfin to .Net Standard, but I do not know if thats possible.

**Comment by cvium** [comment]
It might be possible by re-implementing the Jellyfin.Server project in Xamarin, but feature requests belong here https://features.jellyfin.org
