### ISSUE TITLE
Plugin settings do not get saved

### ISSUE THREAD

**Issue by uuuu1234** [jellyfin/jellyfin#3705]
**Describe the bug**
After changing settings in a plugin and hitting the save button the settings are not saved despite a popup message stating "settings saved".

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Firefox
 - Browser: Firefox 78.02
 - Jellyfin Version: 10.6
 - Installed Plugins: AudioDB, MusicBrainz, OmdB, OpenSubtitles, TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Storage: local

**To Reproduce**
1. Go to 'Dashboard -> Plugins'
2. Click on 'any Plugin'
3. Adjust settings
4. Save the settings
5. go back to the plugin and see that the changes have not been saved

**Expected behavior**
settings should have been saved

**Logs**
[2020-07-26 07:25:58.627 +02:00] [WRN] [73] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.178.22". Time (slow): 0:00:03.2409744. "http://192.168.178.42:8096/Plugins/a629c0da-fac5-4c7e-931a-7174223f14c8/Configuration"
[2020-07-26 07:26:01.694 +02:00] [WRN] [85] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.178.22". Time (slow): 0:00:00.7212948. "http://192.168.178.42:8096/Plugins/a629c0da-fac5-4c7e-931a-7174223f14c8/Configuration"

**Comment by bengalih** [comment]
I have some more relevant data on this.  I just upgraded from 10.5.5 to 10.6.  One of the things I noticed is that I had Pushbullet notification plugin setup in 10.5.5 and I never received a notification that 10.6 was released.  Prior to upgrading I tested my PB and successfully got the test, so something is/was wrong with notifications.  Rather than file that bug I decided to upgrade to 10.6 first.

I had an error on upgrade because you had changed the "-noautorunwebapp" to "--noautorunwebapp"...luckily I caught that quickly....but I saw issues of Pushbullet 3.0.0.0 errors on load up of 10.6.

I tired to install PB 5.0.0.0 plugin but I was seeing access denied errors to the dll.  I shut down JF and manually removed the plugin, restarted and was able to successfully install, however I cannot configure it at all (blue circle just spins).  I also cannot properly delete it as I continue to get access denied errors when trying to remove it.  However, I believe that the issue lies with these log entries:

```
[01:07:03] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /socket
[01:07:03] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://jellyfin.mydomain.com/socket?deviceId=XXXXXXXXXXXXXXXXXXXXXXXXXXXx
[01:07:19] [ERR] [33] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /socket
[01:07:19] [ERR] [33] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://jellyfin.mydomain.com/socket?deviceId=XXXXXXXXXXXXXXXXXXXXX
```

The problem here is that "http://jellyfin.mydomain.com" does not exist.  My server is not accessible over http as I use a reverse proxy (NGINX).  So it will never be able to find that address.  I am accessing my server and configuring it over "https://jellyfin.mydomain.com", and the system should realize that.

That being said, I tried to access the server over the local IP address over HTTP and I see that I have the same problem, though the logs don't show these errors, the circle just spins.

I think I need to revert to 10.5.5, but not sure if I can after it has migrated settings?

**Comment by animegasan** [comment]
> **Describe the bug**
> After changing settings in a plugin and hitting the save button the settings are not saved despite a popup message stating "settings saved".
> 
> **System (please complete the following information):**
> 
> * OS: Ubuntu 20.04
> * Virtualization: Docker
> * Clients: Firefox
> * Browser: Firefox 78.02
> * Jellyfin Version: 10.6
> * Installed Plugins: AudioDB, MusicBrainz, OmdB, OpenSubtitles, TheTVDB
> * Reverse Proxy: none
> * Base URL: none
> * Storage: local
> 
> **To Reproduce**
> 
> 1. Go to 'Dashboard -> Plugins'
> 2. Click on 'any Plugin'
> 3. Adjust settings
> 4. Save the settings
> 5. go back to the plugin and see that the changes have not been saved
> 
> **Expected behavior**
> settings should have been saved
> 
> **Logs**
> [2020-07-26 07:25:58.627 +02:00] [WRN] [73] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.178.22". Time (slow): 0:00:03.2409744. "http://192.168.178.42:8096/Plugins/a629c0da-fac5-4c7e-931a-7174223f14c8/Configuration"
> [2020-07-26 07:26:01.694 +02:00] [WRN] [85] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.178.22". Time (slow): 0:00:00.7212948. "http://192.168.178.42:8096/Plugins/a629c0da-fac5-4c7e-931a-7174223f14c8/Configuration"

If you use the docker, always restart the Jellyfin container. Then there are changes, when pressing restart via dashbord there is always no change

**Comment by uuuu1234** [comment]
Thanks animegasan, I restarted the docker container, but this makes absolutely no difference. I know that after installing a plugin you need to restart jellyfin in order to take effect, but this should not be the case for just changing plugin settings.
And as I said restarting the docker container does not result in changed plugin settings being saved.

**Comment by animegasan** [comment]
> Thanks animegasan, I restarted the docker container, but this makes absolutely no difference. I know that after installing a plugin you need to restart jellyfin in order to take effect, but this should not be the case for just changing plugin settings.
> And as I said restarting the docker container does not result in changed plugin settings being saved.

What is the problem with the AudioDB and MusicBrainz plugins?

Because I just tried checking all the plugins, there are some problems, Anime, AudioDB, and MusicBrainz plugins. And that is exactly what you said.

**Comment by uuuu1234** [comment]
Hi animegasan,

for example, if I try to enable the check boxes in the settings of the AudioDB plugin as shown in the screenshot attached, they are deselected when I return to the settings later although I saved them.
 
![Screenshot from 2020-07-26 09-21-19](https://user-images.githubusercontent.com/49108043/88473839-fd0aef00-cf10-11ea-9ccd-7558d9efe24c.png)

**Comment by crobibero** [comment]
Dupe of https://github.com/jellyfin/jellyfin/issues/3633, will be fixed in 10.6.1

**Comment by xiNeRoar** [comment]
This happens again after updated to 10.10.7

**Comment by KittySaysRawr** [comment]
This still happens in version: 10.11.6, trying to save plugin setting changes reloads the page and the changed settings are not displayed.
