### ISSUE TITLE
Official docker jellyfin/jellyfin vs linuxserver/jellyfin config directory

### ISSUE THREAD

**Issue by geek-baba** [jellyfin/jellyfin#3717]
I am documenting this for others for the visibility as I came across this while switching from LSIO image to official image, the reason I did it because the official image was updated a day before compared to LISO image (10.6). The config directory of these 2 very different and switching from one image to another is not compatible (I looked and it may be possible if you moved stuff manually but very tedious).

LISO image config directory is as follows:
```
jellyfin:~# ls -la /config/jellyfix
total 76
drwxr-xr-x 8 k8s k8s 4096 May 22 13:15 .
drwxr-xr-x 9 k8s k8s 4096 Jul 20 16:49 ..
-rw-r--r-- 1 k8s k8s  195 May 22 13:15 branding.xml
drwxr-sr-x 6 k8s k8s 4096 May 22 13:15 cache
drwxr-sr-x 8 k8s k8s 4096 Mar 19 09:34 data
drwxr-sr-x 4 k8s k8s 4096 Jul 14  2019 dlna
-rw-r--r-- 1 k8s k8s  508 Jan 10  2020 dlna.xml
-rw-r--r-- 1 k8s k8s 1235 Jul 21 11:53 encoding.xml
drwxr-sr-x 2 k8s k8s 4096 Jul 24 23:59 log
-rw-r--r-- 1 k8s k8s 1362 Mar 17 18:55 logging.default.json
-rw-r--r-- 1 k8s k8s  907 Jul 14  2019 logging.old.json
-rw-r--r-- 1 k8s k8s  243 Jun 27 08:44 metadata.xml
-rw-r--r-- 1 k8s k8s 1166 Jul 21 11:39 migrations.xml
-rw-r--r-- 1 k8s k8s  236 Jan 11  2020 playback_reporting.xml
drwxr-sr-x 2 k8s k8s 4096 Jan 17  2020 ScheduledTasks
-rw-r--r-- 1 k8s k8s 6494 Jul 21 11:39 system.xml
drwxr-sr-x 5 k8s k8s 4096 Jun 20 11:51 users
-rw-r--r-- 1 k8s k8s  394 Jan 11  2020 xbmcmetadata.xml
```
Official image config directory is as follows:
```
jellyfin:~$ ls -la /config/jellyfix
total 32
drwxrwxr-x 8 k8s k8s 4096 Jul 25 21:44 .
drwxr-xr-x 6 k8s k8s 4096 Jul 25 13:09 ..
drwxr-xr-x 3 k8s k8s 4096 Jul 25 21:44 config
drwxr-xr-x 5 k8s k8s 4096 Jul 25 22:40 data
drwxr-xr-x 2 k8s k8s 4096 Jul 25 21:43 log
drwxr-xr-x 2 k8s k8s 4096 Jul 25 21:43 metadata
drwxr-xr-x 3 k8s k8s 4096 Jul 25 21:44 root
drwxr-xr-x 2 k8s k8s 4096 Jul 25 21:44 transcodes
```
I am not sure how this is so different as normally the config directory of an application should be same, however looks like its not the case with these 2 different docker implementations.

```
jellyfin/config/* -> linuxserver/
jellyfin/data     -> linuxserver/data/data
jellyfin/metadata -> linuxserver/data/metadata
jellyfin/root     -> linuxserver/data/root
```

**Comment by crobibero** [comment]
I don't see an issue here. Linuxserver can create their own dockerfile and configure it as they wish.

**Comment by geek-baba** [comment]
I do not disagree, was trying to create visibility of the difference, when I was [researching](https://www.reddit.com/r/jellyfin/comments/f9aq8e/difference_between_the_docker_containers_official/) it seems its more or less same.

**Comment by RobLoach** [comment]
Sounds like an issue for the LinuxServer's queue? https://github.com/linuxserver/docker-jellyfin/

**Comment by geek-baba** [comment]
@crobibero @RobLoach I have been thinking to move to official image for stability - looking at the directory structure, is there a safe way to migrate from LSIO to official image?

**Comment by CatBox360** [comment]
@geek-baba What I have done when switching between images is swapping a few lines in my compose file;

Backup, backup, backup (as you should always do when fooling with stuff)
Add "user: 1000:1000" under the jellyfin service
Comment out the PUID/PGID lines in environment and add
    - JELLYFIN_DATA_DIR=/config/data #Uncomment for Jellyfin Images
    - JELLYFIN_CONFIG_DIR=/config #Uncomment for Jellyfin Images
    - JELLYFIN_LOG_DIR=/config/log #Uncomment for Jellyfin Images
    - JELLYFIN_CACHE_DIR=/config/cache #Uncomment for Jellyfin Images

Do the exact opposite to go back to the LSIO images. Hope this helps.

**Comment by harry71019** [comment]
> @geek-baba What I have done when switching between images is swapping a few lines in my compose file;
> 
> Backup, backup, backup (as you should always do when fooling with stuff) Add "user: 1000:1000" under the jellyfin service Comment out the PUID/PGID lines in environment and add - JELLYFIN_DATA_DIR=/config/data #Uncomment for Jellyfin Images - JELLYFIN_CONFIG_DIR=/config #Uncomment for Jellyfin Images - JELLYFIN_LOG_DIR=/config/log #Uncomment for Jellyfin Images - JELLYFIN_CACHE_DIR=/config/cache #Uncomment for Jellyfin Images
> 
> Do the exact opposite to go back to the LSIO images. Hope this helps.

@RoshikPaccoon 
I was trying to do the opposite and moving from the official image to the linuxserver one.
I added these environmental variables matching the ones from the official one but it still doesn't apply them, any thoughts? Any input is appreciated, thanks!
![image](https://user-images.githubusercontent.com/59645782/147871580-dca596e2-e820-4ee8-8f27-27e852b55f20.png)

**Comment by RoshikPaccoon** [comment]
@harry71019 Not 100% sure this still works anymore, and moving from the JF image to LSIO was a bit more involved (required moving directories) last time I did it. I just compared my 10.7.7 LSIO and 1.8.0 JF config directories and this is what I believe will work. (BACKUP **BACKUP** **_HAVE A BACKUP_** 😃 )

Create your LSIO config directory. We will call this /LSIOconfig
Create a folder called "data" in /LSIOconfig
Copy the following folders from the JF image config folder into this folder (/LSIOconfig/data/);
data, metadata, plugins, root, transcodes
Copy your cache and log folders to /LSIOconfig
Copy the CONTENTS of the "config" directory from your Jellyfin image (dlna, users, all the xml files) to /LSIOconfig

This is all that should be needed to move from the JF images to the LSIO images.

Here's a comparison of my LSIO and JF image config directories:
![image](https://user-images.githubusercontent.com/63222124/147891069-ac64119a-e15d-421b-b3d7-1f008849ab91.png)

**Comment by harry71019** [comment]
@RoshikPaccoon Thank you very much for the advice and I was able to get it working. Just needed to update the path for metadata and cache in the web gui and also make sure PUID and PGID are set correctly.

**Comment by brietman** [comment]
I am so glad I made copy.  I was looking at https://www.reddit.com/r/jellyfin/comments/10diybs/whats_the_difference_between_the_linuxserver_and/ a jellyfin dev said: 

>  You can, as long as the paths are the same inside the container, switch between them at will, so feel free to test them both out and see what works best. 

Clearly not.

**Comment by SchultzenDK** [comment]
I ran into another issue I managed to fix myself, and thought I would share it, in case others run into a similar issue

I kept getting the error `Could not find a part of the path '/config/root/default/[LIBRARY]` (replace [LIBRARY] with whatever you have set it up to)

I fixed it with help from this comment: https://www.reddit.com/r/jellyfin/comments/yyrhsu/jellyfin_docker_image_searching_the_wrong_root/iwyr80n/

I have lots of experience with MariaDB, but I had never used SQLite before, so I kept doing something wrong, where it would reset back to the previous value.

So here's a full idiot guide, for people like me:

1. Shut down Jellyfin
2. Make a backup of all `[Jellyfin root]/data/data/library.*` files, just in case
3. IF YOU'RE USING SYNOLOGY download the file `[Jellyfin root]/data/data/library.db` to your PC
4. Edit the `library.db` file with something like https://sqlitebrowser.org/ (rest of guide assumes you use that)
5. Click tab "Execute SQL"
6. Copy the following into the field:
```sql
UPDATE TypedBaseItems
SET Path = REPLACE(Path, '/config/root/default', '/config/data/root/default'),
data = REPLACE(data, '/config/root/default', '/config/data/root/default')
WHERE Path LIKE '/config/root/default%'
```
7. Click the play arrow to execute the query
8. Click "Write changes"
9. IF YOU'RE USING SYNOLOGY copy your modified `library.db` to  `[Jellyfin root]/data/data/`
10. IF YOU'RE USING SYNOLOGY you will have some new `-shm` and `-wal` files where you have your modified `library.db`. You want to also copy those to ` `[Jellyfin root]/data/data/`
11. A NOTE ON PREVIOUS STEP! I have a feeling making brand new `-shm` and `-wal` files is a bad idea, and you should instead have the originals alongside the one you're editing, but I just made new ones, because I wasn't actually sure what I was doing, but it worked out with brand new files, so I don't know.
12. Start Jellyfin and scan your libraries

If anyone knows better on step 11, please let me know, and I'll update this guide.

**Comment by dathbe** [comment]
Is there any other reason (other than possibly a couple days earlier release on the official image) to use one over the other?  I'm on the linuxserver image currently, but would switch if there are other reasons to stick with official.
