### ISSUE TITLE
DLNA Server doesn't work (or log anything)

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin#3721]
DLNA Server doesn't work.  Nothing in log, doesn't show as an available UPnP device on local network.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization:none
 - Clients: Browser
 - Browser: Chrome 84.0.4147.89 
 - Jellyfin Version: 10.5.5./10.6
 - Playback: Stream to Chromecast
 - Installed Plugins: Pushbullet
 - Reverse Proxy: NGINX
 - Base URL: no
 - Networking: see attached
 - Storage: local

Maybe I'm misunderstanding JF's capabilities here, but I assume it has the functionality of a DLNA server to clients, in much the same way Plex does.  I have temporarily disabled Plex, as I have read reports of some issues with the DLNA server there interfering.  I do not believe I have other DLNA servers running on the same machine as JF.

I have the "Enable DLNA server" and "Blast alive messages" enabled.  When restarted, JF logs absolutely nothing regarding DLNA nor am I able to see it on my network from any clients or using something like UPnP DeviceSpy.

If I enable "Enable DLNA Play To" then I see a message like this:
`[2020-07-27 19:32:20.515 -05:00] [INF] [20] Dlna: No matching device profile found. The default will need to be used.`
Followed by device information for my DLNA Onkyo receiver.

Can JF not act as a DLNA sever to stream media to DLNA clients?  If so, why do my logs not even seem to reflect any indication that a DLNA server is even trying to start.

I tried this under 10.6, and it appears to function the same.

**Comment by bengalih** [comment]
Turns out this appears to be related to JF not binding to the proper IP and not honoring any of those settings.
Also, not logging anything at all related to this makes it difficult to troubleshoot.  I document the issue and how it is a problem for Chromecast/RP configurations here:

https://github.com/jellyfin/jellyfin/issues/3712#issuecomment-665980659

Once I forced a binding (outside of JF), my DLNA server is magically visible.

**Comment by BaronGreenback** [comment]
Thanks for your work.

I added some interface priority binding functionality to #3257 last night (not uploaded yet). I'll take a look as soon as i've finished my current PR.

**Comment by maurirope** [comment]
Hello, I dont know if this helps, but I just experienced this issue and in my case I found out that while DLNA uses port 1900 for discovery and it should be open for access, you should also keep in mind that port 8096 should still be open for LAN access as the content will actually be delivered via HTTP through that port.

My issue originated because yesterday I spent like 7 hours configuring SSL and had closed 8096 for every incoming IP due to now serving content through the 8920. It wasnt enough to unmark HTTPS required in jellyfin config, I had to open that port back again on ufw.

Hope you can get this solved
