### ISSUE TITLE
H.265 playback is slow and choppy on Synology DS920+

### ISSUE THREAD

**Issue by CaiSter** [jellyfin/jellyfin#3788]
I recently installed jellyfin on my Synology DS920+ and all of my videos play back just fine except for my 4K files encoded in H.265. I heard that there was an issue with PLEX where you had to manually update some intel drivers on the NAS. Is this also the case for Jellyfin?

I found out about the Plex issue here:
https://youtu.be/fTISHfy-rYg

**Comment by nyanmisaka** [comment]
What he did in the video was not to update the driver, but to replace the buggy `iHD` driver with the old `i965` driver by adding a config. I recently received similar reports on Plex that the `iHD` driver on Gemini Lake caused corrupted output in Intel QuickSync. This should be a specific driver failure on this chip, everything from HD630 to UHD630 should be normal.

Due to the incompatible license, we have been stuck on the `i965` driver, so it is unlikely that the `iHD` driver caused your problem. Unless you manually installed intel-media-va-driver-non-free.

**Comment by poulpor** [comment]
Are you sure your jellyfin container was well configured and can access the dev/dri driver? If not, all your transcoding work is done by the CPU and not the integrated GPU, it won't play nicely. 
It's easy to verify, play a H.265 4K video in jellyfin and while doing so, check the  "resource monitor" widget in DSM. If your cpu is 90% or more load, Jellyfin is not using GPU but CPU.
