### ISSUE TITLE
10.6.# version stopped detecting new media unless Scan Library task is ran manually

### ISSUE THREAD

**Issue by akhoa12** [jellyfin/jellyfin#3847]
**Describe the bug**
Hi, my Jellyfin server is having issue detecting new media as they are imported. It's not detecting new media as soon as they're imported and only detects them when Scan Library task is ran.

**System (please complete the following information):**
 - OS: Linux Mint 20
 - Virtualization: Docker (linuxserver)
 - Clients: Browser, Jellyfin-mpv-shim, Android/Android TV
 - Browser: Chrome 84
 - Jellyfin Version: 10.6.2-1-ls67 (linuxserver)
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: Anime, AudioDB, MusicBrainz, OMDb, Open Subtitles, TMDb Box Sets, TheTVDB
 - Reverse Proxy: Traefik v1.7
 - Base URL:
 - Networking: Bridge
 - Storage: local

**To Reproduce**

1. As server is running, add new media to library with real-time monitoring enabled
2. Wait a few minutes for media to be detected

**Expected behavior**
New media is detected and show up in Jellyfin

**Logs**
Not sure if this is helpful, and I don't know which log to post here

**Additional context**
It was working fine when I was on 10.5.#, but after I updated to 10.6.#, it stopped detecting new media unless the Scan Library task is ran. Everything else seems to be functioning.

**Comment by eltiel** [comment]
I reported this issue in the past https://github.com/jellyfin/jellyfin/issues/3251 and it was claimed to have been fixed.

But like you, I'm still facing this issue on 10.6.2. However, it works sometimes just not every time.

**Comment by ThaChillera** [comment]
I had the same experience, setting up a new jellyfin instance and it recognised some, but by far not all, media content

**Comment by eltiel** [comment]
> 
> 
> I reported this issue in the past #3251 and it was claimed to have been fixed.
> 
> But like you, I'm still facing this issue on 10.6.2. However, it works sometimes just not every time.

Strangely, real-time monitoring has stopped working entirely since my last post.

**Comment by ranaldsgift** [comment]
This appears to be the same issue that I have, except I don't think it's a matter of the real time monitoring not working, I think there is something else causing it to take a long time to update.

I have library scans disabled, and I can see in the logs when a new item is recognized by Jellyfin - this usually happens very shortly after the file appears in the file system. But then Jellyfin won't actually update the item on the server right away. When I check my libraries, I can see a progress indicator as if a library scans was running. Eventually when the "scan" completes the new items will populate, but this can take more than 10 hours.

**Comment by eltiel** [comment]
On my end, logs seem to indicate that the new media is only recognized after a Scan Library task is initiated. As I have notifications for new media as well, I only get the notification post-scan.

In the past, I'll be notified of new media in just seconds after it is downloaded.

**Comment by ranaldsgift** [comment]
Still haven't been able to figure out what is causing this issue. If it's only affecting a small number of people, it must be specific to Jellyfin settings, hardware or software configuration.

I have 4 libraries, 2 of which contain 3 or 4 root folders and the other 2 contain only 1 root folder. I have chapter image extraction off on all libraries. Metadata NFO disabled. Save artwork into folder and download images in advance disabled. Display missing episodes for series enabled. The software is running on my Windows Server 2012 OS. Not sure what else would be relevant.

**Comment by ranaldsgift** [comment]
Is it possible that Jellyfin is refreshing the top parent folder when a new item is added to the filesystem? I can't explain all the OnRefreshStart/OnRefreshComplete that I see otherwise. With library scanning disabled, and real-time monitoring enabled, the only items that should be refreshed are the direct parent of new items, in addition to any items that were manually refreshed, is that the correct expecation?

If this were the case, it could potentially be the culprit for why we seem to see no new items being populated or they seem to be added on a very large delay. My Jellyfin instance was running fine for a while, but I decided to go through my missing episodes and movies to try to fill my catalog. So I had thousands of new items being added, and maybe Jellyfin was scanning the top parent for each new one (or for many of them) causing a massive backlog of refresh tasks.

I've since reinstalled JF on a new machine to try to pin down the issue. I still see tons of OnRefreshStart/OnRefreshComplete whenever a new item is found. In fact, while I was typing this I moved an item from my filesystem into a new directory, deleted the old one, and named the new directory the same as the old. Jellyfin recognized that, and then seemed to trigger a refresh on the top parent because I once again saw the OnRefreshStart/OnRefreshComplete and the library in question has a percentage indicator on it in the Dashboard. Still, no library scanning enabled - only realtime monitoring.

Maybe someone can shed some light on if it's normal to see so many OnRefreshStart/OnRefreshComplete. If this is not normal, I think it may be worth investigating, as there seems to be a lot of activity going on that is seemingly redundant. If I pick through some of the ids that are mentioned as being refreshed, I can see they are items that haven't changed in months or in some cases years. I'm not triggering any manual refresh, so I don't really know why they would be refreshed.

**Comment by eltiel** [comment]
As far as I can tell on my server, OnRefreshStart/OnRefreshComplete entries appear whenever the library is scanned - both through Library Scan Task and TMDb Box Sets plugins. Maybe yours is caused by the plugin?

I have several hundreds such entries within 24 hours as well, and I did not add any new media within that time span.

**Comment by dkanada** [comment]
We moved these to debug in the next version because they are indeed very common.

**Comment by eltiel** [comment]
Real time monitoring is still broken in 10.6.4, unfortunately.

**Comment by eltiel** [comment]
I don't know what happened but a few days ago real-time monitoring started to work again. I made absolutely no change to the server, not even a reboot.

Very strange. It's as though the feature is running on a hidden schedule.

**Comment by eltiel** [comment]
I'm not sure if this is related but I noticed I was getting inotify watch limit reached errors. I increased the limit and real-time monitoring worked after that, though I did not do any thorough testing.

**Comment by akhoa12** [comment]
> I'm not sure if this is related but I noticed I was getting inotify watch limit reached errors. I increased the limit and real-time monitoring worked after that, though I did not do any thorough testing. 

I do not have any notification setup and still have the real time monitoring issue. Waiting on 10.6.5 to see if it'll be fixed

**Comment by eltiel** [comment]
> 
> 
> > I'm not sure if this is related but I noticed I was getting inotify watch limit reached errors. I increased the limit and real-time monitoring worked after that, though I did not do any thorough testing.
> 
> I do not have any notification setup and still have the real time monitoring issue. Waiting on 10.6.5 to see if it'll be fixed

The `inotify` I meant is not related to Jellyfin's notification setup. It has to do with Linux's `inotify` API which monitors filesystem events.

**Comment by boblarouche** [comment]
This issue still exists. No documentation on inotify. Jellyfin docs only state that it uses inotify... don't know if we have to install and configure it or if it's included. Anyways, real-time monitoring doesn't work for me. 

Debian 10
ext4
Jellyfin 10.6.4

Also, I ran `sudo apt install inotify-tools`, restarted jellyfin, but no joy

**Comment by damomato** [comment]
This also not working for me on v10.7.5. I think it seems to work occasionally though which is odd. I've changed the scheduled task to run every 4 hours so that should help a little bit when media downloads while I'm out

**Comment by codeghari** [comment]
In a similar boat, real time monitoring was working flawlessly on 10.6.4 to 10.7.5 but now on 10.7.6 it is broken. Have to run library scans every few hours.

**Comment by Steve-Cooley** [comment]
This post only applies to people who running Jellyfin on Linux with a file system that uses inotify.  In other words, if you're using Windows or some MS file-system, please disregard this post. Also, this post doesn't apply to people who are having issues with very slow library scans.  In other words (again), this only applies to people who can successfully re-scan their libraries in a relatively short time by manually initiating that scan.  

I'm having the same issue, and I have a theory.  Here is a paste of something I found in a log file:
`[2022-07-29 10:10:34.092 -07:00] [ERR] [375] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "/data/tvshows"
System.IO.IOException: The configured user limit (16384) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
`
This file-system is also where my torrents download. Each time my torrent client collects some small piece of data, the kernel is made aware of this change. This means that thousands of changes are made to this file system every second. My interpretation ofthe above log entries is that inotify is being overwhelmed by these small changes, and that is in turn causing real-time monitoring not to work.  

I'm not willing to try this right now, but if I'm correct, if I were to move my temporary torrent files to another drive/FS, then that would resolve this issue.
