### ISSUE TITLE
10.6.2 - LAN Network option not working

### ISSUE THREAD

**Issue by eixel05** [jellyfin/jellyfin#3904]
Using 10.5.5, this works perfectly. I'm using ZeroTier to access my JF remotely (I'm behind CGNAT) and I specified in that option all the devices that are actually in the house. I didn't use IP/Netmask. I manually added the IPs. I do this because my setup of ZT is to bridge. So even if I type the in-house private network instead the one given by ZT, I would still reach it. The IP of the bridging hardware is not added under this option.
.
Whenever I access my JF outside the house using my Mobile Data+ZT, that option applies. I don't see those profiles that are specified not to have remote access.

I upgraded to 10.6.2 (I held until the memory leakage is fixed) and found out that the LAN Network option doesn't work anymore. No matter where I access the server, I still see those Profiles that doesn't have remote access and was able to log-in. It's like the option was defaulted to "left blank" thus the in-house subnet, ZT subnet is all considered Local networks. And no matter what you add, it is ignored.

**Comment by thr33face** [comment]
I'm facing potentially the same issue while trying to enforce the 'internet streaming bitrate limit'
Jellyfin is accessed through a reverse proxy on the same /24 (192.168) and I'd like that IP to be considered public instead of local.

Simplified the setup looks something like this:
[jellyfin | .20] -> [reverse proxy 1 | .60] -> [client 1 | .180]

Since the jellyfin logs show all requests coming from the reverse proxy IP, I assumed that setting 'lan networks' to one of these options would treat .60 as public:
- setting range or IP from lo interface: 127.0.0.0/8 or 127.0.0.1 or 127.0.0.1/32
- setting only one IP of home /24: .20 or .20/32

But none of these produce the desired results and the internet streaming limit is never enforced. (i.e.: bitrates higher than the set limit can be by users)

**Comment by BaronGreenback** [comment]
@thr33face Could you test the following please?

In your LAN definition include the IP in [ ] - eg. 192.168.1.0/24,[192.168.1.60/32]

**Comment by thr33face** [comment]
@BaronGreenback 
Unfortunately this did not work either, even negating the whole subnet does not help.
I also bypassed the reverse proxy, and negated the client IP, that didn't work either.

Log:
[2020-08-16 16:11:05.670 +00:00] [INF] RemoteClientBitrateLimit: 6000000, RemoteIp: "192.168.10.180", IsInLocalNetwork: True

**Comment by BaronGreenback** [comment]
I'll dive into the code and see what's happening.

**Comment by BaronGreenback** [comment]
Looks like in 10.6.2 it is hard coded. 

It is one of the many network fixes in PR #3257 which i'm currently testing.

**Comment by thr33face** [comment]
Thank you for investigating

**Comment by BaronGreenback** [comment]
No problems - would you be up to testing the PR once i've got it running on the new unstable version, to make sure it works?
The PR is massive - so i'm currently doing alpha's  before hand to ensure i don't break more than i fix.

**Comment by thr33face** [comment]
Sure, I can help testing to the best of my abilities.
I have a jellyfish instance up and running in a throwaway VM, so doesn't matter if that one breaks in the process.

**Comment by BaronGreenback** [comment]
Docket image crobibero/jellyfin:3257 is the PR3257.

It's the latest code image - so some interface things may be broken. If you could fire it up and test the networking side, especially with your setup. It has got loads of fixes in it.
