### ISSUE TITLE
System.InvalidOperationException: The server is expected to host the web client

### ISSUE THREAD

**Issue by PlayerRedOne** [jellyfin/jellyfin#3956]
**Describe The Bug**
When I type the command "Jellyfin" in the terminal, I get the following error: 

```
[16:44:38] [FTL] [1] Main: Error while starting server.
System.InvalidOperationException: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings.
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

But the web interface is running and I can access it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/70027346/90910570-d472f980-e3d7-11ea-96ae-a655c1822083.png)

**System:**
 - Platform: Raspberry Pi OS 
 - Jellyfin Version: 10.6.2

**Comment by PlayerRedOne** [comment]
In /etc/default/jellyfin, option JELLYFIN_WEB_OPT:
![image](https://user-images.githubusercontent.com/70027346/91584627-3640df80-e953-11ea-8cab-d66488dfdad9.png)
In /usr/share/jellyfin/web:
![image](https://user-images.githubusercontent.com/70027346/91584835-828c1f80-e953-11ea-9cde-99676b0592d1.png)

But the Webinterface is working:
![image](https://user-images.githubusercontent.com/70027346/91584912-a18ab180-e953-11ea-8821-14a0c1878e38.png)

**Comment by dmitrylyzo** [comment]
@PlayerRedOne 
1. You run Jellyfin without any arguments, so server searches web in its application directory (`/usr/lib/jellyfin/bin` - web was here before the package split). At the moment, you should explicitly specify location of web by `--webdir` (and other dirs too).
_It would probably be more clear if these arguments were empty by default and required (with error output)._

2. Since you can access Jellyfin from browser, Jellyfin service is working.
It runs as `
/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT}`

Why do you want to run Jellyfin from command line?

**Comment by witzker** [comment]
Hi, as I'm new with this server stuff, i do not understand How to solve this ERROR.
Can you Pls. Be so kind and explain the steps to solve this?
Many THX for your patience with me Newbie
