### ISSUE TITLE
Nintendo Switch Port

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin#397]
This is obviously going to be something in the future. But this could top Plex and Emby as they don't have apps for the switch yet. Also it would be very cool being able to play games and watch your favourite films/TV shows on the go. Just an idea/concept for now but I do hope it gets turned into reality someday.

**Comment by sparky8251** [comment]
There is in fact a reason Emby and Plex don't have a Switch app. Nintendo has very very strict requirements for apps.

Plus, I recall hearing about how they require the source code to be closed through very restrictive NDAs. Would basically be stuck relying on 1-2 people for all Switch work.

**Comment by Essasetic** [comment]
Either that or it could be a homebrew app for a bit. Tools have come out so people can compile their own NSPs (eshop installable files) and there are ways to install them.

**Comment by sparky8251** [comment]
Well, the only way to keep the projects goal of free software would be homebrew. It wouldn't even be possible for the devs that signed the NDA to talk about the apps dec process with those that haven't.

**Comment by aveao** [comment]
This would be a hard one:
- libnx' openssl currently doesn't properly support https (but that might be okay considering how jellyfin/emby doesn't do https by default)
- libcurl has some flaws
- official dkp ffmpeg builds don't support network streaming (however, see the "hacking around" link below)

However, it's possible:

- [NX-Shell](https://github.com/joel16/NX-Shell) has a video player that could provide a base for the homebrew.
- [In-House-Streaming](https://github.com/jakibaki/In-Home-Switching) allows in-network game streaming (with some [hacking around](https://github.com/devkitPro/pacman-packages/pull/62)), which could provide a base for the networking code and the ffmpeg version ([here's a build of it btw](https://cdn.discordapp.com/attachments/477945928196816935/525593866972168192/switch-ffmpeg-4.0.1-1-any.pkg.tar.xz)).

I'd argue against releasing .nsp builds as they're ban bait (installing .nsps will get your console banned from online services, be pirated games or homebrew), just releasing .nros should be sufficient (if we really need the extra ram*, we can instruct people to just [forward a game to homebrew launcher](
https://gbatemp.net/threads/use-atmosphere-to-access-full-ram-with-homebrews-without-nsp.521240/)).

---

*: basically, switch has applets and applications. Some examples to applets include the main menu, the album, eshop, mii creator, user profiles etc.  Applications are games and other stuff you see on your main game list on the main menu (youtube app is an application etc). By default, homebrew launcher takes over album as it's available on every switch (unlike any application), however this causes various limitations: various IPC calls don't work (like the one to block home button), and RAM is limited to whatever is shared between applets (IIRC, 1GB) rather than what is available to applications (IIRC, 3GB).

**Comment by JustAMan** [comment]
Why do we want `ffmpeg` on Switch? It's a server thing to have, and Switch is proposed to be a client.
Does it have a browser btw? Maybe some kind of simplified web UI would do?

**Comment by aveao** [comment]
Browser is no go. People are working on getting it working, but it's progressing slowly.

I'm not super informed on how video playback and transcoding works in general, but I think ffmpeg is pretty much necessary to play video on switch.

**Comment by Essasetic** [comment]
@JustAMan ffmpeg has already been ported to the switch. As Pplay demonstrates that video playback using video files on the switch is possible. The switch doesn't officially have a browser but there is a very basic hidden browser. Unfortunately it can't playback video (as I tried with Emby months ago).

**Comment by JustAMan** [comment]
So you rather want parts of `ffplay`, not `ffmpeg` itself, right?

**Comment by aveao** [comment]
Okay, let me be clearer:

The built-in browser is not directly accessible. Games can open it, but they all either use local URLs or HTTPS urls.

We can launch it by abusing the captive portal system, with a custom DNS etc, by making (`ctest.cdn.nintendo.net` needs to return something that isn't `ok` with `X-Organization: Nintendo` header). It doesn't have a whitelist, but it can't play videos.

Launching browser through other means (abusing facebook login etc) does allow playing videos and someone hackily got youtube working through a google sites thing, but sadly it has a whitelist so it won't work for us.

switchbrew.org/index.php?title=Internet_Browser

**Comment by WinterMute** [comment]
> Either that or it could be a homebrew app for a bit. Tools have come out so people can compile their own NSPs (eshop installable files) and there are ways to install them.

You shouldn't install unofficial NSPs, you **will** get banned. We have our own homebrew launcher for a reason.

> And as for homebrew, this would be a hard one:
> 
> * I heard that dkp's openssl currently doesn't properly support https (but that might be okay considering how jellyfin/emby doesn't do https by default)

devkitPro does not supply openssl for switch and probably won't. We're currently trying to track down some issues in mbedtls & will provide ssl support with that eventually.

> * dkp's libcurl has some flaws

If our libcurl binary has flaws then please report them at https://github.com/devkitPro/pacman-packages/issues

> * dkp ffmpeg builds don't support network streaming (it can be enabled and rebuilt, see the "hacking around" link below)

It would be good if people actually spoke to us instead of passing around various bodgeups. See the notes on https://github.com/devkitPro/pacman-packages/pull/62 - once those fixes are done then I can probably merge the PR & roll out a new package.

Bear in mind that Switch homebrew is still relatively new & many things are still being actively worked on.

**Comment by JustAMan** [comment]
Netcore is used for server only, clients could use something else.

**Comment by leo60228** [comment]
Also, the mono guys have said porting mono to libnx shouldn't be incredibly hard (not sure how much I believe that...), and porting dotnetanywhere should be super easy once I figure out how to build it with GCC.

**Comment by anthonylavado** [comment]
Closing this in the sense that, we can't reasonably create a Switch app, but if someone wants to, they are free to do so. Otherwise, if a good enough browser is available on the Switch, the Web UI will work quite nicely for it.

**Comment by Essasetic** [comment]
I've tested the web-applet and it can't even connect to my server.

**Comment by anthonylavado** [comment]
@essasetic Do we think that's an issue with the web-applet or the server? From a quick browse of that switchbrew page, there's a lot to take in.

**Comment by Essasetic** [comment]
@anthonylavado Probably the web-applet. It is very limited in its capabilities.

**Comment by fullmetal1** [comment]
I've managed to get the web applet to sign in. It struggles with just the webpages themselves. It can't handle the videos. Incidentally youtube works on it (I think that's how the youtube app works, but I haven't downloaded the youtube app to try). Youtube complains that it won't support the 'chrome version' for long, so nintendo might release an update to the browser at some point. This is all speculation on my part, however.

**Comment by Stromwerk** [comment]
I have tested it using the SwitchBru DNS method of opening some built in browser and connect to my server - the page is opened, but I only see the Jellyfin logo. I am not sure what the issue is or how to go about finding anything about it.

**Comment by omentic** [comment]
There now exists an unofficial homebrew client: https://github.com/dragonflylee/switchfin

**Comment by impishlucy** [comment]
Yeah unofficial for people who want to get their Switch banned

**Comment by impishlucy** [comment]
I dont have enough time or the credibility on my hands to make this happen alone as nintendo might turn me away since im not behind Jellyfin, but ur a whole team, to see this just get turned away cuz its not in _your_ personal interest is very sad

**Comment by nyanmisaka** [comment]
> I dont have enough time or the credibility on my hands to make this happen alone as nintendo might turn me away since im not behind Jellyfin, but ur a whole team, to see this just get turned away cuz its not in _your_ personal interest is very sad

It is Nintendo that decides whether your software can be published in their store, not Jellyfin.

Obviously Jellyfin cannot bring them any financial benefits. And I don't think you can give an example of another open source software in their store.

**Comment by WinterMute** [comment]
> Yeah unofficial for people who want to get their Switch banned

People don't get banned for running homebrew. The main issue is the difficulty in booting homebrew without a v1 Switch.

The issue you'd have going the official route is the GPL license - Nintendo prohibits use of GPL code with official SDK.

**Comment by aveao** [comment]
> I dont have enough time or the credibility on my hands to make this happen alone as nintendo might turn me away since im not behind Jellyfin, but ur a whole team, to see this just get turned away cuz its not in _your_ personal interest is very sad

Jellyfin is an open source project, with limited capacity in terms of time and money. People will obviously choose to direct in the direction of features/fixes that benefit them.

You're free to develop something that'd fit Nintendo guidelines, then try to work with the Jellyfin team to get it published, but I sadly think there'd be issues with that:

Nintendo puts a lot of the relevant info and tooling behind NDAs, which can be restrictive to having the Switch app open source. Furthermore, I don't think Jellyfin has a legal entity, for example the [official iOS app](https://apps.apple.com/us/app/jellyfin-mobile/id1480192618?mt=8) is published by an individual. That'd complicate figuring out who signs the NDA, and who they get to share information/code/tools with.

Also, Nintendo is pretty restrictive on what they allow into the eShop. Plex, which does have a proper team and financial funding, has apps for many consoles, but not the Switch. I'd be surprised if they didn't try and get rejected by Nintendo.

> Yeah unofficial for people who want to get their Switch banned

Comments 3, 4, 5 and many onwards are talking about having this as a homebrew. And as WM said, you don't get banned for running Homebrew, which I can attest to from my own Switch 1. Bit oversimplified, but it's running pirated software that gets you banned.
