### ISSUE TITLE
DVR

### ISSUE THREAD

**Issue by Gabinator9** [jellyfin/jellyfin#40]
I know this is just starting out and this may take a long time to be implemented but I would love it if you guys could implement DVR like plex or emby. I would instantly switch if that happened

**Comment by louisefindlay23** [comment]
It would be great if there was support for other tuners like USB and PCIE similar to Plex's unsupported tuners. Perhaps natively integrating Tvheadend tuners without the need for HD Homerun emulation via Antennas or tvhProxy.

**Comment by JustAMan** [comment]
@louisefindlay23 is this emulation working reliably? If so, maybe documenting it (or making a plugin for it) is a way to add support?

**Comment by louisefindlay23** [comment]
Antennas is a lot easier and more reliable than tvhProxy. I have had failed recordings but that could be down to the unreliability of Plex DVR (transcoder errors.) I've not tried Emby DVR because I don't have Premiere.

Not installed jellyfin yet but would be happy to install it from the docker container and test. I usually use the docker version of antennas (though there is a non-docker version) https://github.com/TheJF/docker-antennas.

If successful where would I submit the docs to?

**Comment by JustAMan** [comment]
https://github.com/jellyfin/jellyfin-docs ;)

**Comment by joshuaboniface** [comment]
I think DVR functionality is all working, cc @cvium. If so I think we can close this out?

**Comment by cvium** [comment]
If DVR is the same as livetv recording, then yeah.

**Comment by louisefindlay23** [comment]
Installed fine but had to do the xmltv workaround for guide data. Recording works not sure about live tv because I couldn't get my LG WebOS tv to work via DLNA and on the web it complains about profiles. Will add to the docs.

**Comment by anthonylavado** [comment]
Closing in 24h as Live TV recording does work - enhancements should be in a new issue if needed.
