### ISSUE TITLE
Future of the plugin catalog?

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#416]
While removing crappy licensing code I came across the code that fetches available plugins. I think it would be really nice to have such a thing, but it goes against the phone home principle. But then again, package managers break the phone home principle too.
I have a feeling that jellyfin/emby tries to do too much here and that I wish it could be more unix-y "do one thing, and do it well" and that we perhaps could make a .deb of assorted plugins, then make sure it's possible to activate/deactivate each plugin? Other ideas welcome

bonus question/thought about API compatability for plugins. When the logging code was removed, I had to recompile plugins. When any API that plugins use changes then plugins using them need to be recompiled. If we want to make plugins last for many versions, we need to find a set of functionality that most plugins will be happy with and support those APIs for a long time...

**Comment by joshuaboniface** [comment]
I'd actually rather it have a list of official plugins (that are in the JF org, all *consistently* named `jellyfin-plugin-xxx`), and the option to clone/download/install them. That's to say, I see value in the feature, since that isn't really a "phone home" if it can reach out to a git repo and clone it. Other thoughts welcome though.

**Comment by hawken93** [comment]
found #259 related
I think they reached the idea here of bundling a packages.json that then can download supported modules from github releases or such

**Comment by bfayers** [comment]
@hawken93 the better solution is to have a repo called jellyfin-packages which would contain the packages.json that can be updated with PRs/ automatically by a CI system when new releases are made on any of the plugin repos.

**Comment by LeoVerto** [comment]
I think we could learn from Kodi/FDroid here by having an OS-independent plugin that has the official repository as the default but easily allows adding 3rd party ones.

**Comment by joshuaboniface** [comment]
@bfayers @LeoVerto I'm actually considering merging all of the "offical" plugins into a single repo, due to the sheer number of them. That would let is manage a single `packages.json` and single build setup, then distribute the binary plugins individually. Unless that's a really crazy idea, I'm not too sure about how building these plugins actually works!

**Comment by hawken93** [comment]
@joshuaboniface that seems reasonable to me. As for building them, I have tried to document how I went about it in the jellyfin-plugin-anime pull request I made. But there is work to do to here..

**Comment by JustAMan** [comment]
I personally like the idea of one repo per one plugin more.
Maybe we can just put all them to separate org, e.g. `jellyfin-plugins`?

**Comment by bfayers** [comment]
> I personally like the idea of one repo per one plugin more.
> Maybe we can just put all them to separate org, e.g. `jellyfin-plugins`?

I also like the idea of one repo per plugin. CI could easily enough use the github API to check each plugin repos releases and generate an appropriate packages.json

**Comment by joshuaboniface** [comment]
We decided to just tweak and keep the existing plugon catelog. It works without much hassle.
