### ISSUE TITLE
Jellyfin in Docker on Synology writes to the disk every 10 seconds.

### ISSUE THREAD

**Issue by MrSurly** [jellyfin/jellyfin#4203]
**Describe the bug**

**System (please complete the following information):**
 - OS: Synology
 - Virtualization: Docker
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: "latest" from docker repo
 - Playback: Default -- cannot tell, "Playback" tab in settings does not indicate.
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Bridge
 - Storage: local

**To Reproduce**
Install Jellyfin using Docker on Synology NAS

**Expected behavior**
Not to write to the disk constantly.

**Logs**
[jellyfinlogs.zip](https://github.com/jellyfin/jellyfin/files/5278577/jellyfinlogs.zip)

**Screenshots**
N/A

**Additional context**
Seems to coincide with these log entries: `[03:02:22] [WRN] [21] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to 10.1.0.100. Time (slow): 0:00:00.7737274. http://media.local:8096/Sessions/Playing/Progress`

**Comment by Ullmie02** [comment]
In the next version of Jellyfin, you can disable this warning or configure a custom threshold inside the `system.xml` file in the config directory #3556
If you like to disable it now, the only option is to set the minimum log level to `Error` in the `logging.default.json` file (also in the config directory). But then your logs will be pretty much useless because nearly nothing is in the log.
