### ISSUE TITLE
Video transcoded in a 4 fold bigger size video

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin#4343]
**Describe the bug**
Hello,

I've jellyfin server running in a data center on my personal server and I watch videos on my ISP set top box using the Android TV version installed on it. So bandwidth can be a problem.
I've watched a video which a small resolution which was converted to a bigger one

480p MPEG4
CodecMPEG4
codec: XVID
ProfilAdvanced Simple Profile
Résolution 720x408

origin
-rw-r--r--. 1 911 911 729712042  9 oct.  17:12 'source_vid.avi'
converted 
-rw-r--r--. 1 root root 3290379434 17 oct.  19:15 ../config/transcoding-temp/transcodes/transcodes/transcodes/904acb2a07cac40270d646037f1fc4ee.mkv

**System :**
 - OS: Fedora
 - Virtualization: Docker
 - Clients: Android TV
 - Browser: N/a
 - Jellyfin Version: 10.6.4
 - Playback: Transcode
 - Installed Plugins: N/a
 - Reverse Proxy: traefik
 - Base URL: none
 - Networking: docker
 - Storage: local

**To Reproduce**

**Expected behavior**

**Logs**
[transcode.log](https://github.com/jellyfin/jellyfin/files/5397128/transcode.log)

**Comment by telans** [comment]
This isn't really a bug and is more a tradeoff ffmpeg uses when trancoding with vaapi I believe. Instead of taking time to compress transcoded files it just spews them out as fast/efficiently as possible, sacrificing file size.

If you disable hardware transcoding and use a medium/fast preset I'm sure the file size will be much lower, but also slower. You could experiment between the quality/speed of presets like veryfast/ultrafast vs. vaapi if you require a lower file size.

**Comment by bmillemathias** [comment]
> This isn't really a bug and is more a tradeoff ffmpeg has when trancoding with vaapi I believe. Instead of taking time to compress transcoded files it just spews them out as fast/efficiently as possible, sacrificing file size.

Ok understood
