### ISSUE TITLE
Request: add clear warning about nginx and websockets to documentation

### ISSUE THREAD

**Issue by darkphoenix** [jellyfin/jellyfin#4345]
Writing this issue because I've just run into this again and keep taking way too long to figure out what's wrong - when you put Jellyfin behind Nginx, you MUST NOT have a "Connection: Upgrade" in any block other than the one for /socket.  As I am surely not the only one using fixed config templates that just add that header to everything to "make WebSockets work", and this seems to work for literally every other web application on the planet, and fails in a particularly unintuitive way with Jellyfin, with no helpful error messaging, it seems worth it to add an extra note in the nginx section of the docs that this is necessary to spare people like me some suffering.

**Comment by Artiume** [comment]
Do you mind adding it directly here? The nginx docs are mostly maintained by the community as I use traefik and not nginx.

https://github.com/jellyfin/jellyfin-docs/blob/master/general/networking/nginx.md

**Comment by johncadengo** [comment]
@darkphoenix I am having trouble getting my nginx reverse proxy working. I pretty much used the example from the docs that @Artiume mentioned, and it doesn't work reliably for websockets. If I transcode, it works. I'm assuming that it works because each chunk is small. But if it's using websockets, it loses the connection every so often. 

Do you have that experience as well? Can you post your configuration, if it works, here too?

Here are the types of logs I'll get when doing direct play (not transcoding):

```
Feb 13 23:07:21 jellyfin[430352]: [23:07:21] [ERR] Error processing request: The operation was canceled. URL: http://<url>/Videos/275d00c9a169cddcdfe7487009852d09/stream.mkv>
Feb 13 23:07:21 jellyfin[430352]: [23:07:21] [WRN] HTTP Response 206 to <ip>. Time (slow): 0:01:34.6293848. http://<url>/Videos/275d00c9a169cddcdfe7487009852d09/str>
Feb 13 23:07:21 jellyfin[430352]: [23:07:21] [INF] WS ::ffff:192.168.1.200 closed
Feb 13 23:07:23 jellyfin[430352]: [23:07:23] [INF] WS ::ffff:192.168.1.200 request
Feb 13 23:07:23 jellyfin[430352]: [23:07:23] [WRN] Unable to determine session based on query string: []
```

In my case, if I force transcoding, it works.

**Comment by ervinpopescu** [comment]
I have this config for jellyfin:
```nginx
# Handle redirect for missing trailing slash
location /jellyfin {
    return 302 $scheme://$host$request_uri;
}

# Main Jellyfin proxy block including WebSockets
location /jellyfin/ {
    proxy_pass http://$jellyfin;

    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    proxy_buffering off;
    proxy_redirect off;

    # High timeouts to keep the WebSocket alive
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}

location /jellyfin/socket {
    # Proxy Jellyfin Websockets traffic
    proxy_pass http://$jellyfin;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    proxy_set_header Origin $scheme://$host;

    proxy_buffering off;
    proxy_redirect off;
}
```

I do have `/jellyfin` set as a base url under Networking.

No matter what i switch around (Origin header, $host instead of $jellyfin for missing trail slash etc), Jellyfin keeps returning 403 below  or 302 in some lucky instances (to `jellyfin/web`  -- exactly that).

```log
[2026-02-23 21:54:29.545 +02:00] [ERR] Error processing request: "Token is required". URL "GET" "/socket"
```

Any pointers to move forward with my investigation or some other config?

Can we reopen this please? @Artiume sorry for the ping if you are not working on Jellyfin anymore.

Error seems to be thrown here I think:
https://github.com/jellyfin/jellyfin/blob/56a469d8c3c0eed0d809d42a60d847e67ab61671/Emby.Server.Implementations/HttpServer/WebSocketManager.cs#L42

Maybe related: https://github.com/jellyfin/jellyfin/issues/3081
