### ISSUE TITLE
Parental rating not being inherited

### ISSUE THREAD

**Issue by Cissoubaka** [jellyfin/jellyfin#4363]
**Describe the bug**
If I change the rating of a certain anime show (saint seiya) TV-14 to FR-10 the changes are not transfered to episode, so the anime shows in the kid account, but empty.

**System (please complete the following information):**
 - OS: archlinux
 - Virtualization: docker
 - Jellyfin Version: 10.6.4

**Expected behavior**
Episode appears on the kid account

**Comment by J-C-P** [comment]
I agree.
Same problem here.
None of the series had a rating.
I need to add it manually, for the serie, the seasons and the episodes.
And the Metadata management menu do not allow bulk modification (or I didn't found it).
Thanks for taking this into account :-)

**Comment by sebschub** [comment]
As to be expected, the same issue is true for music or audio books. Every single track needs a parental rating in order to be available on the account with enabled parental control, which makes this system unusable for me currently.
Thanks for looking into this.

OS : Docker
Arch : X64
Version 10.7.5

**Comment by korncola** [comment]
parental rating is a mess in jellyfin:
* rating from shows not inherited to seasons and episodes
* re-scraping of rating does not work well, with tvdb i get ratings with number only (6,12, etc. instead of FSK-6, FSK-12 etc)
* international different rating systems not taken in account: it looks like when you lock down a child account do FSK-12 it just does a string matching, so ratings from different regions are seen as forbidden (same with the tvdb scraped stuff: 6 is not the same as FSK-6 from a algorithmic point view, but in real life it is!)
* no allowance tags (only forbidden tags)
* no bulk editing
* no real SQL DB i could just edit with an esay script only this sqlite crap which is undocumented (i didnt find a schema documentation)

To say it clear, jellyfin will not be usable for families (the ppl with money) and the in the nerd niche until problems like this are resolved. Sorry for my rant, but i am really hopeless with a decent mediaserver for a decent amount of media that is family friendly, jellyfin comes closest so far, and i am willing to donate, but the amount issues open in github and the lack of response to issues like this make me sceptical.

**Comment by korncola** [comment]
I found a way to edit the database and fix the issues with parental ratings in tv shows.
To compensate my rant above i will share what i've done.

We need an sqlite client, sqlite3 binary on linux works well.
Then locate the library.db, in my distro (ArchLinux) it is located in /var/lib/jellyfin/data and open it with sqlite3.

I have sent several queries:
```
UPDATE TypedBaseItems SET OfficialRating = 'FSK-6' WHERE SeriesName IN (SELECT Name FROM TypedBaseItems WHERE (OfficialRating = '6' OR OfficialRating = '0' OR OfficialRating = 'TV-G' AND OfficialRating = 'TV-Y7' OR OfficialRating = 'TV-E' OR OfficialRating = 'TV-Y' OR OfficialRating = 'TV-PG') AND Path LIKE '%/tv/%');
UPDATE TypedBaseItems SET OfficialRating = 'FSK-6' WHERE (OfficialRating = '6' OR OfficialRating = '0' OR OfficialRating = 'TV-G' OR OfficialRating = 'TV-Y7' OR OfficialRating = 'TV-E' OR OfficialRating = 'TV-Y' OR OfficialRating = 'TV-PG') AND Path LIKE '%/tv/%');
UPDATE TypedBaseItems SET OfficialRating = 'FSK-6' WHERE SeriesName IN (SELECT Name FROM TypedBaseItems WHERE (OfficialRating = 'FSK-6' OR OfficialRating = 'FSK-0');
```
* The tableTypedBasedItems contains all stuff in database, tv shows as a whole,m the seasons, the episodes etc.
* OfficialRating contains the parental rating
* Name is the name of the property
* SeriesName is a somewhat "parent name", for a episode or season it will contain the tv-show-name, for the tv show entry itself it will be empty
** that one i used for finding all child items related to the tv show
* Path is the filesystem path to the item, i used /tv/ cause its unique for all my tv shows, movies are stored in different location, so choose one thats fits your filesystem structure

* first query updates all items that are childs of a tv show that is rated by the us-system, or just the contains the age itself
* second query updates the tv show itself that is rated the same way
* third query looks for child items that have not inherited the german rating of a tv show

If someone gonne used it:
* Make a backup of your library.db
* modify Path to your needs as mentioned above
* modify what ratings you wanna change and what you wanna have in the end
* make metadata refresh (scanning for new and changed files)

=> boom, child account works as intended

**Comment by korncola** [comment]
will this ever be fixed?

**Comment by Cissoubaka** [comment]
I'm modifing the nfo of the episodes, then refresh the database.

**Comment by korncola** [comment]
oh thanks for the suggestion, works also for me. As not everything has a nfo, i still have to use my sqlite queries via cronjob at night, works well :)
to quote myself: "i am willing to donate, but the amount issues open in github and the lack of response to issues like this make me sceptical."

**Comment by Cissoubaka** [comment]
I had to do more test, but it seems that you have to set the correct parental rating on the show, then update your libraries, then the parental rating is correct for all episode.
I tried on a show and it seemed to worked (10.7.7 version)

**Comment by Cissoubaka** [comment]
ok, so I made som test, and it's working, you have to change the rating of the show, then you need to made a full update of the library, and all season/episode will have the correct rating

**Comment by captainnapalm** [comment]
The above suggestion did not work for me in 10.8.1. I updated the Parental Rating on the show, and did every available option of updating metadata/library scan, etc. The episodes still do not inherit the parental rating.

**Comment by Shadowghost** [comment]
> The above suggestion did not work for me in 10.8.1. I updated the Parental Rating on the show, and did every available option of updating metadata/library scan, etc. The episodes still do not inherit the parental rating.
> 
> I also confirmed that the field for Parental Rating is enabled and not locked, so that's not the issue.

Is anyone of you using NFOs? because those would override whatever you manually set except if you locked the field after editing.

**Comment by korncola** [comment]
no NFOs, and it is still broken.... My workaround works, but its just bad design that is not properly made and designed.

**Comment by Shadowghost** [comment]
https://github.com/jellyfin/jellyfin/pull/8526 takes care of this now for Series, Seasons and Albums.
