### ISSUE TITLE
Not displaying correct dates for upcoming TV Shows

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#4387]
Go to TV Shows library then Upcoming and you will see the dates are wrong, and no it isn't because TVDB has wrong dates because Sonarr displays it correctly in their calendar.

For example it shows "Yesterday" when in fact that should be "Today" and so every date is displayed incorrectly. It needs a +1 day to be correct.

You could look at Sonarr code to see how they dealt with it since Sonarr is C# as well.

**Comment by cvium** [comment]
In their infinite wisdom, they have decided to store the airdate in "network local time" ie. it is based on the _timezone of the network_ it airs on. I would argue that tvdb has the wrong dates.

**Comment by Protektor-Desura** [comment]
It is actually stored in UTC and somehow Sonarr manages to get it correct and display dates and times correctly.

**Comment by Protektor-Desura** [comment]
I guess everyone gave up on this issue?

**Comment by crobibero** [comment]
Go speak to TVDB, this is not a Jellyfin issue.

**Comment by ultratiem** [comment]
_"Go speak to TVDB, this is not a Jellyfin issue."_

It's December 2023, I don't have the TVDB plugin installed, and this is still an issue. Moreover, it represents a deeper systemic problem within the project.

As of now, using the TMDb, TV Shows pull the correct data. There is no issue with the time and date stored within Jellyfin's DB. Looking at the meta data, we see Fargo (2014) airs on Sunday's at 10:00pm:
![Screenshot 2023-11-26 at 10 02 10 AM](https://github.com/jellyfin/jellyfin/assets/2991193/5dea7d67-1f0d-4ab6-ae22-345fcb4a9f44)

But when we look at the Upcoming page, we see it listed as Monday:
![Screenshot 2023-11-26 at 10 03 07 AM](https://github.com/jellyfin/jellyfin/assets/2991193/4c43a369-7d98-4ef3-9127-d9c550140d23)

Moreover, changing the metadata Air time does nothing. A user has to _totally_ replace the entire metadata for the show to even get listed (or updated).

These bugs far extend beyond "tVdB pUllInG ThE wRonG DaTeS". And it's a shame that the devs have just tossed it out, blaming someone else's code.

**Comment by cvium** [comment]
@ultratiem The code for the Upcoming endpoint relies on the existence of episodes in the database with a premiere date in the future. The TVDB plugin is the only metadata plugin we have that actually creates such entries, and they refuse to provide any timezone data.

**Comment by ultratiem** [comment]
@cvium that still doesn’t explain why I have been refreshing shows like Invincible (https://thetvdb.com/series/invincible-2021), replacing the entire metadata and it’s not showing on upcoming shows. New episodes will not list on the page.

Moreover, since Jellyfin doesn’t ship with TVDB anymore, why is that tab visible without it? You’re forcing a user to install a “broken” plugin to even populate it? Which it won’t do anyway? I’m really confused why a broken “feature” with obvious bugs continues to exist in the project and the only explanation I can see is that it’s someone else’s fault? What?

**Comment by cvium** [comment]
@ultratiem  There's a lot to unpack here and I could really do with less attitude. Nevertheless, I will try to answer...

> Moreover, since Jellyfin doesn’t ship with TVDB anymore, why is that tab visible without it? You’re forcing a user to install a “broken” plugin to even populate it? 

The tab is visible because any plugin can populate it? The fact that it's only been the tvdb plugin populating it, doesn't make it a tvdb feature.

> I’m really confused why a broken “feature” with obvious bugs continues to exist in the project and the only explanation I can see is that it’s someone else’s fault?

Tvdb provides premiere dates in their API, but the timestamp is "network local time", which is complete rubbish. We're not going to maintain a database of TV networks and their timezones...

> that still doesn’t explain why I have been refreshing shows like Invincible (https://thetvdb.com/series/invincible-2021), replacing the entire metadata and it’s not showing on upcoming shows.

You've already said you don't have tvdb installed, so which is it? Our tvdb plugin is currently in a weird state. Their API migration hasn't gone terribly well and the .NET library we've used seems abandoned. We have to decide whether we want to maintain our own.
