### ISSUE TITLE
Sometimes Syncplay group is not cleaned up and this can cause clients to get stuck in a loop of joining it

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#4680]
**Description**
If for some reason leaving a Syncplay group does not result in the group being deleted on the server side, at least the web client will be stuck reentering it until you also clear local storage. At this time, if you join the group (since it still exists with no one inside it), the client gets stuck in this loop again. This makes it so that urls like the home page forcibly load the Syncplay interface too.

Additionally, when its broken in this manner the syncplay session struggles to actually play the video. It can take a minute or more for playback to start if at all and the OSD never appears.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Web
 - Browser: Firefox 83
 - Jellyfin Version: 10.7.0-rc1

**To Reproduce**
Unsure of the steps to cause the group to not be cleaned up, but once it fails to be cleaned up the web client will refuse to leave until you clear the cookies. If you join the group, any page you go to afterwards will force you into the session until you clear the cookies.

**Expected Behavior**
When I leave the group, I expect it to clear itself up if there's no one in it anymore.

Alternatively, I expect the client to not be stuck in a perma joining loop until I clear cookies.

**Screenshots**
![Screenshot_20201205_152645](https://user-images.githubusercontent.com/1992688/101262671-6cd68500-370e-11eb-8c49-5f509d536abe.png)

I'm the only user on this server and given that I get this screen, I'm obviously not in a group right now so why is there an empty group thats persisting?

**Comment by OancaAndrei** [comment]
It was supposed to be a feature :sweat_smile:, but it needs polishing. Sessions remain in a group until they explicitly request to leave: the idea was that in case of WebSocket disconnections or page refreshes the playback would resume and sync.

If I'm not mistaken, sometimes (maybe often) the server sends updates before the client is actually ready to process them which results with SyncPlay not being enabled client side.

By clearing the local storage a new session is created and when you join the old group with this new session it's like two of your devices are connected to sync with each other. So the playback won't resume because it's waiting for the old session to report its state.

I think that I can fix this by making the client actively check to see if it should enable SyncPlay instead of waiting for a server message (at least when the page finishes loading, or every time the `ws` connection is back).

**Comment by sparky8251** [comment]
Hmm... In trying to find a way to replicate this I can see the feature you describe in action. I can't seem to get the client being pulled back in without my say so though.

I'm not entirely sure how big of an issue this will be as it seems to have very specific conditions in which it occurs.

**Comment by OancaAndrei** [comment]
I guess that it comes off as scary seeing the player popping up on its own. Another more user friendly approach would be to enable SyncPlay and not resume the playback but show some message instead, while moving the auto playback as an opt-in setting somewhere.

**Comment by xkronusx** [comment]
I want to add to this because I believe it stems from the same area.

When the Syncplay group reaches the next video it gets locked in what I think is the same feedback loop as described above.

Playback is affected so you can't seek but if you click the dropdown it gives the option to resume local playback and will then jump to the time that was selected.

Refreshing the page or going home also forces back into the video in the syncgroup.

By the way, thanks OancaAndrei for all the effort with Syncplay. It has really made the last few months so much better being able to watch stuff with my family.

**Comment by OancaAndrei** [comment]
> When the Syncplay group reaches the next video it gets locked in what I think is the same feedback loop as described above.

This one's a little different. Somehow the playback starts on its own, as if SyncPlay was not enabled, when letting the player pick the next item. I thought I had fixed this problem once.

> Refreshing the page or going home also forces back into the video in the syncgroup.

And by reloading it resets to a clean state and resumes playback (I assume).

> By the way, thanks OancaAndrei for all the effort with Syncplay. It has really made the last few months so much better being able to watch stuff with my family.

I'm glad it has served you well :)

**Comment by sparky8251** [comment]
> I guess that it comes off as scary seeing the player popping up on its own. Another more user friendly approach would be to enable SyncPlay and not resume the playback but show some message instead, while moving the auto playback as an opt-in setting somewhere.
> 
> At least until users don't get used to how this new implementation works.

For me, this isnt the issue. The entire web client became unusable until i cleared the cookies and could get back to my usual pages. Every other time it forced me into the session, the playback never started and no UI elements ever appeared (but the loading backdrop for the video appeared). It was *completely* unrecoverable aside from knowing to clear cookies and doing that. Everything else left me with a 100% non-functional client.

**Comment by OancaAndrei** [comment]
I had another insight on this: the browser [blocks media automation](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) if not directly initiated by the user. I keep forgetting about this.

**Comment by OancaAndrei** [comment]
> For me, this isnt the issue. The entire web client became unusable until i cleared the cookies and could get back to my usual pages. Every time this problem was happening it forced me into the session, the playback never started and no UI elements ever appeared (but the loading backdrop for the video appeared). It was _completely_ unrecoverable aside from knowing to clear cookies and doing that. Everything else left me with a 100% non-functional client.

And add a mix of [UI becoming invisible](https://github.com/jellyfin/jellyfin-web/pull/1945#issuecomment-738116522) and we should get what you experienced.

**Comment by OancaAndrei** [comment]
@xkronusx, I've created a [dedicated issue](https://github.com/jellyfin/jellyfin-web/issues/2193).

**Comment by OancaAndrei** [comment]
> Additionally, when its broken in this manner the syncplay session struggles to actually play the video. It can take a minute or more for playback to start if at all and the OSD never appears.

With the PR above it's now obvious that something is going on with the WebSockets.
All goes smooth until one refreshes the page. Upon reconnection, SyncPlay is re-enabled but often it doesn't work properly. It feels like some messages are sent by the server with some delay and in batches.

**Comment by TheNamelessWonderer** [comment]
This still seems to be an issue in 10.7-RC2. I have a group which says there is still one user in but the user isn't online. There doesn't seem to be a way to get rid of the group although restarting the server might do it but users are watching content so I can't test this yet!

**Comment by Uatschitchun** [comment]
I had a group staying after playing a file from a library the user who created the group has no access to

**Comment by OancaAndrei** [comment]
Little note for future me: a workaround (until the root cause is found, if any) would be to start a timer when all the users in that group become inactive (no active WebSocket connection); if the timer times out the group is deleted; otherwise cancel timer once a user becomes active again.

**Comment by sparky8251** [comment]
Looks like this issue can be agitated/replicated by using the browser tools to simulate a shitty and slow connection. Not sure how I triggered it the first time on a LAN, but it does explain why its difficult to replicate.

Hope that helps some @OancaAndrei !

**Comment by OancaAndrei** [comment]
Yep, I can now reproduce this:
1. start a group watching a video (browser will grant playback permission);
1. enable network throttling (I've used `DSL` in Firefox);
1. refresh page, if playback doesn't start before the predefined 30 seconds timeout the browser will revoke playback permission.

The client is now stuck in limbo:
- they cannot leave the group as buttons are hidden;
- refreshing again won't solve the problem as SyncPlay is not allowed to start playback (missing user input, missing playback permission) which results again in `Error while waiting for 'playbackstart' event! startPlayback Timed out.`.

Cool :laughing:. Prompting again for playback permission should fix this. Maybe I'll have to give a second look at how the timeout is handled as well, maybe replace it entirely, so that slower connections are not affected this much.

Still not sure how to trigger the empty group not being deleted.

**Comment by tlaporte** [comment]
This is happening for me on 10.7.0.

All I did was create a group to test the new syncplay out (works great for TV shows, thanks for that!), and then I just used the back arrow to "leave" instead of actually clicking "Leave group" in the syncplay menu. After browsing around for a bit, I refreshed the page and it is constantly redirecting me to a syncplay group that no one was controlling.

Only way out was to clear cookies as suggested here.

**Comment by Sidefix** [comment]
I'm not 100% sure if this is related, but I've been able to reproduce the described result here relatively reliably by simply joining the syncplay group created by someone outside of my network (where jellyfin is hosted) and joining myself.
3 out of 10 times the OSD would simply not display and there would just be the splash screen of the video we were trying to watch, with the video never loading on my end (working perfectly fine on their end).

I always check the logs in these instances and I never observed any errors or anything to indicate that there was a timeout or any other such issues.

I never cleared my cookies though; when this occurred, I would just restart jellyfin altogether and refresh the browsers then re-create the group and this would obviously fix it.

**Comment by peperunas** [comment]
I am experiencing this bug as well. I was able to create a second group after getting out of the infinite loop of the first one and now it's impossible to even get to the home menu. :-(

**Comment by OancaAndrei** [comment]
If anyone is up for some testing, I've pushed a Docker build at `andreioanca/jellyfin-syncplay-preview:latest`.

This build includes a dialog that will enable, when needed, the required playback permissions, along with a fix that should better handle WebSocket re-connections (for example, when reloading the page).

The dialog allows the user to block the auto-playback as well.
