### ISSUE TITLE
robots.txt support no longer present at root URL /robots.txt

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin#4689]
Add back support for serving robots.txt

**Comment by joshuaboniface** [comment]
Context:

This isn't working anymore because a `robots.txt` as it previously existed (i.e. within the Web client artifacts, at say `/usr/share/jellyfin/web/robots.txt`) would show up at `/web/robots.txt`.

Ideal solution is to have the API respond to `/robots.txt` and send something. I can think of two options:

1. Have it redirect transparently to `/web/robots.txt` and keep the "manual file under webroot" method.
2. Have it be constructed by the API. This is nicer IMO because then we can turn this into a setting in the Dashboard Networking section where users can enter a custom `robots.txt` in a text field.
