### ISSUE TITLE
10.7 Not possible to downgrade plugins

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin#4698]
Due to the way plugin upgrades and cleanup is currently done, it is impossible to downgrade to an earlier version of a plugin.

On start, the server deletes all but the highest version of a plugin before loading the plugins, resulting in any attempt of installing a lower version of a plugin not succeeding.

**System (please complete the following information):**
 - Jellyfin Version: 10.7-pre, up to and including 10.7.0-rc1
 - Installed Plugins: affects all plugins

**To Reproduce**

1. Attempt to install older plugin version
2. Restart server
3. See the highest numbered version still present, and the wanted version getting deleted during start

**Expected behavior**

Expected behavior would be for the server to keep track of which version is desired, and display in the web UI which version will be used after a server restart.

**Logs**

```
Dec 06 15:52:53 1070L jellyfin[7873]: [15:52:53] [INF] Emby.Server.Implementations.ApplicationHost: Loading assemblies
Dec 06 15:52:53 1070L jellyfin[7873]: [15:52:53] [DBG] Emby.Server.Implementations.ApplicationHost: Deleting /var/lib/jellyfin/plugins/Playback Reporting_9.0.0.0
...
Dec 06 15:52:53 1070L jellyfin[7873]: [15:52:53] [INF] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=9.2012.500.608, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_9.2012.500.608/Jellyfin.Plugin.PlaybackReporting.dll
```

**Additional context**
The current workaround is to uninstall the plugin first.

**Comment by BaronGreenback** [comment]
ApplicationHost.cs 

```
public IEnumerable<LocalPlugin> GetLocalPlugins(string path, bool cleanup = true)
```

change cleanup to false by default, and the folders won't be deleted. Might be worth adding this as a config option ??

The mod which could be done, is to add **enabled** in the meta.json file.
This would enable rollback/forward whilst skipping the windows file lock issue.
It would still require a restart to reload the correct one.

**Comment by BaronGreenback** [comment]
Is possible with #4709

**Comment by da-anda** [comment]
where is this mentioned "user option" to delete plugins after update - didn't spot anything in the UI settings? IMO the current approach to just leave plugins on disk is not ideal. Couldn't we be smarter about this up-/downgrade scenario? I mean, jellyfin must have some sort of database/index where it stores the enabled/active plugins. If you add the version number of the currently used version there, you can easily check on startup if it's an upgrade or downgrade and once finished delete the old version.
Alternatively download plugin updates/downgrades into a separate folder, check this folder on startup and replace the current plugin with the one form the temporary folder.
Wouldn't any of these solutions be better than to just keep infinite version of plugins forever?

**Comment by BaronGreenback** [comment]
I will not argue that the current implementation of plugins is not ideal - but it's design is not one that can be fixed in one go without causing a major implications to all the plugins. Hence the small steps.

- the user option to remove all older plugins isn't currently available in the UI - it's in the system.xml as "RemoveOldPlugins". However, individual plugins can be uninstalled which deletes them.

- there is currently no central repository of plugins.

- file locks stop the ability to dynamically load/unload/delete plugins, with some plugin information only being accessible once they are loaded into memory and thus "locked" until the next restart.

- Some people don't want to auto-update plugins / others may like to be able to drop down a level. (I develop, so tend to have multiple versions installed. This enables me to check functionality between differing versions)

- Deleting something is a perminent option - hence the decision to make it as user choice.

As with all JF - improvements will be made over time, which i'm sure will include some sort of central database of plugins.

**Comment by sim642** [comment]
I'm still experiencing this issue on 10.11.2 and the workaround to first uninstall the plugin doesn't work either.
Here's what happens:
1. The plugin is not installed.
2. I install a non-latest version, I'm told to restart.
3. I restart.
4. The plugin status is still "Restart".
5. So I restart again.
6. The latest version of the plugin is installed, not what I clicked "Install" on.
