### ISSUE TITLE
--webroot seems to ignore ../ (parent directory relative path)

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#4725]
**Describe the bug**
@Sylk over at matrix found it while trying to point to `../jellyfin-web/dist` and the server interpreted it as `jellyfin-web/dist`

**System (please complete the following information):**
 - OS: OS X El Capitan
 - Jellyfin Version: master
 - Installed Plugins: none (clean install)

**To Reproduce**
1. Compile the server
2. run it with `--webroot ../other/location` where that other location has jellyfin-web installed

**Expected behavior**
It should follow the location up to the parent directory as normal

**Screenshots**
![bilde](https://user-images.githubusercontent.com/1411903/101401216-4d885500-38d2-11eb-9852-551e002cf607.png)

**Comment by Sylk** [comment]
OS: OSX el capitan
Jellyfin Version: Master

**Comment by nielsvanvelzen** [comment]
What was the working directory when executing the dotnet command?

**Comment by crobibero** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=net-5.0
This function should fix the issue

**Comment by Sylk** [comment]
@nielsvanvelzen the working directory was the jellyfin-server folder, which held the master code.

**Comment by hypervtechnics** [comment]
Maybe try a command similar to `dotnet run --project Jellyfin.Server -- --webdir ../jelllyfin-web/dist`? Also webdir and webroot is used. Are this options the same?

**Comment by Ullmie02** [comment]
We are already using `Path.GetFullPath`. But this function doesn't take the command line working directory as the base path but (assuming the Jellyfin server code is inside `jellyfin-server`) `jellyfin-server/Jellyfin.Server` because this is the project that runs. 
So the argument that works correctly is `../../jellyfin-web/dist`
.NET seems to be changing the working directory to the project that is executed, regardless what the command line working directory is. (I have checked this with running this command from a random directory `dotnet run --project <absolute-path-to-Jellyfin.Server-directory>`)
