### ISSUE TITLE
Server broadcasting as VirtualBox Host-Only Network Address

### ISSUE THREAD

**Issue by cbarter** [jellyfin/jellyfin#4784]
I have a few Vagrant VM's for some projects I'm working on. When shutdown (or not) the VirtualBox Host-Only Network Adapter remains setup. For whatever reason, when I try and access the Jellyfin server through GoogleTV(androidTV), aka the chromecast app, it detects this IP for my server, rather than my actual local IP. I suspect this is the same reason I can get the chromecast app to launch when I try and cast from the web UI, but media will not stream.

Not sure what's causing this. But I can manually enter the IP for my machine w/ port and connect and stream from the server. 

Removing the virtual host adapters resolves the issue. Preferably though this could be fixed on the jellyfin server side.

I would be interested in contributing to the fix, if anyone has any input on why this would be happening before I dive in.

**Comment by anthonylavado** [comment]
Moving to the main server repository (the Windows one is just for the installer/wrapper), but IIRC, we provide an option to set what the server IP should be in 10.7. The current public release just uses what the system reports it's IP address as.

Because of the already included fix, I will also close this as fixed in a future version.
