### ISSUE TITLE
PS4 DLNA appears to be incompatible with TS container, so no videos that requires remux/transcode appears

### ISSUE THREAD

**Issue by hansoljin** [jellyfin/jellyfin#4806]
**Describe the bug**
This isn't exactly a Jellyfin bug, rather it seems like an incompatibility with the PS4 DLNA client.
None of the videos that require transcoding (such as HEVC or DTS) appear in the built-in DLNA client. However, in Jellyfin dashboard, when setting the "Transcoding" profile from the TS container to the MP4 container, the video appears but will not play. 
This leads to an educated guess that possibly the TS container is unsupported by the PS4.

**System (please complete the following information):**
 - OS: UnRAID
 - Virtualization: Docker
 - Clients: PS4 DLNA client
 - Browser: Edge (Chromium) 87.0.664.60
 - Jellyfin Version: 10.6.4
 - Playback: Transcode, remux
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Locate any video in a format unsupported by PS4 (notably HEVC or DTS) in its DLNA client.
2. The video will not show up at all.

**Expected behavior**
All videos requiring transcoding or remuxing should show up in the PS4's Media Player. 

**Logs**
No errors Jellyfin-side as this is a fault of PS4's file browser system.

**Additional context**
https://manuals.playstation.net/document/gb/ps4/music/mp_format_m.html
This is a list of supported formats. All of these sound correct enough except for the MPEG-2 TS part. Any videos that require transcoding as per the DLNA profile in Jellyfin dashboard does not show up. No TS files to test as of this writing.
A suggestion is that maybe there should be an alternate transcoding container compatible with anything other than TS so that the PS4 recognizes it.

**Comment by cvium** [comment]
Please include ffmpeg transcode logs.

**Comment by hoewer** [comment]
I can't see how merging this bug with the aac audio issue should help?
I'm on Ver. 10.7.7 and the bug is still occuring. It seems not connected to audio codecs but to the details of the transcoding container format or codec, resulting items not showing up in PS4 Media Player (as well as other in DLNA-Players, but I don't know whether for the same reason).
Other DLNA-Servers show up and play just fine (e.g. Serviio) - but they usually transcode to MPEG-TS Container with MPEG2 codec. Would that be an option?

**Comment by lifehackerhansol** [comment]
It worked on my end post-merge. I would double check if anything in the later versions got screwed over but my Jellyfin install kind of broke (and I moved to LinuxServer.io's docker since the official Jellyfin seems to be gone from UnRAID's community apps) so not sure if that's even worthy of making a note of here.
