### ISSUE TITLE
Season numbering gone in 10.7.0-rc2

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#4948]
**Describe the bug**
When displaying Seasons in 10.6.4, they were named "Season 1", "Season 2", etc. In 10.7.0-rc2 only the show name is shown on all seasons instead. Not sure if it's intended but seems kinda odd.

**System (please complete the following information):**
 - OS: CentOS 7
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 84
 - Jellyfin Version: 10.7.0-rc2
 - Reverse Proxy: nginx

**To Reproduce**

1. Go to a show
2. Scroll down to Seasons
3. All seasons are named the same, which seems to be the show name (same on multiple shows I've checked)

**Expected behavior**
Same as 10.6.4, Season 1/2 etc.

**Logs**
No related errors that I can see.

**Screenshots**
10.6.4:
![10 6 4](https://user-images.githubusercontent.com/13684929/103541334-94e70e80-4e9b-11eb-98d2-bd34c8bf765d.png)
10.7.0-rc2:
![10 7 0](https://user-images.githubusercontent.com/13684929/103541342-97496880-4e9b-11eb-9533-0bc722cd5090.png)

**Comment by crobibero** [comment]
What metadata providers do you have enabled?

**Comment by krutburken** [comment]
TMDb and OMDb. I've tried replacing the metadata from either but it only the images seems to change

**Comment by krutburken** [comment]
If I switch to the tvdb plugin instead, the numbering works as expected

**Comment by Larvitar** [comment]
Similar issue has already been reported a while ago: #4134

TmDBSeasonProvider sets season name [here](https://github.com/jellyfin/jellyfin-plugin-tmdb/blob/master/Jellyfin.Plugin.Tmdb/Providers/TV/TmdbSeasonProvider.cs):
```C#
            result.Item = new Season
            {
                Name = info.Name,
                IndexNumber = seasonNumber,
                Overview = seasonResult.Overview
            };
```
For some reason `SeasonInfo` that is passed by Jellyfin to `GetMetadata` contains series name instead of current season name, but I still fail to understand why. 
A quick fix would be to just drop `Name = info.Name` in the provider (provider will not return `Name` value so it won't be changed in the library) but the main issue is still the wrong value of `SeasonInfo.Name`.

On the other hand why do we even set `Name` value if it's not a value returned by TmDB itself? This prevents any other provider (further in queue) from ever setting this value.

**Comment by krutburken** [comment]
Yeah that looks very similar, and probably the same issue. I've disabled everything but the tvdb-plugin for now until this issue is fixed.
