### ISSUE TITLE
Photo scanning and display not supported for TIF images

### ISSUE THREAD

**Issue by bigcookie** [jellyfin/jellyfin#5039]
In photo library, tif images throw exceptions in log:

**System (please complete the following information):**
 - OS: docker on QNAP
 - Virtualization: QNAP
 - Clients: MacBook Pro, FireTV Jellyfin App
 - Browser: Safari, Chrome
 - Jellyfin Version: 10.6.4
 - Playback: Direct
 - Installed Plugins: None
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: IP_ADR:8096
 - Networking: Docker host mode
 - Storage: local network, media folder embedded as read only.

**To Reproduce**
Put tif images in your photo library and restart scan

**Expected behavior**
TIF images are supported in scanning and display.

**Logs**
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate)
[2021-01-17 11:39:35.320 +00:00] [ERR] [67] Emby.Server.Implementations.Library.LibraryManager: Cannnot get image dimensions for "/media/Bilder/Compilation - LaFT/2003 Gaesteschiessen/Offiziell/Dsc_0097.tif"
Non-success codec result: InvalidInput

**Screenshots**

**Additional context**

**Comment by bigcookie** [comment]
Any progress?

**Comment by computamike** [comment]
I need something similar so I've just downloaded the source to see if I can add TIF support.  I did once write a image viewer for a .NET Desktop app which had multi page tiff support.

**Comment by computamike** [comment]
I have been looking into this - and I think there are 2 issues here.

Firstly - as you say there are potentially error messages being thrown in the back end when indexing TIF images.
Secondly, those images aren't showing up in the browser front end.

I believe that these are 2 different issues.  I would like to add tif support because I have some family photos that are scanned as TIF.  

What I'm seeing from the front end is that the server is returning a valid image/tif 'stream' - it's just that the browser doesn't render it, as it doesn't support tifs.  I think that Safari may support tif images - but Edge / Chrome / Firefox don't.

I switched my approach to attempt to fix the front end - and found the front end has a plugin model, allowin code to register as supporting media types.

I wrote a tif provider that potentialy could inject JS into the page, that would render tif images - but the plugin loader has a flaw where it filters the providers for that media type, and returns the first one.  This means that my TIF provider wasn't being loaded because there's a built in provider called photoplayer - which was always being picked.

I'll carry on working on both problems - but I'm going to concentrate on the Front End fix, as I think that would offer the most benefit.  I'll then look at how the back end scanning works, and try and fix the error messages.
