### ISSUE TITLE
The next episode of audio novels continues to play!

### ISSUE THREAD

**Issue by zelohon** [jellyfin/jellyfin#5086]
English
1, in version 10.7, continue to listen and be ready to use! But there is a problem that if the playing audio is unexpectedly interrupted or paused and exited, jellyfin cannot continue to play after it is opened next time.
2, I hope to optimize the current playback position and continue listening while listening!
中文
1，在10.7版中，继续收听终于可使用了！  但是存在一个问题，如果正在播放的音频意外中断或暂停并退出，在jellyfin下一次打开后 无法继续播放。
2，希望优化当前播放位置，并在 继续听 里可以直接播放 连续每一集的播放！

**Comment by zelohon** [comment]
This problem occurs in docker

**Comment by chrstfer** [comment]
@zelohon do you mean that if the playback is interrupted then it doesn't save your playback position? I'm having trouble understanding exactly what you mean, but I am having the same problem. Before I changed the background power usage settings on my android the client would get killed if backgrounded for more than a few minutes, and I would always need to seek to where I was listening, rather than it recalling the position I was at.
