### ISSUE TITLE
Create collection to the wrong user after login another account

### ISSUE THREAD

**Issue by blacksider** [jellyfin/jellyfin#5123]
I tried to add a video to collection, and the collection is new, the new created collection is not on my current login account, but pre login account, and then I tried to add a new collection directly, it is still not appears on my current account, after I logout current account and login pre account, it is on that count.

 - OS: Centos7
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 88.0.4324.96
 - Jellyfin Version: docker image 10.6.4
 - Networking: Host
 - Storage: local

**To Reproduce**
Before A and B:
1. Login first account(which is the admin account)
2. Logout admin, then login a new created user

A:
1. Go to library
2. Click on any video and select save to collection
3. Save to a new created collection, then go to your collection to check if the created collection exists

B:
1. Simply go to your collection list and create a new collection
2. Go to collection list to check

And it seems like login token is not working as I refresh the whole browser by F5, only if I select remeber-me on login page(I am not sure it is by intention or A bug, just wanna metion it here as well).

**Comment by Ullmie02** [comment]
I can't reproduce this.
To see newly created collection from a different account, you first have to go to the Home page with that account. This reloads the library including the collections.

If you didn't check "remember me" during sign in, you have to log in every time you reload Jellyfin. I'm pretty sure that's expected behavior.
