### ISSUE TITLE
Linux Issue with exclamation marks in file path

### ISSUE THREAD

**Issue by scott-nuskool** [jellyfin/jellyfin#5155]
I'm running Jellfin on Ubuntu Server and when a file needs transcoding playback isn't working. I've done a bit of investigation and I can see that the ffmpeg command isn't working due to an exclamation point in the file path not being escaped properly in the command parameter. Just copying and pasting the command to a shell I think I've figured that enclosing the parameters in single quotes rather than double quotes appears to fix the issue however I don't know what other effects this may have.

Please let me know if there is any other information i can provide to help.

**Comment by Ullmie02** [comment]
Could you provide us the ffmpeg command that isn't working?

**Comment by scott-nuskool** [comment]
Hi @Ullmie02 

This is taken from the log file (I changed the filename but that isn't the important part):

[2021-01-31 15:11:28.295 +00:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i file:\"/mnt/External/!Films/My Movie.mkv\" -map 0:2 -an -vn -c:s copy \"/var/lib/jellyfin/data/subtitles/2/296b423e-e149-5211-5557-606f019b54be.srt\""

**Comment by Ullmie02** [comment]
I can't reproduce this. 
Does transcoding work for other items that don't have an exclamation mark in the path? 
Could you try copying this file to a test library without an exclamation mark?
What operating system are you using? It would have helped a lot if you chose the bug template while opening this issue and filled out the template:

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**Comment by soulnull** [comment]
OS: Ubuntu 21.10
    Virtualization: LXM
    Clients: (happens with multiple)
    Browser: (happens with multiple)
    Jellyfin Version: 10.7.7
    Playback: Transcode
    Installed Plugins: AniDB, Anilist, Anime, AudioDB, Auto Organize, Fanart, Kitsu, Kodi Sync Queue, MusicBrainz, OMDb. TheTVDB
    Reverse Proxy: none, nginx (happens either way)
    Base URL: /
    Networking: Direct IP
    Storage: rclone mounted as a FUSE filesystem.


Background: files not using ! are transcoding correctly. 

Cleaned log output:
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] User policy for token. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: True
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Not eligible for DirectPlay due to unsupported subtitles
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Not eligible for DirectStream due to unsupported subtitles
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Profile: Jellyfin Android, Path: /home/torrents/files/tv/Tester!/Specials/Tester! - S00E01.mkv, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Not eligible for DirectPlay due to unsupported subtitles
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Not eligible for DirectStream due to unsupported subtitles
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Profile: Jellyfin Android, Path: /home/torrents/files/tv/Tester!/Specials/Tester! - S00E01.mkv, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Not eligible for DirectPlay due to unsupported subtitles
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Not eligible for DirectStream due to unsupported subtitles
Dec 24 09:19:35 rikka jellyfin[4177886]: [09:19:35] [INF] Profile: Jellyfin Android, Path: /home/torrents/files/tv/Tester!/Specials/Tester! - S00E01.mkv, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
Dec 24 09:19:36 rikka jellyfin[4177886]: [09:19:36] [INF] Starting User Changes Sync...
Dec 24 09:19:36 rikka jellyfin[4177886]: [09:19:36] [INF] "USERSYNC" User e61e9fe0f4be401fb037be101e9983df(token) posted 2 Updates: 70b57c4dcd2deaf62868a305ba97935c,9b2d6e11d4743a92eccc7a65e8e09422
Dec 24 09:19:36 rikka jellyfin[4177886]: [09:19:36] [INF] User Changes Sync Finished Taking 00:00:00.0029387
Dec 24 09:19:37 rikka jellyfin[4177886]: [09:19:37] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -f matroska,webm -i file:"/home/torrents/files/tv/Tester!/Specials/Tester! - S00E00.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 copy -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/2d879a575273585a0c9fb05c816fab96%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/2d879a575273585a0c9fb05c816fab96.m3u8"
Dec 24 09:19:38 rikka jellyfin[4177886]: [09:19:38] [WRN] Slow HTTP Response from http://127.0.0.1:8096/videos/70b57c4d-cd2d-eaf6-2868-a305ba97935c/hls1/main/0.ts?DeviceId=1e4a4a73a9c28208e61e9fe0f4be401fb037be101e9983df&MediaSourceId=70b57c4dcd2deaf62868a305ba97935c&VideoCodec=h264&AudioCodec=mp1,mp2,mp3,aac,ac3,eac3,dts,mlp,truehd&AudioStreamIndex=1&SubtitleStreamIndex=2&VideoBitrate=999040000&AudioBitrate=960000&PlaySessionId=6ba77eaf399c413f84c9b94cd6bedfb1&api_key=2373458f6c104a8c98b5cbddf05a70e4&SubtitleMethod=Encode&RequireAvc=false&Tag=37a8b5b766b39ffdac175fb6e6c56bbc&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=SubtitleCodecNotSupported to 127.0.0.1 in 0:00:01.8109498 with Status Code 200
Dec 24 09:19:39 rikka jellyfin[4177886]: [09:19:39] [INF] Starting User Changes Sync...
Dec 24 09:19:39 rikka jellyfin[4177886]: [09:19:39] [INF] "USERSYNC" User e61e9fe0f4be401fb037be101e9983df(token) posted 2 Updates: 70b57c4dcd2deaf62868a305ba97935c,9b2d6e11d4743a92eccc7a65e8e09422
Dec 24 09:19:39 rikka jellyfin[4177886]: [09:19:39] [INF] User Changes Sync Finished Taking 00:00:00.0102385
Dec 24 09:20:01 rikka jellyfin[4177886]: [09:20:01] [INF] FFmpeg exited with code 0
Dec 24 09:20:40 rikka jellyfin[4177886]: [09:20:40] [INF] Transcoding kill timer stopped for JobId a835051060794d81ab84afac335e35f5 PlaySessionId 6ba77eaf399c413f84c9b94cd6bedfb1. Killing transcoding
Dec 24 09:20:40 rikka jellyfin[4177886]: [09:20:40] [INF] Deleting partial stream file(s) /var/lib/jellyfin/transcodes/2d879a575273585a0c9fb05c816fab96.m3u8

Attempting to run the jellyfin-ffmpeg command as printed above directly results in this:
-bash: !/Season: event not found

Running the above command modified to do this instead results in the desired behavior..
[..]/usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -f matroska,webm -i file:"/home/torrents/files/tv/Tester"\!"/Specials/Tester"\!" - S00E00.mkv" -map_metadata [...]

So it appears as though there is an escaping issue somewhere with this setup. Whether an issue with bash, fuse, or jellyfin, something appears to be struggling here.

If there are any other additional things I can test to narrow down the issue, please let me know.

**Comment by jerwansyah** [comment]
It's a bash problem. Just add `set +H` to `~/.bashrc` to disable history expansion. CMIIW.
