### ISSUE TITLE
Audiobook

### ISSUE THREAD

**Issue by froopyloot** [jellyfin/jellyfin#52]
Hi, I'd love to see audiobook support with mp3, ogg, and m4b.  Chapter markers, bookmarks, etc.  Thanks!

**Comment by Fhrost0213** [comment]
There's an existing project for pulling audiobook metadata that looks like it scrapes from audible - https://github.com/macr0dev/Audiobooks.bundle

**Comment by jedichric** [comment]
I just wanted to check in and say I would like this feature as well.

**Comment by designgears** [comment]
I was about to post the same, Proper audiobook support.

**Comment by leram84** [comment]
This https://emby.media/community/index.php?/topic/50141-embook-proper-support-for-audiobooks/ has been the most promising abook solution, imo, for the past few years. Booksonic is too narrow in scope, plex is a bloated bureaucratic nightmare to deal w these days for stuff like this (or anything that won't provide immediate new rev streams), but embooks targeted mobile client improvements, while falling back on emby for general all purpose use, is pretty much the sweet spot for a solid server/client abook implementation. Unfortunately the dev wasn't getting the support from emby he needed and then it seems like personal stuff got in the way, but this is part of what i think makes jellyfin so appealing atm... all the various projects out there that started to feel like pie in the sky suddenly have new potential for life!

**Comment by s1mpleman** [comment]
Just want to add my support for this too! Making them a first class citizen with Movies, Shows and Music would be great too!

**Comment by leram84** [comment]
We might be in for a surprise way sooner than expected!

![ohdamn](https://user-images.githubusercontent.com/21117493/50782596-7fbc5280-1276-11e9-8f9c-0a2892698ff4.PNG)

**Comment by anthonylavado** [comment]
@leram84 We likely won’t be able to use anything they publish though. They forced us to a much older version (as is their right for when they dropped the open license), and we’ve had to rebuild some of the structure.

Now that being said, all features are still possible, but it will take some time for new ones to land.

**Comment by Inrego** [comment]
I'm the dev of EmBook. And yeah, life happened, coupled with very slow changes on the backend of Emby, made me halt the project. My pull requests were ignored, and Luke made minor changes which broke my plugin quite frequently.

I might pick it up again sometime, and if there's no good backend, I guess I'll have to develop that as well.

**Comment by dkanada** [comment]
Hi there @Inrego, what kind of changes did you have to make on the server for improved book support? We are definitely eager to add more functionality for written content over here so if you ever have time again we'd love to work together.

**Comment by Inrego** [comment]
I had 2 simultaneous approaches:

1. Communicate with Luke about what he needed me to make in the backend, in order to naively support audiobooks. This was mostly targeted towards recognizing files that belong together as a book, and ordering them correctly for playback.

See my commits regarding that here:
https://github.com/Inrego/Emby.Naming/commits/master

2. A plug-in for Emby, which provided web services that more or less did the same, as well as metadata scraping from Google books.
This allowed me to develop the app, without proper support in the backend. There was actually a functional version of the app using this plug-in, but it was the first time I ever built a mobile app, so needless to say, it wasn't that good. With my new experience, I pursued a v2, while updates in Emby backend killed my plug-in and therefore the app as well.

Also, issues in the media playback framework I used for Xamarin.Forms, caused me to halt v2 of the app. Xamarin.Forms went on to use dotnet standard, but this framework didn't support it. And this message was quite discouraging: https://github.com/martijn00/XamarinMediaManager/issues/333#issuecomment-390252247
So that means I had to also build a new similar library for iOS and Android, in order to make new app functional. All this was a bit much to take on.
Luckily, it seems like the framework finally supports dotnet standard.
Also in the meantime, I've gotten a lot more experience in developing apps with Xamarin.Forms at my job. So with the right backend, developing an app should be a breeze now.

**Comment by Inrego** [comment]
By the way, I am writing on my phone, and it's 4.30 am. So I apologize in advance for auto corrects and/or spelling mistakes

**Comment by dkanada** [comment]
So you were writing a Xamarin client as well that focused on audiobook support? That sounds super nice to have. I remember an old Emby plugin for Google Books metadata, it might have been yours I was looking at. Don't worry about spelling mistakes :p and if you'd like to talk with all the devs we have a pretty active community on [matrix](https://jellyfin.readthedocs.io/en/latest/getting-help/) for general discussion.

**Comment by Inrego** [comment]
Yeah, most of the work was actually the Xamarin app and supporting web services. An audiobook player tends to have very different requirements than the other types of media on Emby, so I thought a standalone app made sense.

And yeah, that might've been my plug-in that you've looked at.

Now that the media manager framework seems active again, I think I might just get back to this project. First, I'll have to reevaluate how far Emby has gotten with audiobook support in core, since I know there has been some updates in my absence.

**Comment by dkanada** [comment]
Sounds good! Let us know if you'd like to collaborate on the backend or other clients here for any book-related improvements.

**Comment by Inrego** [comment]
I've just checked Emby (haven't checked Jellyfin), and it seems like enough progress has been made, that I might be able to make the app without any extra work on the backend/plugin.

**Comment by pb1051** [comment]
I for one would really enjoy this.

**Comment by onny** [comment]
We might move this issue to the Jellyfin feature requests site: https://features.jellyfin.org

**Comment by anthonylavado** [comment]
It loses some of the history, but please follow the request here: https://features.jellyfin.org/posts/243/audiobook-support

**Comment by CrashyBang** [comment]
@anthonylavado above link is dead.

**Comment by anthonylavado** [comment]
>@anthonylavado above link is dead.

@CrashyBang Shouldn’t be. Sounds like the server died. I’m getting the right people to kick it
