### ISSUE TITLE
Shows with numbers in the title interpreted as Season number

### ISSUE THREAD

**Issue by molokov** [jellyfin/jellyfin#5221]
**Describe the bug**

I've found that Jellyfin has been giving season numbers in the metadata to shows which have numbers in their title, e.g.

Big Hero 6: The Series --> all episodes in 'Season 6'
Avenue 5 --> Season 5
Sense8 --> Season 8

Manually editing the metadata for each folder (and renaming to Season 1, 2, etc) is a workaround, but annoying to do.

Individual episodes appear to have the correct season/episode data in their metadata.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: Web, Android TV
 - Browser: Firefox 85 on Windows
 - Jellyfin Version: 10.6.4

**Comment by Slomo17** [comment]
I opend a new bug about this last year [#6928](https://github.com/jellyfin/jellyfin/issues/6928). But it seems that this problem is not considered to be a bug, as it can be worked around if you use a different namen scheme (the season folder should only be named "Seaon" not the name of the show again, and the number without leading zeros)

**Comment by tremby** [comment]
Thanks, I'll respond over there.
