### ISSUE TITLE
Cannot change user profile picture

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin#527]
Users are not presented with the option to change their user profile picture on the edit profile page any more.

**Comment by sparky8251** [comment]
Not a dupe. New bug.

That said, think the same PR broke them. #399 is the first PR in which the elements required for changing your profile pic disappear. But since it also crashes the page, it's possible it shows up later in the loading process and was broken in a later PR.

More investigation is needed.

**Comment by cvium** [comment]
It was broken by https://github.com/jellyfin/jellyfin/pull/491 wherein one line too many were removed (`showImageEditing = !0`)
