### ISSUE TITLE
Provide "real" build instructions for Linux

### ISSUE THREAD

**Issue by lbeltrame** [jellyfin/jellyfin#528]
The documentation only mentions Debian derivatives (or Windows) and mentions scripts, while it would be useful to have instructions to build from scratch and which are the requirements. These might be useful for integrators (distributions) to tune up their packages.

**Comment by lbeltrame** [comment]
I'd say it's more important than I thought - i took a look at the scripts and the Docker images and it's totally unclear on what they do, what they are building and for what purpose.

**Comment by sparky8251** [comment]
Well, some of the build wonkiness is because the project is designed to be insanely intertwined.

We have a separate repo for doc, jellyfin-docs, and do plan to add proper build instructions to it. They are still changing often as we clean out the code base and gain a greater understanding of it.

Folks are welcome to submit a PR against that repo to have it included in the official docs or ask in our matrix dev chat for answers. Right now, it's low priority since its changing rapidly. Once it settles, it'll be bumped up to high.

**Comment by joshuaboniface** [comment]
Pretty much what @sparky8251. The `debian/rules` folder is the gold standard: that shows exactly what gets run to compile the binaries, i.e. `dotnet publish`; the Docker setup is just a wrapper around that. More specifics about your particular setup would be appreciated (e.g. what distro are you trying to build for?)

**Comment by lbeltrame** [comment]
No problem. For now I'm taking inspiration from Arch's PKGBUILD, which is pretty clear. I might give it a shot in the future and if I get something workable, PR against the jellyfin-docs-repo.

I'm trying to build this for openSUSE, so I can run Jellyfin on my NAS and see how it fares (I don't want to use Docker if possible, and I can't use the host networking method in Docker anyway, because the application will be behind a reverse proxy).

**Comment by joshuaboniface** [comment]
@lbeltrame That's fantastic, thanks! I started looking at OBS yesterday but got lost pretty quickly.

If you have any questions please don't hesitate to ask! There's also an RPM spec in #420 that may help as well.

**Comment by lbeltrame** [comment]
One "problem" (not really a problem) is that AFAICS you need dotnet directly from Microsoft at this point, and I'm not sure the OBS can support "external" repositories (I do some fancy tricks with it, but I never had this happen until now).

One more question: does the build require internet access? Because all distro builders I know of forbid internet access when buidling.

**Comment by Bond-009** [comment]
@lbeltrame Yes, dotnet requires internet to restore the packages.

**Comment by joshuaboniface** [comment]
And yes, it requires .NET Core from Microsoft, AFAIK it isn't official in any distro yet.

**Comment by hawken93** [comment]
It is possible to cache the packages locally and use what's called a local nuget repository by changing the nuget repo url to a local folder path. If it contains all needed nupkg files, the build should work

**Comment by casasfernando** [comment]
> And yes, it requires .NET Core from Microsoft, AFAIK it isn't official in any distro yet.

Are you sure this is required?
Maybe I'm confused but I'm currently building my own Emby 3.5.2 rpms for CentOS 7 against Mono 5.14 with msbuild instead of xbuild without any issues.
I'm also building msbuild myself and as far as I recall that doesn't required .NET core either.
Actually I'm not using .NET core at all on my server, just Mono.

I will try to build Jellyfish and report my findings.

**Comment by JustAMan** [comment]
@casasfernando Yes, we're sure. We dropped Mono support early in the start of Jellyfin project because Mono is being deprecated in favour of .netcore.

**Comment by casasfernando** [comment]
> @casasfernando Yes, we're sure. We dropped Mono support early in the start of Jellyfin project because Mono is being deprecated in favour of .netcore.

Ok got it. So I will not waste my time on trying to build it against mono.
Thanks.

**Comment by joshuaboniface** [comment]
The unified build script provides the "proper", consistent path to build on Debian using Docker that will be well-documented. With our modernized packaging from #335 just running a `dpkg-buildpackage` from the root of the repo is no longer supported to avoid there being too much stuff in the root of the repo. I think that PR will close this issue out, but I'd appreciate your feedback on that @lbeltrame.

**Comment by lbeltrame** [comment]
Disclaimer: I'm no build system expert (although I've dabbled with some). To your knowledge do C# projects only rely on using `dotnet` and what not without any form of build systems?

The script looks fine to , but it largely replicates what a build system does, although it does only require bash (and the deps for jellyfin). Not a criticism, just an observation: from a quick search there aren't proper alternatives to what you are doing ATM.

**Comment by Bond-009** [comment]
Build instructions for a normal release build:
`git clone git@github.com:jellyfin/jellyfin.git`
`cd jellyfin`
`git submodule update --init`
`dotnet build -c Release Jellyfin.Server`

**Comment by sparky8251** [comment]
Can this be closed or do we still need additional documentation?

**Comment by mooninite** [comment]
> @casasfernando Yes, we're sure. We dropped Mono support early in the start of Jellyfin project because Mono is being deprecated in favour of .netcore.

Why? Because you don't want to maintain support for multiple runtimes? Most distros will have mono freely available, but will not have dotnet available because of its inability to be built from source.

I say this with my Fedora packager hat on. I would like to get Jellyfin into RPMFusion without having to package a bunch of new .NET packages.

**Comment by joshuaboniface** [comment]
Dropping mono was done before JF was even a thing, because that's what Emby did. No release of JF has ever supported Mono, it's all dotnet core.

**Comment by mooninite** [comment]
The last FOSS release that Jellyfin is based off of included improved mono support. If the non-FOSS version has dropped mono support, OK, but that's little justification for a fork to follow their footsteps. In any case I'll investigate dotnet for RPMFusion, but you may see me in the future with a PR to add mono support back.

**Comment by EraYaN** [comment]
Why do you need Mono specifically? It's a service, Mono only really provides extra stuff for client apps IMO.

**Comment by mooninite** [comment]
@EraYaN, while some people may use Windows (Microsoft .NET) there are plenty of other people that do not. Linux users must rely on either Mono (mono-project.org / xamarin) or dotnet (Microsoft) to have a .NET runtime.

While it may be trendy to offer docker or snap or flatpak this is not how I use Linux. I would like to package Jellyfin as a proper RPM-format package for users of Fedora.

**Comment by EraYaN** [comment]
Alright, you need to read my edit, and read the dotnet docs. And as far as I know there is an RPM? And there are deb packages as well? I don't think there is a snap even (although that might be a good idea).

https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd

That means there are no deps on any runtime, it will only need the base deps that dotnet needs. (icu and the like)

**Comment by mooninite** [comment]
Thanks for the replies, but I don't think you understand what I am trying to accomplish. SDCs are basically like static builds in the C world. Static builds are against the Fedora packaging guidelines and for good reasons. The RPM spec offered here also violates Fedora guidelines, but I will make an effort to share any updates with a PR.

**Comment by EraYaN** [comment]
Anyway, since we are slowly moving to asp.net core, mono is just not on the table

**Comment by LogicalPhallacy** [comment]
Jellyfin is in dotnet core to support your use case. There is nothing stopping you from building in self contained net core which would allow you to package however you'd like for just about any *nix.
The build instructions are literally install dotnet core, pull the repo, run git submodule update with recurse and init, then run dotnet publish  with the rid of the platform you want and the self contained switch.

https://github.com/dotnet/cli/issues/6043 this issue tracks if you want to use mono to run net core and not run self contained

**Comment by joshuaboniface** [comment]
>The RPM spec offered here also violates Fedora guidelines

Could you please offer specifics? The RPM specs were contributed by @Wuerfelbecher

The build process creates a selfcontained binary on all Linux versions. No runtime is required. Can you confirm why that is not an acceptable solution?

The dotnet core conversion was done by another user months before JF was started, because dotnet is superior to mono in multiple ways. We built off his work to create the first JF release. Going back to Mono is not on the table in any form nor should it since an official .NET for Linux is now provided by Microsoft (I.e. dotnet core).

**Comment by JustAMan** [comment]
@mooninite btw why do you say that netcore is not buildable from source? I believe it's published under MIT.

**Comment by mooninite** [comment]
@JustAMan, .NET is a complicated beast. This isn't a license issue. To Windows users or people unaware it may look simple, easy-to-use, and friendly to develop on. However, for Linux folks it isn't easy. Microsoft provides dotnet as a binary blob and building it from source is complicated. It requires using binaries to bootstrap. Typical compilers like llvm or gcc bootstrap themselves from source code and it's easy to get those packaged and updated in Linux distributions.

Fedora requires all software be compiled from source and be able to reproduce the binaries from source. This provides a benefit that is not well appreciated to end-users, but it prevents Mono or dotnet from entering the Fedora distribution.

A side note: Mono became this same, complicated mess at version 5.0 when they added support for msbuild and roslyn that is borrowed from dotnet. MSBuild itself must be bootstrapped!

There isn't all bad news though! Mono 5.18 is very close to entering Fedora (currently version 4.8). There's work to bootstrap using monolite (binaries! :( ) and use the csc compiler instead of msbuild / roslyn.

The dotnet package set is also being actively worked on by Red Hat employees with dotnet 2.2 available on a 'copr' (similar to a Ubuntu PPA): https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/ However, it has been a few years since I've poked my head in to see how their work is progressing towards entering Fedora proper.

I hope this helped!

**Comment by hawken93** [comment]
To me, it sounds like it's time to put to the test how open this dotnet stuff really is :) if it is open it should be possible to build it from source and package it properly. This would also pave way for inclusion in official debian repos etc

**Comment by Bond-009** [comment]
Looks simple enough https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md#Environment

**Comment by EraYaN** [comment]
And then I suppose you might need this for the runtime as well: https://github.com/dotnet/cli/blob/master/Documentation/project-docs/developer-guide.md

**Comment by JustAMan** [comment]
We might consider re-opening this one, and extracting things to make a build script which works in  Debian, then re-use same script in our `Dockerfile`.

**Comment by lbeltrame** [comment]
OTOH, trying to build it without Docker is getting increasingly difficult. I had to reuse part of what was written in the spec files to be able to build something workable.

**Comment by jobhh** [comment]
> The `docker-build.sh` script in each target is already exactly that. It is what gets run inside the Container.

I haven't fully read up on the topic, I just stumbeled on this issue while searching for a Synology package. Maybe @chickenandpork could clarify, if you have the time. Is the `docker-build.sh` enough to build outside a Docker container, and creating a Synology package, as described in #2328?

**Comment by joshuaboniface** [comment]
>We might consider re-opening this one, and extracting things to make a build script which works in Debian, then re-use same script in our Dockerfile.

This was done as part of the Azure build conversion. The scripts "deployment/build.$1.$2", where $1 is the platform (e.g. debian) and $2 is the architecture perform builds in a native environment. They can be run directly on a local machine assuming you have all the deps installed. The `deployment/Dockerfile.$1.$2` Dockerfiles build standardized environments in which to run this script but are technically optional.
