### ISSUE TITLE
Unix socket permissions

### ISSUE THREAD

**Issue by army1349** [jellyfin/jellyfin#5311]
Listening on Unix socket is great feature, but without ability to specify permissions on that socket it is quite unusable for common setup.
I hope this qualifies as bug.

**Comment by cvium** [comment]
I don't see any cross platform way of doing this from C# unfortunately.

**Comment by army1349** [comment]
Current implementation is not cross-platform anyway, so maybe Mono.Posix.NETStandard could be used?

**Comment by cvium** [comment]
Current implementation uses standard ASP.NET libs and Windows 10 actually supports unix sockets. I'm not sure how well supported it is yet though, which is why we only enable it for macOS and Linux, but it is built-in.

**Comment by army1349** [comment]
I know about Windows support and I agree permissions would require different approach for it.
But that does not seem like a big mess.

**Comment by cvium** [comment]
Well, if you have any examples of it being neat and simple, then please share. I do not currently see any way of doing this without P/Invoke on chmod or similar.

**Comment by kevincox** [comment]
Right now this can kinda be done with `UMask` but that affects all things that Jellyfin creates and doesn't allow per-group permissions which is my use case (so that the reverse proxy can connect and nothing else). It is also hard to do this on Jellyfin's side because in order to change the group of a socket it may need to belong to that group which isn't always ideal (depending on system settings). For example you want to give the socket to `http` but don't want Jellyfin to have access to all sockets on the system.

A POSIX limited approach which is really full featured is inetd/systemd style socket passing. In this setup a (possibly privledged) process starts Jellyfin with the desired socket in it's environment and Jellyfin just uses it. Not caring where it lives. This provides full features because the creator is responsible for permissions, location and similar.

This also opens up other benefits such as allowing no-downtime restarts (as the socket will queue up connections) as well as lazy-activation including possibly shutting down Jellyfin when idle for a period of time. (Maybe not ideal due to Jellyfin's slow startup time but if resource saving is important it could be nice.

**Comment by kevincox** [comment]
go away
