### ISSUE TITLE
Two different playbacks simultaneously ? 

### ISSUE THREAD

**Issue by pirona** [jellyfin/jellyfin#5330]
I don't know for sure if this is a real issue or not, so apologies in advance.

When I start any playback, and then log out and login with a different user, I'm getting the playback started in the previous user 
session.

I would like to know for sure if two users can playback two different files simultaneously.

Not  sure if anything below is relevant, but I'm sharing anyway, for the sake of following your procedures at least.

Congrats on the good work by the way, I'm a big fan of your solution.

**Server System (please complete the following information):**
 - OS: Debian 10
 - Jellyfin Version: last version to date
 - Hardware settings & device: simple proxmox VM with minimum requirements
 - Reverse proxy: none
 - Other hardware notes:  Media mounted in CIFS/SMB share
 
**Client System (please complete the following information):**
Any client : web interface or android app or ps4 web browser

**Comment by ikomhoog** [comment]
It should work with multiple video's, even on the same account.
I use jellyfin to host for family and friends, and lately i have been using the syncplay feature with 1 guest account i gave to multiple friends.
This works fine, even if the guest accounts are playing different files.

"Jellyfin Version: last version to date" please note the version since the branch you are using differs in which version is the latest
Are you using latest (10.6.4), stable-rc (10.7.0-RC4) or unstable (10.8.0)?

Are the users in a syncplay group?, if so there is a current feature with a bug:
if you disconnect while in a syncplay group you will automatically rejoin and start playing the video.
But this also means if you logout without leaving the group that it rejoins you to the video and you need to restart jellyfin to get out of it.


"When I start any playback, and then log out and login with a different user, I'm getting the playback started in the previous user
session."
can you explain this in more detail?
Because when I try to reproduce it I follow these steps and already break your explanation:
1. start watching any video on my account
2. click back (which stops playback so it already breaks what you said)
3. click the account icon
4. click logout
5. login with a different user
6. nothing happens as I had to stop playback in order to logout

Do the logs provide any errors at the time of logout/login?
