### ISSUE TITLE
Support ffmpeg 4.1

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#555]
Currently it's known that `ffmpeg` other than 4.0 causes problems (see #260 and others).
We should eventually update the commands and support more up-to-date `ffmpeg`.

**Comment by nvllsvm** [comment]
Requring ffmpeg 4.1 would break many installation. Jellyfin should support both unless overly difficult.

**Comment by sparky8251** [comment]
Well, #415 requires 4.1 so no matter what, I'd say we should consider it.

**Comment by Bond-009** [comment]
@nvllsvm we need to support it, not require it.

**Comment by nvllsvm** [comment]
@sparky8251 good point, though I'd still hate to break distributions that don't yet have ffmpeg 4.1.

**Comment by JustAMan** [comment]
Aren't we planning to ship our own build? Otherwise we're in a hellish ride of trying to support changing CLI interface based on `ffmpeg` version...

**Comment by sparky8251** [comment]
Hence the reason both Plex and Emby have bundled their own FFMPEG versions for sooo long.

I agree "support not require" is a nice goal, but each version we support will require version specific tweaks and prevent some users from using some features.

I'm not sure that it's a worthwhile goal. Pulling in FFMPEG or building our own like we do for docker is better.

**Comment by Pilo11** [comment]
The current used static build in the Dockerfile works fine for me, thanks to nvllsvm for the good work. Only my VAAPI transcoding won't work with it. I tried a ffmpeg command with VAAPI device on baremetal linux and it worked with installed ffmpeg version 4.1. The static ffmpeg version 4.0 did not work in Docker. So I thought, maybe it is because I failed configuring the Docker<->VAAPI device relation.
So I decided to extract the static ffmpeg on the baremetal linux and boom, the same problem "No VA display found for device: /dev/dri/renderD128". I think the static ffmpeg build was not compiled with "--enable-vaapi" or something like that.
The static 4.1 build from John Van Sickle has the same problem... So this could not be a final solution. 
So we really should ship our own build...

**Comment by BobOkisama** [comment]
For grins, try pointing the transcoder to your personal version of 4.1. Add - - device /dev/dri/renderD128:/dev/dri/renderD128 or whatever to your docker run and see if it works.

I contacted van and he said it is not possible to bake in nvenc/nvdec and vaapi into a static build, so we certainly have to build our own.

**Comment by ctlaltdefeat** [comment]
What is the current status, given one of the referenced PRs seems to fix the reported issue (#260)?

**Comment by VoodooZ** [comment]
I was able to build my own static ffmpeg 4.1 with nvdec/nvenc using the script at https://github.com/ilyaevseev/ffmpeg-build. 
Hope this helps

**Comment by Lyle-Tafoya** [comment]
Any chance of Jellyfin ever shipping with it's own version of ffmpeg? This is what Plex does. I don't like having to recompile a custom version of ffmpeg that is separate from my system version every time I update ffmpeg's dependencies on my system.

**Comment by anthonylavado** [comment]
@lyle-tafoya It is a long term goal, but we have been prioritizing the server and client work first.

**Comment by z3ntu** [comment]
So ffmpeg 4.2 is supported now as well?

**Comment by barolo** [comment]
> So ffmpeg 4.2 is supported now as well?

At least with Kodi I can confirm that ffmpeg 4.2+ now works, feels snappier too

**Comment by anthonylavado** [comment]
Yes, in the nightlies, 4.0.x-4.2.x is supported. This is part of the next release, 10.4.
