### ISSUE TITLE
[Bug with fix] Lost ability to connect to chromecast

### ISSUE THREAD

**Issue by Typhonragewind** [jellyfin/jellyfin#5577]
**Describe the bug**
Not able to cast to chromecast via android app.

**System (please complete the following information):**
 - OS: Ubuntu and Android 11
 - Virtualization: Docker
 - Clients: Android and Browser
 - Browser: Firefox 72
 - Jellyfin Version: 10.7.0
 - Playback: Irrelevant
 - Installed Plugins: LDAP
 - Reverse Proxy: nginx
 - Base URL: jellyfin.example.com
 - Networking: Bridge
 - Storage: CIFS

**To Reproduce**
I was able to fully use chromecast from the android app until one day it suddenly stopped showing the option. I tried restarting jellyfin, checking the logs on the server, disabling features, temporarily disabling pihole, etc.
Phone could still access chromecast in other apps. Attempted casting from my tablet and it worked no problem, but still nothing on my phone.

I fixed it by reinstalling the phone app.

**Logs**
Nothing to report unfortunately.

**Comment by ikomhoog** [comment]
First, I think this should be moved to the Jellyfin-android repository, since the browser versions worked fine and it is app related.
But ill let the more experienced users be the judge of that.

I had this yesterday, a simple phone restart fixed it for me.
I should have tried force stopping the app from settings first actually, to see if that fixed it.

These things also happen for youtube and Netflix sometimes when changing your network.
For those, simply closing and reopening the app fixes it, but maybe the jellyfin app was still running in the background.

> I tried restarting jellyfin

did you only press the square and then swipe the app away?, or did you actually stop the app via the settings menu?
Apps do things in the background even without the app being open, to really close the app you need to close it using settings -> apps -> Force stop.
The force stop button only works while the app is running, which for jellyfin is also the case when it is closed.

For more ideas on how to reproduce:
I was changing wifi networks around and such, so the Chromecast had to connect to a different network.
chances are that I had my app open at the time, which is what cause these issues for youtube and netflix.
I will test this further, to see if it is a background process issue.

**Comment by Typhonragewind** [comment]
> 
> 
> First, I think this should be moved to the Jellyfin-android repository, since the browser versions worked fine and it is app related.
> But ill let the more experienced users be the judge of that.

Good point, i should have done that.

> I had this yesterday, a simple phone restart fixed it for me.
> I should have tried force stopping the app from settings first actually, to see if that fixed it.
> 
> These things also happen for youtube and Netflix sometimes when changing your network.
> For those, simply closing and reopening the app fixes it, but maybe the jellyfin app was still running in the background.
> 
> > I tried restarting jellyfin
> 
> did you only press the square and then swipe the app away?, or did you actually stop the app via the settings menu?
> Apps do things in the background even without the app being open, to really close the app you need to close it using settings -> apps -> Force stop.
> The force stop button only works while the app is running, which for jellyfin is also the case when it is closed.

That makes sense, but i was sleepy and didn't think that far. In the morning i took the nuclear approach and reinstalled the app. If it happens again i'll try that and report back.

> For more ideas on how to reproduce:
> I was changing wifi networks around and such, so the Chromecast had to connect to a different network.
> chances are that I had my app open at the time, which is what cause these issues for youtube and netflix.
> I will test this further, to see if it is a background process issue.

I haven't messed with my network in months, so i think it's more likely to be a background process issue.
