### ISSUE TITLE
Jellyfin doesn't display shows

### ISSUE THREAD

**Issue by Whisper40** [jellyfin/jellyfin#5599]
**Describe the bug**

Jellyfin doesn't display shows that i have downloaded in the shows tab.
**System (please complete the following information):**
 - Virtualization: Docker, your image
Serveur : 8675874c0ccb
Version : 10.7.1
Système d'Exploitation: Linux
Architecture : X64

**To Reproduce**
A simple docker-compose with Jellyfin, mount your data into the container, add some torrents of series.

**Expected behavior**
It shoulds shows my shows

**Logs**
No one error, all is 200.

**Screenshots**

![image](https://user-images.githubusercontent.com/30440458/112055387-1115f780-8b57-11eb-8db1-28278e793581.png)
**Additional context**
Fresh install
Tested with 10.7.0 and 10.7.1
I can see my content in "Suggestions".
I don't have any poster on shows.
I already tried many times to refresh all, but no changes.

**Comment by ikomhoog** [comment]
>add some torrents of series

Jellyfin doesn't download torrents, Jellyfin just plays video files.
You need to download the torrents yourself.

**Comment by Whisper40** [comment]
I never said that Jellyfin download torrents.. 
I said jellyfin doesn't display shows THAT I HAVE DOWNLOADED.

The add some torrents of series is just for saying add data in order that jellyfin displays shows..

**Comment by ikomhoog** [comment]
Sorry, the wording just made it look like you had a folder of .torrent files instead of the videos.
Can you play the video's from the suggestions tab?

**Comment by Whisper40** [comment]
Yes without problem

**Comment by ikomhoog** [comment]
the only way I can get this is by setting the filter to something that I don't have like 4k movies:
![image](https://user-images.githubusercontent.com/9083045/112343436-6a9b3500-8cc3-11eb-847e-7be9284832b3.png)
When I do that I get an empty movie screen but suggestions show up fine.

But, filters should be reset when opening a library from the homepage(or at least it does for me) so that shouldn't be the problem.
Can you check the filters just to be sure everything is unchecked?

can you also try switching to another view mode?
![image](https://user-images.githubusercontent.com/9083045/112343846-ce256280-8cc3-11eb-8d41-5796f0f8737d.png)

**Comment by Whisper40** [comment]
I tried it without success, i just tested the https://hub.docker.com/r/linuxserver/jellyfin and it's working without problem on this one..

**Comment by ikomhoog** [comment]
To my knowledge(might be very wrong here) linuxserver doesn't really change things about the docker images.
So it would be weird to not have the issue there if you have it here.

Can you try a clean install of the original jellyfin docker image?, just set a different config directory
Something might have been corrupted with your current install and that caused this issue.

Have you already tried to restore a backup of the config folder from before this issue appeared?

You haven't posted any info on when this happened or what might cause this, so it's difficult to pinpoint where it went wrong.

**Comment by Whisper40** [comment]
Finally the problem appears also with their image.
The posters do not appear
The content is however readable
The series do not appear, but appear in the suggestions or episodes tab...

Gif to explain what's wrong (linuxserver image)
![jellyfinbug](https://user-images.githubusercontent.com/30440458/112541390-a01f4b80-8db3-11eb-8213-b6acaa82dcc4.gif)

It's a fresh install, so all is news. Working without problem with PLEX, same rights.

**Comment by Whisper40** [comment]
Just tester the official immage, with a fresh config directory, same data. I have exactly the same behaviour..

Can you try it on your side too with a fresh docker compose ?

**Comment by Whisper40** [comment]
I just tested the unstable tag, same thing

**Comment by ikomhoog** [comment]
Okay, I found the problem.

Jellyfin doesnt like series/movies to be in one folder:
![image](https://user-images.githubusercontent.com/9083045/112603926-e907ec00-8e15-11eb-9392-8ef2ceb45c82.png)

Jellyfin wants all things organized:
![image](https://user-images.githubusercontent.com/9083045/112604068-0dfc5f00-8e16-11eb-974d-becc7068d24e.png)
![image](https://user-images.githubusercontent.com/9083045/112604090-15236d00-8e16-11eb-9061-d54da3522186.png)
![image](https://user-images.githubusercontent.com/9083045/112604115-1b194e00-8e16-11eb-9f8c-4f8d69c222e3.png)

Thanks to your gif I noticed that you probably downloaded those videos yourself since they were not renamed.
You can automate this downloading, ordering and renaming with sonarr and radarr for series and movies respectively.
They will automatically create these folder structures so you don't have to worry about it.
And since those are used everywhere in this community there are tons of guides for setting them up.

**Comment by Whisper40** [comment]
Yes i have sonarr and radarr, but for this example i was not using it.
Plex doesn't have any problem for searching the content.
I'm sure that the behaviour that i'm showing should be the default one.
It's the jellyfin job to find my content and to identify it :) . I really think that should be improved

**Comment by ikomhoog** [comment]
The need for organized folder structures is because this is a fork of emby which also has this.
Even Plex specifies that you should organize your media this way: https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/
I also wouldn't want my 1500+ videos library all in 1 big folder

With an organized library, it never failed to identify my files(after I stopped radarr and sonarr from doing it wrong).


Can you confirm that it does work with an organized library?
And if so, please close this issue to remove clutter from the issue page

**Comment by Whisper40** [comment]
Thanks for your solution, it works.
I will close this issue, but i will open a feature request, because i think it's a basic thing that should be include.

It is not my use case, but for people that are alone on their server, it can be a simple thing if they don't use automation.
