### ISSUE TITLE
[Feature Request] Change Ports

### ISSUE THREAD

**Issue by drakus72** [jellyfin/jellyfin#56]
The more I think about it more I think/feel the ports should be change from the default 8096 & 8920 to something else instead of the user having to do it. This is a common practice amongst 99% of forks of other projects.

Maybe change them to 9880 & 9943, just an idea.

**Comment by brianjmurrell** [comment]
I think I disagree.  I want to be able to drop this fork in place of Emby and not have to announce to everyone that uses it the new port numbers.

I guess you did say "change the default" so I can't be terribly opposed.  Just not sure I see why.

**Comment by Mengine** [comment]
I do agree, but maybe make this request dependent on the completion of some of the native clients? Would cause less hassle for people in the migration phase.

**Comment by drakus72** [comment]
I understand the drop in replacement like mysql/mariadb, didn't think about it that far. So I guess I have to agree to disagree with myself LOL.

**Comment by JustAMan** [comment]
I don't think I see a point - they are not meant to co-exist by default...

**Comment by joshuaboniface** [comment]
This is a hard no. The ports need to remain compatible for drop-ins as @brianjmurrell mentions - otherwise we're asking _everyone_ to change ports when they upgrade, rather than just the few who might want to run both. And as @JustAMan says you should not have both `emby-server` and `jellyfin` running at the same time anyways. The Debian package makes that explicit (via a `Conflicts` entry) but other build types do not.
