### ISSUE TITLE
Changing local port

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#568]
Changing the local ports just goes back to default after restating.

---

Copying here the report by @PrplHaz4:
I can confirm I'm seeing the same behavior.  Running on windows with a portable installation, JF install and data/config/cache in a separate directories off of C:\ root.

**Description**
Updating the port in the web interface doesn't have any effect on the underlying service.

**To Repro**
Start Server, navigate to http://localhost:8096/web/index.html#!/dashboardhosting.html, change Public HTTP Port # to 8097, Save, Restart JF Server, Navigate to http://localhost:8097 - Can't connect

**Expected**
JF is accessible on port 8097 (either immediately, or after restarting JF Server

**System**
Windows 10
Firefox
JF 10.2.2

**Comment by hawken93** [comment]
before we get into it, what is the target port? If it's a privileged port, jellyfin probably can't bind to it.

**Comment by screwfaze** [comment]
Sorry I'm on Server 2012 and just trying different port than the default one as I am still running emby on that one. Any port will do. I will try to edit the conf8g file as someone has suggested on reddit just thought I should let you guys know.

**Comment by hawken93** [comment]
I was able to change port in the GUI and verify that it was written to the config file..

In case it is a permission problem with writing to settings, is jellyfin able to change any system settings at all?

In case you are binding to low ports, such as 80: I don't know about windows, but on linux normal users such as the jellyfin user are not allowed to bind on low ports, instead what is commonly done is to put a reverse proxy (nginx, apache, ...) in front on the right ports and point it at jellyfin :)

**Comment by bobberb** [comment]
Which config file. What did you type? Specifics don't hurt us.

**Comment by bobberb** [comment]
"you should probably stop the service first"

...are you here for help or are you giving it out, you've lost me now.

**Comment by screwfaze** [comment]
Mate I am reporting a problem so it can be investigated what is your deal?

**Comment by bobberb** [comment]
I want to help you! I may have missed something over email.  
As you can see, you must open the file system.xml and edit the port there. 
If JF changes it back to default, have you tried setting it to read-only?

**Comment by screwfaze** [comment]
Sorry for confusion it is not changing back when I edit the file only when I do it from the web console. So it's working fine now thanks for the help I was only trying to report it so you know the problem exists.

**Comment by bobberb** [comment]
For best results, it might be prudent to close this issue and reopen per the format:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Please paste any log errors.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.0.1]

**Additional context**
Add any other context about the problem here.

**Comment by PrplHaz4** [comment]
I can confirm I'm seeing the same behavior.

**Description**
Updating the port in the web interface doesn't have any effect on the underlying service.

**To Repro**
Start Server, navigate to http://localhost:8096/web/index.html#!/dashboardhosting.html, change Public HTTP Port # to 8097, Save, Restart JF Server, Navigate to http://localhost:8097 - Can't connect

**Expected**
JF is accessible on port 8097 (either immediately, or after restarting JF Server

**System**
Windows 10
Firefox
JF 10.2.2

**Comment by anthonylavado** [comment]
Hrm. I just tried this in my Debian install and it seemed to work. Will try with a Windows install (though I’m using 8.1).

**Comment by PrplHaz4** [comment]
@anthonylavado I think I got to the bottom of this one - the port is not saving because the default for secure connections is "Preferred but not required", which is invalid without having an SSL cert loaded.  This prevents the whole form from not being saved.

Changing "Secure connection mode" to Disabled allows the form to be saved, and Jellyfin to prompt you to restart the server.

If the default is "Preferred but not required", you should probably be allowed to save changes to the https port without having an SSL cert loaded.

**Comment by alkissack** [comment]
re: "Changing "Secure connection mode" to Disabled allows the form to be saved, and Jellyfin to prompt you to restart the server." this allowed me to move to 8097  - but I seem to have lost access to EMby on 8096

**Comment by sergiotapia-papa** [comment]
To change the port you can update the file in: `C:\ProgramData\Jellyfin\Server\config` - system.xml

**Comment by EddyMerkxs** [comment]
> what do i change in system.xml to modify the port from 8096 to 9096?

For future reference I changed the network.xml file instead and it seemed to work.

**Comment by kariudo** [comment]
> > what do i change in system.xml to modify the port from 8096 to 9096?
> 
> For future reference I changed the network.xml file instead and it seemed to work.

Thanks, this comment saved me a headache. 

It would be really nice if this could be set by an environment variable like the published URL for the purpose of docker. This caused me some annoyance as is when there was a conflict for the port with a project called Music Assistant, when the default docker guidance is for host mode in order to support DLNA.
