### ISSUE TITLE
Filtering with large amount of tags

### ISSUE THREAD

**Issue by gottsman** [jellyfin/jellyfin#6142]
**Describe the bug**
A lot of my movies have automatically imported tags which I kinda like. When I try to filter on tags, its not possible to filter on all tags do to the number of tags currently used.

**System:**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chromium
 - Jellyfin Version: 10.7.5
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: N/A
 - Storage: N/A

**To Reproduce**

1. Within the movie library, click the filter icon
2. Click on tags
3. Scroll down to end
4. Not able to see all tags. For me its in the letter "b"s, but I imagine its a fixed number of tags shown.

**Expected behavior**

Able to see all tags easily

**Server Logs**

N/A

**FFmpeg Logs**

N/A

**Browser Console Logs**

N/A

**Screenshots**

<img width="282" alt="tags" src="https://user-images.githubusercontent.com/6173136/120583157-b07b2480-c3fb-11eb-9599-eab4dcb09a1b.png">

**Additional context**

None

**Comment by gottsman** [comment]
Found it as a feature request.... Probably where the ask belongs....

https://features.jellyfin.org/posts/635/search-by-tag

**Comment by nearcatch** [comment]
> 
> 
> Found it as a feature request.... Probably where the ask belongs....
> 
> [features.jellyfin.org/posts/635/search-by-tag](https://features.jellyfin.org/posts/635/search-by-tag)

I think this should be reopened. The feature you linked is separate from what this issue is saying.

Feature: Allow searching of tags

This issue: The currently implemented tag filter does not show all tags.

It's legitimately a bug. There's no way the accepted behavior should be that the tag filter only shows 50 tags when Jellyfin allows auto-importing tags, which will balloon any medium-sized library beyond that.
