### ISSUE TITLE
[bug] Unnecessarily transcoding vp9 in Firefox

### ISSUE THREAD

**Issue by cory171185** [jellyfin/jellyfin#6149]
**Describe the bug**
Jellyfin on web client is transcoding during playback of vp9 video when vp9 is supported by Firefox and my computer. 

**System (please complete the following information):**
 - OS: Ubuntu Server 20.04.2
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 88.0.1 (on Ubuntu 21.04)
 - Jellyfin Version: 10.7.5
 - Playback: Transcode
 - Installed Plugins: none? manually installed none, default plugins (AudioDB, MusicBrainz, OMDb)
 - Reverse Proxy: caddy
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Play vp9 video on firefox on ubuntu. Open playback information.

**Expected behavior**
Transcoding only audio, or nothing (idk if aac is supported on firefox)

**Server Logs**

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

![Screenshot from 2021-06-04 03-52-16 censored](https://user-images.githubusercontent.com/45303123/120777604-14304b00-c4eb-11eb-8fd8-268b1e5dc489.png)

**Additional context**
Video was downloaded with youtube-dl, not sure how it handles metadata if that is relevant? Playback was also occasionally dropping frames, I assume transcoding may have something to do with it.

If you need me to add server logs, ffmpeg logs, or browser console logs, I am willing, but do not know how.

**Comment by cory171185** [comment]
I just checked, it is also happening on Chrome 91 on Ubuntu 21.04.

![Screenshot from 2021-06-04 04-19-42 censored](https://user-images.githubusercontent.com/45303123/120779556-c87ea100-c4ec-11eb-90a5-665e8c923ef9.png)

**Comment by cory171185** [comment]
Also for context, it plays back fine without transcoding in the Jellyfin Media Player desktop app.

![Screenshot from 2021-06-04 04-26-37](https://user-images.githubusercontent.com/45303123/120779809-11cef080-c4ed-11eb-8ae4-e8152737a59c.png)

**Comment by cory171185** [comment]
Alright, after more investigation, I found another video in my library with the combination of vp9 and aac, and realized that these videos were actually in an mkv container format, and not webm as the "playback info" reported during playback. I'm not sure if this is a bug anymore, or where or what. Attaching screenshot of media info. 

![Screenshot from 2021-06-04 04-39-07](https://user-images.githubusercontent.com/45303123/120781912-1e544880-c4ef-11eb-83d6-8fc8a1fe0f96.png)

Before opening this issue, I searched through the issues and found something about 1.7.5 requiring you to set a setting for playing back video with conversion but not transcoding, so I checked, and I had already enabled that for my user. To make sure, I disabled it, saved, and re-enabled it. I also just tried to restart the server in case there was any funkiness there, but it is still happening.

![Screenshot from 2021-06-04 04-43-53](https://user-images.githubusercontent.com/45303123/120782803-fd402780-c4ef-11eb-87de-5fb3dd56b56c.png)

**Comment by cory171185** [comment]
After testing more videos, this issue does not occur if the container is webm, or if the combination of codecs is different (checked an mkv with av1/opus and it was able to direct play on both firefox and chrome). 

I also just found this page https://jellyfin.org/docs/general/clients/codec-support.html which makes me even more confused, as Firefox was able to direct play mkv av1/opus and this issue is reproducible in both Chrome and Firefox. Anyway, next I will try to find another video that should be able to be remuxed/direct streamed, and test if it works in Chrome/Firefox.

**Comment by cory171185** [comment]
I found a video which direct streams fine. It is mkv h264/opus and direct streams on both Firefox and Chrome. Attaching media info and playback data.

![Screenshot from 2021-06-04 05-07-15](https://user-images.githubusercontent.com/45303123/120785964-4d6cb900-c4f3-11eb-867b-150f226337e5.png)

![Screenshot from 2021-06-04 05-07-46](https://user-images.githubusercontent.com/45303123/120786001-552c5d80-c4f3-11eb-80a1-d6406fce6d7e.png)
Firefox playback data. Direct streaming

![Screenshot from 2021-06-04 05-10-35](https://user-images.githubusercontent.com/45303123/120786007-56f62100-c4f3-11eb-9067-a1b863738f21.png)
Chrome playback data. Direct streaming

I don't know where to go from here. Sorry if I'm spamming a thread, or if the issue is obvious or already known. Thanks for any help

**Comment by Artiume** [comment]
the issue is vp9 isn't a supported video type for ts/fmp4 files which is used when transcoding occurs. so if you need to change any aspect, be it the mkv container or the audio stream, it has to use ts/fmp4, thus it has to convert the video as well.

**Comment by GodTamIt** [comment]
> so if you need to change any aspect, be it the mkv container or the audio stream, it has to use ts/fmp4, thus it has to convert the video as well

@Artiume I don't believe this is true. I just went stepping through the actual code path there with the debugger and one of the transcoding profiles available for streaming is actually webm/http (vorbis, vpx). The selection logic just happens to select the ts/hls, since it is the first matching item in the array. You can see some of my tweaked code I tested with in #6450 that actually works around this.

**Comment by cory171185** [comment]
That makes sense for why it needs to transcode video when it does transcode, but now I wonder why it is transcoding at all?

The thread is kind of spaghetti since I added new info in new comments as I was discovering it, so I'll put it all here:
vp9/aac/mkv - transcodes, why?
vp9/opus/webm - direct play
av1/opus/mkv - direct play
h264/opus/mkv - direct stream, also why?
These are the same for both Firefox and Chrome.

New ones I just tested:
h264/aac/mp4 - direct play

So it would appear that Firefox and Chrome can direct play mkv and vp9 and aac, yet Jellyfin will transcode on vp9/aac/mkv. Interestingly, it will direct stream on h264/opus/mkv even though it can direct play all of these as well it seems.

My main question now is why does vp9/aac/mkv not direct play, and also why doesn't h264/opus/mkv? Does this have something to do with the codecs/container formats, or with the way Jellyfin/Jellyfin Web streams things specifically, or is it an artifact of the codec selection code or profiles? If I'm being stupid don't be afraid to tell me so, I just went hunting through my library for a vp9/aac/webm video for 15 minutes before remembering that webm can only hold vp9/opus :facepalm:

**Comment by GodTamIt** [comment]
So for some background to my answers, here are the "supported" video `DirectPlayProfile`s that is reported for the browsers:
```
DirectPlayProfile {
  AudioCodec: "vorbis,opus"
  Container: "webm"
  Type: Video
  VideoCodec: "vp8,vp9,av1"
}
DirectPlayProfile {
  AudioCodec: "aac,mp3,opus,flac,vorbis"
  Container: "mp4,m4v"
  Type: Video
  VideoCodec: "h264,vp8,vp9,av1"
}
```

>My main question now is why does vp9/aac/mkv not direct play

Neither Firefox nor Chrome fully support mkv (Matroska) as a container -- only webm, which is a subset of mkv (see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=999580&q=matroska&can=1) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1422891)). The logic [here](https://github.com/jellyfin/jellyfin/blob/eeb5d4bd1e63ad89f599fd52a79b3c80ed8f8ad1/MediaBrowser.Model/Dlna/StreamBuilder.cs#L1902) and [here](https://github.com/jellyfin/jellyfin/blob/eeb5d4bd1e63ad89f599fd52a79b3c80ed8f8ad1/MediaBrowser.Model/Dlna/StreamBuilder.cs#L731) in jellyfin just says, "we'll transcode to the first video `TranscodeProfile` we stumble upon."

>also why doesn't h264/opus/mkv

This, I'm not entirely sure why it's not transcoding actually, given the logic linked above. Again, it isn't direct playing because of the lack of mkv support in browsers. If someone knows where the code is to determine when to direct stream, please let me know.

Also, for posterity, the reason `av1/opus/mkv` **does** DirectPlay is technically the logic (and the browser) denotes that mkv as if it were also a webm file (subset, remember?). The `MediaSourceInfo` actually articulates the container as `"mkv,webm"`.

I'm happy to write a PR to fix some of this but I'm still getting adjusted with the codebase.

**Comment by sourpatched** [comment]
AV1 is supported direct play with Google TV and FireFox but Jellyfin always trancecodes the media

Title:720p AV1 SDR
Codec:AV1
Profile:Main
Level:5
Resolution:1280x720
Aspect ratio:16:9
Interlaced:No
Framerate:23.98
Bitrate1070 kbps
Video range:SDR
Pixel formatyuv420p
Ref frames1

The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 251fps

5.5 Mbps TS H264 AAC


Reason for transcoding:
VideoCodecNotSupported
AudioCodecNotSupported
