### ISSUE TITLE
Entire database suddenly gone

### ISSUE THREAD

**Issue by Miicker** [jellyfin/jellyfin#6202]
I started using Jellyfin a few weeks back. I've been using Plex before I was using Jellyfin, but I moved to Jellyfin because there were some things I did not like about Plex.

Everything was fine for a few weeks. Indexing my entire library took a few days, but after that I was able to watch episodes and movies without any problems. The last time I watched anything was last Wednesday (it's now Saturday). Yesterday I wanted to watch something and I got an message that there was no connection to the server. I decided to restart Jellyfin (which I am running in Docker). No luck. Then I decided to restart the entire NAS.

After the NAS was back up and I launched the interface, it showed me the initial setup. Now I have to setup the entire thing again and specify my library and everything.

So I have basically two questions:
1. How can something like this happen all of the sudden?
2. Can I somehow revert this mess and go back to the situation of Wednesday?

Some information about my setup:
I am running Docker on a Synology NAS. I am using the official Jellyfin image. I am running dockupdater to keep my Dockers up-to-date.

Thanks in advance.

**Comment by nielsvanvelzen** [comment]
Did you create a Docker volume for your data?

**Comment by Miicker** [comment]
> Did you create a Docker volume for your data?

What do you mean? I've set up the docker container and it was working for a few weeks. I am also able to select the library again in the setup that is shown at this moment when I start Jellyfin.

**Comment by nielsvanvelzen** [comment]
You need to create a volume or mount for the Jellyfin data directory or it won't persist

**Comment by Miicker** [comment]
> You need to create a volume or mount for the Jellyfin data directory or it won't persist

Ok thanks. Is there any documentation on this or a tutorial on how I do this? Because I followed a instruction of setting up the Docker, but I can't remember something about this.

Ps. I don't know if its allowed here but based on your name I would say you're Dutch, so you can also reply in Dutch.

**Comment by nielsvanvelzen** [comment]
Our documentation is available at https://jellyfin.org/docs/general/administration/installing.html. It might be a bit technical at some points but our community made lots of tutorials etc. on YouTube, blogs and other places that might help you.

If I understand it correctly you didn't create a volume or mount for the Jellyfin data directory. This means that when Docker restarts it doesn't have that folder saved anymore and that's why the database was empty. This is not recoverable. If you need any help installing Jellyfin I suggest joining one of our chats (https://jellyfin.org/docs/general/getting-help.html). I can't personally help much more with installation instructions.
