### ISSUE TITLE
Scanning TV shows cannot penetrate the category folder

### ISSUE THREAD

**Issue by cgkings** [jellyfin/jellyfin#6220]
**Describe the bug**

My media library setting path：/home/TV
There are many classified folders under this path，such as /home/TV/JAPAN_TV , /home/TV/US_TV
jellyfin can't penetrate the category folder,Instead, the category folder is used as the TV show name to identify
![image](https://user-images.githubusercontent.com/58586625/123187896-a1a10280-d4cd-11eb-9a3a-948fc0baba8a.png)
![image](https://user-images.githubusercontent.com/58586625/123187913-ae255b00-d4cd-11eb-94e2-11a96e153595.png)

**System (please complete the following information):**
 - OS: Debian,10
 - Virtualization:KVM
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Server Logs**

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**

**Comment by MrTimscampi** [comment]
That is expected.  
Your folders needs to respect the naming conventions outlined here: https://jellyfin.org/docs/general/server/media/shows.html

**Comment by cgkings** [comment]
> 这是预期的。
> 您的文件夹需要遵守此处列出的命名约定：[https](https://jellyfin.org/docs/general/server/media/shows.html) : [//jellyfin.org/docs/general/server/media/shows.html](https://jellyfin.org/docs/general/server/media/shows.html)

Is there something wrong with my folder structure?
Media library folder
   ├──china tv
          ├──war tv
                ├── Series (2010)
                │   ├── Season 01
                │   │   ├── Episode S01E01-E02.mkv
   ├──japan tv
          ├── Series (2010)
          │   ├── Season 01
          │   │   ├── Episode S01E01-E02.mkv



│   │   ├── Episode S01E03.mkv
│   │   └── Episode S01E04.mkv
│   └── Season 02
│       ├── Episode S02E01.mkv
│       └── Episode S02E02.mkv

**Comment by cgkings** [comment]
I like jellyfin,However, the inability to scan through folders does cause a lot of trouble. Can you scan through folders like emby and browse by folder?
![image](https://user-images.githubusercontent.com/58586625/123364512-1a27c200-d5a7-11eb-848e-e6a90b78e03a.png)

**Comment by Artiume** [comment]
Map each Category folder, not the main folder.

do JAPAN_TV, US_TV, CHINA_TV

Not TV/JAPAN_TV , TV/US_TV, TV/CHINA_TV.



There is a folder view that you can enable: Dashboard > Libraries > Display > 'display a folder view'

**Comment by lsahnicne** [comment]
For over a decade i've ben sorting downloaded media in my file system by the year. So it looks like this:
.../tvshows/1999/tvshow1
.../tvshows/2000/tvshow2
.../tvshows/2001/tvshow3
etc.
It is very annoying to add each individual %year% folder instead of one common root folder and then remember to add new ones in case they are created later. I wish jellyfin was able to dig deeper into sub-folders.

> That is expected. Your folders needs to respect the naming conventions outlined here: https://jellyfin.org/docs/general/server/media/shows.html

To be fair, nowhere on that page it says that your file structure _needs_ to be just like what is shown. It only describes it as an "common" example.

**Comment by srcrist** [comment]
The need to adhere to the naming conventions in the Jellyfin documentation is an intentional design choice that various aspects of the server use to parse the media and its metadata. Closing this issue as it is not actually a bug.

The criticism of the wording of the necessity of following the convention is fair, and the documentation should be updated to reflect the necessity. You're welcome to open an issue on the documentation repository about it, or I'll try to fix it myself when I have a chance.
