### ISSUE TITLE
How do you completely turn off transcoding?

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#645]
How do you completely turn off transcoding?

**Comment by Ayrler** [comment]
As far as I know there is no general option to disable transcoding once and for all, however you can do this in your profile settings.  You should uncheck the following options:
- Alow audio playback that requires transcoding
- Allow video playback that requires transcoding
- Allow media downloading and syncing that requires transcoding

**Comment by surdu** [comment]
I don't manage to find these options :(

**Comment by anthonylavado** [comment]
@surdu

Hey there! :wave:
* Log in, and go to the dashboard
* In the menu on the left, click Users
* Find the user you want to change, and click the three dots on their name “…”
* Choose “Open”
* Now you should see these options under “Media Playback”

**Comment by surdu** [comment]
Got it! Thanks!

**Comment by LJPapenfort** [comment]
So I tried this too, but everytime I start a movie in firefox over the web interface jellyfin starts ffmpeg in the background and is eating up CPU cycles nonetheless.
Disabled all permissions concerning trancoding. Any idea why?

**Comment by JustAMan** [comment]
Please show a screenshot of user's settings and some relevant logs from your JF instance running the transcode.

**Comment by LJPapenfort** [comment]
Here is the relevant part of the log
[jellyfin.log](https://github.com/jellyfin/jellyfin/files/3889521/jellyfin.log)
So it hits the bitrate limit and transcodes anyway?
Btw, is there a way to increase this limit?

**Comment by JustAMan** [comment]
> So it hits the bitrate limit and transcodes anyway?

It looks so, yes. This is a bug I think.

As for increasing - I think there is an option somewhere in admin settings, try exploring around.

**Comment by hereisderek** [comment]
I would like the option to turn off transcoding completely globally instead of specific user based, to just similarly as a file server. I'm running on a raspberry pi among other services, and media service is just a nice add on.

**Comment by ksb749** [comment]
I agree, such a feature would be very nice to have, so you wont need to do many chnages on new users created, since transcoding as default is allowed - Im also using an Raspberry Pi 4, but my reason is to use a low poer server..

**Comment by azumukupoe** [comment]
how do I disable transcoding in DLNA?

**Comment by tbabik** [comment]
I've removed all access rights from the transcodes folder. This seems to work for me, but have yet to check how different clients will react.

**Comment by dmitche3** [comment]
Great about changing permissions on the transcodes folder.  Which folder is that? I've tried modifying the individual settups for the TVs in the system directory yet everytime Jellyfin restarts it overwrites the settings and there is no option or intelligence to not overwrite a newer file with an older one.

**Comment by tbabik** [comment]
That might be different for you. I'm using Jellyfin in Docker and provided a volume to store the config, but you should also have a config directory for your Jellyfin installation.

Should look something like this. The "transcodes" folder is within ../data and I've did a "chmod 000 transcodes" to remove all access. On a container start the entrypoint script will actually change the owner, but it does not modify the privileges set from the host.

![image](https://user-images.githubusercontent.com/47258245/196174195-aa1d3102-9f26-43cb-a96a-81b464604551.png)

**Comment by sebastianhaberey** [comment]
> So I tried this too, but everytime I start a movie in firefox over the web interface jellyfin starts ffmpeg in the background and is eating up CPU cycles nonetheless.

I'm having the same issue on Jellyfin 10.8.9. Number #3 of the settings mentioned above doesn't seem to exist in that version. I deactivated the other two and "Allow video playback that requires conversion without re-encoding" instead, but that just got me an error:

> This client isn't compatible with the media and the server isn't sending a compatible media format.

The transcode directory approach didn't work for me either. Made a docker bind to an empty directory on the host system, set permissions to 000, but the CPU still runs hot for about five minutes each time I start playback.

I'm not sure if it's me or if the above does not work for current versions any more, would be interested in other users' experience!

**Comment by zhongzx** [comment]
If the "direct play" cannot be enabled,  it seems that the Jeffyfin is much more inconvinient than Emby free version.

**Comment by Thorocaine** [comment]
Hi, [anthonylavado](https://github.com/anthonylavado)

>     * Log in, and go to the dashboard
> 
>     * In the menu on the left, click Users
> 
>     * Find the user you want to change, and click the three dots on their name “…”
> 
>     * Choose “Open”
> 
>     * Now you should see these options under “Media Playback”

I am trying this, but I am not finding the "Users" on the left of the dashboard?

**Comment by wisukind** [comment]
Hi !

First thanks everyone for bringing that great piece of software to the community !

I have the same issue; trying to disable transcoding completely for my LG TVs accessing jellyfin via DLNA. I'm jusing jellyfin 10.8.10
Disabling transcoding at user level as explained here doesn't work in my case. My TV will complain the format is not supported; although when accessing the file from a simple minidlna server it works like a charm. I want to switch from minidlna to jellyfin because minidlna has issues discoving new files; but my LG TVs don't need transcoding at all. They support all codecs & formats natively. 

I tried all other approaches like removing transcoding folder, enforcing h265 as a direct playback format in my DLNA profile, etc... but nothing works. Jellyfin keeps launching ffmpeg whenever I'm trying to access a file in x265. 

Any clue ?

Thanks !

Attached my user profiles.

![image](https://github.com/jellyfin/jellyfin/assets/48824957/70373ec2-1ca8-4f09-8703-09539193080c)

**Comment by Taldorus** [comment]
I tested this configuration with my smartphone and jellyfin version 10.8.10 and it worked fine, transcoding is disabled with this manipulation

first install vlc on your device (android, windows, ...)
go to profile > client settings > in the video player section
select "external player
I launched the video and checked the resource consumption on my server. For a single device, I was at 10% cpu, whereas before I was at 90%.

**Comment by C-Duv** [comment]
Jellyfin embeds it's own ffmpeg binary? Even in Debian releases?
Because if not you can't rename it as advised without breaking other applications.

**Comment by kitopopo** [comment]
> Hi !
> 
> First thanks everyone for bringing that great piece of software to the community !
> 
> I have the same issue; trying to disable transcoding completely for my LG TVs accessing jellyfin via DLNA. I'm using jellyfin 10.8.10
> Disabling transcoding at user level as explained here doesn't work in my case. My TV will complain the format is not supported; although when accessing the file from a simple minidlna server it works like a charm. I want to switch from minidlna to jellyfin because minidlna has issues discoving new files; but my LG TVs don't need transcoding at all. They support all codecs & formats natively. 
> 
> I tried all other approaches like removing transcoding folder, enforcing h265 as a direct playback format in my DLNA profile, etc... but nothing works. Jellyfin keeps launching ffmpeg whenever I'm trying to access a file in x265. 
> 
> Any clue ?
> 
> Thanks !
> 
> Attached my user profiles.
> 
> ![image](https://github.com/jellyfin/jellyfin/assets/48824957/70373ec2-1ca8-4f09-8703-09539193080c)
> 

I have the same issue! Some 4K movies in H.265 are giving me trouble. I have two LG 4K TVs, and Jellyfin detects that they cannot play the files directly because the video and audio are "not compatible" with the client. As a result, everything gets transcoded, making playback almost impossible because it constantly stutters.

The strange thing is that Plex manages to play everything directly on both TVs without any issues.

I can't find any option to force direct playback or completely disable transcoding. If I disable hardware transcoding, software transcoding kicks in, and it performs even worse—to the point where the files won’t even play.

I see you mentioned that your TVs fully support these codecs, just like mine. Were you able to find a solution to this problem?

Any help would be greatly appreciated. Thanks!
