### ISSUE TITLE
repeated tvg-id in m3u playlist will not show

### ISSUE THREAD

**Issue by SmokeyBR** [jellyfin/jellyfin#6527]
**Describe the bug**

m3u playlists (Live TV) if they have the same tvg-id only one channel will show, i have multiple channels with the same tvg-id but only one will shows.

**System (please complete the following information):**
 - OS: ubuntu 20.04
 - Virtualization: NO
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.7.7 stable
 - FFmpeg Version: 4.2.4-1ubuntu0.1
 - Playback: N/A
 - Hardware Acceleration: NO
 - Installed Plugins: N/A
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to Dashboard > LiveTV
2. Add m3u playlist with repeated tvg-id
3. jellyfin will scan only one channel

**Expected behavior**

To show the same guide (which is definied with the tvg-id tag) from the same source on multiple channels

**Comment by crobibero** [comment]
This doesn't sound like a bug to me, aren't channels identified using the `tvg-id` field?

**Comment by SmokeyBR** [comment]
well im not entirety sure how m3u works so it could not be a bug, however im comparison with kodi for example i am able to add multiple channels with the same tvg-id making possible to add very small EPG xml

in jellyfin i am making very large EPG xml list since it doesnt show channels with the same tvg-id

**Comment by alanmilinovic** [comment]
Is there any plan for this to be fixed? Usually live tv clients are not relying on any of the tags, it is all optional in m3u file.

**Comment by alanmilinovic** [comment]
Do we need to open a feature request here instead?

**Comment by alanmilinovic** [comment]
I would love to use Jellyfin and it is great what has been done with this amazing project but this is a blocking issue in regards to using a Live TV for me.

Are there any considerations for puting this issue on a short road map?

**Comment by alanmilinovic** [comment]
This is clearly a bug as if you have two channels with same tvg-id. It will show second channel but with url from first one. Please consider fixing it by ignoring tvg-id as a uniqueidentifier and just sort and display channels like they are listed in m3u8 file. Thank you, looking very much forward to response from any of contributors.

**Comment by alanmilinovic** [comment]
Any news?

**Comment by alanmilinovic** [comment]
Is this fixed or not?

**Comment by felix920506** [comment]
According to a linked pull request, it is fixed in master but hasn't made its way to any release. If you would like to test it yourself on master then keep in mind that the upgrade is irreversible so please backup your Jellyfin files before doing so. If the same behavior still happens then please make a new report.

**Comment by alanmilinovic** [comment]
Thanks for the explanation.

**Comment by alanmilinovic** [comment]
I gave up on testing because, Jellyfin is eating too much CPU. Also all of my live channels are not working because of "Playback error". Some video streams that are not live TV  are working, but only after I open jellyfin in incognito page in Chrome. Very strange.

For now I will have to give up on this beautiful project and start to search some better solution and alternative. It is a pity because I really like this project.
