### ISSUE TITLE
album artists separated by commas are not split properly 

### ISSUE THREAD

**Issue by chrpinedo** [jellyfin/jellyfin#6536]
**Describe the bug**
"album artists" separated by commas are not splited and all of them are considered like one unique artist.
For classical works, firstly writers must be detailed. Semicolons are used to separate between writers and performers. And commas to split among multiple writers (if there are multiple writers) and among multiple interpreters (if there are multiple interpreters, which is quite usual).

Semicolon is correctly interpreted by jellyfin but comma is not. 

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 91
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: -
 - Playback: - 
 - Hardware Acceleration: -
 - Installed Plugins: Musicbrainz, AudioDB
 - Reverse Proxy: nginx
 - Base URL: /
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Add one classical album with one writer and multiple interpreters such as https://musicbrainz.org/release/8e6949e3-e090-49b5-a396-9e16124fb8e8, written by Giacomo Puccini and interpreted by Mirella Freni, Luciano Pavarotti...
2. Check that interpreter list is not split by jellyfin:

![image](https://user-images.githubusercontent.com/2324630/132757923-146a9425-43ef-4e4c-8e18-bd5583458452.png)

![image](https://user-images.githubusercontent.com/2324630/132758074-06dcb821-cd08-4bb1-96d8-6cddc1783f6c.png)

**Expected behavior**
Besides semicolon, comma should also be used to split the list of artist.

**Comment by DomiStyle** [comment]
I also have my artists separated by commas, mostly because for Plex and other programs that are not able to split artists by `/` that was the nicest way to display artists. Jellyfin of course tries to create a separate artist for each song. So you end up with like 100 separate artists for the same one and the artists page is mostly unusable.

I looked into the source code and the places where the delimiters are defined are here:
https://github.com/jellyfin/jellyfin/blob/531efc345a2bc6ef64a48b83b0458f327081f394/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L138
https://github.com/jellyfin/jellyfin/blob/531efc345a2bc6ef64a48b83b0458f327081f394/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L29

I'm looking into batch editing all my files to replace `, ` with ` / ` where possible. That seems to be a nice compromise between being able to look at the field for programs which do not split the artists. `;` just looks ugly imo.

As for this issue maybe the delimiters should be configurable to allow more control over this messy splitting. After all there are plenty of artists with `/` and `,` in the name so there are no sensible defaults. It would also be nice if the whitelist could be configurable too:
https://github.com/jellyfin/jellyfin/blob/531efc345a2bc6ef64a48b83b0458f327081f394/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L44

**Comment by chrpinedo** [comment]
Regarding which separator to use to split artists, I would suggest to follow the best practices of MusicBrainz https://musicbrainz.org/doc/Style/Classical/Release_Artist, which is one of the biggest databases for recordings of music (as well as open). 

In order to split artists, MusicBrainz uses mainly commas but sometimes it uses semi-colon (to split between composer and performers). I think MusicBrainz doesn't use "/" to split artists (but I barely read some style guides of MusicBrainz).

In my previous example of the opera, the artist field of the opera is split with semicolons and commnas: "Giacomo Puccini; Mirella Freni, Luciano Pavarotti...". Jellyfin understands only the semicolon (as @DomiStyle found) and it prints "/" in the web interface instead of ";" but it is only a display decision.

**Comment by Shadowghost** [comment]
This is still a thing but needs some consideration because technically how we're handling it isn't incorrect per se.

The proper way of doing multiple artists is having each of them in their own artist tags. This is supported on ID3v2.4 and APEv2 and most tagging programs allow doing so by using `\\`.

Musicbraiz Picard has a plugin which creates seperaten tags for each kind of participant/arrist which imo is the proper way adding more info than just artist and album artist.

**Comment by lo97** [comment]
Any update on this?

**Comment by lo97** [comment]
But it still doesn't recognize commas as separator of multiple artists and creates a different one for each of them. Is there a way to fix this? (I'm sorry, I'm not a developer).

<img width="1621" alt="Screenshot 2022-11-02 at 16 49 21" src="https://user-images.githubusercontent.com/56902258/199536692-2cb7f156-1b24-4719-8254-1273a9acc121.png">

**Comment by bubundas17** [comment]
It is not fixed yet, I ended up writing a simple python script to retag all of my downloaded flac files. 
hope it might help someone.

**Disclaimer: Do not run this script without knowing what it is doing. It will cause irreversible change.** 
```python
import os
from mutagen.flac import FLAC

path = './music'

for root, dirs, files in os.walk(path):
    for filename in files:
        if filename.endswith('.flac'):
            filepath = os.path.join(root, filename)
            audio = FLAC(filepath)
            artist = []
            albumartist = []
            primary_artist = filename.split(' - ')[1]
            # print(audio)
            if("artist" in audio):
                for i in audio['artist']:
                    for j in i.split(', '):
                        artist.append(j)

            if("albumartist" in audio):
                for i in audio['albumartist']:
                    for j in i.split(', '):
                        albumartist.append(j)

            # if artist is empty, add albumartist to artist and if albumartist is empty, add primary_artist to albumartist
            if not artist:
                if albumartist:
                    artist = albumartist
                else:
                    artist.append(primary_artist)
            
            if not albumartist:
                if artist:
                    albumartist = artist
                else:
                    albumartist.append(primary_artist)

            # print(artist)
            # setattr(audio, 'artist', artist)
            # setattr(audio, 'albumartist', albumartist)
            audio['artist'] = artist
            audio['albumartist'] = albumartist
            # print(audio)
            audio.save()
            print('Edited: ' + filepath)
```

**Comment by TorchedSammy** [comment]
![](https://safe.saya.moe/GnxTa3n8gIl8.png)

this issue annoys me a lot. it doesn't even look like jellyfin is splitting up album artists at all. if jellyfin can get music data from musicbrainz, why doesn't it just use that to correctly get all the artists and link them separately?

commas and semicolons aren't the only ways artists are split, and musicbrainz specifies how artists are joined together.

**Comment by Shabinder** [comment]
was this ever fixed ?
audio library still doesnt split based on comma's ?
