### ISSUE TITLE
Sorting TvShows by "Date Played" has no effect

### ISSUE THREAD

**Issue by Zelgadis87** [jellyfin/jellyfin#6712]
**Describe the bug**
From the Jellyfin Web tvshows main screen, using the sorting menu, if I select "Sort By: Last Played", Jellyfin just sorts by name (either in ascending or descending order).
I can confirm I have played a show, one from Kodi and one from Jellyfin on Android TV, but these don't show up at the top or at the bottom at the list, they are in the middle, according to their respective initial letter.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: Docker
 - Clients: Android TV / Browser
 - Browser: Edge 94
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: irrelevant
 - Playback: irrelevant
 - Hardware Acceleration: irrelevant
 - Installed Plugins: irrelevant
 - Reverse Proxy: irrelevant
 - Base URL: irrelevant
 - Networking: irrelevant
 - Storage: irrelevant

**To Reproduce**
1. Open Jellyfin
2. Watch one episode of show A
3. Go to TvShows main screen
4. Sort by Date Played
5. Notice how show A is neither the first or last item in the list; Shows are simply in alphabetical order

**Expected behavior**
Show A is at the top (date played descending) or at the bottom (date played ascending) of the list

**Additional info**
I can provide any logs or screenshot if needed, as the issue is reproduced every time.

**Comment by RemcoSchrijver** [comment]
Having looked at the code base I think the problem is the fact that the [base class for ListView.](https://github.com/jellyfin/jellyfin-web/blob/0fa6dfa611da1baaeb48a750d0851e7036673043/src/components/listview/listview.js#L20) Does not implement the DatePlayed id as referenced [here.](https://github.com/jellyfin/jellyfin-web/blob/cdf1bf72de2307c060144d9b535933518e409591/src/controllers/shows/tvshows.js#L270) But my JS is rather rusty, but if I can find the time I'll have a look if I can implement that and put it in a PR.

**Comment by axelsimon** [comment]
Further to this issue, if the date played is stored somewhere, it is nowhere to be found in the Jellyfin web interface.
