### ISSUE TITLE
Symlinks fail for DLNA and download

### ISSUE THREAD

**Issue by skug67** [jellyfin/jellyfin#678]
**Describe the bug**
I'd been having a number of problems with DLNA and only recently stubmled onto the fact that it is due to the majority of my library being a collection of symlinks (using Plex-style folder and naming conventions) to a single directory of MythTV recordings (which are named simply by channel name and the time the recording was started).  While the recordings play fine in the web interface, they fail whenever I try to access them via DLNA or to download them (as opposed to playing them) from the web interface.

**To Reproduce**
1. Create a library that includes symlinked files
2. The file is properly identified by the library scan (including the size of the target file)
3. The video also plays fine in the web interface
4. Access the file via download or DLNA and it tries to download a 32 or 40 byte file, then terminates.

**Expected behavior**
Jellyfin would follow the symlink in all cases and allow it to play via DLNA or be downloaded.

**System (please complete the following information):**
 - OS: Debian
 - Browser: Chrome/Opera/Firefox browsers, VLC for iOS/Infuse for iOS via DLNA
 - Jellyfin Version: 10.0.2.0 (installed via repository deb package)

**Comment by skug67** [comment]
As a workaround, because I share the media directory via Samba (using "wide links" and "follow symlinks") I was able to re-point my Jellyfin library to a copy of the directory that had been mounted as a Samba share at that point everything works normally.

It's a slight annoyance and I assume has some amount of performance degradation (but nothing that I've noticed).  So if following symlinks w/in Jellyfin turns out to be hard could simply note the limitation and this workaround in the Wiki.

**Comment by MasterCATZ** [comment]
same problem I use symlinks for my Anime collections they are not being followed

**Comment by JustAMan** [comment]
Not saying I don't believe you, but I find it highly unlikely because as a programmer you have to do some _substantial_ effort to differentiate symlinks from normal files, otherwise your program will treat them equally. So far I think it's the case for Jellyfin.

I so far only saw reports of Jellyfin incorrectly supporting symlinks which turned out to be configuration errors in the end (mostly caused by Docker, some caused by permissions).

Feel free to prove me wrong, though, I'm open to admitting I said something incorrect.
