### ISSUE TITLE
[Issue]: Shows with numbers in the title interpreted as Season number

### ISSUE THREAD

**Issue by Slomo17** [jellyfin/jellyfin#6928]
### Please describe your bug

As the old bug report #5221 got closed and it's still an issue in the lates version i open a new one:

If a TvShow has a number in the title, all Episodes get sorted into a Season corresponding to the tiltes number
e.g.
The 100 --> all episodes in season 100
Stargate SG-1 ---> all episodes in season 1
24 ---> all episodes in season 24

The metadata of the individual episodes however seems to be correct.

I attached a screenshot as an example.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 21.10
- Virtualization: Docker
- Clients: Web, Android
- Browser: Firefox, Chrome (on Linux and Windows)
```

### Please attach any screenshots here

![Screenshot](https://user-images.githubusercontent.com/14056946/144071144-30d8571d-6fef-4abb-87fb-cef4e3b854cb.png)

**Comment by cvium** [comment]
Please include your folder structure

**Comment by Bond-009** [comment]
`The 100 Season 01` should just be `Season 1` I think (for best results)

**Comment by Slomo17** [comment]
Ok i renamed them to Season 1 and now it works (Season 01 does not), thanks for the hint. However I would still consider this a bug or at least an improvement if it would detect the episodes correctly with my folder structure, as i sometimes want to copy different seasons from differente shows onto one hard drive. I would have to rename them by hand in this case, if they are all just called Season # .

**Comment by Slomo17** [comment]
I tied it with a diffrent Series (Stargate SG1) and there it doesn't seem to work with the naming scheeme "Season #", will keep testing it with diffrent shows

**Comment by Maxplosion** [comment]
for reference on ideal naming you could take a look at the docs here:
https://jellyfin.org/docs/general/server/media/shows.html
if you follow this most issues should vanish

**Comment by tremby** [comment]
There's a comment above which says "should be just `Season 1`", and another which says leading zeros break things. Yet the link posted by Maxplosion has example naming which *does* include leading zeros.

Regardless of the above, I still see the way season folders are currently identified as a problem.

I expect I'm not the only one who likes to keep the files' and directories' original naming, so that it's obvious where it came from, and so I don't need to manually go and rename anything. Generally each season would have the show name in it, and it might say "series xx" or "season xx" or "Sxx". (Daily shows might have 4 digits, since they're often separated by year.)

The current code is here: https://github.com/jellyfin/jellyfin/blob/b2a2bdb088fc912e54655f6a277a43629ce277f4/Emby.Naming/TV/SeasonPathParser.cs

It's actually looking for a whole lot more than just "Series xx", which means the behaviour is not properly documented in the link posted above, and it's designed to be more fuzzy than the documentation lets on. In fact, it seems to be working just fine as is for everything I have except shows with numbers in their name. This is hundreds of season folders, only a small handful of which are named "Season xx". Since it works fine in almost all cases without the user needing to read those docs, the current behaviour in mishandling shows with numbers in their names presents as a bug.

To me, the code is at the same time overly complicated and much too naive. Here's what it does:

1. If "support special aliases" option is set, and the entire name is (case insensitive) "specials" or "extras", it's a specials folder; stop.
2. If "support numeric season folders" option is set, and the entire name is a number, that's the season number; stop.
3. If the name starts with an "s" or "S" and the entire rest of it is a number, that's the season number; stop.
4. It then loops through a hardcoded array of words for "season"/"series". For each one, it looks for that word anywhere in the name (and it doesn't need to be at word boundaries -- it'd match xxxseriesxxx for example, and it'd also match "A Series of Unfortunate Events"). If it's found, that word is removed from the string and replaced with a space. What happens next is commented as `Extracts the season number from the second half of the Season folder name (everything after "Season", or "Staffel")` but in fact looks at the entire rest of the name including before the matched word. The code here is convoluted, and I'm pretty sure it has other issues (for example there's one part commented `There's other stuff after the season number, e.g. episode number`, but I don't think this code is working as the author intended). Anyway, if it thinks it finds a number, that's the season number; stop.
5. The name is split by various characters (dot, space, hyphen, underscore), any empties (like you'd get if there are two of those characters in a row) are removed, and then it looks at each of these parts in left to right order. If it finds one which is an "s" or "S" followed by one or more digits, the number is the season number; stop.
6. It's deemed not a season folder.

IMO almost the whole thing could be replaced with a simple regex. After checking for extras and simple numbers based on those options, it could be something like `.*/\b(?:s|season|series|...)[ ._-]?(\d+)/` followed by parsing the capture group as an integer, where `...` can be whatever other keywords to look for. This would match everything relevant I can think of, including "Season 1", "Season 01", "series 01", "s1", "show.name.s01", "show_name_season_2023_whatever_extra_info", and so on.

(The `.*` at the start means it'll match as late in the source string as it can, so for example if there were a show called "Codename ZZ-S04-B" a season folder called "codename-zz-s04-b-s01" would be deemed season 1, not season 4.)

I don't know C# and I don't particularly want to set up a dev environment for it. But if it would be useful for me to write what I think would probably work and open a PR for it, for someone else to review and get production-ready, I'd be happy to do that.
