### ISSUE TITLE
Building on Windows via build-jellyfin.ps1 is broken

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#705]
**Describe the bug**
Looks like `build-jellyfin.ps1`, it builds the `MediaBrowser.sln` file while it should be building a project.

**To Reproduce**
Try running `build-jellyfin.ps1`, observe build errors.

**Expected behavior**
`build-jellyfin.ps1` should succeed.

**Logs**
User reported: https://pastebin.com/uu3kq0f7

**System (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Jellyfin Version: current tip e0315b569591b71938829a8f35ac264399ef66bd

**Comment by Wuerfelbecher** [comment]
Not only building on windows is broken it looks it's broken for all platforms.
Building the `.rpm` and `.deb` packge also failed -> [build logs](https://gist.github.com/Wuerfelbecher/1ec481d08cc28250c755eb77cbc19bad).

**Comment by joshuaboniface** [comment]
@Wuerfelbecher This has been corrected (both the original issue and the `deb`/`rpm`s). It was related to #311, which resulted in the (now-empty) taglibsharp submodule dir, which then removed it from the previous history, i.e. the previous release. We've corrected this with a release branch (`release-10.1.0`) and updating the `v10.1.0` tag to target this rather than master.
