### ISSUE TITLE
[Issue]: Support for OpenSSL 3.0

### ISSUE THREAD

**Issue by heitbaum** [jellyfin/jellyfin#7084]
### Please describe your bug

With LibreELEC 11 we have moved to using OpenSSL 3.0. With the existing 2.7.7 release of portable we are getting the error `No usable version of libssl was found`, looking at the commit logs. This seems to have been a previous issue - https://github.com/jellyfin/jellyfin/pull/1693 - what are the options on this?

- https://github.com/LibreELEC/LibreELEC.tv/pull/6064
- https://github.com/LibreELEC/LibreELEC.tv/issues/6065

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: LibreELEC 11
- Virtualization: NA
- Clients: NA
- Browser: NA
- FFmpeg Version: NA
- Playback Method: NA
- Hardware Acceleration: NA
- Plugins: NA
- Reverse Proxy: NA
- Base URL: NA
- Networking: NA
- Storage: NA
```

### Jellyfin logs

```shell
No usable version of libssl was found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Can you please check if Jellyfin 10.8 runs?
According to [0] dotnet 6 has support for openssl3.0

[0] https://github.com/dotnet/runtime/issues/46526

**Comment by heitbaum** [comment]
Tested with alpha3 and addon update in LE11 - working now. https://github.com/LibreELEC/LibreELEC.tv/pull/6066 
Good to close 👍
I haven’t created the PR for Jellyfin 10.8 addon into LE11 yet. (I will probably create it as a draft PR) - minor issue with the download link, and we need to improve our downloader / update logic.

**Comment by Mhowser** [comment]
I'm not able to start Jellyfin 10.8.10 with openssl 3, I have to preload libssl-1.1 in order to start my server. 
this is the launch script I use to launch the server on my Steam Deck:
```sh
#!/bin/bash

# establish jellyfin server and ffmpeg directories
JELLYFINDIR="/home/deck/Vaults/jellyfin-media-server"
FFMPEGDIR="/home/deck/Vaults/jellyfin-media-server/jellyfin-ffmpeg"

# Start the server with outdated libssl because of dotnet 6
LD_PRELOAD=~/.local/lib/openssl-1.1/libssl.so.1.1 exec dotnet $JELLYFINDIR/jellyfin/jellyfin.dll \
 -d $JELLYFINDIR/data \
 -C $JELLYFINDIR/cache \
 -c $JELLYFINDIR/config \
 -l $JELLYFINDIR/log \
 --ffmpeg $FFMPEGDIR/ffmpeg
 ```
This is the version of openssl installed on Steam OS 3.5.1
 - OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)

And this is the version of dotnet I have
 - Microsoft.AspNetCore.App 6.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]



> Can you please check if Jellyfin 10.8 runs? According to [0] dotnet 6 has support for openssl3.0
> 
> [0] [dotnet/runtime#46526](https://github.com/dotnet/runtime/issues/46526)

@crobibero It looks like they decided to move support to a future release?
