### ISSUE TITLE
[Issue]: 10.8.0-alpha5 - DMG corrupt on older OSX

### ISSUE THREAD

**Issue by keen99** [jellyfin/jellyfin#7157]
### Please describe your bug

DMG for 10.8.0-alpha5 won't uncompress on osx 10.10 - presumably the dmg is using an unsupported compression.

I dont know if there are any other blocking issues running on 10.10, but I can't even test. :)  (I hope not, since roku's force killing rarflix, so those of us with old plex installs will be SOL)

### Jellyfin Version

Other

### if other:

10.8.0-alpha5

### Environment

```markdown
- OS: mac osx 10.10
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/1108844/148846344-3173058b-a50b-4a22-a1a5-652be0a75ea7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
There's a few concerns here. Sadly, it won't run on 10.10. I don't think any of the previous releases would either. Note that this isn't just because of how the .app or .DMG are built, but rather because we stay up to date with .NET as it moves forward.

in this case, even if you got it extracted, the use of .NET 6 for the latest version enforces a minimum of 10.15: https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md

Even throughout the life of the menu bar app that I build Jellyfin with would require 10.14.6 at a minimum because of its use of Swift 5.

Just to be on the safe side, I had a look at supported OS versions for when we first started Jellyfin just over three years ago. Even then it was already at a minimum of 10.12.

Sorry.
