### ISSUE TITLE
Docker on synology ds418j

### ISSUE THREAD

**Issue by DevSynthes3d** [jellyfin/jellyfin#7163]
I would like to install Docker on my synology ds418j,
but not possible even through manual installation.
Do you have any solutions please?

**Comment by poulpor** [comment]
Sorry but you need an x86_64 cpu if you want to install docker on a Synology, which means Intel or Amd cpu only. Yours is a Realtek RTD1293, ARM architecture. That's why I often suggest people to buy a DSxxx**+** instead of weaker DSxxx**J**, or they'll soon feel very frustrated by the lack of possibilities :(
