### ISSUE TITLE
[Issue]: ASS

### ISSUE THREAD

**Issue by davidmurdoch** [jellyfin/jellyfin#7389]
### Please describe your bug

`Subtitles` section displays the word "ASS" in this G rated movie in latest Alpha version because the subtitle selections now include the type/codec.

(see screenshot)

Aside: I don't think end-users care about encodings for _anything_ (including audio and video ), and I think this is especially true for subtitles. Obviously some users want this, but maybe this can be a user-level setting, e.g., "Display media codec"?

### Jellyfin Version

Other

### if other:

10.8.0 alpha 5

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/187813/156247383-b382e810-510f-4442-8fc9-58e899ca4e67.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
"ASS" is the name of the subtitle format. https://en.wikipedia.org/wiki/SubStation_Alpha#Advanced_SubStation_Alpha I'm not in favour of hiding this legit piece of technical info because it uses the same letters as a common, and honestly pretty minor, "swear" term for a part of human anatomy.

There is [an existing feature request for a "Kid's Mode"](https://features.jellyfin.org/posts/531/child-mode), which this would fall under, though a bit indirectly (by hiding all such technical information as non-relevant, not specifically because of this one word), but we don't have that on the roadmap yet.

Short-term, if the name of the subtitles format used on the file is a concern, I'd remove them from the file so it doesn't show as part of the metadata.

**Comment by davidmurdoch** [comment]
Yes, I understand that. And as and admin I love to see the additional meta data. But I don't think technical information should be the default for end-users ever. Users can already see this exact information if they want to by viewing the Media Info, right?

Adding additional meta information to an already busy interface is a step backwards in terms of UI/UX for normal users.

Suggesting that we remove subtitles entitled just so some power users can view subtitle codecs without having to open a menu is not a solution.

**Comment by LePips** [comment]
What you are pointing out specifically is what the subtitle track is named itself. You will have to change the name of the subtitle track.

**Comment by davidmurdoch** [comment]
No I'm not.

**Comment by davidmurdoch** [comment]
🙃``
