### ISSUE TITLE
[Bug] Music Metadata in Different Languages Doesn't Merge When Renamed

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin#7422]
# Please describe your bug
## Context
As stated in the issue below, there seems to be some major issues with how metadata is handled with music.
https://github.com/jellyfin/jellyfin-plugin-musicbrainz/issues/13
However, these issues are just as present when the music you import already had metadata associated with it. I'd rather it rely on that before changing it all with the plugin. However it's impossible to check everything I download for proper metadata.

For example, an album I have I believe has metadata in German.
Album Artist: Verschillende artiesten
Genre: Klassiek

So it would be amazing if it would be smart enough to automatically retitle it to English, and merge it in Jellyfin with 
Various Artists
Classical
but it does not.

## Issue
I have just manually tried renaming the genre and album artist, expecting it to merge with the other genre with the same exact name. (Genres > Click Klassiek >` Rename to "Classical"). It did not, instead now I have two identical genres called called "Classical" and they both show only one set of content instead of merging the two together.
Same with the Various Artists album artist.

Jellyfin Version
10.7.7

Environment

• OS: Win 10
• Virtualization: No
• Clients: Web, Jellyfin Mopidy, Finamp
• Browser: Firefox ESR
• Playback Method: Web
• Networking: Local

• Code of Conduct
- [x]  I agree to follow this project's Code of Conduct

**Comment by Maxplosion** [comment]
if this is ever done with renaming stuff into english then please make it optional. for users that have very clean and manually created metadata that is a big nogo to have jellyfin change it with an assumption it might be e.g. in a different language. 
how would that even be possible to find that out? maybe there is a general genre called 'Klassiek' and that one is th3n not the same as classic in english. (as in german it would be Klassik btw) 
[assuming I understood your post correctly]

**Comment by certuna** [comment]
**Genres**
The problem is that Genre is stored as a string, so there's no obvious way to localize languages.

Back long ago in the 1990s, in the old id3v1 standard, Genres were stored as [8-bit integers](https://en.wikipedia.org/wiki/List_of_ID3v1_Genres), or in other words: only 256 genres would be possible, which was of course a very naive way of thinking, but it did allow mapping that integer into any language on the client-side.

**Various Artists**
The localization problem can be fixed by making Album Artist empty and Compilation = True, that way a player knows that the album is a Various Artists compilation, and can insert its own localized version of the string "Various Artists" as album artist.

However, many servers/players don't support the Compilation tag in FLAC/id3v2/mp4

**Comment by seniorm0ment** [comment]
This problem still is relevant.

However I still have not figured out a way to fix my issue of when I renamed the genre from Klassiek to Classical expecting it to merge. Instead it just made the genre Klassiek disappear, and all the music files didn't merge into Classical. Would be nice to recover this, I don't know which files where in Klassiek so I can't just go manually do that there was too many.

**Comment by seniorm0ment** [comment]
Relevant

**Comment by seniorm0ment** [comment]
Still relevant
