### ISSUE TITLE
All libraries scanning when a new library is created.

### ISSUE THREAD

**Issue by trumblejoe** [jellyfin/jellyfin#745]
When creating a new library, all libraries are being auto-scanned. Obviously the behavior should be that only the newly created library is scanned.

Jellyfin Version: 10.0.1

**Comment by cvium** [comment]
For the curious, I think it happens here https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/LibraryManager.cs#L2907-L2912

Dunno if I would call it a bug though. Seems intentional enough.

**Comment by JustAMan** [comment]
What harm is in re-scanning all libraries? If there's no data change it should be fast, if it isn't that's a separate bug IMHO.

**Comment by hawken93** [comment]
Um, it's weird. I don't want jellyfin to go off doing random library scans whenever I do something unrelated. I hope there's at least one good reason why all the libraries have to be rescanned when adding a new one..

**Comment by sparky8251** [comment]
I'd agree more with @hawken93 here. Yeah, it should be quick but software should *never* do something unexpected from the perspective of the admin/user.

Adding a library should trigger a scan on the new library. That's the expected behavior. It's pretty surprising that adding a library triggers a full library scan for everything.

**Comment by Unimeron** [comment]
Hello :)

> What harm is in re-scanning all libraries? If there's no data change it should be fast, if it isn't that's a separate bug IMHO.

Well, scanning all libraries when only adding a new library, means the underlying disks of those libraries have to spin up for no real purpose.

I asked that question the emby devs a few weeks ago and they said they could change that sometimes later.

Another reason against scanning without request I read about, was that some guys "lost" the library because the particular network share or mount point was not available. So Emby/Jellyfin might think the content was removed.

**Comment by BugFixesAndPerformanceImprovements** [comment]
Just had this happen to me on Jellyfin 10.11.6 when adding a new library. Rescanned the entire 70TB+ of files in the other libraries. Still very much an issue.
