### ISSUE TITLE
[Issue]: Jellyfin IOS app wont connect remotely

### ISSUE THREAD

**Issue by Joeharrison94** [jellyfin/jellyfin#7456]
### Please describe your bug

Describe the bug

I have Jellyfin setup with a subdomain. I am using a reverse proxy (swag) to connect to the Jellyfin docker. When I connect to the URL I setup through a web browser remotely it connects fine. When I put the same URL into the IOS app it can't find the server. I have tested the Android App, Android TV App, Firestick App and Windows Client all work and connect fine through fqdn remotely but the IOS app will not connect

Open Jellyfin IOS app enter url in format https://jellyfin.mydomain.co.uk
Error failed to connect.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Docker
- Clients: All (works) except for the iOS version.
- Browser: All Work
- FFmpeg Version: 4.3.2-Jellyfin
- Playback Method: All
- Hardware Acceleration: NVENC
- Plugins: Webhooks, Themes, Collections and OpenSubtitles
- Reverse Proxy: Nginx (SWAG)
- Base URL: jellyfin.mydomain.co.uk
- Networking: Docker Bridge
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Joeharrison94** [comment]
> You don't mention any details about your ssl setup but if you maintain your own pki, apple has more strict requirements than your average bear. Here are some as an example, there are more: https://support.apple.com/en-us/HT210176

It works on safari and my certs are through cloudflare so I know they conform.

**Comment by nickwilkie** [comment]
I have the same issue. All clients work with SWAG except for iOS app. iOS app works when I connect directly (not through SWAG reverse proxy). I'm using the default configuration (jellyfin.subdomain.conf.sample) and I've set the PublishedServerUrl to the correct address, although I think that's just for discovery. 

iOS app just says it can't connect, doesn't give any more specific error. Would love to fix this.

Default SWAG conf might be the prob, since a lot of the options in the other ones like authelia/http authentication aren't listed in their normal commented-out format that I see in all the others.

**Comment by Bond-009** [comment]
Not a server issue

**Comment by ssebs** [comment]
Any update with this? I'm facing the same issue.
