### ISSUE TITLE
[Issue]: Search does not work properly for åäö

### ISSUE THREAD

**Issue by LinAGKar** [jellyfin/jellyfin#7484]
### Please describe your bug

Searching for a word containing å, ä or ö does not work properly, as Jellyfin replaces it with the similar-looking ASCII character. So for example, if you type "Jön", "Indiana Jones" will be included in the results, but not "Jönssonligan".

### Jellyfin Version

Other

### if other:

10.8-alpha5

### Environment

```markdown
- OS: OpenSUSE Leap 15.3
- Virtualization: Docker jellyfin/jellyfin
- Clients: Browser
- Browser: Firefox 98
- FFmpeg Version: 4.4.1-Jellyfin
- Hardware Acceleration: none
- Plugins: AudioDB 10.8.0.0, MusicBrainz 10.8.0.0, OMDb 10.8.0.0, Studio Images 10.8.0.0, TMDb 10.8.0.0
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbenco** [comment]
Seems like the Diacritics package doesn't strip this diaeresis correctly out of the film name retrieved from TMDB

![image](https://user-images.githubusercontent.com/13434960/160278849-ae6d134e-aa26-4543-8875-7d81c8d9d35c.png)

**Comment by Jellifi007** [comment]
This bug is related to regression introduced by Bond-009@981cf4cfa0d45a3654578a1989738fc82469c889

Reverting to our own RemoveDiacritics extension should do the work (not sure why this has been changed).

I think we should put our own "reverted RemoveDiacritics extension" in a separated project ("Jellyfin.Diacritics" ?) to allow for less coupling with existing projects, rather than re-adding the extension into "MediaBrowser.Controller.Extensions;" like before.

Proposed target class optimized with shared thread safe regex object :
![Diacritics_corrected](https://user-images.githubusercontent.com/93096110/163390514-7b8d1a0f-f8c5-4bcb-9bd0-c84c8bf5dc54.png)

Proposed source :
[Extensions.cs.zip](https://github.com/jellyfin/jellyfin/files/8489164/Extensions.cs.zip)

Diacritics package has to be removed and import references corrected in following projects in order to restore correct Jellyfin behavior:
![Diacritics_projetcs](https://user-images.githubusercontent.com/93096110/163391403-98f548ea-bac1-4d92-a405-1446555a595a.png)

if someone can approve I will do the PR.
