### ISSUE TITLE
[10.8.0][Issue]: restart.sh not working with new 10.8.0 update

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin#7503]
### Please describe your bug

Unit name /jellyfin.service= is not valid
Turns out after restart the server didn't close the port and couldn't connect to the port again.

Also the issue template that asks what version of Jellyfin are you running needs 10.8.0 added to it.

### Jellyfin Version

Other

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourpatched** [comment]
Beta 2 still has this issue

**Comment by zexindai** [comment]
Beta 3 still has this issue

**Comment by VigibotDev** [comment]
Sorry same problem on 10.8.0 Stable updated today

**Comment by sourpatched** [comment]
@joshuaboniface Has this issue gone unnoticed?

**Comment by joshuaboniface** [comment]
I'm not sure I understand what the issue actually is. Please provide more details and logs, etc.

**Comment by sourpatched** [comment]
> I'm not sure I understand what the issue actually is. Please provide more details and logs, etc.

When you restart the server, it doesn't start back up on ubuntu 20.04 until you foreclose the port then start via commend line

**Comment by joshuaboniface** [comment]
The internal restart has always been flaky at best, this has been a known issue since the earliest days. It has to do with flaws in how the child script gets handled. You could try tweaking restart.sh but we did a lot of that back in 10.6.0 and nothing helped. We've never turned it off because it seems to work just enough of the time for it to be worthwhile, but if it's a consistent problem I'd recommend sticking to the CLI for restarting the server process.

**Comment by sourpatched** [comment]
[2022-06-12 13:35:50.456 +10:00] [INF] Starting new instance
[2022-06-12 13:35:50.456 +10:00] [INF] Executable: "/usr/lib/jellyfin/restart.sh"
[2022-06-12 13:35:50.456 +10:00] [INF] Arguments: "--webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg   "
[2022-06-12 13:38:29.205 +10:00] [INF] Jellyfin version: "10.8.0"
[2022-06-12 13:38:29.238 +10:00] [INF] Environment Variables: ["[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]"]
[2022-06-12 13:38:29.241 +10:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2022-06-12 13:38:29.242 +10:00] [INF] Operating system: "Linux"
[2022-06-12 13:38:29.242 +10:00] [INF] Architecture: X64
[2022-06-12 13:38:29.243 +10:00] [INF] 64-Bit Process: True
[2022-06-12 13:38:29.243 +10:00] [INF] User Interactive: True
[2022-06-12 13:38:29.243 +10:00] [INF] Processor count: 4
[2022-06-12 13:38:29.243 +10:00] [INF] Program data path: "/var/lib/jellyfin"
[2022-06-12 13:38:29.243 +10:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2022-06-12 13:38:29.243 +10:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2022-06-12 13:38:29.388 +10:00] [INF] Setting cache path: "/var/cache/jellyfin"

That explains why it worked before but not now, I think in another log I saw something about sudo and UID being 0 or something, I'll look into it

**Comment by joshuaboniface** [comment]
Actually, you're on to something - I definitely remember this being fixed in 10.7.0 after looking back through some history, but if I test now I can replicate this. It stops the service but never restarts it.

```
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2612597]: [23:42:13] [INF] [15] Main: Starting new instance
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2612597]: [23:42:13] [INF] [15] Main: Executable: /usr/lib/jellyfin/restart.sh
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2612597]: [23:42:13] [INF] [15] Main: Arguments: --webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/share/jellyfin-ffmpeg/ffmpeg
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + '[' -d /run/systemd/system ']'
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + cmd=systemctl
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + type sudo
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + sudo_command=sudo
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + echo 'Detected service control platform '\''systemctl'\''; using it to restart Jellyfin...'
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: Detected service control platform 'systemctl'; using it to restart Jellyfin...
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + case $cmd in
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + sudo systemd-run systemctl restart jellyfin
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843682]: sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
Jun 11 23:42:13 jf1.i.bonilan.net jellyfin[2843681]: + exit 0
Jun 11 23:42:13 jf1.i.bonilan.net systemd[1]: jellyfin.service: Succeeded.
Jun 11 23:42:13 jf1.i.bonilan.net systemd[1]: jellyfin.service: Consumed 22min 57.954s CPU time.
```

For clarity I set `-o xtrace` in the `restart.sh` script to show it's output, and that sudo error is definitely not what we'd expect. I'll keep testing and see if there's a good solution here.

**Comment by sourpatched** [comment]
Found this: 
 sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

**Comment by joshuaboniface** [comment]
Yep, I've tracked the problem down to several of the systemd security enhancements that were added in #6953. I'm doing some testing to find out exactly which one causes it since it wasn't one of the obvious ones.

**Comment by joshuaboniface** [comment]
OK looks like there's actually two facets to the problem:

1. Our sudoers config (`/etc/sudoers.d/jellyfin-sudoers`) was never updated to take into account that `restart.sh` now calls `systemd-run` instead of a direct call to `systemctl`. So even with all the hardening gone, this broke `restart.sh`.

2. The hardening definitely caused breakage with the inability to call `sudo` from within the jellyfin service namespace. If I remove all hardening options from #6953, in conjunction with fixing the above sudoers issue, it works fine:

```
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857306]: [00:20:39] [INF] [27] Main: Starting new instance                                                                                                                                         
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857306]: [00:20:39] [INF] [27] Main: Executable: /usr/lib/jellyfin/restart.sh                                                                                                                      Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857306]: [00:20:39] [INF] [27] Main: Arguments: --webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/share/jellyfin-ffmpeg/ffmpeg
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + '[' -d /run/systemd/system ']'                                                                                                                                                          
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + cmd=systemctl                                  
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + type sudo                                                                                                                                                                               
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + sudo_command=sudo                                                                                                                                                                       
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + echo 'Detected service control platform '\''systemctl'\''; using it to restart Jellyfin...'
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: Detected service control platform 'systemctl'; using it to restart Jellyfin...                                                                                                            
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + case $cmd in                                                                                                                                                                            
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + sudo systemd-run systemctl restart jellyfin   
Jun 12 00:20:39 jf1.i.bonilan.net sudo[2857550]: jellyfin : PWD=/var/lib/jellyfin ; USER=root ; COMMAND=/usr/bin/systemd-run systemctl restart jellyfin
Jun 12 00:20:39 jf1.i.bonilan.net sudo[2857550]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=110)          
Jun 12 00:20:39 jf1.i.bonilan.net systemd[1]: Started /usr/bin/systemctl restart jellyfin.                                                                                                                                                     
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857551]: Running as unit: run-rb059630e8dbe4701ad7f6b8e29f032ec.service
Jun 12 00:20:39 jf1.i.bonilan.net sudo[2857550]: pam_unix(sudo:session): session closed for user root                                                                                                                                          
Jun 12 00:20:39 jf1.i.bonilan.net jellyfin[2857549]: + exit 0                                                   
Jun 12 00:20:39 jf1.i.bonilan.net systemd[1]: Stopping Jellyfin Media Server...                      
Jun 12 00:20:39 jf1.i.bonilan.net systemd[1]: jellyfin.service: Succeeded.                           
Jun 12 00:20:39 jf1.i.bonilan.net systemd[1]: Stopped Jellyfin Media Server.                          
Jun 12 00:20:39 jf1.i.bonilan.net systemd[1]: jellyfin.service: Consumed 35.377s CPU time.                  
Jun 12 00:20:39 jf1.i.bonilan.net systemd[1]: Started Jellyfin Media Server.
```

Reviewing back through those issues, I'm still not entirely sure what they were actually trying to solve (perhaps @matthiasdv you can provide a bit more context as to why we'd need all these?) despite approving it since it seemed like they were all OK at the time.

Once I figure out which ones are OK and which ones break `restart.sh`, I'll do up a PR to fix for 10.8.1 and a workaround for right now.

**Comment by sourpatched** [comment]
Thanks for the update to this small issue, I'll keep an eye out for the workaround.

**Comment by joshuaboniface** [comment]
OK so for part 1, it looks like we *did* fix this, but I guess my ancient install (continuously upgraded) instance never applied the change to `/etc/sudoers.d/jellyfin-sudoers`. You can verify if issue 1 affects you by looking for the line in that file that begins with `Cmnd_Alias RESTARTSERVER_SYSTEMD`. If it looks like this:

```
Cmnd_Alias RESTARTSERVER_SYSTEMD = /usr/bin/systemd-run systemctl restart jellyfin                                                                                                                                                         
```

then that part of it is fine. If it doesn't look like that, modify it to match that string exactly using `sudo visudo /etc/sudoers.d/jellyfin-sudoers`.

For 2, despite much trial-and-error, I've not been able to find exactly *which* of the various hardening options is causing the issue. Even if I comment out the "obvious" ones it still fails until I comment out every single one. So, I think we're going to have to revert that in order to get this functionality to work again, and move the various hardening options into the optional `/etc/systemd/system/jellyfin.service.d/jellyfin.service.conf` overrides and let NixOS deal with it.

As a short-term workaround, you can copy the unit file from `/lib/systemd/system/jellyfin.service` to `/etc/systemd/system/jellyfin.service`, and comment out or remove all the lines starting with `NoNewPrivileges=true` and ending with `SystemCallErrorNumber=EPERM`. Then run `sudo systemctl daemon-reload` and `sudo systemctl restart jellyfin`, and `restart.sh` restarting from the GUI will work again.

**Comment by sourpatched** [comment]
The file should look something like this
`[Unit]
Description = Jellyfin Media Server
After = network-online.target

[Service]
Type = simple
EnvironmentFile = /etc/default/jellyfin
User = jellyfin
Group = jellyfin
WorkingDirectory = /var/lib/jellyfin
ExecStart = /usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} ${JELLYFIN_ADDITIONAL_OPTS}
Restart = on-failure
TimeoutSec = 15
SuccessExitStatus=0 143

#NoNewPrivileges=true
#SystemCallArchitectures=native
#RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
#RestrictNamespaces=false
#RestrictRealtime=true
#RestrictSUIDSGID=true
#ProtectControlGroups=false
#ProtectHostname=true
#ProtectKernelLogs=false
#ProtectKernelModules=false
#ProtectKernelTunables=false
#LockPersonality=true
#PrivateTmp=false
#PrivateDevices=false
#PrivateUsers=true
#RemoveIPC=true
#SystemCallFilter=~@clock
#SystemCallFilter=~@aio
#SystemCallFilter=~@chown
#SystemCallFilter=~@cpu-emulation
#SystemCallFilter=~@debug
#SystemCallFilter=~@keyring
#SystemCallFilter=~@memlock
#SystemCallFilter=~@module
#SystemCallFilter=~@mount
#SystemCallFilter=~@obsolete
#SystemCallFilter=~@privileged
#SystemCallFilter=~@raw-io
#SystemCallFilter=~@reboot
#SystemCallFilter=~@setuid
#SystemCallFilter=~@swap
#SystemCallErrorNumber=EPERM

[Install]
WantedBy = multi-user.target
`
Server now restarts as expected.

**Comment by RainbowPants** [comment]
adding that the changing the service file as above solves jellyfin failing to start with the only error showing up in logs. being:
`jun 13 11:30:52 hc4 jellyfin[23734]: Failed to create CoreCLR, HRESULT: 0x8007FF02`
which sent me on a trail of dotnet issues that apparently had little to do with it. jellyfin service would not start at all after updating to 10.8.0, with the only error showing was the above. commenting here if anyone runs into the same issue. this was on an arm64 device running ubuntu 20.04.
