### ISSUE TITLE
[Issue]: Playing a watched episode and then stopping within the first few minutes marks episode as unwatched.

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#7535]
### Please describe your bug

I noticed this in the web player and in a 3rd party client as well

1. Play a watched episode
2. let episode play for 10 seconds
3. stop playback
4. episode is marked as unwatched

Episode should not be marked as unwatched. It is still watched, just wasn't watched again.

Here is UserData for the episode after it was marked unwatched.

```
UserData: {
PlaybackPositionTicks: 0,
PlayCount: 2,
IsFavorite: false,
LastPlayedDate: "2022-03-31T18:03:30.8895109Z",
Played: false,
Key: "121361008006"
}
```

And then after I manually marked it as watched to fix the problem
```
UserData: {
PlaybackPositionTicks: 0,
PlayCount: 3,
IsFavorite: false,
LastPlayedDate: "2022-03-31T18:12:16.576Z",
Played: true,
Key: "121361008006"
},
```

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KoboDev** [comment]
I had this happend to me before, although it went away I thought it was because of the files itself.
Icarly was about 76gb's and i thought that was too much and the system thought so too.
So it just exits out of the episode after freezing.
I can say try these first:
Re-encode videos
or
Condense the videos

I had to condense Icarly down to like 36gb's and it started playing fine.

**Comment by SenorSmartyPants** [comment]
Video playback is not the issue, they play fine. It is the changing of the watched state to unplayed.

**Comment by KoboDev** [comment]
Maybe the system thinks that a stopped video is essentially meaning the streaming is ended.
The system may think its normal, and hell it may even be a normal thing in general.
But it does exist and its slightly annoying.
Although I think this goes deeper than config, I think its either an coding mistake or just Jellyfin being Jellyfin.

**Comment by JPVenson** [comment]
![image](https://user-images.githubusercontent.com/6794763/163736609-637fadac-ba04-42ae-b2f0-e50522c03849.png)
Isn't that by design?

**Comment by SenorSmartyPants** [comment]
Not in my mind. If you've watched something and decide to watch it again, but then stop. That doesn't make it that you've never watched it before. Which is what it means if something is marked unwatched.

**Comment by SenorSmartyPants** [comment]
Still an issue. Will be fixed if #8275 is merged.

**Comment by davemsh** [comment]
I just ran into this as well. The watched status is instantly removed when playback is started, whereas I'd prefer to be able to either have it not mark it unwatched until it has passed the configured "resumable" threshold, or by having a setting on whether to unset the watched status at all.

Ideally I'd prefer the second one - once it's watched, it's watched permanently, and only the user can manually set it to unwatched by toggling the checkmark.

**Comment by SenorSmartyPants** [comment]
My PR mentioned above does the second option

**Comment by SenorSmartyPants** [comment]
Don't close.

**Comment by klueman** [comment]
I'd very much like to see this resolved. Having to constantly go through and recheck all the checkmarks on a bunch of shows and episodes anytime I use the shuffle feature is very annoying.

I'd honestly just love a way to disabled "mark unwatched" all together. I have no need for it and it creates a mess anytime I rewatch things.

**Comment by srcrist** [comment]
Closing this issue as it does not document an actual Jellyfin bug. This is perhaps poorly designed but intentional behavior, and would be best served by a meta discussion about this functionality on the meta repo (https://github.com/jellyfin/jellyfin-meta/discussions) if someone is interested in writing a PR, or a feature request submission if someone would like to ask for help in getting the functionality changed (https://features.jellyfin.org).

I think there is relatively broad consensus that this functionality is bad, for what that's worth, and I'm sure the meta discussion will quickly lead to an accepted proposal.

**Comment by journeym** [comment]
Omg is this really happening? Ppl just plainly ignore good design options?

**Comment by GlassedSilver** [comment]
Hello googlers and fellow users who would like to emphasize this is a relevant issue for them. (and arguably whether or not it's considered a bug it does lead to core functionality getting interrupted)

Please upvote, comment and or propose ideas/link PRs here:

https://features.jellyfin.org/posts/3367/dont-immediately-mark-a-played-episode-unplayed
