### ISSUE TITLE
Play trailer rather than show poster if one exists in the media folder

### ISSUE THREAD

**Issue by g33kphr33k** [jellyfin/jellyfin#766]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When you select a movie the background changes to the poster image. Most of my movies have a trailer in the folder with a naming convention. If the movie is called "Maleficent (2014, PG).mp4" then the trailer would be "Maleficent (2014, PG)-trailer.mp4". Should a trailer exist in the folder then this should be played in the background rather than the poster being displayed. At the end of the trailer, switch back to the poster.  This should be an optional feature to toggle on and off.

**Describe alternatives you've considered**
Plugins, but none exists.

**Additional context**
I believe there is enough detail above.  See Netflix for a good example of playing a trailer when you select a show although they do it on highlight rather than full show selection.

**Comment by sparky8251** [comment]
Not sure a plugin would work for this since a goal is to separate the web ui from the server and this is a large change in the web ui.

That said... Isn't there too much stuff on screen with actors and descriptions to make this useful? Feels like most if not all of a trailer would be covered up by images and text.

Wouldn't a "play trailer button" be more useful?

**Comment by g33kphr33k** [comment]
Actually, a play trailer button would work fine as it could then just open in a lightbox style window and play. The current play trailer seems to only run off to YouTube.
