### ISSUE TITLE
Reduce hard disk access during playback

### ISSUE THREAD

**Issue by d3f113** [jellyfin/jellyfin#7689]
It is amazing how hard my NAS is working during playback. Plex on the other side has nearly no hard disk activity. It would be great, to reduce it.
1. Hearing all the time the rumbling noises from my synology is not nice
2. It will definitely lower the lifespan of the disks
3. It is not necessary, as for example Plex shows it

Besides that, Jellyfin is quite nice, even if it has some bugs :)

**Comment by gbakeman** [comment]
I'd like to jump in on this issue since it has been affecting me for quite some time as well. On Jellyfin 10.8.4 in docker. I've only opened the server from a web browser and attempted to look at my library when the performance issues hit. Jellyfin appears to be maxing out my disk I/O (which to be fair, is not much) and it's causing the entire system to choke. It's not entire clear what exactly Jellyfin is doing (which this was shown somewhere in the dashboard, and the logs aren't terribly helpful with lots of delayed HTTP response errors indicating the slowdown.

**Comment by Shadowghost** [comment]
Do you save your artwork alongside your media?
Because Jellyfin does not cache local artwork but instead directly loads it from the respective directory

**Comment by gbakeman** [comment]
> Do you save your artwork alongside your media? Because Jellyfin does not cache local artwork but instead directly loads it from the respective directory

It looks like I have "Save artwork into media folders" unchecked. I've since rebooted the entire operating system that was hosting docker & Jellyfin, and suddenly it's responding incredibly fast. No idea why that would've fixed anything... In the future though, it would be nice if we could see what the Jellyfin backend was doing on our dashboard.
