### ISSUE TITLE
[Issue]: Folder wrongly identified as album

### ISSUE THREAD

**Issue by elettrico** [jellyfin/jellyfin#7704]
### During the scan Jellyfin add metadata, artists and songs to a folder which is not an album

I am scanning a library of mp3 organized in a directory tree like this:

```
.
├── Alfabetico
│   ├── A
│   │   └── [...]
│   ├── B
│   │   └── [...]
│   ├── C
│   │   └── [...]
│   ├── D
│   │   └── [...]
│   ├── E
│   │   └── [...]
│   ├── F
│   │   ├── Alberto Fortis - A voi romani.mp3
│   │   ├── Eugenio Finardi - Radio.mp3
│   │   ├── David Fiuczynski & John Medeski
│   │   │   └── 1994 - Lunar Crush
│   │   │       ├── 01 - Vog.mp3
│   │   │       ├── [...]
│   │   │       └── 10 - Fima's Sunrise.mp3
│   │   ├── Fabri Fibra
│   │   │   └── 2006 - Tradimento
│   │   │       ├── 01 - Rap In Guerra.mp3
│   │   │       ├── [...]
│   │   │       └── 17 - Cuore Di Latta.mp3
│   │   ├── Faithless
│   │   │   ├── Faithless - God Is A DJ (Astral Projection Remix)(1).mp3
│   │   │   ├── Faithless - We Come One (Sergio Machine Remix).mp3
│   │   │   └── Sunday 8 PM
│   │   │       ├── Faithless - Sunday 8 PM - 01 - The Garden.mp3
│   │   │       ├── [...]
│   │   │       └── Faithless - Sunday 8 PM - 11- Killer's Lullaby.mp3
[...]
```
mp3 files can appear directly under the letter or under the letter/artist or under the letter/artist/album.
Jellyfin can't assign correct metadata to folders, based on the example above I have the "Faithless - God Is A DJ (Astral Projection Remix)(1).mp3" with this id3 tag:
```
mp3info Faithless\ -\ God\ Is\ A\ DJ\ \(Astral\ Projection\ Remix\)\(1\).mp3
File: Faithless - God Is A DJ (Astral Projection Remix)(1).mp3
Title:   God Is A DJ (Astral Projection Track:
Artist:  Faithless
Album:                                  Year:
Comment:                                Genre:  [255]
```
correctly shown in jellyfish, but the album art was incorrect, it shows the cover from "tradimento" by "fabri fibra", other album present in the "F" directory. 
In fact, if I go to the Album, it contains all tracks from the "F" directory as the "./Alfabetico/F" was incorrectly identified as an album and its metadata shows: 
- the directory is "./Alfabetico/F"
- the name is "Lunar Crush", taken from the album by "David Fiuczynski & John Medeski", from the same directory
- the image from the album "Tradimento" by "Fabri Fibra", from the same directory

Basically it's like a "soup" of what jellifysh encountered during the scan of the "F" directory.
The same happened for the others directories.
I think jellyfish, when try to identify an album or an artist, must go up on or two level, no more, from the current mp3 position, or maybe ask for a pattern to identify. I think  maybe is better to simply ignore it if there's no id3 tag than have songs wrongly collected to enormous albums, or maybe create a "virtual album" having the same name of the directory ("F", in this case).

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Linux Mint 19.3 Tricia
- Virtualization: no
- Clients: Browser
- Browser: Chrome
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- Plugins: none
- Reverse Proxy: no
- Base URL: -
- Networking: LAN
- Storage: Local raid
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maxplosion** [comment]
In my opinion if I want to use a thing that requires xyz to be done, then thats how it is, and if I don't like that then I look for another thing.
I can ask for changes, or provide them myself e.g. as PR. but outside of that it imho. but maybe I'm weird and should be a little more entitled in that regard, who knows?

**Comment by elettrico** [comment]
Thank you for your opinion. I've posted this as an issue because I think it may contribute to build a better jellyfin, not as complaint of course (but maybe my english sounds a little rude, sorry if it's the case). 
I see your point and maybe you're correct: I can reorganize a over 2TB collection or I can look for something more flexible (any suggestion?). I already use Kodi in my media center but I think it's not the best solution for managing a music library.
Anyway, I think jellyfin is a very good project and I find its simplicity and lightness a very good reasons to use it.
Maybe some developer can think about my suggestions.
Thanks

**Comment by Maxplosion** [comment]
In general looking at your structure I think you would already be quite fine by just dropping the folders with letter 'A'  'B' and so on, that should be very easy and fast to test.
another approach, but that is much clicking could be to try to set each letter folder as root in your music library, that means that you then have 26 entries in your library folder settings, one for each letter.

best to try this with a smaller sample of your tracks maybe and easiest would be to spin up a new instance of jellyfin in docker for example, that way you can test around, maybe this way you can find a setup that you and also jellyfin like

**Comment by Maxplosion** [comment]
oh and for tools to organize you could (depending on the quality of your tags) use e.g. mp3tag to sort songs into artist/album folders.
if the tags are not super great, you can run your files through musicbrainz picard to tag them - clean tags are never a waste of time, as this not only helps you in jellyfin but all other tools too!

**Comment by derkington** [comment]
This sounds very similar to this issues which I logged https://github.com/jellyfin/jellyfin/issues/5517#issuecomment-859492435.  Everything worked pre Jellyfin 10.7.  Since upgrading plain folder does not work because folders are identified as artists.  I tried various combinations of putting library’s together as suggested above but none of them worked. My file layout structure has been around for about 15 years, and everything is nicely tagged. It’s a shame that this used to work and now it does not.

**Comment by basos9** [comment]
> You're correct, but generally speaking jellyfin is installed when a collection already exists, so what if I can't change directory structure or simply want another? Imagine having songs from more than 5.000 or 10.000 artists, or a lot of song I grouped by collections (ie: "the fabolous 80s"), maybe already indexed with other software (ie: kodi, installed on another pc, index these songs/albums correctly)? Assuming the root directory of the collection is the starting point to build metadata is not so flexible, and also taking songs and random metadata when it is not possible to deduce from the filesystem structure and/or tags for me is a bug. **My suggestions:**
> 
>     * consider the folder of the song as the "base", not the highest folder, I mean this structure:
> 
> 
> ```
> /Music
>     /Artist
>         /Album
>             01 - Song.mp3
>             02 - Song.mp3
> ```
> 
> is respected in my example above if you consider the file as the starting path and then go upper:
> 
> ```
> /Faithless (artist)
>     /Sunday 8 PM (album)
>         /Faithless - Sunday 8 PM - 01 - The Garden.mp3 (song)
> ```
> 
>     * let the user can configure a pattern (or a list of pattern) if he wants and don't force it to reorganize all collection to meet the structure jellyfin wants
> 
>     * let the user decide what the action should be if jellyfin can't identify a song
> 
>     * let the user decide the priority between metadata from filesystem structure or from external provider (like Musicbrainz)
> 
> 
> (for readers: sorry for my not-so.good english and sorry for mispelling jellyfin as jellyfish)

Hello, I have the same issue.
I also own a library which I polish and manage since almost 20 years ! And I have tried some music library software during this time (from winamp, amarok, audacious and my latest favorite for desktop clementine). There are two basic issues with big collections, scalability (search queries, player load time,..) and usability (how music is presented in regards to meta data, and album covers). 
I also try to correctly tag files. My directory structure is mostly Artist/Album based, organized under Genre folders. e.g.
```
LIBA/1_Legends/Jimi Hendrix/Jimi Hendrix (2000 - Experience)
```
but there are also "stray" files in the sence of directory structure like 
```
LIBA/1_Rock_Alt/Antimatter/Antimatter - Nowhere Destiny.mp3
```
and of course there are tags missing (never managed to finish this).

The thing with jellyfin is that something causes this huge "albums" to be created. Maybe some tag missing in a file that triggers album discovery and the retrospectively scanning all the children of the fake album ? 

For example something has created an "album" 
`/media/data/Music/LIBA`
where my mysic library is /media/data/Music and LIBA is a whole library (10k of songs) !!! 

I think this sound like a bug !

**Comment by baszied** [comment]
Just started to investigate the usability of Jellyfin and love what I see so far except for the Folder view of my Music collection.  Like others in comments above I have a huge collection of music an in my case I have them grouped by genre. Structure is  
- Genres - Artists - Albums

Since there's also a thing like music collections, I also have in a directory literally called 'Albums' in each Genre directory to have my 'Best of ' etc....   Anyway, I see that some Genres folders are recognized as artists and therefore the folder is populated with the MusicBrainz info related to that id. Take for example 

- [Pop Pop](https://musicbrainz.org/artist/3fc5be5e-3d8d-4901-9450-83115b890cd7) 
(Rapper from Houston, Texas.)

Wouldn't it be nice if one could simply mark individual folder as a 'Folder' and let the indexing logic ignore this one to be looked up and continues scanning it's subdirs ?

**Comment by Amunak** [comment]
This is definitely still an issue in one way or another. A very simple fix would be an option to just ignore folder names as a "metadata source" for any given library; that way it at least would never be *wrong* (you'd get metadata from the actual file metadata) and worst case you would have some metadata missing (using the filename as the song title).

**Comment by harlanx** [comment]
My music structure is categorized by genre however jellyfin during the scan seems to consider it as an album with multiple artists. I wish it had an option to rely on embedded metadata regarding album names to group and create the Album entries instead of relying solely on folder structure.

**Comment by basos9** [comment]
I am dissappointed to see this still persists. Anyway i realized jf is not still fitting for large musik collections . After a time with ampache i ended up using emby for now. Its closed source but free until now. :(
