### ISSUE TITLE
Bug when starting a stream via Emby app when playback via external player.

### ISSUE THREAD

**Issue by lolento** [jellyfin/jellyfin#777]
**Describe the bug**
When using "External Player" option via Emby Android App (3.0.27), server always starts Direct Play and then switches to transcode.  I think during this switching, stream is cut and drops back from the external player to the Emby app.  So unless the stream can be "Direct Play", we cannot use "External Player".

**To Reproduce**
1.  Select use External Player under playback profile in Emby app.
2. Start a stream from Emby app.
3.  Watch Jellyfin server behavior.
4.  Stream on Android phone should kick back to the app and refuse to start if any transcoding is needed.

**Expected behavior**
The stream should start on the external player on Android

**System (please complete the following information):**
 - Jellyfin Version 10.1.0
- Emby App Version 3.0.27

**Comment by lolento** [comment]
This issue seem to be fixed in 10.2.0.

Just tried it once and external player now work with the Emby App (compatible version).

**Comment by anthonylavado** [comment]
Hi @lolento!
We're glad to hear it's working again in 10.2.0. We're gonna close this for now since we don't *officially* support the Emby apps, and things may break further in future.

We do have some testing versions of the Jellyfin Android app available, if you'd like to try it. It's not perfect (I believe external player support is missing, for example), but we are working on that app pretty regularly - and we accept bug reports too!
