### ISSUE TITLE
[Issue]: [10.8.0 beta3] identify deletes manual added backdrops and covers

### ISSUE THREAD

**Issue by StevMaHo** [jellyfin/jellyfin#7782]
### Please describe your bug

If you use the identification for films that have already manually added covers and backdrops, and dont disabled the "replace existing pictures" it deletes them. No image is then displayed.
All image sources are disabled in the libary settings.

Normaly it wont touche them ( on 10.7.7 it didnt)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows
- Virtualization:
- Clients: Browser, Android
- Browser:Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:Anidb, Anilist
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
This was an intentional behavior change (#7078) in 1.8.0 when fixing (#7040): If identify is used jellyfin assumes either there is no metadata or whatever metadata it has is the result of a misidentification, so it clears it (and images, if checked) to ensure that old data isn't kept in the case of missing fields/images in the new metadata download.

To keep it from replacing the existing images you should uncheck "Replace existing images".

Alternately, depending on how you're running Jellyfin, you can restrict the Jellyfin user to read only access of the media directory to keep it from making any changes to what you've set up in the media directories.
