### ISSUE TITLE
[Issue]: core-dump 

### ISSUE THREAD

**Issue by uigse-g7x2u** [jellyfin/jellyfin#7796]
### Please describe your bug

I am trying to install jellyfin on fedora 36 but i am unable to start jellyfin after installing it: `sudo systemctl start jellyfin` followed by `sudo systemctl status jellyfin` returns:
```
× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/usr/lib/systemd/system/jellyfin.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─override.conf
     Active: failed (Result: core-dump) since Wed 2022-05-25 13:29:39 CEST; 13min ago
    Process: 13914 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} ${JELLYFIN_ADDITIONAL_OPTS} (code=dumped, signal=ABRT)
   Main PID: 13914 (code=dumped, signal=ABRT)
        CPU: 127ms

May 25 13:29:39 server systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
May 25 13:29:39 server systemd[1]: Stopped jellyfin.service - Jellyfin Media Server.
May 25 13:29:39 server systemd[1]: jellyfin.service: Start request repeated too quickly.
May 25 13:29:39 server systemd[1]: jellyfin.service: Failed with result 'core-dump'.
May 25 13:29:39 server systemd[1]: Failed to start jellyfin.service - Jellyfin Media Server.
```

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Fedora 36 Workstation
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Likely duplicate of https://github.com/jellyfin/jellyfin/issues/7471

**Comment by mihawk90** [comment]
All I can say is "works on my machine".

But in all seriousness how did you compile, what did you try... there's not a lot of info in your report. The official releases won't work on F36 for obvious reasons.

**Comment by telans** [comment]
You can inspect / get a backtrace from coredumps through `coredumpctl`. Find the coredump PID via `coredumpctl -r` and then `coredumpctl debug <PID>`. Then just type `bt` when in the gdb window.

**Comment by campagnolohedonist** [comment]
Hi, I seem to be having the same issue. Here is the info I could gather. If there is anything else I should look for/try and then share, please do let me know. 

### Problem
jellyfin.service fails to start
```
$ sudo systemctl status jellyfin.service 

× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/usr/lib/systemd/system/jellyfin.service; disabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Sun 2022-06-12 16:19:57 CEST; 9s ago
    Process: 3759 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAP>
   Main PID: 3759 (code=exited, status=137)
        CPU: 8ms

Jun 12 16:19:57 resonator systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Jun 12 16:19:57 resonator systemd[1]: Stopped jellyfin.service - Jellyfin Media Server.
Jun 12 16:19:57 resonator systemd[1]: jellyfin.service: Start request repeated too quickly.
Jun 12 16:19:57 resonator systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Jun 12 16:19:57 resonator systemd[1]: Failed to start jellyfin.service - Jellyfin Media Server. 
```
### How was Jellyfin installed
Followed the steps provided in the [Jellyfin documentation](https://jellyfin.org/docs/general/administration/installing.html#fedora). For steps 2 and 3 I used the rpm packages I built following the steps provided by @mihawk90 in [this comment](https://github.com/jellyfin/jellyfin/issues/7471#issuecomment-1122774664).
```
git clone https://github.com/jellyfin/jellyfin.git
cd jellyfin
git fetch origin pull/7614/head
git checkout -b pr FETCH_HEAD
cd fedora
make rpms
sudo dnf in jellyfin-server.rpm
```
```
git clone https://github.com/jellyfin/jellyfin-web.git
cd jellyfin-web
git fetch origin pull/3571/head
git checkout -b pr FETCH_HEAD
cd fedora
make rpms
sudo dnf in jellyfin-web.rpm
```
### System Info
Fresh install of Fedora 36 (KDE Plasma Edition) running on bare metal. Kernel 5.17.13-300.fc36.x86_64.
### Additional Info
Tried rebooting after enabling jellyfin.service, did not work. When running `coredumpctl` as suggested above there are no logs in the time window during which the service tried to start (and failed). When running `jellyfin` from terminal it seems to start without any issues and the web interface can be accessed through localhost:8096. I suppose the problem is therefore with the service unit and not with the package per se. Will do some experimenting to see if I can figure out how to fix the service unit with my limited knowledge (open to suggestions :D ).

**Comment by caleb87** [comment]
I had this issue, because my disk space ran out. Given that JF uses a huge amount of disk saving TS files, this is probably common. I think it would be a good idea to have an error message stating the disk is full.
