### ISSUE TITLE
LiveTV playback not starting

### ISSUE THREAD

**Issue by Maskedman** [jellyfin/jellyfin#78]
Playback on LiveTV not starting in chrome browser, server running Ubuntu 18.04 LTS, jellyfin installed via readme instructions.

HD Homerun tuner added successfully, SchedulesDirect added successfully, still not able to playback live tv at the moment. It works in emby premiere. 

Any ideas on what I should be looking at settings wise?

**Comment by drakus72** [comment]
Log files will help.

I have recorded over 40 shows so far and they all played back fine, I have also tried watching several shows and they are all playing back fine as well. I am running the docker version currently.

I haven't spun up a VM yet in my cluster at home to check installs on various *nix OS's. I will be doing that in the upcoming few days. 

I am going to try to test everything and do what I can testing wise to help determine any bugs along the way.

**Comment by dinki** [comment]
I think I'm seeing something similar.  Set up two HDHR devices and imported guide data.  Was able to watch live tv and recorded one tv program and one movie just fine.  I now click on the same station I watched previously and get a pop up reading 

`"Playback Error No compatible streams are currently available. Please try again later or contact your system administrator for details."  `

I get a spinning circle like something should be happening but the stream never starts.  I restarted the container and can watch live tv again.

Jellyfin running as docker container on debian.

Here's the log.  Live TV watch fail happens at the end of the log file https://www.dropbox.com/s/6gl1bvim0ni1eai/jellyfinlog.txt?dl=0

**Comment by drakus72** [comment]
Try 2 things, refresh guide and rescan media.

Also open VLC or whatever media player you have and see if this will stream http://192.168.0.44:5004/auto/v24.3

**Comment by dinki** [comment]
Will try this when/if it fails again and will report back.  Thanks.

**Comment by drakus72** [comment]
Please. I remember this happening in Emby and that was the easy solution & fix. Not sure what or why it caused it, but that did fix it in the past.

**Comment by dinki** [comment]
I'm coming from Plex so I don't know anything about Emby so you'll have to excuse my ignorance.  Can you tell me if this is something I can change on my end or was it something that had to be fixed in the code?

My primary goal for Jellyfin is to use it as a DVR and Live TV viewer.  As such, I really need the tuners to be rock solid in regards to availability.  I do understand that this is a very new venture and things may be rocky at the beginning.  Just wanted to share what I am wanting to use it for.  Thanks

**Comment by drakus72** [comment]
I so far am not having any issues, I am not sure if anyone else has been or if this was just a fluke.

I have recorded over 75 shows; up to 6 at one time so far, can do 8; so far with no problems and have watch about 2 dozen shows on live tv and recorded so far with no problems.

The 3.5 series of code has been rock solid and should still be, They are working on getting things as stable as possible with the hard fork and trying to do some updating as well. There will be some breakage due to the change over, etc, but I am sure they will be on top of things. 

Their first priority is making stable and solid, than working on on the updates and added features. There is a lot of work ahead so bear with them. I am just doing what I can to help with support as I can so they can focus on the coding and conversion.

**Comment by JustAMan** [comment]
Jellyfin uses ffmpeg under the hood to remux your files if needed and to serve them as HLS, might be your case here.

**Comment by Maskedman** [comment]
ffmpeg needed to be installed. Thanks to @RWING5 and @JustAMan for the hint.

**Comment by JustAMan** [comment]
@Maskedman can you please close the issue then, if your problem is solved?
I think latest `Jellyfin` builds contain dependency on `ffmpeg`, so that should no longer occur again.

**Comment by sparky8251** [comment]
Is this still an issue? 3 weeks later and we havent heard anything back. I'd assume we can close this, correct?

**Comment by joshuaboniface** [comment]
Closing due to lack of response - assuming fixed. Please reopen if not.
