### ISSUE TITLE
Transcoding media due to unsupported subtitles codec

### ISSUE THREAD

**Issue by YodaQ** [jellyfin/jellyfin#7809]
When playing back an mkv file with embedded subtitles that are either ASS or SSA the video is transcoded before it is being delivered to the client. This happens with the integrated player on the android client.
If you disable the subtitles play the video then re enable the subtitles the video will direct play and you will still get subtitles. 
The problem is not an issue on the web player but that has other issues such as subtitles being very out of sync. Subtitles not showing up until you disable then re-enable them which are worse problems.
The option to let the subtitles be delivered as plain text is enabled.

The issue is why is the whole video being transcoded when only the subtitles are a problem. I know that with ffmpeg you are able to just re-encode the subtitles. The phones also clearly supports the subtitles without re-encoding but the server still thinks that transcoding is needed.. 

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.7.7
 - Hardware settings & device: no hardware acceleration
 - Reverse proxy: no
 - Other hardware notes: Media mounted through nfs (problem also occurs on local storage).
 
**Client System (please complete the following information):**
 - Device: Android phones (Samsung Note 8 && Samsung A52)
 - OS: Android
 - Client: Android
 - Client Version: 2.4.4

**Comment by Nalsai** [comment]
Android does not support ASS/SSA subtitles correctly with the integrated player, which uses ExoPlayer. You can follow the issue here: https://github.com/google/ExoPlayer/issues/8435 It is slowly being worked on, but I don't foresee good support any time soon. 

The web player uses [JavascriptSubtitlesOctopus](https://github.com/libass/JavascriptSubtitlesOctopus) and from my experience there are some problems with sync, fades and sometimes lines being missing, although it is apparently supposed to work. 

You can't convert ASS/SSA without losing most features, except for basic text. In order to display them correctly, they have to get burned in to the video.

If your device supports the video format, I recommend installing mpv and using it as an external player for direct play. It even works with playback position and everything and it supports subtitles perfectly. Otherwise, transcoding the whole video is sadly the best option.

**Comment by YodaQ** [comment]
Thanks for the info although it would be great if there were an option where you could enable just using basic text instead of transcoding as some subtitles are in basic text they are just encoded in ass/ssa. Like subtitles on english media.

**Comment by Nalsai** [comment]
If someone is willing to program it (I could maybe do it during vacation), I'm sure that could be made an option in jellyfin-android. It looks like there is a rewrite in progress for the playback code, so it might have to wait until that is done.

**Comment by YodaQ** [comment]
Thanks this is why I really like Jellyfin due to its great community and the fact that all the options are there for power users to tweak and see what works best.

**Comment by YodaQ** [comment]
Possible inclusion of play subtitles in basic format to prevent trascoding option in the android app. If anyone is willing to code it.
