### ISSUE TITLE
[Issue]: file always being transcoded for audio channels 

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#7880]
When playing a media, i'ts now being always transcoded for audio.
I feel this is due to some changes made to match the transcoded channel to the player audio channels.

This prevents a lot of files to be directly played, wich consume ressources and delay the stream play.

This was not the case under Jellyfin 10.7 and never leaded to any problems on all my clients.

Is there any informations about the intentions behind this?
Is there a way to avoid the files being transcoded just for audio channel layout related things?

Thanks to every Jellyfin contributors!

### Jellyfin Version

10.8.0

### Jellyfin logs

```shell
"/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -fflags +genpts  -i file:\"/media/films/The Unbearable Weight of Massive Talent (2022)/The Unbearable Weight of Massive Talent (2022).mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/transcodes/51424adcee47c049c92f786ab9e07d78%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/transcodes/51424adcee47c049c92f786ab9e07d78.m3u8\""
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ajkid93** [comment]
I too have this error. A temporary fix is to have two accounts one for direct play and one for transcoding. I disable all transcoding for the one user and the other it is left enabled. It can be adjusted in the user settings (admin panel). I found when transcoding is enabled and watching dolby vision stuff and true hd is an option, it transcodes the audio and then transcodes the video. When I switch to a lower quality audio it has no issues playing dolby vision or the audio with direct play. But as I said the fix was to disable video/audio muxing and transcoding. Which means if you want transcoding ever you have to reenable it or in my case have two users.
