### ISSUE TITLE
Randomized UDP may need to be open for DLNA renderer detection to work

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#790]
My Jellyfin setup was unable to detect my Sony Blu-Ray player as a DLNA renderer until I opened the randomized UDP port that was previously thought to be only used for live TV in my local firewall.

I discovered this by running a JF server on my laptop and capturing all traffic to/from the Blu-Ray player. Presumably after some kind of unicast discovery, which I filtered out, the player starts sending what seems to be HTTP data to the randomized UDP port on the server.

This obviously makes setting up firewall rules pretty hard, is there any way we can instead hardcode the port without breaking anything?

**System (please complete the following information):**
 - OS: Docker on Debian 9 (with host networking)
 - Jellyfin Version: 10.1.0

**Comment by JustAMan** [comment]
Should we make this configurable, so it's possible to keep this port as random or have it fixed?

**Comment by JustAMan** [comment]
This looks like the reason for needing `--net=host` on docker for DLNA, isn't it?

**Comment by LeoVerto** [comment]
@sparky8251 I'll try to confirm this once I've got a bit more time but I'm pretty confident that port is required.

Where in the codebase is listener even created opened?

> This looks like the reason for needing --net=host on docker for DLNA, isn't it?

Pretty sure that's mostly for DLNA discovery on port 1900 which requires multicast packages to work and thus all devices to be on the same layer 2 network.

**Comment by sparky8251** [comment]
Looks like it has 2 potential bind points actually...?

One in `Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs` that can be found by searching `GetRandomUnusedUdpPort()`

And a second in `Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs` that can be found by searching for `public static int HdHomeRunPort = 65001;`

Since it binds the random one last I knew, whats the point of the 65001?

**Comment by gdm85** [comment]
> Since it binds the random one last I knew, whats the point of the 65001?

@sparky8251 that is used to check the availability of the endpoint, see
https://github.com/jellyfin/jellyfin/blob/ac9dfa8e93106d907bbf78fe2350adfa47c76cec/Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs#L110

So it's not used to open a port but to connect to one, which I assume is standard for that type of tuner host.

> _Should_ be easy to pick a consistent port and modify it to use that instead. Do we have a port number we can agree on?

I think there should be a configurable port range (one port might not suffice), otherwise it's impossible to create firewall rules for Jellyfin; I checked with a Philips smart TV and it does try to connect to random UDP ports (failing if you have a firewall).

**Comment by JustAMan** [comment]
@gdm85 since you have brought this up and seem to have a set up, can you disable https (so no ssl) and try capturing packets to see if it's a TV that chooses a port, or does it get this port from JF server via some API response?

**Comment by gdm85** [comment]
> see if it's a TV that chooses a port, or does it get this port from JF server via some API response?

Reverse engineering is not necessary, the UDP port is being chosen here: https://github.com/jellyfin/jellyfin/blob/e44a7ae3f60f95a6233690d77df326038d8f50fc/Emby.Server.Implementations/Networking/NetworkManager.cs#L424

See C# documentation: https://docs.microsoft.com/en-us/dotnet/api/system.net.ipendpoint.-ctor?view=netframework-4.8#System_Net_IPEndPoint__ctor_System_Int64_System_Int32_

> `port` Int32
> The port number associated with the address, or 0 to specify any available port. port is in host order.

So in order to select from a range instead we could use something like this: https://gist.github.com/jrusbatch/4211535#gistcomment-2754532

(Racy, but workable if there is some retry mechanism in place)

**Comment by PrplHaz4** [comment]
Looks like we could use some logging here to assist w/troubleshooting:
https://github.com/jellyfin/jellyfin/blob/48120d01dc1b73f58eb3b2c17530622320624721/Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunUdpStream.cs#L51

I can't seem to get this line to trigger w/my HDHR:
`Opening HDHR UDP Live stream from {host}`

**Comment by BaronGreenback** [comment]
Have added this to PR #3789.

Will add into testing units.

**Comment by BaronGreenback** [comment]
This functionality will be added to unstable as soon as 10.7 is released.

**Comment by srcrist** [comment]
Issue closed by https://github.com/jellyfin/jellyfin/pull/4124
