### ISSUE TITLE
[Issue]: Episode titles being truncated incorrectly

### ISSUE THREAD

**Issue by sxales** [jellyfin/jellyfin#8096]
### Please describe your bug

Since updating to 1.8.0 (also 1.8.1) that Jellyfin no longer displays full filenames by default.

I have episodes that follow the format:

    SeriesName Year S##E## EpisodeTitle CodecInfo.FileType

Previously when displaying a season Jellyfin displayed these file names in full; however, now it truncates them so it just lists the series title over and over like this:

![Screenshot 2022-07-09 at 22-38-11 Jellyfin](https://user-images.githubusercontent.com/29420152/178157321-c851198f-5e64-477c-8043-6c34be822198.png)

Obviously this is not very useful. For seasonal episodes it is at least putting them in the correct order but the specials and special features it is chaos. 

If the series doesn't have a year it seems to truncate after the episode number unless the series has more than a thousand episodes (like One Piece) in which case it cuts off the episodes number.  Whatever code was added in 1.8.x to clean up the displayed filenames is not working ideally. 

This only affects files added after updating. The preexisting library still displays correctly.

I don't see an option in the library settings to turn this truncation off and I would hate to have to manually edit every episode's title.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 10
- Clients: All
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxales** [comment]
I just checked 10.8.9 and I am still having the same issue.

**Comment by oddsoul** [comment]
Also seem to be experiencing this issue on 10.8.7 where the names are cut off when browsing

**Comment by BatCountry** [comment]
This is still affecting 10.8.10.  Could we get a comment on whether this is how the feature is intended to work?

**Comment by sxales** [comment]
I can confirm, on my end anyway, that it is still happening in 10.8.10. If no episode metadata is present, those episodes are displayed as _series title_ instead of the filename (as they had been previously).

**Comment by srcrist** [comment]
To be clear: Everyone in this issue is using a metadata provider together with the naming and organization convention documented here: https://jellyfin.org/docs/general/server/media/shows. Correct? The purpose of the file names is strictly for the parser to match the media with metadata provided by your configured providers. Any metadata parsed from the file name itself is a best effort process and not the intended workflow. The expectation is that metadata would at least be provided by local NFO metadata files if an external provider is not used.

Is this the case?
