### ISSUE TITLE
Update interlaced video detection

### ISSUE THREAD

**Issue by gaudat** [jellyfin/jellyfin#8216]
Hello @dmitrylyzo I stumbled upon this issue when finding why MP4 test videos generated by ffmpeg is recognized as interlaced in Jellyfin.

I used the following command to generate the video:
```
/c/Users/anon/Apps/ffmpeg/bin/ffmpeg -re -f lavfi -i "smptehdbars=rate=30:size=1920x1080" \
-f lavfi -i "sine=frequency=400:sample_rate=48000" \
-vf setparams="field_mode=prog",drawtext="text='1080 30fps h264 mp4 %{pts\:hms}':rate=30:x=(w-tw)/2:y=(h-lh)/2:fontsize=48:fontcolor=white:box=1:boxcolor=black" \
 -to 10 -c:v h264 -profile:v baseline -pix_fmt yuv420p -preset ultrafast -tune zerolatency -crf 28 -c:a aac testvid.mp4
```

This video along with the 2 of yours do not have a "fiel" atom in the file structure. In this case ffprobe will report the video as neither interlaced nor progressive.

It is unlucky that the timebase duration is the same as half of the video frame duration in our videos. I have yet to find a way to change it in ffmpeg.

One has to bend ffmpeg in weird ways to make it spit out a interlaced H264 video as shown in this SO question... [Link](https://superuser.com/questions/1344442/ffmpeg-how-to-create-an-interlaced-h-264-video)
ffmpeg's "interlace detection" is unreliable. It detects @dmitrylyzo 's interlaced video as mostly progressive, while my supposedly interlaced video is undetermined.

It is pretty rare to see interlaced video in this age of digital streaming. I think the last device I used that gives out interlaced video is a camcorder made in 2011. Is it time to change the default from interlaced to progressive, or to whitelist modern codecs (H264/H265/VPx) such that these are progressive by default?

_Originally posted by @gaudat in https://github.com/jellyfin/jellyfin/issues/6222#issuecomment-1207285585_

**Comment by orryverducci** [comment]
Progressive **is** the default.

Video is only handled as interlaced if FFprobe reports it as being interlaced, or in the case of #6222 if the file is a H.264 coded MP4 and the timebase is exactly half the framerate, which was put in as a workaround due to FFprobe not always reporting these files are being interlaced when they are.

Also SD and HD broadcast television is interlaced, so it is still much more common than you may think.

So I believe the detection is already the best it's going to be, at least until such a time that FFprobe fixes the interlace reporting for MP4 files or Jellyfin uses something else to probe the files.
