### ISSUE TITLE
Is jellyfin under GPLv2+ or GPLv2 only?

### ISSUE THREAD

**Issue by natewrench** [jellyfin/jellyfin#8226]

**Comment by joshuaboniface** [comment]
This is a very complex topic because, frankly, Emby's license hygiene was abysmal.

The code we inherited was officially licensed as GPLv2, but with no clear indication of whether this was 2-only or 2+. However, this codebase also directly included forks of other tools that, taken together, meant that the compiled binaries that resulted *must* have been licensed under the GPv3 (specifically, because of several Apache 2.0-licensed inclusions there).

Due to the complexity and ambiguity of this, early on we reached out to the Software Freedom Law Center, but never did get any sort of response, so we've been operating under a "GPL unversioned" model for the code (effectively, then, 2+) with the binaries under GPLv3; no code authors have complained so far, I suppose because it would require them to explain why the license hygiene was so bad (or admit to violating the licenses of several other projects). We've avoided changing the `LICENSE` file in any way since its history is absolutely critical to our argument/defense here, and while we have removed a large number of these in-repo inclusions, I believe we do still included at least one Apache 2.0-licensed library, or at the very least, we have a clear chain of changes back to when this was decided.

If there's a *specific* thing that is concerning about the license, please don't hesitate to ask.
