### ISSUE TITLE
[Issue]: unexpected maxrate when transcoding H264->H265

### ISSUE THREAD

**Issue by TheTyrius** [jellyfin/jellyfin#8344]
### Please describe your bug

Hello,

I have set a bitrate limit of 16mbps for out-of-network devices.
Recently I set my Jellyfin Media Player device profile to prefer h265 encoding to get the best quality at this rate.

This usually works as expected using the maximum allowed bitrate. With a H264 source file (with high bitrate) I noticed that the playback info showed a bitrate <16mbps and wondered why that would be.

I think this happens here: https://github.com/jellyfin/jellyfin/blob/33611614ed3362bd6b9b83781a47927fc16bba5a/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L1970-L1980

`ScaleBitrate` leads to a 40% reduction in bitrate. This seems sensible generally (as a sort of "equivalent" bitrate to h264).
I would propose to disable this "if" block in the case of `TranscodeReason.ContainerBitrateExceedsLimit` as in this case I would expect the transcoding to use the maximum allowed bitrate regardless of input/output codecs.

Let me know what you think about this behaviour, and thank you for spending time on jellyfin development :)

Best regards,
Tyrius

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: any
- Virtualization: no
- Clients: JMP
- FFmpeg Version: 5
- Playback Method: transcoding
- Hardware Acceleration: NVENC
- Reverse Proxy: haproxy
- Networking: Bitrate limited
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
I have awared of this behavior may hurt the video quality when it comes to transcoding from a well optimized H.264 video to HEVC by using HW encoders or the libx265 SW encoder with `veryfast` preset.

The cause is that some HW HEVC encoders or presets cannot achieve the target of saving 40% bitrate while maintaining the same quality of the source H.264 video. But it's indeed saving a lot bandwidth when you are in a not that fast network connection.

So I suggest you add a transcoding option on the server side so that the user can choose whether to automatically reduce the bitrate when transcoding to a more advanced video codec. This change may also apply to future AV1 encodings. Also, when transcoding from HEVC to H.264 instead, it's best to keep the current behavior of always upscaling the bitrate.

**Comment by TheTyrius** [comment]
Right, ideally the overall "scaling" would be configurable. In the short-term I'm out of my depth for that though.
For this issue my primary concern was the case of a bandwidth limit for out-of-network devices: If the reason for the transcode is exceeding the limit, imo it would seem logical to utilize the maximum allowed bandwidth (regardless of codecs). Please let me know what you think about that.

**Comment by TheTyrius** [comment]
From my re-tests I observe the same with latest JMP 1.7.1 and server 10.8.9:
H264->H265 transcoding bitrate is 0.6 * "Internet streaming bitrate", instead of using the full "budget" provided by the streaming setting.

I humbly request the issue to stay open, if only to remind me again about becomeing stale (some day I'll hopefully find the time to poke into the codebase myself).
