### ISSUE TITLE
[Issue]: 10.8.4 prevents Synology NAS from hibernating HDDs

### ISSUE THREAD

**Issue by Rybeusz100** [jellyfin/jellyfin#8437]
### Please describe your bug

After upgrading from 10.7 to 10.8.4, HDDs on the Synology DS920+ no longer hibernate.
I'm using the official jellyfin/jellyfin docker image, I have mapped /config and /media folders to shared folders.
I lost my previous settings, because I've not mapped the /config folder on 10.7, but I can't find anything that I could've changed then, that could have an impact on hibernating HDDs

### Jellyfin Version

10.8.4

### Environment

```markdown
- OS: DSM 7.1-42661 Update 4
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Host
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WarhawkCZ** [comment]
I face the same issue using the same system and hardware. Any resolution?

**Comment by AleksandrShchegolev** [comment]
I can also confirm this problem with hibernation on the same hardware, Synology DS920+ (DSM 7.1.1-42962 Update 4), running an official jellyfin docker image. I should note that this issue is not specific to version 10.8.4 and occurs in subsequent releases (I observed it on 10.8.7, 10.8.8 and 10.8.9). Shutting down the container restores the hibernation. I've tried to set the minimum log level to `Error` in `logging.default.json` and also set a specific period for all jellyfin tasks but all these steps haven't helped the issue.

**Comment by matmielke** [comment]
Same problem here on a DS916+.
I'm running the synocommunity Jellyfin package, not the docker file. But I guess there shouldn't be a huge difference in hibernation behavior.
Is there any chance to get a solution?

**Comment by C2gl** [comment]
I also have the same issue on my synology ds1019 running dsm 7.2 

My jellyfin is running as a syno comunity package too, i suspect it could be because jellyfin writes continuously in the config or log files? Even when no one uses the service, but from the nases perspective the drives where accessed, thus itcant hybernate , maybe there could be a way to ignore some folders from being factored in when going trought the inactivity countdown?

**Comment by antoineguillou** [comment]
Same issue with jellyfin 10.9.6 in a docker container on a synology running dsm 7.2

**Comment by felix920506** [comment]
Does anyone here have the media and the application data saved on the same pool?

**Comment by AleksandrShchegolev** [comment]
> Does anyone here have the media and the application data saved on the same pool?

I have one storage pool with one storage volume on my NAS with docker volumes configured as:
```
/volume1/docker/jellyfin/cache:/cache:rw
/volume1/docker/jellyfin/config:/config:rw
/volume1/media:/media:rw
```
Hope this answers your question.

**Comment by cvium** [comment]
> > Does anyone here have the media and the application data saved on the same pool?
> 
> I have one storage pool with one storage volume on my NAS with docker volumes configured as:
> 
> ```
> /volume1/docker/jellyfin/cache:/cache:rw
> /volume1/docker/jellyfin/config:/config:rw
> /volume1/media:/media:rw
> ```
> 
> Hope this answers your question.

Jellyfin will often read/write to cache and config. If everything is on the same disk, it can't really hibernate the disk

**Comment by felix920506** [comment]
If the database is on the HDD then there's really not much we can do about it. Please move Jellyfin program files to a SSD.

**Comment by beipink** [comment]
> If the database is on the HDD then there's really not much we can do about it. Please move Jellyfin program files to a SSD.

isn't this a regression from 10.7 to 10.8.4? It's a serious problem that will shorten the life of disks and NAS

**Comment by damtt** [comment]
It's not only happening on Synology NAS; I have an Acasis EC-7352 enclosure with Jellyfin installed on my SSD using Docker. The HDD enclosure never goes to sleep until I stop the Jellyfin container. It took me a couple of days to figure out what was preventing my HDDs from sleeping.

Please help look into this issue.
Many thanks!

**Comment by MacTheCodeMonkey** [comment]
Seeing this same issue with Synology DS920+ and JellyFin 10.11.3.  Very disappointing that this is dismissed as won’t fix when competing offerings can hibernate the drives correctly, and previous older versions worked too.  No attempt to even explain why this is “unfixable” after working previously.
