### ISSUE TITLE
[Issue]: Can connect to Chromecast, but playing any media throws an error

### ISSUE THREAD

**Issue by Taewan-P** [jellyfin/jellyfin#8457]
### Please describe your bug

So I have been reading a lot of Chromecast connection issues and Chromecast playback issues from GitHub and Reddit. However, the bug that I'm facing hasn't been reported a lot, and also there were no clear working solutions.

I am able to connect to my Chromecasts via Android app from the Play Store and Chrome browser. However, when I try to play something, it would say `Your Google Cast receiver is unable to contact the Jellyfin server. Please check the connection and try again.`

What I discovered and couldn't figure out what's going on.
* There were no console errors on the browser
* There were no requests that got blocked. (or any other 4xx or 5xx requests. Only 200)
* The Chromecast remote controller from the jellyfin ui showed no information. (No play button, and etc) However, when I manipulate the volume button, it would say `Uncaught TypeError: Cannot read properties of undefined (reading '0')` from `playback-queue.xxxxxxxx.chunk.js:1`
* `cast_sender.js` loads successfully when I refresh my browser.

What I am using as my environment:
* I do have https connection from outside the server, cert signed from LetsEncrypt.
* I applied reverse proxy with traefik using CNAME (for subdomain).

Is there anyone that is facing this issue?

### Jellyfin Version

10.8.0

### if other:

10.8.4

### Environment

```markdown
- OS: Linux (TrueNAS)
- Virtualization: Docker
- Clients: Android, Browser
- Browser: Chrome 105
- FFmpeg Version: 
- Playback Method: Just won't play
- Hardware Acceleration: none
- Plugins: [AniDB, AudioDB, Email notifications, MusicBrainz, OMDb, Open subtitles, Studio Images, TMDb]
- Reverse Proxy: traefik
- Base URL: none (all pages)
- Networking: 
- Storage: local
```

### Jellyfin logs

```shell
No logs when connecting to Chromecast, and also no logs when clicking any media.
```

### Please attach any browser or client logs here

No special logs

```
Requesting https://subdomain.mydomain_url/web/configurationpage?name=AudioDB
Requesting https://subdomain.mydomain_url/Plugins/a629c0da-fac5-4c7e-931a-7174223f14c8/Configuration
Requesting https://subdomain.mydomain_url/Plugins
Requesting https://subdomain.mydomain_url/web/configurationpages?pageType=PluginConfiguration
Sending web socket message: Keep Alive
```

### Please attach any screenshots here

![jellyfin_error](https://user-images.githubusercontent.com/27392567/192226042-f33c3c81-3b89-4e17-9854-51e277704bfb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mirolm** [comment]
I had the same issue when i configured my chromecast. I had my jellyfin server configured to my domain (jellyfin.site.com pointing to xxx.xxx.xxx.xxx) and i had made a local dns record in my router (jellyfin.site.com pointing to 192.168.88.xxx) for my local network. 

Issue is that chromecast uses google dns servers and resolves your jellyfin according to your domain records ignoring secords you set into your router. This can be fixed with hairpin nat in your router. It's something like port forwarding but for your local network. Wherever someone requests your real ip router will forward that traffic to your jellyfin server in your local network.

If your case is the one i describe the above hairpin nat can fix your issue.

**Comment by Taewan-P** [comment]
@mirolm  Hmm...

I setup my network as mysite.com to xxx.xxx.xxx.xxx (A record), and
jellyfin (CNAME) pointing to mysite.com. (This is done in DNS record editing page, not local dns router)
mysite.com is pointing to my server, with traefik and I hame my CNAME pointing to my server as well because I use reverse proxy.

* Would this configuration not work?
* To solve this issue, do I need an actual A record pointing to the container? (Which AFAIK, is impossible with my case)

**Comment by KptCheeseWhiz** [comment]
I had the same problem where my internal DNS server was giving a different IP from an external one. 

If you have a linux device connected with ethernet and your chromecast is also connected with ethernet (some models have an ethernet port on their powerbank), you can do some ARP spoofing to intercept the DNS requests to your internal server.

Here's a gist that does it for you using dsniff on Ubuntu (do not forget to enable ipv4 packet forwarding)
https://gist.github.com/KptCheeseWhiz/94922c4151edac3a510d46627ee5ec39

**Comment by EmixamPP** [comment]
I'm exactly in the same situation and configuration than you @Taewan-P 

> Packets cannot automatically go outside and return back inside once again.

In fact, lots of router implements loopback which avoid such issue. This is my case, and yet I have this issue :cry:

**Comment by EmixamPP** [comment]
No issue when bypassing traefik (direclty using the https port and a certificate). 
So this is caused by the reverse proxy. When I have some time I'll try to talk with the TrueCharts maintainers (I guess you also use that).

**Comment by BloodyIron** [comment]
I'm in a similar boat here and have been trying to figure this out for weeks. And no, I will not enable Hair-Pin NAT as pfSense (my gateway) has it off by default for security concerns (and I trust pfSense dev's to know good practices of such things).

The Chromecast devices, and my clients (android app in this case) are on the "general LAN". The jellyfin container runs in a k8s cluster behind MetalLB (Layer 2) and Nginx Ingress (Layer 7), so there's a single IP that handles in-bound traffic for the k8s cluster, which in this case since we're dealing with HTTPS, uses SNI to ensure the right traffic goes to the right pod (based on the FQDN, in this case jellyfin.domain.com or whatever). Also, using Let's Encrypt certificates everywhere.

Additionally, I'm using split-horizon and reverse-proxy configuration outside the k8s cluster, for the "general LAN", so FQDNs result in the same service functionality whether I'm on the LAN, or on the public internet.

In the case of my Jellyfin set up, I have the reverse-proxy in-front of the k8s cluster. Again, the website traffic works, and goes through this reverse-proxy.

I have gone through so many configuration permutations, I am losing my mind trying to figure out how the fuck to get Jellyfin (android) to Chromecast to my... Chromecast. The error is the same of OP "...Chromecast cannot connect to your server...".

1. I'm not doing hair-pin NAT, again, security problems, unacceptable solution
2. I'm not blocking 8.8.8.8 or 8.8.4.4 per-IP in this case as that's also an unacceptable (and sloppy) solution

Can anyone give me some sort of additional options here? Please?

**Comment by Bond-009** [comment]
Not a Jellyfin bug

**Comment by BloodyIron** [comment]
@Bond-009 can you please explain before closing the issue? I have generally given up on chromecast currently for Jellyfin in a docker container in my kubernetes cluster. Knowing why you believe this is not a Jellyfin bug is worthwhile.

**Comment by Bond-009** [comment]
Like @mirolm said, it's a network config issue.
Unless you can prove it's really an issue with the server and not your config in which case I'll reopen this.

**Comment by BloodyIron** [comment]
What they said is speculation, not proof or evidence, and IMO not worth closing this thread. The FQDN on my LAN resolves to the appropriate LAN IP, not the public IP. Jellyfin connects to the Chromecast and loads the splash screen, but when telling Jellyfin to load media, it goes no further. Nothing in the logs so far as I have seen has shown why, let alone whether what @mirolm is relevant to the issue.

Clearly the Chromecast and Jellyfin are able to communicate bi-directionally, otherwise the handshake would fail and I wouldn't be getting as far as the splash screen.

**Comment by 1337joe** [comment]
My understanding of this is that connecting to the chromecast for control (such as when you get the splash screen) is direct, but media streams are resolved differently from the chromecast side (via google DNS) so it's easy for it to just not find its way back to your server if you've got an extensive custom networking configuration. Furthermore, since it's the chromecast reaching out for the stream and not finding the right place you don't get anything logged because the messages aren't getting to you and you can't see what's going on inside the chromecast.

That's all been consistent with my experience hooking chromecast up to use with my home assistant and jellyfin installs running in podman.

I don't have anything approaching your network complexity so there's precious little I can do to debug it. You can try taking DNS out of the equation for a test: Connect your jellyfin app directly to the ip/port of jellyfin, skipping the reverse proxy, https, everything. Try to cast and see if it works. Add things in a layer at a time to see when it breaks.

Regardless, all the fixes suggested above are outside the scope of what Jellyfin controls. There's nothing for us to fix in the server so this issue was closed.

**Comment by Nebula83** [comment]
I just ran into the exact same issue, trying jellyfin for the first time. I run Jellyfin in a container, my hostname is behind a Traefik edge router. I use a domain name behind a custom top-level domain name just because it's cool. That domain name will definitely not resolve outside my home. The 2-minute solution was to just use the internal IP address and port, which fixed it for me. No idea how to set it up behind `jellyfin.tld`, but that is indeed a networking thing, and something for my router to resolve somehow.

**Comment by ReallyPhil** [comment]
I ran into this same problem and can confirm the theories in this issue.  Google home uses Google DNS to lookup your jellyfin domain to figure out how to connect to it even if your router advertises different DNS servers.  So if your jellyfin domain can't be looked up from 8.8.8.8 then it'll fail to play media.

The easiest solution for me was to use my firewall to block external DNS queries from my google home.  This forces it to use my network's actual DNS servers (pihole) which resolves the domain to an internal LAN IP and everything now works fine.

**Comment by osexpert** [comment]
Have the same problem. But why does it work to cast from other apps? I have VLC on my Android phone, it can cast without problem. LocalCast can too. Plex can too! Everything else can!

**Comment by BloodyIron** [comment]
So I tried blocking 8.8.8.8 and yeah the situation didn't improve.

I seriously, after like going on 6 months now... cannot get this working. What the fuck am I missing here?!?!?

**Comment by kumarjola** [comment]
@BloodyIron: can you check this comment on Reddit and see what localaddress your Jellyfin server publishes via the System/Info/Public API endpoint?

https://www.reddit.com/r/jellyfin/comments/gkui48/unable_to_cast_from_android_app_to_chromecast/fqtls3w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Maybe you are in the same boat as me whereby the localaddress reported there is actually the internal address inside the container, so nothing that is accessible to a chromecast...

If you find a way (other than the NGinx rewrite explained in the reddit thread linked above) to change that localaddressvalue to the actual URL that should be used to access the Jellyfin server, please let me know...

**Comment by Taewan-P** [comment]
@kumarjola Nope. I just checked and it is my subdomain.domain.com address I use. (It isn't even IP address btw)
The problem is it connects to the Chromecast successfully, but when I try to play it, it will throw an error before casting anything.

**Comment by kumarjola** [comment]
@Taewan-P : thanks for your comment... it forced me to look a little deeper.
So now I have found a way to change the localaddress value returned by Jellyfin API.
It can be done via the server configuration UI

![image](https://github.com/jellyfin/jellyfin/assets/38747843/eed848cd-165d-49f9-b36e-10c9fb88e81d)
See also:
- https://www.reddit.com/r/jellyfin/comments/rnltr8/what_does_those_networking_settings_do/
- https://github.com/jellyfin/jellyfin/pull/3994

But casting to chromecast still does not work!
However, I do not get the "The google cast receiver is unable to connect to jellyfin server" error message anymore on the android app so it seems to have some effect!

**Comment by BloodyIron** [comment]
> @BloodyIron: can you check this comment on Reddit and see what localaddress your Jellyfin server publishes via the System/Info/Public API endpoint?
> 
> https://www.reddit.com/r/jellyfin/comments/gkui48/unable_to_cast_from_android_app_to_chromecast/fqtls3w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> 
> Maybe you are in the same boat as me whereby the localaddress reported there is actually the internal address inside the container, so nothing that is accessible to a chromecast...
> 
> If you find a way (other than the NGinx rewrite explained in the reddit thread linked above) to change that localaddressvalue to the actual URL that should be used to access the Jellyfin server, please let me know...

"LocalAddress"="https://correct.domain.com" and "ServerName"="correct.domain.com" are the values reported at that endpoint "correct.domain.com/System/Info/Public". But it was doing that without the nginx return 200 override, and the "add_header Content-Type "application/json; charset=utf8";" part (adding it) did not improve the situation (so I'm going to remove it).

Just to re-iterate, since it's been a while, I know my environment is complicated, and at this point I'm not sure if I'm missing something basic, but it roughly goes like this.

Chromecast/Android device -> nginx reverse-proxy (in VM, outside of the k8s cluster) -> k8s cluster, but first step is the Metal LB Layer 2 (ARP) IP (this IP is an IP outside the cluster and is on my LAN, again outside the k8s cluster) -> Metal LB then sends HTTP/HTTPS traffic to -> NGINX Ingress, which the Deployment/related for Jellyfin is configured to reverse-proxy the HTTPS traffic for correct.domain.com to -> Jellyfin Service -> Jellyfin Deployment

The internal IP range in the k8s cluster is 10.0.0.0/8, and I don't manage it at all, it is auto-defined when the cluster was created and I let it manage itself.

Additionally, I do believe I still have my (testing) Chromecast device blocked from reaching 8.8.8.8, but since I cannot SSH into the Chromecast to manually verify, I need to trust it.

Additionally, my gateway does DNS resolution override, and correct.domain.com resolves to the IP of the **Nginx Reverse-Proxy VM** and this is even the case within the Jellyfin Pod/Deployment (it resolves to the Nginx Reverse-Proxy VM). I tried adding a host-override for the Deployment, having it resolve (within the Pod/Deployment) to the Metal LB Arp IP, but that didn't seem to improve things.

Additionally, when I watch the Jellyfin logs, most of what I see (which is barely any logs at all) is "Slow HTTP response from https://correct.domain.com/Users..." and a few other similar entries. But none of the logs seem to show the IP of the Chromecast itself (which I have reserved to a DHCP-assigned "static" IP for the testing Chromecast's MAC Address).

I know that my situation is esoteric and not-typical, but I'm really trying to drink the k8s kool-aid here, and I want to do more k8s stuff over time.

Anything I'm missing maybe??? :(

**Comment by BloodyIron** [comment]
Oh I also had "LAN networks:" (setting in Jellyfin webGUI) previously set to the LAN IP subnet (outside the k8s) which is a /24, however I removed it and left it blank. This did not seem to improve the situation...

**Comment by BloodyIron** [comment]
It really would be nice to know all the settings and configurations one _should_ use here, and the Jellyfin documentation really seems extremely lacking/insufficient in this regard. :(

**Comment by BloodyIron** [comment]
@kumarjola 

**I THINK I JUST FIGURED IT OUT!!!!!!!!!!!!!!**

Okay so here's how I think I figured it out... I looked into the DNS that Chromecasts use and discovered that they supposedly use 8.8.8.8 AND 8.8.4.4 . And at that point my router/gateway (pfSense) was only blocking 8.8.8.8 via a firewall rule specific to this single testing Chromecast (which also in pfSense I defined the static-via-DHCP assignment for the MAC Address for my testing Chromecast).... so... I then added a rule to block 8.8.4.4 for the testing Chromecast device, unplugged power for the testing Chromecast device, plugged it back in, and... uhhh... the device never "completed initialisation". In-that, it never showed the time, what network it was connected to, I could not see it as an endpoint to use (Jellyfin app/otherwise) but I could see other Chromecast devices... it like... never finished initialising...

So I did more digging about Chromecasts, DNS, pfSense and such, and found that other people report _actual success_ (not specific to Jellyfin) with using DNS NAT Port Forwarding instead! ( the last reference that got me working: https://www.reddit.com/r/PFSENSE/comments/ms6i8d/spoof_google_dns/ )

So I disabled the DNS blocking rules for the testing Chromecast device to 8.8.8.8 and 8.8.4.4 and set up the DNS forwarding as per pfSense documentation, except declaring the source IP of the testing Chromecast device, which is empty as a value by default and the pfSense documentation ( https://docs.netgate.com/pfsense/en/latest/recipes/dns-redirect.html ) does not cover.

Hit apply config. Power cycle Chromecast. Jump on phone with Jellyfin app.... connect to Chromecast... play test media...

IT. WORKS.!!!!!!!!!!!!!!

And as of this writing I do believe it is still going through my NGINX Reverse-Proxy VM as per the earlier description, not directly to the Metal LB ARP IP (the NGINX Reverse-Proxy VM points this traffic to the Metal LB ARP IP via "proxy_pass" declaration method (typical stuff).

YAY!!!!!!!!!!!!!!!!! The thing that tipped me off was that the testing Chromecast refused to complete initialisation when I blocked BOTH 8.8.8.8 and 8.8.4.4... so blocking is actually INSUFFICIENT and you need to intercept+redirect to (in my case my router 127.0.0.1 which resolves correct.domain.com to the IP of my NGINX Reverse-Proxy VM, and not Google's DNS server records lol).

**Comment by BloodyIron** [comment]
So to be even more explicit... the UX... I see art work for my test music album, like the wallpaper and I see the small logo for the album. I see the band name, the album song, and I get the audio music. I can scrub forward/back... however I have a new issue (and this may be just a Jellyfin bug)... I can only seem to play the first and sometimes second song of an album, but nothing more than that! Even if I tell it to directly play a specific song. This is via Chromecast method, to same testing Chromecast device... how odd...

**Comment by BloodyIron** [comment]
Yeah for some reason Jellyfin will only ever play one or two songs... then just refuse to play any more... like the next button just doesn't do anything, and when the "end" song (sometimes one, sometimes two) finishes, the playback just stops... unsure if this is a Chromecast-centric issue or not...

**Comment by BloodyIron** [comment]
@Bond-009 this looks to be a Jellyfin documentation shortcoming, and the Jellyfin app itself seems to have some bugs. Can we please have this re-opened?

**Comment by BloodyIron** [comment]
Okay so I add video media to my Jellyfin set up, and same thing... Hit play for a series and can only actually play the first and/or second video... cannot go back to previous episode, cannot go to episode after the second one... ://///////////

**Comment by BloodyIron** [comment]
Switching to the "Experimental" version of Chromecast in the Jellyfin Android app actually makes it so now nothing at all plays. No music, no video... just "Ready to cast" (beside the Jellyfin logo) in a slightly different layout and... NOTHING.

Well... two steps forward, one step back...

**Comment by BloodyIron** [comment]
Thanks @Bond-009 ! :)

**Comment by sfwr** [comment]
@BloodyIron  Any chance you're running behind a https reverse proxy?  I was able to solve most of my problems by settings this env variable on the docker container running jellyfin:

JELLYFIN_PublishedServerUrl=https://my.public.domain

**Comment by BloodyIron** [comment]
Yeah I am behind an HTTPS reverse-proxy, and I already have that ENV variable at-play. It has not improved the situation. Additionally, I'm running Jellyfin in a kubernetes (k8s) cluster behind a Metal LB load-balancer and NGINX Ingress (plus with the aforementioned reverse proxy in front of all that, but have tested without the reverse-proxy with zero improvement).

**Comment by srcrist** [comment]
Closing this issue as it does not reference an actual Jellyfin bug. If any users encounter this or any similar issues, please visit our support communities on the forum or our Matrix/Discord servers for assistance with network connectivity problems.

**Comment by BloodyIron** [comment]
How exactly is this NOT a Jellyfin bug? That statement doesn't have any evidence to support it, and this very much is the appropriate space for this. Please re-open @Bond-009 or someone, the problem persists.

**Comment by srcrist** [comment]
I see no evidence that this is anything other than a reverse proxy issue. What support do you have that this bug remains in the jellyfin code, and not in your proxy configuration?

**Comment by srcrist** [comment]
My position is that this is, at best, an incorrectly filed duplicate of https://github.com/jellyfin/jellyfin-chromecast/issues/110, which belongs in the Chromecast repo. Do you have any support at all for a server bug?

**Comment by BloodyIron** [comment]
> I see no evidence that this is anything other than a reverse proxy issue. What support do you have that this bug remains in the jellyfin code, and not in your proxy configuration?

I've tested this exhaustively with and without reverse-proxying and had the same failure results.

Also I don't know what you mean by "any support at all for a server bug"...???

**Comment by srcrist** [comment]
I have tested the issue on two separate installations, one on Windows and one on Linux, and Chromecast worked on both just fine. One of them even uses an HTTPS reverse proxy, and still connects without issue. My conclusion is, thus, that whatever issue you are experiencing is not, in fact, a Jellyfin bug, or at least not a server bug--which, to be clear, is what these issues are actually for. 

I am asking you if you can actually provide any support for your belief that this is, in fact, a bug in the code of the Jellyfin server. That is what would be required for this issue to be reopened. Some sort of evidence that your issue is a problem with the Jellyfin server code itself, rather than something in your particular configuration. You have multiple layers of virtualization and network management between your server and your clients. It remains my belief, without some tangible evidence to the contrary, that your issue actually lies in one of those things, and not the Jellyfin server code. It may not be your reverse proxy, but it also does not appear to be Jellyfin. Jellyfin works fine without your setup.

**Comment by BloodyIron** [comment]
1. I have been able to make progress with efforts here : https://github.com/jellyfin/jellyfin-chromecast/pull/107
2. I still have to do the DNS overrides, so that's a thing

The fact is that I don't have the means to actually tell where the remaining outstanding issue is (at this point specifically the DNS blocking requirement). The exhaustive work I've put into this for many months (most of this year) has not turned up any logs that gives any evidence to whether the DNS issue is due to the Jellyfin-Server, the Jellyfin-Android app, the Chromecast-App that Jellyfin sends, the kubernetes/k8s ecosystem at-play, the LAN aspect, the gateway, or anything actually specific.

I have tried to provide as much evidence in many threads on this matter as I can scare up. That's the best I can do, so I cannot reliably say it is, or is not Jellyfin-Server. And I think asking for more evidence than what _CAN_ be provided is asking for blood from a stone, and rather unreasonable. Frankly I'm not the dev here, and I know this is open-source, but software dev and debug to further degree than I have done is nowhere near in my wheelhouse.

And "Jellyfin works without my setup" is irrelevant, because there are multiple other threads with roughly identical configurations (yes, in kubernetes) having effectively identical problems. Jellyfin-Server is provided in many forms, including a docker container, so wanting to run it in a kubernetes cluster is within reasonable usage, and treating that usage as "out of spec" is a double-standard since the image is already provided under the premise that it's stable, etc.

Anyways, at this point I have no way of determining what is making Jellyfin Chromecasting require the DNS blocking. The blocking is not required for my current Emby system, so I don't know if there's a code difference that's relevant, and since their stuff is closed-source, I have no means to do anything useful there.

Either you're going to open the issue, or keep it closed, do what you're going to do. I've done my part to move this forward, and come what may.

**Comment by OCT0PUSCRIME** [comment]
I am also having this issue, both from within LAN and from outside LAN.

I can playback Jellyfin just fine without Chromecast from within LAN and from outside LAN, but Chromecast fails on both. I can cast to other devices from within LAN, but haven't been able to test non chromecast devices outside LAN.

using `curl -fs https://myserver.tld/System/Info/Public` from within LAN and outside LAN both return with the LAN IP Address and the LAN hostname. I do not see a reason this should be happening because myserver.tld has A and AAAA records on public DNS for my WAN addresses. I also have my internal LAN DNS resolving myserver.tld to my WAN addresses to ensure all traffic to that site goes through my reverse proxy. If I want to connect with LAN only my internal hostname is myserver-lan.tld which I have to type in manually.

It seems the "Published Server URIs" setting should allow me to enter myserver.tld and the json respons from the /System/Info/Public endpoint should be using the IP address that is returned from that call and not the LAN IP, but it is not.

I am not sure if I am misunderstanding something here, but for now I am resorting to rewriting the JSON response with my reverse proxy.

**Comment by djryanj** [comment]
So I am in the same boat as @BloodyIron except I'm fighting to get both the-four-letter-app-that-shall-not-be-named and Jellyfin set up in Kubernetes, and I managed to succeed with the other guy with specific local connections, and here's what I found, which I think is useful to this discussion:

1. Ignoring the stupid tunnelling and relay "features", the other guy uses a .direct TLD (more on this in a second) to resolve a set of "additional server IPs" it should know about. When running in Docker/Kubernetes, this is useful because the Docker container can't really know about what's on the other side of the Docker/Kubernetes network (with specific exceptions, but using host networking is undesirable for containerization) without being explicitly _told_ about it.
2. As we've established, one major issue with Chromecast is that it will not use anything other than Google DNS servers, so using a local DNS name really doesn't matter at all (which would solve the problem in 1 by just having clients connect to that like we want).
3. The .direct TLD used by the other guys essentially relies on DNS rebinding to work; the full DNS lookup is something like `#.#.#.#.xxx.name.direct`, with `#.#.#.#` being equal to the IP address it detects. This is either the internal container IP (which is unroutable for Kubernetes and Docker) or the public IP address. This isn't great, because we need to tell our routers (pfSense, opnSense, whatever) that DNS rebinding is _allowed_ for the <otherguy>.direct domain, _and_ it means that internal IP addresses are leaking out.
4. I propose a feature that splits the difference; allow users to specify the specific additional IP addresses that they want to communicate with, and specifically when communicating with Chromecast, it should try those instead of the DNS name. Some additional detection might be needed here to decide whether the server is remote or private; e.g., if remote, use DNS because that should resolve from Googles DNS servers anyway.

Note that I recognize that the use of the .direct TLD by the other guy alongside their certificate service means that encrypted communications are more seamlessly possible, which is harder to do with Jellyfin unless you have a full blown private PKI (and even then it wouldn't help much since Chromecast won't know about it anyway) since you can't have a private IP address in a public cert (e.g., from LetsEncrypt). So this "solution" does require acknowledging either unencrypted communications on a local network only with Jellyfin, _or_ it requires accepting all certificates without checking them (which of course means things are encrypted but insecure for a different reason).

Any thoughts on that @srcrist ?
