### ISSUE TITLE
Copy-Item : Could not find a part of the path '\jellyfin\--InstallFFMPEG\install-jellyfin.ps1'.

### ISSUE THREAD

**Issue by Evoley** [jellyfin/jellyfin#856]
**Describe the bug**
When building from the .ps1 with --InstallFFMPEG flag the build fails with 
Copy-Item : Could not find a part of the path 'C:\Users\Mew\Desktop\jellyfin\--InstallFFMPEG\install-jellyfin.ps1'.
At C:\Users\Mew\Desktop\jellyfin\build-jellyfin.ps1:105 char:1
Copy-Item .\deployment\win-generic\install-jellyfin.ps1 $InstallLocat ...

**To Reproduce**

1. Download latest git
2. Move build-jellyfin.ps1, install.bat and install-jellyfin.ps1 to main jellyfin folder
3. Run ./build-jellyfin.ps1 --InstallFFMPEG

**Expected behavior**
Jellyfin to be built with ffmpeg.

**Logs**
[new 2.txt](https://github.com/jellyfin/jellyfin/files/2848918/new.2.txt)

**System (please complete the following information):**
 - OS: Windows

**Comment by JustAMan** [comment]
cc @logicalphallacy

**Comment by LogicalPhallacy** [comment]
Powershell does not support -- for flags. What you wanted was build-jellyfin.ps1 -InstallFFMPEG

by passing it 2 dashes it messes up the powershell language parser and it treats it as a string for the first positional path parameter. Does the documentation use 2 dashes? Because if so that needs to be fixed.
