### ISSUE TITLE
[Issue]: tmdbid referencing a tvshow and not movie

### ISSUE THREAD

**Issue by TobbeJ** [jellyfin/jellyfin#8663]
### Please describe your bug

In my movies media library i got an old recording from tv, when scanning this in it gets misdetected.
So i added [tmdbid-39203] to the filename to get it to show up with the correct metadata.
This did not work at all because apparently the same id number exists both as a movie and a tvshow on tmdb.

correct url: https://www.themoviedb.org/tv/39203
wrong url: https://www.themoviedb.org/movie/39203
Note the identical id number but tv vs movie

How do i convince the scanning to pick the one with tv in it and not the movie?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maru801** [comment]
Jellyfin will go based on what media type library you have it in. You said that it's in a movie library, so it will search based on movies.

If you want it to get the tv version automatically, you will have to move the content to a tv show library.

If you don't want to move it from where it's currently at, you can still edit the metadata yourself. Make sure to lock the metadata so that it doesn't change again with the incorrect info if you do this.

**Comment by TobbeJ** [comment]
ok, i was hoping it would be possible to do something like: [tmdbid-tv39203] or similar to force it to lookup the data as a tvshow instead of the default (based on library type)

or if that is not possible, add the corrected tmdb reference in the metadata for the file and then get jellyfin to update the rest of the metadata based on this new, corrected id.

**Comment by cvium** [comment]
The id is the reference

**Comment by Bond-009** [comment]
TV shows aren't supported in a movie library
