### ISSUE TITLE
[Issue]: Can't login if there is space at the end of user name

### ISSUE THREAD

**Issue by linux2good** [jellyfin/jellyfin#8897]
### Please describe your bug

Just like in title. I think when somebody type their name on phone, their keyboard suggest complete it to their user name, but after that, their keyboard set space at the end (that's useful for messengers i guess). And, user can't login. I think it can be fixed by regex? By the way, that affects all clients on different platforms.

### Jellyfin Version

Other

### if other:

10.8.8.0

### Environment

```markdown
- OS: Debian
- Virtualization:
- Clients: Jellyfin Android, Jellyfin IOS
- Browser: Firefox, Google Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy: nginx
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[ERR] Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[INF] Authentication request for "User " has been denied (IP: "<IP>").
[ERR] Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname".

...

[INF] Authentication request for "User" has succeeded.

# notice the space in the authentication request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
I want to start of by saying that I have no in depth knowledge on the server and client implementation of the authentication system. But I want to give my view and opinion on some solutions and issues that I came up with when thinking of a way to "solve" this.

I'm not sure if this is a bug or not. This could be fixed in a couple of ways. One of them is by ignoring the white space at the end of a username in the server. The other option, that I can think of, is by removing trailing white spaces on the client side before sending it to the server.

There are probably more solutions for something like this. But these options are intrusive as it will break login's for people who currently use trailing white spaces in their usernames. This means these accounts need to be converted and "cleaned" of trailing white spaces. To make this even more complex, what if a user created 2 accounts with the same name but with 1 and 2 white spaces differentiating them. This would make converting said accounts painful or impossible without changing the names by adding some unique identifier or by forcing an admin to change the names. I am personally against allowing trailing white spaces in usernames when creating a user. But the server currently allows this so its something we have to think about.

If this is something that needs to be dealt with, I am suggesting to start with disallowing username creation on the server side that start or end with white spaces. And after that let clients deal with the input however they want (this still does not cover how to migrate duplicate account names that are differentiated by white spaces). Clients can more easily remove trailing white spaces at that point as its not allowed for usernames to begin with.

But I am not sure if this is something that needs to be fixed to begin with. I am sure that I am just overthinking this, but it sounds like a lot of work, and could introduce edge cases in the authentication system that can pop-up, when trying to "solve" this.

**Comment by AhiyaHiya** [comment]
Has this bug been assigned to any developers, or are there developers actively working on this fix? If not, I would like to take a stab at this.

**Comment by TimGels** [comment]
> Has this bug been assigned to any developers, or are there developers actively working on this fix? If not, I would like to take a stab at this.

I'm kinda curious on how you are planning on doing the migration of the already existing users using white spaces. Especially when taking the things into account that I mentioned before. I think it is an interesting problem to deal with.

**Comment by nielsvanvelzen** [comment]
If we're adding restrictions to the username we should probably look at more then only spaces at the begin/end of the username. We might want to remove all special characters and only allow `[A-Za-z0-9]` to avoid any issues when signing in.

**Comment by TimGels** [comment]
> [A-Za-z0-9

We will need to make sure to allow alternate writings like Kana (i.e. `アップル`), or Kanji etc for people not using our alphabet.

**Comment by nielsvanvelzen** [comment]
> > [A-Za-z0-9
> 
> We will need to make sure to allow alternate writings like Kana (i.e. `アップル`), or Kanji etc for people not using our alphabet.

Yeah of course that should be considered, the range I provided was illustrative. Most (web-)apps don't support a lot of special characters in usernames for various reasons. In our case I think we should consider only basic characters to make input easier on various devices (especially TV's/other remote controlled devices) and in case we ever need to support usernames in URL's (profiles/invites/whatever).
Important to remember is that these are usernames for authentication, **not** display names. So not supporting whitespace at all is pretty much a default in most systems.

**Comment by oddstr13** [comment]
I have in the past used full names as sign-in (a couple of years ago when I was playing with LDAP), which include accented characters and spaces, so people already having deployed systems with "special" characters as part of usernames needs to be taken into consideration here.

(Also, this is all my fault in the first place I guess :laughing: jellyfin/jellyfin#3703)
Current validation code; https://github.com/jellyfin/jellyfin/blob/a6efdd850a551bd63cb4ca8459078352578d53e2/Jellyfin.Server.Implementations/Users/UserManager.cs#L737-L743

I think that allowing only latin letters would mess up most current non-english setups, and we do have a fairly large amount of users that mainly utilize non-latin scripts.

I think (server-side) whitespace normalization would be the best solution here; replace all sequences of whitespace characters with a single 0x20, strip leading and trailing whitespace. Some thought need to be put into migration of existing users.

**Comment by TimGels** [comment]
Such a migration needs to be very informative and straight forward in my opinion. Most people don't follow the release notes so only mentioning is in there isn't very practical I think. But it also needs to be very easy to understand and comprehend why and what is happening and what needs to be done. 

Maybe something like a modal on screen when an admin goes to the dashboard (or somewhere else). The modal could then contain a couple things. One of them could be a button that migrates users from the old whitelist to the new. And for users that are only uniquely distinguished by (illegal) characters it could show a list to the admin which accounts need to be manually converted. This can be made even easier (takes more time to develop most definitely) when the admin can bulk convert the accounts, which could not be automatically trimmed from illegal characters, in the same modal.

This is just one idea of course and it doesn't take everything into account. It is just a quick idea from me without having thought about much details.

**Comment by AhiyaHiya** [comment]
> > Has this bug been assigned to any developers, or are there developers actively working on this fix? If not, I would like to take a stab at this.
> 
> I'm kinda curious on how you are planning on doing the migration of the already existing users using white spaces. Especially when taking the things into account that I mentioned before. I think it is an interesting problem to deal with.

Do we need to do a data migration?

We could advise the user that they should edit the username in the UI.

Also, who would make this type of design decision?

**Comment by AhiyaHiya** [comment]
Well, this sounds a lot more than a simple code fix. I will bow out, and let the next developer, who has had experience with the data migration code, craft up a solution. Thanks.

**Comment by JeffReeves** [comment]
Not trying to necro an old issue, but I ran into this today with my child's phone when they were trying to sign in. 

Simple fix was to just remove the space after the username, but that's not easy to look for if you don't know that it could cause an issue.

My suggestion here wouldn't be to get fancy with the Regex but to do something simple like a call to a .trim() function to strip off any leading or trailing whitespace when the sign-in button is pressed.

Secondarily, you could extend this solution to when the button is pressed to create a new user account by trimming the username field.

I haven't forked the code to see where I could add this myself, but if I find the time I'll create a PR for this. Anyone else more familiar with the codebase might be able to do this in the meantime though.

**Comment by SwatterMatter** [comment]
Just ran into this problem today. It seems to me that a backwards compatible solution might be to only apply the trim() function to the username if the username is not found on the first check.
