### ISSUE TITLE
Sortby Name in media broswer works unexpected

### ISSUE THREAD

**Issue by HernandoR** [jellyfin/jellyfin#9161]
current sort by Name like this
<img width="1878" alt="image" src="https://user-images.githubusercontent.com/45709656/214030280-79cc264f-c7e1-41b9-a727-7e3fca404f6c.png">

Expected sorted by name should be aligned with the name it displays.

I believe it's due to the Non-English name it shows.

I found this line may be controlling the sort-by-name behaviour, but I don't know how to change the `ItemSortBy.SortName` here.

https://github.com/jellyfin/jellyfin/blob/620a5d5e831b1892599b334d44098d67ff2ee36f/MediaBrowser.Controller/Entities/Movies/BoxSet.cs#L122

Also, if it is desired to remain SortName, we may need to ensure that the sortName be aligning with the display name.

**Comment by Killerbee437** [comment]
I don't have any test data to confirm it, but the most likely culprit is this line:
https://github.com/jellyfin/jellyfin/blob/719e5eae16a3488de449a5b2a7c56132c8f1e5c1/Emby.Server.Implementations/Sorting/NameComparer.cs#L31
Here the sorting is done using Ordinal sorting which doesn't take culture into account. I don't know what the reason was for this sorting type, so people with more knowledge of the underlying choices would be better suited for fixing this bug.
In its simplest form it would probably be just replacing the sort type with StringComparison.InvariantCultureIgnoreCase, but that would have to be investigated for other edge cases.
