### ISSUE TITLE
[Issue]: `System/Restart` endpoint does not work

### ISSUE THREAD

**Issue by yellowhat** [jellyfin/jellyfin#9168]
### Please describe your bug

Hi,
I am trying to configure my jellyfin instance using REST APIs.
In order to install a plugin it is required to restart the application.

The `System/Restart` endpoint should allow to restart the application, if I run:

```bash
$ curl -v -X POST "http://localhost:30182/System/Restart" -H "Accept: */*" -H "X-MediaBrowser-Token: <token>" -d ''
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying localhost:30182...
* Connected to localhost (127.0.0.1) port 30182 (#0)
> POST /System/Restart HTTP/1.1
> Host: 127.0.0.1:30182
> User-Agent: curl/7.87.0
> Accept: */*
> X-MediaBrowser-Token: <token>
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Tue, 24 Jan 2023 08:17:15 GMT
< Server: Kestrel
< X-Response-Time-ms: 1
< 
* Connection #0 to host 127.0.0.1 left intact
```

But the server is not restarted and nothing new shows in the logs.

Any ideas?

Thanks

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Kubernetes
- Virtualization: Container
- Clients: curl
- Browser: -
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- Plugins: -
- Reverse Proxy: -
- Base URL: http://localhost:30182
- Networking: kubernetes
- Storage: container
```

### Jellyfin logs

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Firstly, please use the latest version (currently 10.8.9) when reporting bugs.
Considering you are runningJellyfin in a container, the restart endpoint won't work because Jellyfin is the main process of the container and the restart script currently invokes the service management (systemd/sysvinit/...) to restart Jellyfin which is not available within the container.
This will change in 10.9 due to https://github.com/jellyfin/jellyfin/pull/9100 not requiring using the distro service management anymore.

**Comment by yellowhat** [comment]
Hi, thanks for you reply.
I am using 10.8.9, but the drop down only has 10.8.0.

Perfect. I will try on 10.9.
