### ISSUE TITLE
Startpage > latest series

### ISSUE THREAD

**Issue by Snipy2k4** [jellyfin/jellyfin#9173]
Hello,

I have a problem on the main page with the "Recent Media" feature for series.

I use Jellyfin on a QNAP in version jellyfin 10.8.9-1. But that was also the case with version 10.8.8-1.

Source: https://github.com/pdulvp/jellyfin-qnap

When I add series to my series folder, jellyfin recognizes them without any problems, but not all of them are displayed on the main page under latest media. The tiles always move so that instead of 9 or more, only 3 or 4 newest series are displayed. If I then go straight into series, all series and seasons are there and I can also look at them.

I've recreated the "Series" library several times, but every time it's finished scanning, only 2-4 series are displayed on the start page under the latest series...

Do you understand my request? Sorry I use google translator because I don't speak english :D

Everything works wonderfully with films, I don't know where the problem or error is with the series. Do you have an idea?

**Comment by Shadowghost** [comment]
Only the most recent X (I think it's something like 84) episodes are fetched and afterwards groups into series.
This is done because the underlying database transactions within the server are time intensive and fetching more than the set amount of items would probably delay loading the page for several seconds or even more on slow systems like a raspberry pi.
Without a new database schema (which is worked on) the amount of fetched episodes is unlikely to change drastically.

**Comment by Snipy2k4** [comment]
I see... thanks for the explanation

Visually on the start page it's not nice, but now I understand it.

The "problem" has existed for a long time and, as you said, a new database is being worked on. Is there a date when it should come?

An idea for a workaround until the new database is there:

An option for people with good hardware who can disable or set this display limit themselves?

**Comment by Snipy2k4** [comment]
Addendum:

I noticed that on the FireTV Stick or the version on it, significantly more "latest series" are displayed than in the web interface or on the LG WebOS app.

is this relevant or helpful?

**Comment by TheStutterNerd** [comment]
Same issue/design flaw here, only just noticed it right now because I added all the episodes for Brooklyn 99 again. It really does make you instantly think something has broken or is going wrong till you come across a post like this.

It seems like it filters the latest 100 episodes as specified above which can seem confusing, especially when you previously had like 12 shows showing then instantly drop down to 3.

**Comment by Mega-Volti** [comment]
Same issue here. "Latest Shows" used to show the latest 8 or so shows I added. But after adding two new ones (with about 80 episodes in total), my previous shows all disappeared from the "Latest Shows" list and only the 2 very newest are shown.

All shows still show up properly in the library shows view.

**Comment by Mega-Volti** [comment]
To add to the previous comment: I've managed to reliably reproduce the issue with a series that has mkv / avi files. It's a TV series with 78 eps / 6 seasons, some of which are in "old" formats. Whenever I add this series, all previously added series get "forgotten" and don't show up in the latest series section any more. Any series added afterwards show up fine again.

Even weirder, a series added beforehand will "disappear", but new episodes for the "disappeared" series will show up in the latest shows. So let's say I have a series with 4 episodes. I add 2 of them, they show up in latest shows. Then I add my series with the mkv files, the 2 eps disappear. Then I add the remaining 2 eps of the other series, and only those two show up in latest shows. Which means the series itself is shown again, but only with a 2 ep marker instead of a 4 ep marker, even though 4 eps are not watched.

This reliably happens after adding the series with mkv files in it, and only with that one series. I wasn't able to reproduce it with any other.

**Comment by Kianda** [comment]
Noticed this today! A large show have broken my "latest shows" section.

What happens if we increase this limit? What are the drawbacks?
https://github.com/jellyfin/jellyfin/blob/v10.8.10/Emby.Server.Implementations/Library/UserViewManager.cs#L365

Example:
1. Break the "latest shows" with a large (100+ unwatched episodes) tv show
2. Test Items API call with the 16 limit:
http://YOUR_JF_ADDRESS_HERE/emby/Users/YOUR_USER_ID_HERE/Items/Latest?GroupItems=true&IncludeItemTypes=episode&Limit=16&api_key=YOUR_API_KEY_HERE
3. Test the same with a higher limit:
http://YOUR_JF_ADDRESS_HERE/emby/Users/YOUR_USER_ID_HERE/Items/Latest?GroupItems=true&IncludeItemTypes=episode&Limit=200&api_key=YOUR_API_KEY_HERE

The Items API with a higher limit is replying with all the shows with the correct ChildCount.

It's possible to have that limit as a settings parameter? Or environment variable? At least until a better solution comes out!
I know it's "dirty" but it seems that this issue is here since 2019 and, at this point, a "dirty solution" is better than nothing!

^^

**Comment by Snipy2k4** [comment]
Will this be fixed or not? ????

**Comment by nielsvanvelzen** [comment]
Yes but it will take a lot of work and time

**Comment by Snipy2k4** [comment]
Okay, nice, but the “problem” has been known for a long time

**Comment by dotbanana** [comment]
> Okay, nice, but the “problem” has been known for a long time

It is now five years. This won't ever get fixed because nobody of these people here knows how to do it.  
The code was written by Luke, who is working on Emby.  
The Jellyfin-people even haven't managed to remove the traces of emby in their code. A rewrite of core-components of this you won't ever see. Sorry to say this.

**Comment by Snipy2k4** [comment]
-.-

**Comment by JPVenson** [comment]
Everyone is more then welcome to shime in and propose a new architecture how latest should be handled differently on our meta repro to discuss and then implement the discussed proposal.

**Comment by Snipy2k4** [comment]
So the problem persists?!

**Comment by nielsvanvelzen** [comment]
To fix this issue we first need to complete revamp the underlying data structure of Jellyfin. This has been in progress for a long time now. The hard part is to do it in a way that migrates existing data so all of our users don't need to start all-over. If you're not satisfied with the time this takes from all the unpaid volunteers that spend their free time on it you should use different software.

**Comment by Snipy2k4** [comment]
I understand that, but for 5 years already?!

**Comment by JPVenson** [comment]
Yes as we do this in our free time and cannot work 8 hours per day on this project including other errors.
You are very welcome to help with the EfCore migration to accelerate the progress on the issue.

**Comment by Snipy2k4** [comment]
why was my post marked as spam? I just think it's pretty sad that this mistake has been around for so long since I otherwise love Jellyfin

**Comment by JPVenson** [comment]
@Snipy2k4 We dont mark stuff as spam, github does

**Comment by Snipy2k4** [comment]
spam, offtopic... wtf is going on here? why is this happening?

**Comment by dotbanana** [comment]
> The hard part is to do it in a way that migrates existing data so all of our users don't need to start all-over.

The users will have to start all-over anyway when nothing goes forward.   
I already did the migration away to Emby and yes it took weeks for me to do this, but at least there is _some_ progress there and those forever-bugs that plague Jellyfin are solved there.   
I don't know if this is the right place but the JF-Projectlead has simply made organizational mistakes.  
It was a mistake to not allow bug- and feature-bounties for money because on one side you pretend to follow some strict "anti-commercial" line of action while on the other side unproportional amounts of money get dumped into the "test-servers" of the project-admins.   
It was a mistake to care for all those obscure clients for different systems (mobile, TV and whatnot). The main focus should have always been the server-component and the web-client.    
I can only repeat myself but in the end, and this is not joking by me, it would have been faster and smoother and easier to just start from scratch, maybe with a modern language like GO, or something that more people can code like Python, than to quickly fork the complex code of someone else and hell-bent try to make something out of it just because it exists and then explain half a decade stagnation with trying to keep up compatibility.   
Just my two cents.

**Comment by JPVenson** [comment]
> I don't know if this is the right place but the JF-Projectlead has simply made organizational mistakes.

While i agree on certain aspects of that statement i can assure you that the "leadership" is fully aware of that and there were just recently made actions to help with that. But this is just possible as a new group of volunteers (including me) stepped forward and took over some responsibilities. While i understand the frustration, this is A: not the correct place to discuss this and B: very easy to say if you dont spend a lot of time helping on issues.

> It was a mistake to not allow bug- and feature-bounties 
Its the majority agrees this project should be operated.

> unproportional amounts of money get dumped into the "test-servers" of the project-admins.

All expenses are open and visible and i am currently working on a easy alternative to test things instead directly here on github.

> maybe with a modern language like GO, or something that more people can code like Python

you are absolutely free to do that but the majority of JF core contributors will continue to work on jellyfin because they _want_ it that way. They want to do C# and they will continue to do so. There is really no discussion on rewriting the server because you would very likely loose the majority of the core team which would be a death sentence for the project.

**Comment by Snipy2k4** [comment]
This issue has been somewhat fixed in the latest 10.9.0/10.9.1. Many bugs have been fixed but this one apparently hasn't been fixed. Will there be anything else to come?

**Comment by dotbanana** [comment]
> but this one apparently hasn't been fixed

I really don't understand why you still with JF.    
I have completely changed my mind on this topic.     
Luke has written all of Emby/Jellyfin. He has put enormous amount of work into Emby.  
And this code was basically stolen and now what we are watching is that the people that stole it don't know how to use it/utilize it. 
All of Jellyfin code is still full of Traces of Emby. They did not even change/remove the naming scheme in Jellyfin.  
In all these years!  Because nobody knows how.  
The folks that manage this are using the JF-Project for their own promotion. Look at it.  
It goes the way "i manage a high star project on github please pay me 30k for this simple job". But they are basically not doing anything here. It is fraud.   
If you go to Emby everything just works, stuff is patched/fixed very fast and Luke gets some little money for his hard work back.  
He knows all about this code. Jellyfin and Emby. It is his personal baby.  
And the Database-problems, that are topic in this thread, have been changed/adapted years ago.   
Jellyfin is years(!) worth of work behind in functionality robustness and client support.  
It develops into a direction where in future people will maybe call it the "Jellyfin-Effect".  
Open Source is not magically always automatically better. A hard lesson for a lot of people in the industry.
