### ISSUE TITLE
Remove Mono support

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#95]
Now that we're building with .NET Core, we should deprecate and remove all Mono-related code. It's more to maintain and test.

**Comment by nvllsvm** [comment]
@joshuaboniface Thoughts?

**Comment by joshuaboniface** [comment]
Agreed, the Deb packages work well without Mono so we should clean up whatever we can.

**Comment by DoctorMacc** [comment]
If I'm correct, .NET Core doesn't fully support FreeBSD (see [https://github.com/dotnet/corefx/issues/1626](here)). How will this affect future FreeBSD releases?

**Comment by Bond-009** [comment]
dotnet does "support" FreeBSD, but you need to build it from source.

**Comment by DoctorMacc** [comment]
I can only speak from my experience, but the FreeBSD userbase also includes FreeNAS, which currently provides an Emby package in its plugins UI.

**Comment by JustAMan** [comment]
If one can build netcore for FreeBSD then it should be a matter of finding a maintener for FreeBSD build of Jellyfin... I am all for removing Mono support - it's already being deprecated in favor of netcore, so I think that maintaining two versions gives too much load and yields too small "profit" to the community as a whole.

P.S. Quick search says that FreeBSD has docker support since 2015, and we provide docker image.

**Comment by joshuaboniface** [comment]
Yea I actually think Docker is the best bet for platforms that we can't/don't directly support - managing packaging for dozens of distros and OSes gets really tedious unless we have dedicated maintainers, so Docker is a nice common denominator.

FreeNAS/FreeBSD seems to support Docker: https://www.freenas.org/blog/docker-done-right/ but having not used it I can't say for sure.

**Comment by mcarlton00** [comment]
Last I've heard, docker on FreeBSD was still experimental.
https://wiki.freebsd.org/Docker.
Doing a bit more digging, it also appears to be [unmaintained](https://github.com/kvasdopil/docker/tree/freebsd-compat).  Last commit July of 2015.

Personally, I'm in favor of compiling dotnet from source, but I have no idea how that could work on FreeNAS systems.  On the bright side, it looks like dotnet might be able to get merged into ports "soon", but work seems to have stalled in recent months: https://github.com/dotnet/coreclr/issues/18067#issuecomment-418930115
Pinging @mateusrodrigues, are there any more updates or something to be done to push things along?

**Comment by mateusrodrigues** [comment]
Hi guys. The FreeBSD version of dotnet runtime/sdk are currently still experimental. Following the steps on this [tutorial](https://github.com/dotnet/corefx/wiki/Building-.NET-Core--2.x-on-FreeBSD#building-freebsd-sdk) were working since I built my last SDK back in August, not sure what the state is now.

I've been overwhelmed with other work, but there's a port for dotnet under review written by me [here](https://reviews.freebsd.org/D16707). The only problems are managed runtime components for FreeBSD need to be built on Linux and SDK components need to be copied over as-is from Linux version - which doesn't represent a problem at first because they are mostly DLLs, but I'm sure there will be some issues further along. We can only currently build native runtime components (coreclr, corefx, and core-setup). I still haven't been able to push this along, but I do plan to.

In terms of usability of runtime/sdk, I was able to run PowerShell - which is also included in the port review - using this experimental version of dotnet. However, I'm not sure how it would behave for your application.

**Comment by sparky8251** [comment]
Correct me if I'm wrong... Docker shares the hosts kernel with the containers it runs. I presume this is the case for FreeBSD, so even if Docker works on FreeBSD you still need FreeBSD support in Jellyfin.

**Comment by doug0162** [comment]
Docker on FreeNAS also requires a minimum of 2GB of RAM dedicated to the virtual machine. It'll be _fine_ for a few early adopters, but its not viable for the vast majority of users given ZFS's hunger for RAM.

https://www.ixsystems.com/documentation/freenas/11.2/virtualmachines.html#docker-host-requirements

**Comment by JustAMan** [comment]
One could always run a debian or other linux-based VM, if all else fails. At least as an intermediate solution...

**Comment by mkvalluri** [comment]
Do we already have a branch for dotnet core migration?

**Comment by joshuaboniface** [comment]
This should be all good now, there should be no more Mono code left.
