### ISSUE TITLE
[Issue]: Wrong screencap loaded for episode from themoviedb

### ISSUE THREAD

**Issue by MaximeLussier** [jellyfin/jellyfin#9567]
### Please describe your bug

The episode screencaps loaded for episodes are not the correct ones.
The screecaps on themoviedb.org are correct.

This MAY be caused by the episodes being doubles (e.g S09E22-23)

Easy to reproduce with Season 9 of the Paw Patrol, however, the other seasons also do this.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: Google TV (Shield, CcWGTv), Android, iOS, Browser
- Browser: Firefox/Chrome
- FFmpeg Version: (Included in docker)
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: Playback Reports
- Reverse Proxy: SWAG (nginx)
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/944488/229000360-31bfab04-943a-4a10-9cc4-de4957e2efff.png)
![image](https://user-images.githubusercontent.com/944488/229000571-3e68fcbe-dbfc-41ac-a4bb-ae859354586e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MaximeLussier** [comment]
I've also seen this issue with other TV series, not only kids show.

**Comment by srcrist** [comment]
Closing this issue as it does not contain and actual Jellyfin bug. Media files containing multiple episodes can still only display one title card. Even within the file the second episode's title card will display when the first episode ends. You could choose a different image if you'd like, but Jellyfin cannot produce a combined title card that does not exist.

**Comment by MaximeLussier** [comment]
@srcrist no, the title card is not associated with any of the two contained episodes...
If it was either the first or second title card it would be fine...
You can check the example I provided, if you need more examples I can do that
Please re-open the issue if you see that there is indeed an issue!
Thanks
Maxime

**Comment by MaximeLussier** [comment]
Or maybe the numbering is wrong... I will take a further look 🤨

**Comment by MaximeLussier** [comment]
Ah, maybe the numbering from the metadata source differs from the picture source 😯

**Comment by srcrist** [comment]
To rewind a bit, even if the images are matched incorrectly it's unlikely to be a bug. But I was not clear to me from your images what the issue was, because the images in the TMDB screenshot actually matched the images from your Jellyfin screenshot. I am now parsing that it's the first image, which is not in your TMDB screenshot at all, which is incorrect. 

Just the same, check your file names and compare them to the metadata source and make sure that you're following the naming and organization conventions here: https://jellyfin.org/docs/general/server/media/shows/

This isn't indicative of a bug, but of a mismatch between your files and the metadata source. Jellyfin does not create these images or anything. It just matches your files with the source and downloads the artwork that its given.
