### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by chuckn246** [jellyfin/jellyfin#988]
**Describe the bug**

Play song (not sure about video) then move volume slider at bottom of page. Slider moves but volume does not increase/decrease.

Volume control does work on the playlist page.

**To Reproduce**

1. Go to album or song
2. Click on play
3. Attempt to adjust volume
4. Slider moves but volume does not change

**Expected behavior**

Volume should raise/lower to coincide with slider movement.

**Logs**

Nothing to note

**System (please complete the following information):**
 - OS: Debian 4.9.144-3 (Jellyfin VM)
 - Browser: Firefox and qutebrowser
 - Jellyfin Version: 10.2.0

**Comment by sparky8251** [comment]
@chuckn246 I use Firefox myself and was the one that submitted the fix for slider behavior in 10.2.0.

Can you test something for me? Its been working finr for me since launch so want to eliminate some possible causes.

If you hit F12 you should get a developers menu, go to the network tab and tick the "disable cache" checkbox. Then hit F5 to reload whatever page of Jellyfin you are on.

Keep the F12 menu open and start playing music however you do. When you have the page up where the slider behaves strangely, hit F5. Music playback will likely stop. Go back and start it again keeping the F12 menu open the whole time.

This time, test the slider. I presume it will work after going though the above process. There is some really aggressive caching and it would explain why the slider works in some places but not others (the code for slider adjustments lives in 3 files for the 3 different UIs it appears on).

**Comment by chuckn246** [comment]
Just followed your steps a couple of times to no avail.

I am noticing though that there are no Network requests(?) being sent when using the slider at the bottom of the page on album view for instance. 

Once I select the playlist view and adjust the volume slider, I get EventName: volumechange requests(?).

**Comment by sparky8251** [comment]
Well, good news is that I can replicate. So I'll get digging into whats causing this stupidity. Guessing I forgot something in my PR... Coulda sworn I tested it in all 3 places.

**Comment by chuckn246** [comment]
Perfect, thanks!

**Comment by sparky8251** [comment]
Well, found the problem. Not sure if we are going to be doing a 10.2.2 but if we are, expect a fix "soon."

**Comment by sparky8251** [comment]
Best to wait until the real fix is in so you don't get more folks opening issues about this :)

**Comment by chuckn246** [comment]
Ok, I'll leave it up. 

Thanks again!

**Comment by chuckn246** [comment]
Yep, I was just looking at the pull request. That was quick!

It's just a minor annoyance, so no rush to push it out. Just glad that I wasn't going crazy or had other issues with the few systems that I stream on.

Should I close this or wait until the fix is implemented?

**Comment by joshuaboniface** [comment]
@sparky8251 I'm OK with 10.2.2, fits with my ffmpeg fixes too.

**Comment by JustAMan** [comment]
@chuckn246 we keep issues open until the fix for them lands in `master`. The PR that fixed this particular issue landed in our release branch (as it's slated for `10.2.2` hotfix release), so it will end in `master` after the release is out. Please keep this open until the backmerge from release is done.

**Comment by joshuaboniface** [comment]
Included in 10.2.2.
