### ISSUE TITLE
[Issue]: Dates set by the user are treated as UTC rather than local time

### ISSUE THREAD

**Issue by fhriley** [jellyfin/jellyfin#9891]
### Please describe your bug

Dates that are input by the user are treated as UTC. This means when they are displayed to the user or used by software in local time, they will be wrong. For example, if I use jellyfin to set today's date (`06/15/2023`) as the `date added` field of an episode, it will be displayed and used in Kodi as `06/14/2023` because I am in a UTC-5 time zone.

Instead, dates should be treated as local time and converted to UTC before being stored in the database.

Steps to reproduce:

1. Edit the metadata on an episode and set the `Date added` field to a date
2. Use the API to retrieve the episode and see that the `Date added` field is set to the date in UTC time with 00:00:00 as HH:MM:SS.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian
- Linux Kernel: Linux a880d31b7165 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
- Virtualization: Docker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobslusser** [comment]
Thinking out loud a bit here to make sure we get the right fix/feature for this.

The API is correct to be using ISO8601, UTC time. I don't think we need to discuss that. The issue is the UI is parsing the ISO8601 date from the API but then *displaying* it as ISO8601 and so the easiest fix for this might be to simply change the UI to use `date.toDateString()` instead of `date.toISOString()`. See [here](https://github.com/jellyfin/jellyfin-web/blob/c077a177e376553f57614331358e64bd70400d05/src/components/metadataEditor/metadataEditor.js#L789C1-L799C6).

In theory, that would then display the UTC time from the API to the user's local time as identified by the browser. IMO, though, using the browser to determine local time is never reliable. What if the user is on VPN? For that reason, I prefer to capture the user's time zone preference in their profile, in which case, we would:

1. Add a new user preference for preferred time zone.
2. Update the user display UI to allow them to configure time zone preference. 
3. Use the user's time zone preference in date display and update operations.
